### ISSUE TITLE
Library - The breadcrumb navigation for a folder is not being displayed correctly

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10221]
## Observed behavior
The breadcrumb navigation for a folder is not being displayed correctly

## Expected behavior
The breadcrumb navigation for a folder should be displayed correctly

## Steps to reproduce the issue
1. Install the the latest [0. 16 build ](https://buildkite.com/learningequality/kolibri-python-package/builds/7597) 
2. Import the QA channel and go to Library > QA Channel > African Story Books

## Video

https://user-images.githubusercontent.com/79847249/224100562-8d0f99f8-b2b0-4389-b9ba-41647fe5e013.mp4

## Usage Details
Ubuntu 22  - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
The TypeError appears to be coming from `KResponsiveWindow` - it's possible that this breakage is then causing the failure to resize other elements, and could be the root of the bug.

**Comment by shrinishant** [comment]
Hey @pcenov, I couldn't find QA channel while searching for import. Could you please let me know how to find that channel?

**Comment by radinamatic** [comment]
@shrinishant  Kolibri QA channel is unlisted, but you can use the token `nakav-mafak` to import it.

**Comment by shrinishant** [comment]
> The TypeError appears to be coming from `KResponsiveWindow` - it's possible that this breakage is then causing the failure to resize other elements, and could be the root of the bug.

@rtibbles @radinamatic @pcenov  i'm not getting any TypeError at my end.

@rtibbles sir, after exploring a bit i found that for this specific QA channel - a css property (top: 64px) is being imposed on the side panel unlike for other channels. Further, that 64px is being dynamically set under stickyCalculation() at line 661 of kolibri/plugins/learn/assets/src/views/TopicsPage/index.vue file.

I tried removing it and then this issue is gone and that sidePanel is no longer overlapping over the breadcrumbs. But, i'm not sure whether this would impact something else or not.

**Comment by rtibbles** [comment]
Fixed in #10298
