### ISSUE TITLE
The device management PIN functionality is not functioning correctly on a Learn-only device

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10238]
## Observed behavior
After creating a Learn-only device I do see the PIN modal however it's not accepting the the PIN. Also after removing the PIN from the main facility and restarting both servers, the PIN modal is still being displayed.

## Expected behavior
Fully functional PIN functionality.

## Steps to reproduce the issue
1. Install the the [following build ](https://buildkite.com/learningequality/kolibri-debian/builds/6281) 
2.  Setup a full facility and add a Device management PIN at Facility > Settings
3. Setup a Learn-only facility and attempt to import a channel.

## Screenshot
![2023-03-14_17-28-43](https://user-images.githubusercontent.com/79847249/225056620-2f5ac60c-24cc-42a5-94f4-ef6db2c8e644.png)

## Usage Details
Windows 10, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic @marcellamaki @akolson

**Comment by akolson** [comment]
This looks to be an issue related to object-level permissions on the `facilitydataset` resource. @rtibbles is this the case? Also, what would be the best way to open up access to the `is-pin-valid` resource?

**Comment by rtibbles** [comment]
Hrm, yes - I think the issue is that the permissions model assumes that a POST or PATCH is a write operation, so it is then disallowing these operations for someone with only `can_manage_content` permissions who is not allowed to write to the facility dataset.

The simplest way to handle this might be to spin out the `is_pin_valid` [viewset action](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/api.py#L223) into a separate APIView, with permissions that allow anyone with superuser or can manage content to POST to.

There's an example of something similar here: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/api.py#L406, although that example doesn't use any permission classes at all!

Adding a permissions class like this one: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/device/permissions.py#L26 might be sufficient.

Details on setting permissions on Django REST Framework views/viewsets are here: https://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy
