### ISSUE TITLE
Tasks displayed in a list in the Task Manager do not have any explicit ordering

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10308]
## Observed behavior
Currently, when we display tasks that are running, neither the API, nor their display in the frontend enforces any specific ordering. This can make it harder for administrators to find a running task if there is a long list.

## Expected behavior
I think the simplest behaviour here is simply to order by 'scheduled_datetime' in the frontend, which is now returned by the API endpoint.

## User-facing consequences
Confusion, irritation, annoyance.

## Steps to reproduce
Queue several tasks and see the order being somewhat random.

## Context
 * Kolibri version: 0.15+

**Comment by luna215** [comment]
@rtibbles Love to take this on, and how would I go about queueing multiple tasks here. I have the kolibri develop branch up and running on my machine.

**Comment by rtibbles** [comment]
Hi @luna215 - long time no see! You should be able to select multiple channels to import and it will queue them up. Even if the tasks finish, just don't clear them from the task manager, and you should still be able to play with the sorting.

**Comment by luna215** [comment]
@rtibbles just double checking that this is the window you're referring to?
<img width="962" alt="Screenshot 2023-03-27 at 9 17 37 AM" src="https://user-images.githubusercontent.com/7971405/228001735-4d417413-95c2-4748-a25d-fe48ae34ef3d.png">

~~What is the expected behavior here? I'm also assuming that we also want the tasks that are still processing to be at the top of the list as - from the image I shared - opposed to them coming after tasks that have finished?~~

Update:
Just saw the expected behavior for this.

**Comment by rtibbles** [comment]
Yes, this is the right one! I will review your PR soon, been out with a cold yesterday and today.
