### ISSUE TITLE
Unable to create learn-only user on Windows 10 VM

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10311]
## Observed behavior
Reported by: @radinamatic in the alpha-10 bug-bash. Unable to create the learn-only user on Windows 10 VM, but was able to successfully create the user after switching to Ubuntu.

https://user-images.githubusercontent.com/46411498/227546489-1a6ebc02-4bbe-4e5f-8802-b47b1dd7f69a.mp4

## Errors and logs

[kolibri.txt](https://github.com/learningequality/kolibri/files/11063084/kolibri.txt)
[daemon.txt](https://github.com/learningequality/kolibri/files/11063087/daemon.txt)

## Expected behavior

Users on Windows 10 are able to create learn-only users.

## User-facing consequences

Affects ability of learn-only users to use Kolibri on Windows 10

## Context
0.16.0-alpha10
Windows 10 VM (Quad Core with 16MB RAM)

**Comment by radinamatic** [comment]
Basically, I was only getting the blank screen once I selected the option **Create a new user for an existing facility**.

There was a suggestion that it might be because of the resource-constrained VM system, but I bumped the machine to 4 cores and 16MB of RAM, restarted the setup wizard from scratch, and the result was the same.

Creating a new user for and existing facility from the Ubuntu device was successful.

@pcenov is trying to replicate on his side to confirm.

**Comment by pcenov** [comment]
This must have been a temporary glitch or a browser caching issue as I am not able to replicate in 0.16.0-alpha10 on Windows 10:

https://user-images.githubusercontent.com/79847249/227559496-3da2fba0-da7b-4250-ad66-08836d35a9d0.mp4

**Comment by radinamatic** [comment]
Good news 🎉 , I will try once more on my side with a different Windows 10 VM setup, and close if unable to replicate.

**Comment by radinamatic** [comment]
Closing as unable to replicate anymore with 0.16a11.
