### ISSUE TITLE
Learner > Class > Lesson - 'Not Found' error page is displayed after clicking the 'Go back' button

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10360]
## Observed behavior
A 'Not Found' error page is displayed after clicking the 'Go back' button while viewing a resource within a Class. The URL in the browser is: http://127.0.0.1:8080/en/learnundefined#/?

## Expected behavior
The 'Go back' button should bring the user back to the Class > Lesson page

## Steps to reproduce the issue
1. Install the the following [Alpha 11 build ](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-alpha11) 
2. As a learner view a resource from a lesson and click the 'Go back' button

## Video

https://user-images.githubusercontent.com/79847249/229148816-36cf8e60-2c16-45e3-9b8b-540c89f5d7f9.mp4

## Usage Details
Windows 10, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
Wth is` /learnerundefined/` in the URL? Did they got disconnected somehow? 😕

**Comment by Wck-iipi** [comment]
@radinamatic I think `/learnerundefined/ `was created because `genExternalBackURL()` was called on the wrong URL. Since `genExternalBackURL` returns a `base` (returns "/en/learn"), `path` (returns undefined), `?` and `new URLSearchParams(query)` (returns "") [as it returns `${base}${path}?${new URLSearchParams(query)}`], and javascript just converts each to string, concatenates them and gives this weirdly confusing url.
