### ISSUE TITLE
Unavailable network device not listed as unavailable

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10411]
## Observed behavior
Reported by: @bjester in the alpha-12 bug bash

Network device that was unavailable did not show as unavailable; the device was blocked by firewall.

![Screenshot from 2023-04-06 12-52-19](https://user-images.githubusercontent.com/46411498/230502949-e365daa6-6990-460f-b5ae-5123c8bd7104.png)

## Expected behavior
Unavailable network devices are not displayed as available.

## User-facing consequences
Confusion and errors can occur if unavailable network devices can still be selected.

## Context
0.16.0-alpha12
Using Android app download `kolibri_0.16.0a12-0ubuntu1_all.deb`

**Comment by pcenov** [comment]
@radinamatic - I'm not able to replicate the above issue, my guess is that it was fixed at some point as currently I am seeing the expected behavior (which we assume is to actually see the firewalled device in the list but shown as a disabled radio button):

![2024-04-09_14-09-01](https://github.com/learningequality/kolibri/assets/79847249/cde2fee7-7138-4610-8c44-3866bb301375)

Steps to replicate:
On my Ubuntu device I have setup a full facility, and on the other Windows device I am going through the Setup Wizard and want to import a learner on a Learn-only device. So to replicate the issue above one needs to enable the firewall on the Ubuntu device by typing `sudo ufw enable` and then on the Windows device to go though Group learning > Learn-only device > Import one or more existing user account from an existing facility.

**Comment by radinamatic** [comment]
Closing as not extant anymore! 💥
