### ISSUE TITLE
Reduce gutter size for content blocks on mobile

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10530]
## Observed behavior
Noted by @bjester in the alpha12 bug bash: 

The gutter size could be reduced on mobile, which would make better use of the space. Any suggestions @jtamiace @tomiwaoLE ?

![gutter](https://user-images.githubusercontent.com/17235236/233401900-9c00c26e-7f55-4902-b419-699e4e401ca1.png)

## Context
0.16.0-alpha12

**Comment by bjester** [comment]
Addressing this is beneficial for Android / mobile UX, because the hefty gutter increases the likelihood of unnecessary  horizontal scrolling within cards, like the table shown in the screenshot. There's too much dead space which can be better served displaying card content to the fullest extent possible

**Comment by jtamiace** [comment]
8px could do pretty nicely I think

<img width="506" alt="Screenshot 2023-04-20 at 11 42 19 AM" src="https://user-images.githubusercontent.com/6668144/233458540-904899b0-15b1-4e04-b8e1-10fb3d8d2df6.png">
