### ISSUE TITLE
Coach >Plan > Lessons - Missing translation for 'No visible lessons'

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10540]
## Observed behavior
See the attached screenshot.

## Expected behavior
The translation should be displayed correctly.

## Steps to reproduce the issue
1. Install the build asset from https://github.com/learningequality/kolibri/pull/10487
2. Go to Coach >Plan > Lessons and filter by status Visible

## Screenshots
![2023-04-20_17-02-28](https://user-images.githubusercontent.com/79847249/233631879-fde793c1-1bf1-4543-a3e6-510edf849a22.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by AllanOXDi** [comment]
Hi @pcenov when I was trying to investigate on this issue , I discovered that the string [declared](https://github.com/learningequality/kolibri/commit/6f34f64036278ca6742cb4c92eea03509286633b) is not complete, It is missing  the correct format. I think could be the reason for the issue-and because of this, it might have been missed during translation.

**Comment by radinamatic** [comment]
@AllanOXDi There was a [decision to replace specific strings for 0 filtered results with a generic one `No results`](https://learningequality.slack.com/archives/CB37UM23A/p1678892072445599). This string has been included in the [commonCoreStrings](https://github.com/learningequality/kolibri/blob/e332e6937b43f42b05c4b462309b48175865df64/kolibri/core/assets/src/mixins/commonCoreStrings.js#L393) prior to the string freeze, and has been translated. What probably happened is that this decision has not been implemented to all possible options, and hence it's displaying the old version (which has not been translated).
