### ISSUE TITLE
Two clicks required on first load of setup wizard "Continue"

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10597]
## Observed behavior
Noted by @bjester in the alpha 13 bug bash 
https://www.notion.so/learningequality/First-load-of-setup-wizard-always-requires-2-clicks-on-very-first-Continue-86285b42b48b4dce98a3eff51336d0c1?pvs=4

> First load of setup wizard always requires 2 clicks on very first ‘Continue’.  Doesn’t reproduce on refresh but I’ve experienced it consistently on first page load of setup wizard

## Expected behavior
Only one click should be required 

## Context
v0.16.0-a13

**Comment by thanksameeelian** [comment]
after looking into it, i was only able to recreate this error in the special case of completing the set-up flow, deleting my `.kolibri` folder, and re-entering the setup wizard without clearing my local storage. 

i was not able to recreate it if i'd cleared all my kolibri local storage and cookies as well as deleting my `.kolibri` folder, which may be more representative of the typical user, rather than dev, experience. 

continuing to investigate & work on a small solution!
