### ISSUE TITLE
Log in/out vs Sign in/out

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1079]
## Summary

Where exactly do we stand in this? Maybe I missed the discussion where it was decided...

Small details, no rush, but just to be consistent, we have:

![kolibri - google chrome_104](https://cloud.githubusercontent.com/assets/1457929/24022068/7e3fa23c-0a61-11e7-9c44-3d16b3903d23.png)

However:

![learn - instant schools math - kolibri - google chrome_101](https://cloud.githubusercontent.com/assets/1457929/24022102/a27ef8e6-0a61-11e7-8f8f-6a303d3312d0.png)

If it's `Log in` on the homepage, it should be `Log out` from inside Kolibri.
Or, even better, change `Log in` on the homepage to `Sign in`, as in the URL.

Also, `/user/#/signup` page has a weird `Log In` in the upper right corner, purpose of which I'm not sure, since creating an account logs in automatically the new user ...

![kolibri - google chrome_106](https://cloud.githubusercontent.com/assets/1457929/24022266/aa609320-0a62-11e7-9dbf-a0fac4f76012.png)

**Comment by jtamiace** [comment]
My suggestions: on the /signin page, makes sense to change the button text to "sign in" to make it consistent with the "sign out" button

However, I think the /signup URL name should be changed to something different, because it is too close to "sign in/out". They are two different things, and this could be made evident by having different verbs, phrasing, and style. Something like /create_account or /new_account (or something else)

Following all that, the "Log in" text on the /signup page should be "Sign in"

**Comment by jtamiace** [comment]
http://uxmovement.com/buttons/why-sign-up-and-sign-in-button-labels-confuse-users/
