### ISSUE TITLE
403 Forbidden error in quiz/lesson track progress on LODs

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11045]
## Observed behavior
Reported by @nucleogenesis 
> PUT http://localhost:8080/api/logger/trackprogress/03de6052b239818befdf2f4c8c0c5bc3/ 403 (Forbidden) after completing a quiz/lesson

This may be connected to existing bugs in some of the syncing work, and may or may not be resolved alongside those fixes.

## Expected behavior
No track progress error when user completes a quiz or lesson

## User-facing consequences
Progress not correctly syncing

## Steps to reproduce
1. Set up a LOD and join a facility
2. Work through an assigned lesson or quiz 
3. Observe a 403 error on quiz completion

## Context
0.16.0-beta0

**Comment by jredrejo** [comment]
According to my tests, it seems the frontend is sending two progress requests, first one is correct, next one is not because the payload is empty:
![image](https://github.com/learningequality/kolibri/assets/1008178/b6af2704-3518-4d5a-9d57-c6e74116654a)
![image](https://github.com/learningequality/kolibri/assets/1008178/dce152d3-b23c-4bcc-aecd-ee3f2f970be4)

It only happens when doing quizes, not with lessons.
@marcellamaki Is there anything else to check to reproduce it with lessons?

**Comment by marcellamaki** [comment]
I'm not sure, @jredrejo - maybe @nucleogenesis can remember something from his testing during the bug bash though! Jacob, any suggestions for José?
