### ISSUE TITLE
"Remove selected" does not work as expected

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11044]
## Observed behavior
As reported by @nucleogenesis in the beta0 bug bash
> Even when downloads table is interactable, the “Remove selected” does nothing

## Errors and logs
```
500 error DELETE /api/content/contentrequest/0
```

## Expected behavior
List of selected items should all be removed

## User-facing consequences
User cannot delete multiple 

## Steps to reproduce
Download several items. Select multiple, and use the "delete selected" to remove them

## Context
v0.16.0beta0

**Comment by amitpanwar789** [comment]
I want to work on this bug ?

**Comment by rtibbles** [comment]
Hi @amitpanwar789 - this issue is already assigned to @marcellamaki, please look for issues tagged as Help Wanted https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+help+wanted%22 or Beginner Friendly to help contributing https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+beginner+friendly%22+
