### ISSUE TITLE
Display of resources limited by apparently wasted vertical space

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11074]
## Observed behavior
Browsing on an Android device:
![Android Learn Display](https://github.com/learningequality/kolibri/assets/1680573/a8c66abb-547c-493c-80a6-c977065e2440)

Also during the loading state, it seems the breadcrumb was displayed in a fully expanded style, rather than collapsed (I assume this was only because the children had not loaded yet).

## Expected behavior
Display should be significantly more compact, and prioritize showing the resources to the user, rather than pushing them below the fold.

## User-facing consequences
Seeing very little that is informative on first page load.

## Steps to reproduce
Browse Kolibri Studio remotely on breakpoint 0.

## Context
Kolibri Android App

**Comment by rtibbles** [comment]
I tried again, and this time the no-collapse replicated and persisted:
![expanded breadcrumb](https://github.com/learningequality/kolibri/assets/1680573/89d083d6-d963-4d7e-b2cb-df1b4f1d65d9)

**Comment by LianaHarris360** [comment]
In regards to the uncollapsed breadcrumb style, this seems to be the only topic folder I can find with this particular set up. `Listening and Learning Strand` has two ancestors (`Prekindergarten English Language Arts` and `EngageNY (en)` ). I believe the fully extended breadcrumb is intentional here because the topic folder `Prekindergarten English Language Arts` would have no subsequent content to display besides the folder `Listening and Learning Strand` itself.
