### ISSUE TITLE
Device > Settings - The 'Save changes' button is changing it's position

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11178]
## Observed behavior
When I go to Device > Settings for the first time then I see the 'Save changes' button correctly positioned at the bottom right of the screen. However if I navigate specifically to the 'Info' page and then go back to 'Settings' then the button is no longer positioned correctly.

## Expected behavior
No changes in the button's position.

## Steps to reproduce the issue
1. Install the latest [Beta 4 build](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta4).
2. Go to Device > Settings and observe the position of the button.
3. Go to Device > Info
4. Go back to Device > Settings

## More information

https://github.com/learningequality/kolibri/assets/79847249/4ec8c28c-6d2b-45e7-a309-00e01a2075da

## Usage Details
Kolibri 0.16beta4
Windows 10, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by nikkuAg** [comment]
Is this issue still open? I would like to work on this.

**Comment by MisRob** [comment]
Hi @nikkuAg, yes it is and you're welcome to tackle this one

**Comment by nikkuAg** [comment]
@MisRob, on which branch should I create the PR?

**Comment by nikkuAg** [comment]
@MisRob, I have opened a PR, please review it

**Comment by MisRob** [comment]
Thank you, @nikkuAg, we will have a look

**Comment by 0xV0YD** [comment]
@MisRob   is this issue still open , if yes then can you assign it to me?

**Comment by MisRob** [comment]
Hello @yash1378. this has already been fixed by @nikkuAg in https://github.com/learningequality/kolibri/pull/11186

**Comment by 0xV0YD** [comment]
@MisRob   can you please suggest me some beginner friendly issues as i am totally a newcomer?

**Comment by MisRob** [comment]
Hi @yash1378, thank you for your interest. I just opened an issue here https://github.com/learningequality/kolibri/issues/11287 that should be very simple so I'd recommend that as the first one. Just a note that you need to do your setup on `release-v0.16.x` branch rather than `develop` for that work. Please send us a comment on that issue, otherwise I won't be able to assign you.

If you haven't seen it already, I recommend checking out the contributing guidelines https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md.

We'll probably have some more issues here in Kolibri or perhaps in Studio (other product we welcome contributions for) next week.
