### ISSUE TITLE
HorizontalNavigationWithOverflow isn't always providing the overflow correctly

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#11423]
Expected behavior is to show the ellipsis button when there's not enough room:

Mac app (Mac OS Catalina 10.15.7):

https://github.com/learningequality/kolibri/assets/79847249/c9c66004-3c09-40a5-b43f-422af46dfe7c

Note that this has not been replicated on newer MacOS versions, and so may be an issue with the older MacOS version specifically, or may be a result of resource constraints on the device.

Chrome browser (correct behaviour):

![2023-10-17_12-13-11](https://github.com/learningequality/kolibri/assets/79847249/c37b691d-cf22-4c37-a91c-ab2b5ebe1e71)

_Originally posted by @pcenov in https://github.com/learningequality/kolibri/issues/11386#issuecomment-1766008862_

**Comment by bjester** [comment]
We need to figure out how to reproduce this for development/fixing purposes

**Comment by nick2432** [comment]
Can I contribute to this issue? I'm new here, but I have experience contributing to many other organizations. Is there a Discord channel or any other channel where I can discuss and get assistance?

**Comment by akolson** [comment]
Hi @nick2432!

Thank you for your interest in contributing to this this issue. However, this issue is MacOS specific(Mac OS Catalina 10.15.7) issue and requires replication on that specific environment. If you have access to this kind of device and OS version, you are welcome to contribute. 

Otherwise I advise you choose from a host of other [Kolibiri issues](https://github.com/learningequality/kolibri/issues) available in our backlog, more specifically looking out for issues with the `help wanted` label. You can also look into [Studio](https://github.com/learningequality/studio/issues)(with `good first issue` label) and [KDS](https://github.com/learningequality/kolibri-design-system/issues) issues too.

Concerning channels, you are welcome to join our developer community slack channel by writing to `info@learningequality.org` requesting to be added. 
We look forward to having you as a regular contributor and member of our developer community.

Thanks again!

**Comment by marcellamaki** [comment]
I've been able to replicate a related incorrect overflow experience on mobile browser Kolibri. My suspicion is that something with the dynamic calculating of what is appearing and what is in the overflow menu is going awry. Here you can see that sometimes the overflow menu button is rendering properly, and sometimes it is not, and sometimes the last "visible" item in the menu bar is disappearing.

https://github.com/learningequality/kolibri/assets/17235236/01dd762e-582b-472a-b62a-3720d1b85b35

I'll reprioritize this, because it will be important to fix this for 0.16 since it is impacting the browser versions of Kolibri, not just the mac app.
