### ISSUE TITLE
internationalize user-facing strings in javascript files

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1144]
Currently, no user-facing strings in .js files are internationalized. Once our intl library supports it, let's audit for all user-facing strings. (https://github.com/learningequality/vue-intl/issues/11)

see e.g. https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/learn/assets/src/state/actions.js#L182

**Comment by rtibbles** [comment]
This is not a `vue-intl` limitation, but rather a limitation with how we look for user facing strings to extract for translation.

My proposal for how we approach this is to replicate the system we have used in the `.vue` files - if a JS file wants to expose translations it should define the following two variables:

`const $trNameSpace = 'namespaceHere';`
```
const $trs = {
    someMessageDescription: 'Some message to translate',
};
```

Unfortunately, dissimilarly to Vue components, we cannot rely on the internals of Vue in order to magically use these variables, so we would have to set up the translation function with them in order to use them. For that we could have a function such as:
```
import { get$tr } from 'kolibri.utils.i18n';

const $tr = get$tr($trNameSpace, $trs);
```

The `$tr` function could then be invoked as it is ordinarily in vue components, by passing the key of the message into it to retrieve the translated text.

**Comment by indirectlylit** [comment]
This looks good to me overall. I'd be happy to use this.

----

Unrelated to this PR: if possible, I'd love it if we could the `$trNameSpace` parameter and instead auto-populate it with the plugin name and file path:

* seems like boilerplate
* we're inconsistent with how these namespaces are set
* plugin name + filepath will often give a translator more context than what we put there, and make it easier for them to view the source if desired

----

Specific to this PR: One potential API alternative would be to create a "translator object":

```javascript
import { createTranslator } from 'kolibri.utils.i18n';

const i18n = createTranslator({
  someMessageDescription: 'Some message to translate',
  anotherMessageDescription: 'Another message to translate',
});

console.log(i18n.$tr('someMessageDescription'));
```

**Comment by rtibbles** [comment]
For the things specific to this implementation, I am not sure what other methods the translator object would have except `$tr`, which is why I suggested just creating the function itself.

For the other items, I had looked into doing that, and it was a pain - I can see a way to do it now, but it will involve dynamically injecting these variables into the code at build time.

**Comment by indirectlylit** [comment]
sounds good. I might still prefer another name than `get$tr` (similar to `createTranslator`, or something similarly explicit). To me, `get$tr` reads like "get translation".
