### ISSUE TITLE
Display a meaningful error warning when KDS path is not provided when running `yarn run devserver-with-kds`

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#11632]
This is a follow-up to https://github.com/learningequality/kolibri/pull/11446 which introduced `devserver-with-kds` package.json command. This command requires KDS path being specified, e.g. `yarn run devserver-with-kds /path/to/kolibri-design-system`.

Currently, when we forget to specify the KDS path and run only `yarn run devserver-with-kds`, unless one is familiar with the command in detail, it is hard to figure out why the command doesn't work as expected.

We'd ideally show an error warning when the path is missing.

**Comment by KshitijThareja** [comment]
Hi @MisRob. I'd like to work on this issue. Could you please assign it to me?
Thanks :)

**Comment by MisRob** [comment]
Hi @KshitijThareja, thank you. I'd like to wait to @Jaspreet-singh-1032 for a bit to confirm whether he'd like to work on this since it's a follow-up to his recent work and we talked about continuing some of it.

**Comment by Jaspreet-singh-1032** [comment]
@MisRob, thanks for creating this follow-up.

Hi @KshitijThareja, If you want to work on it, you can proceed. Feel free to let me know if you need any help.

FYI I had added a kds flag in the previous [PR](https://github.com/learningequality/kolibri/pull/11446#discussion_r1374150521) to know if the yarn command is run using `devserver-with-kds`. But it was removed later because It was an extra flag and was not needed at that moment. But now I think you will need to add that flag back because otherwise, I think there is not any other way to know if the yarn command is run using `devserver` or `devserver-with-kds`. So, I think you can use this approach or try if you have any other ideas.

**Comment by KshitijThareja** [comment]
Thanks @Jaspreet-singh-1032. I'd definitely approach you if I need any help. And thanks for your suggestion too, I'll look into it.

**Comment by MisRob** [comment]
Okay, thanks both :) Assigning you, @KshitijThareja

**Comment by MisRob** [comment]
@KshitijThareja I've just merged @Jaspreet-singh-1032 PR https://github.com/learningequality/kolibri/pull/11446/ to the release branch so it should be now available for further work

**Comment by MisRob** [comment]
Closed by https://github.com/learningequality/kolibri/pull/11657
