### ISSUE TITLE
devserver-with-kds: The --watchonly flag being stops watching KDS changes

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#11667]
## Observed behavior

Follow-up from #11657 [(comment)](https://github.com/learningequality/kolibri/pull/11657#discussion_r1434517955)

## Expected behavior

When using the sweet new `devserver-with-kds` command it would be nice to be able to use `--watchonly` as well while still getting the automatic rebuild from changes occurring only in KDS.

## Steps to reproduce

Example:

`yarn devserver-with-kds path/to/kds`

Here you can go into your local KDS and make a change then the front-end will rebuild each Kolibri plugin where that change affects it (ie, if you change KTextbox then all plugins using that component will rebuild).

`yarn devserver-with-kds path/to/kds user_auth` 

This is only `--watchonly`-ing on changes to the `user_auth` plugin now so when you make a change in KDS you won't see it reflected unless you make a change in the `user_auth` plugin.

**Alternatively** we could simply remove the `--watchonly` flag from the `devserver-with-kds` script. However, this would still not be ideal.

**Comment by iskipu** [comment]
Hi @nucleogenesis ,
while trying to fix this issue i came across some problem 
`yarn run devserver core,learn` (throwing error i believe its bcz my development environment is windows)

however if `yarn run devserver core,learn` command works properly in ur environment, i think this issue can be fixed by running core along with whatever plugin user inputs i.e
 `yarn devserver-with-kds path/to/kds user_auth`
should be ran as 
`yarn devserver-with-kds path/to/kds user_auth,core` (cli.js should be modified such that core is always ran when using watch only with devserver-with-kds) so that kds changes get reflected.

**Comment by rtibbles** [comment]
Hi @iskipu - I think that's broadly accurate, as KDS components are registered in core. I think making the modification to always watch for changes to core if the KDS path option is passed makes the most sense.

**Comment by nick2432** [comment]
can i work on this?

**Comment by bjester** [comment]
Hi @nick2432, I just assigned you to a different issue. I see you're now assigned 3 issues, so when those others are completed and fixes merged, please comment again on this issue and we can assign you. Thank you for your interest in contributing

**Comment by thesujai** [comment]
Hello @bjester, please assign this to me

**Comment by AlexVelezLl** [comment]
Hi @thesujai I will assign this issue to you, thank you!

**Comment by rtibbles** [comment]
Fixed in #11785
