### ISSUE TITLE
Difference in class activity notifications after full facility import

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11782]
## Observed behavior
In a [recent test](https://github.com/learningequality/kolibri/pull/11765#issuecomment-1906241734) I noticed some differences between class activity notifications displayed between two devices after the full facility import. Today I could not replicate the 'need help' status disappearance after full facility import from Win11 (0.16b10) to Win7 (0.16b13), howver, the class activity notifications continue not to display on the source (Win11) device anymore. The last syncing activity on that Win11 server was 5-6 days ago.

<img width="1089" alt="2024-01-24_22-11-19" src="https://github.com/learningequality/kolibri/assets/1457929/68e7fd3a-4454-452c-b693-bb059ba057cf">

## Errors and logs
[Logs and dbs](https://drive.google.com/drive/folders/1vQlYj-o4Hkcy-GmZnCNQDF8pqADk3nSV?usp=drive_link) for both servers.

## Expected behavior
Consistent display of class activity on both devices

## User-facing consequences
Confusing and inconsistent information presented to the coach.

## Steps to reproduce
Import the full facility (with some class interactions and notifications) from one server to another. 

## Context

 * Kolibri version:  Windows 11 (0.16b10) and Windows 7 (0.16b13)

**Comment by marcellamaki** [comment]
As discussed during the planning meeting, we'll downgrade to P1, but if we can possibly fit it in before 0.16.0 we will

**Comment by rtibbles** [comment]
Looking at the notification databases, this is not an issue with the notifications being properly generated, but rather that our code at some point is implicitly relying on the auto-incrementing integer id order to be indicative of the timestamp ordering for the notification. When we were generating the notifications just after the activity, this assumption held true, but now with the bulk creation after sync, it is no longer the case.

This can be fixed by ensuring that we always order the LearnerProgressNotifications by their timestamp field, not the id field.

**Comment by varshith257** [comment]
I would like to work on it

**Comment by marcellamaki** [comment]
Possibly related issue noted by @jredrejo in the 0.17.0-alpha0 bug bash:

> [Notifications don’t appear in the coach panel after failing 7 responses in a row](https://www.notion.so/learningequality/Notifications-don-t-appear-in-the-coach-panel-after-failing-7-responses-in-a-row-e6f34c2a17cd4c259cb6284b1c7c74bf)

**Comment by rtibbles** [comment]
Fixed in #12386
