### ISSUE TITLE
Facilites on devices without public channels are not visible to on-my-own devices who try to join

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11787]
## Observed behavior
While testing the change facility feature on 0.16.b13, my on-my-own Android device was not able to see the facilities on a server device (Windows 7) that at that time did not have any public channels in the library. I caught a glimpse of this situation the other day on 0.16b11, and replicated again yesterday, and I'm suspecting that it is because I only had the QA channel on the server, and was able to see its facility to join from the on-my-own Android device only **AFTER** I checked the option to make the private channels visible.

@rtibbles 

> if the filtering was accidentally filtering by 'has channels' by default ... I think it's worth opening an issue for - it feels inadvertent

![2024_01_24_23 31 42](https://github.com/learningequality/kolibri/assets/1457929/e5ed9001-0564-4174-9e20-6a4fe43cdaf0)

## Errors and logs
[Logs and dbs](https://drive.google.com/drive/folders/1vQlYj-o4Hkcy-GmZnCNQDF8pqADk3nSV?usp=drive_link) for both servers.

## Expected behavior
User on the on-my-own devices should be able to see the facilities on the devices whether they have channels imported or not.

## User-facing consequences
Impossibility to join a facility.

## Steps to reproduce

1. Set up a server without public channels in the library.
2. If you have imported the unlisted channels, do not change the default option that they cannot be seen by other devices in the network.
3. Set up the second device with ``on-my-own`` flow.
4. Go to Profile and try to change the facility. 

## Context

 * Kolibri version:  Windows 7 (0.16b13)

**Comment by marcellamaki** [comment]
Hey @radinamatic, I think this may have been incidentally resolved since January, as I haven't been able to reproduce it, and I can't see anything in the code that makes it seem clear where this could be happening, and the API request is returning the correct data. My only other thought is that it might be android-specific, although I also can't see anything apparent in the code that could be causing this to happening. 

Would it be possible for you to see if you can reproduce this still, and if so, can you try on both android and browser-based on-my-own setup? 🙏 

https://github.com/learningequality/kolibri/assets/17235236/3a78b59b-4bd4-4ef0-9afc-68d367fd74b9

**Comment by pcenov** [comment]
I'll have a look as well. Thanks @marcellamaki!

**Comment by pcenov** [comment]
I confirm that this has been fixed and now a facility without public channels is visible. @radinamatic we can close this one.

**Comment by radinamatic** [comment]
Closing as not extant anymore! 💥
