### ISSUE TITLE
I see the “You can also configure Facility settings” link in Device settings - but on a LOD I can’t access facility

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11877]
Spotted by @nucleogenesis in the 0.16 syncing session Feb 14 2024
## Observed behavior
I see the “You can also configure Facility settings” link in Device settings - but on a LOD I can’t access facility

**Comment by ishanjha03** [comment]
Can you assign me this?

**Comment by MisRob** [comment]
Hi @ishanjha03, thank you, it'd be best to volunteer for issues tagged with "help wanted" as those are ready for contribution.

**Comment by Abhishekzod007** [comment]
Hi @marcellamaki , the issue is unclear, I tried interacting with `You can also configure Facility settings` in device settings and the redirection works just fine, similarly the link from facility to device settings works fine.
I'd love to volunteer would you mind clarifying the issue a little. thnks

**Comment by marcellamaki** [comment]
Hi @Abhishekzod007 - thanks for your interest in this issue. The issue is not yet ready for contribution. I'll be updating it in the coming days, and when it's ready, it will have the "help wanted" label. I know you have volunteered for at least one other issue that you can work on in the meantime, and you can also look for other issues with the "help wanted" label, which are the best option for volunteering on.

**Comment by Abhishekzod007** [comment]
Ok thanks @marcellamaki
