### ISSUE TITLE
[Needs decisions: not ready for assignment] Update the UX in the setup wizard when a username already exists

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11882]
Scenario reported by @MisRob during the 0.16 sync session on Feb 14 

## Observed behavior
I was able to complete the page where I inserted a new learner’s username and password. 

| step  | screenshot  |
|---|---|
| as soon as my device started syncing with the Mr Tibbles facility, the sync failed | ![Screenshot from 2024-02-14 17-14-16](https://github.com/learningequality/kolibri/assets/17235236/c0bb5a57-4548-41c1-a0c4-c3101f9c640f) |
| I clicked retry and received the generic error page | ![Screenshot from 2024-02-14 17-16-12](https://github.com/learningequality/kolibri/assets/17235236/53eb0e0c-145b-462c-8889-544b8d9fb91c) |
| Then, I clicked “Start Over”. When I arrived at learner account creation, this time it said that the learner exists already (so even though I had errors, it seems it was actually created) | ![Screenshot from 2024-02-14 17-18-21](https://github.com/learningequality/kolibri/assets/17235236/9bbc523a-1b47-4cd0-b3d1-c1c8777cc93b) |

So I went back and joined the facility by importing “michaelar” user. Then, I was able to sync successfully.

## Expected behavior
This is not so much a bug (we are actually handling disconnections and failures as we should - with the created user name being indicated as available even though the entire import sync didn't succeed) as a UI that is not very seamless for the user experience.

At the UI when the user name already exists, perhaps a better approach would be to update the user experience so that we can prompt the username and password to be entered to the user can proceed, rather than making the user start over. 

For example: "Username" already exists. Sign in with your username and password [link/button]

Some additional design decisions would be helpful to figure out the best way forward.

**Comment by ishanjha03** [comment]
I'd like to add to the discussion regarding the learner account creation flow, particularly when a username already exists. I completely agree..... that while the current behavior handles disconnections well, the UI could be improved for a smoother user experience.

Here are a few options we can consider:

Direct Login: Upon encountering an existing username, display a clear message: "Username '[username]' already exists. Sign in with your username and password: [link/button]". This option provides a clear and efficient path for returning users.

Contextual Information:  In addition to the login prompt, consider offering a brief explanation like "It appears your learner account creation might have been interrupted due to a previous sync issue. Sign in to access your existing account." This clarifies the situation for the user.

Offer a Choice: We could display both options - a login prompt and a "Start Over" button. This allows users who are unsure or prefer a fresh account creation process to proceed accordingly.

It also goes without saying that we should take care of the user experience beyond the initial prompt.  This means making sure any login errors provide clear messages for troubleshooting,  using visual design elements to make the login option stand out, and finally, thoroughly testing the entire flow across different devices and scenarios  to iron out any potential bumps in the road. This level of polish will ensure a smooth and frustration-free experience for new learners.
