### ISSUE TITLE
Facility > Data - Clicking the "..." (Options) button shifts the Sync button to the left

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12186]
## Observed behavior

Clicking the "..." (Options) button shifts the Sync button to the left:

https://github.com/learningequality/kolibri/assets/79847249/a91fc2e9-73d7-4df0-8e39-7e186cfb25f0

I checked the 0.16.1 version of Kolibri and it's not extant there so it must be caused by recent changes.

## Expected behavior

The menu should be displayed under the Options button without changing the position of the Sync button

## Steps to reproduce the issue

1. Install Kolibri 0.16.2b2
2. Go to Facility >Data
3. Click the "..." (Options) button

## Usage Details
Kolibri 0.16.2b2
Windows 11, Ubuntu 22  - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
Hi @pcenov @radinamatic - I've tried to replicate this on Chrome, Firefox, and Safari, and so far I can't (I think because I'm testing on MacOS). My thought is that there might be a KDS related change that is causing this, but looking through the review notes there isn't any obvious that sticks out right away. Since it doesn't appear to be on _every_ browser and OS, I may downgrade this and have it roll into our next release, as I think the problem may require some KDS tweaks, another KDS release, and an upgrade with QA on windows and ubuntu which would be... rather difficult to do on a tight turn around. What do you think, Radina? (cc @rtibbles )

**Comment by pcenov** [comment]
Hi @marcellamaki I am able to consistently replicate that issue in all OSs and browsers but only when using the official 0.16.2b2 build while when using the build asset from this PR https://github.com/learningequality/kolibri/pull/12193 for example - the issue is not extant - so yeah, there's something strange happening here...

**Comment by marcellamaki** [comment]
Let's confirm whether or not it's in the beta3 that I'll be tagging today and we'll decide next steps after that. Thanks Peter! Useful insights as always :)

**Comment by pcenov** [comment]
Hi @marcellamaki I confirm that this issue is not extant in the Beta3 build so I am closing it.
