### ISSUE TITLE
'new class' workflow creates two classes when using keyboard

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#1224]
## Summary

 - Version:  0.4.0alpha1.dev536
 - Operating system: macOS
 - Browser: Chrome

## How to reproduce

1. Go to http://localhost:8000/management/#/classes
1. Click 'Add New Class'
1. Fill out 'Class Name' with e.g. "new unique class"
1. Tab twice to focus on 'Create Button'
1. Press enter
1. I then see two instances of "new unique class" in the list.

**Comment by christianmemije** [comment]
Due to the fact that `createNewClass` is called when the button click and also on the enter key. https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/manage-class-page/class-create-modal.vue#L6

**Comment by DXCanas** [comment]
We've come across this before, I've had luck using the a `form` and listening for `submit` instead of listening for enter.

See https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/management/assets/src/views/user-page/user-create-modal.vue#L8

Made a PR explicity addressing this not too long ago
https://github.com/learningequality/kolibri/pull/1037/files

**Comment by DXCanas** [comment]
I think the issue lies more in our use of `<button>` outside of forms, even though that was their purpose. 

IIRC, the button emits `enter` on click, which is useful inside of form because `enter` is triggers `submit` since the button is `primary` by default. This works fine, but if you tab to the button and hit `enter`, the `enter` event is emitted twice, causing the double submission.

**Comment by indirectlylit** [comment]
One work-around (without using forms) is to add `@keydown.enter.stop` as an attribute on buttons to prevent the outer `enter` event from firing. It feels a little hacky though - probably the modal's `enter` event listener is a poor design.

Maybe instead, a form wrapper with a `submit` event should be built in to the core modal instead of `@enter`?

**Comment by DXCanas** [comment]
@indirectlylit That would sort of narrow the scope of contexts where the modal is useful, i think. May be the best solution, but I think we should make the name of the component more explicit - like `modal-form` or something.
