### ISSUE TITLE
Fix nav bar item alignments and truncation 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12282]
<img width="839" alt="Screenshot 2024-06-13 at 4 29 34 PM" src="https://github.com/learningequality/kolibri/assets/17235236/ede9db30-0ce6-42e5-8916-668c7e85d8e8">

**Comment by CHIRANTH-24** [comment]
Greetings of the day @marcellamaki ,
I'm interested in resolving this issue.
Could you please assign this issue to me?

**Comment by MisRob** [comment]
Hi @CHIRANTH-24, we appreciate your interest. This issue is already assigned.

There are contributing opportunities in three repositories. See the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)
- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)
- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

You can also see the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories.

**Comment by marcellamaki** [comment]
Closed with #12496
