### ISSUE TITLE
How will be kids proceed to the next question on MG exercise?(Query)

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1243]
## Summary
How kids will process to next question if a kid does not know the answer for the current question.

## System information

*Please specify the Kolibri version you were using and your operating system!*
 - Version: Kolibri 0.4.0aplha2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce
1. Login with Learner.
2. Open the exercise of MG.
3. Start solving the exercise.

##Query
In order to address this we need to pass the correct answers as part of hint for all the MagoGenie questions in the Ricecooker/content curator itself?
Please confirm the above, Or is there any-other workaround in this case.

## Screenshots
![4](https://cloud.githubusercontent.com/assets/12776071/25118199/d6df029e-2432-11e7-814f-982176fb4a52.png)

**Comment by rtibbles** [comment]
Generally, we have tried to make the exercises mastery oriented, and as such, moving on from a question when you have not got the correct answer for it yet has not been part of the overall design.

In that vein, having hints to allow users to successfully complete a question is ideal - it is preferable if those hints work through the solution for them, rather than just give the answer - but if there are time constraints, then that may be the simplest solution.

**Comment by harishbalachandran** [comment]
@rtibbles Yes, I totally agree! Since for MagoGenie questions we do not have time to add hints that would allow the kid to work trough the problem, hence we will add the correct as the hint. 

But we are unable to work on this since the dependency on this bug logged in [Ricecooker](https://github.com/learningequality/ricecooker/issues/68). Can you please work on fixing the rice cooker one so that we can import and check this feature for MagoGenie questions.

**Comment by indirectlylit** [comment]
That seems like a reasonable workaround.

I'm going to close this issue. If it seems like this model is causing problems down the line we can revisit the design.
