### ISSUE TITLE
Create MVP Coach "channel card" using `<KCard>` to use in the resource management side panel

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12528]

**Comment by Reddi-Umamahesh** [comment]
Hi @marcellamaki , I’m working on the MVP Coach "channel card" using <KCard>, but I’m unsure where to implement this in the codebase. Could you point me to the relevant files or directories? 
Thanks!

**Comment by MisRob** [comment]
Hello @Reddi-Umamahesh, welcome! We appreciate your interest, however this issue is really not ready to be worked on. Before starting to work on an issue, please make sure to ask for an assignment first and wait for our response.

There are contributing opportunities in three repositories. See the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)
- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)
- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

You can also see the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories.

**Comment by Reddi-Umamahesh** [comment]
Hi @MisRob 
Thank you so much for the guidance! I appreciate you pointing me in the right direction and will make sure to follow the guidelines moving forward

**Comment by marcellamaki** [comment]
Addressed with https://github.com/learningequality/kolibri/pull/12607
