### ISSUE TITLE
Move core notifications handling into NotificationsRoot component

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#12626]
Currently all the admin notifications are handled through the core vuex state, but these are only accessed and used in the NotificationsRoot component and its child component UpdateNotifications.

- [x] `notifications` state should instead be set as a data property on the NotificationsRoot component.
- [x] The [two actions](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/state/modules/core/actions.js#L182) should be moved into methods of the NotificationsRoot component, and refactored to directly alter the notifications property, rather than use Vuex mutations
- [x] `getNotifications` should now be called in the `created` hook of the NotificationsRoot component, and references to the action in kolibri_app.js and its associated spec file should be removed
- [x] the `notifications` state key should be deleted along with any associated Vuex mutations

**Comment by iamshobhraj** [comment]
@rtibbles can you please assign me this issue.

**Comment by rtibbles** [comment]
Yes, assigned! Feel free to ask any follow up questions here!

**Comment by iamshobhraj** [comment]
> Yes, assigned! Feel free to ask any follow up questions here! 

What two actions are to be moved as methods in NotificationRoot component. I could only find one action from the given link.

**Comment by MisRob** [comment]
Hi @iamshobhraj. From function names I would assume the other one could perhaps be `saveDismissedNotification`? But basically the idea here is that anything notification related that is used from the `NotificationRoot` needs to be in this component rather than in the global Vuex state. So even though there's useful tasks in the issue as pointers, I'd still recommend you to examine how it works right now and simply make sure all that is used solely by the `NotificationRoot` is placed in it.

**Comment by MisRob** [comment]
@iamshobhraj Perhaps you've already done that, so just a general recommendation - always best to preview that logic before/after on the dev server. Then you will also get a mental picture of how the user experience looks like as well as what's going on under the hood, and can use it for verification that it still works as expected after the refactor. Thanks :)!

**Comment by nucleogenesis** [comment]
Closed by #12644
