### ISSUE TITLE
Implement "Filter by Groups" functionality with new information architecture page structure

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12706]
### Overview 

The "filter recipients" is a way to limit the view of a particular overview table within Coach (i.e. lessons, quizzes) to show only items assigned to given recipients. 

It should be a dropdown menu that for now does a client-side filter corresponding to the "recipients" column. (As we update coach to make use of `KTable`, we may have a larger discussion about whether or not we want to use some type of pagination of external/backend sorting). 

The "recipients" can be:
- 'Entire class' 
- any groups that the coach has created
- individual learners. 

Examples from the current UI of the "recipients" column: 

![Image](https://github.com/user-attachments/assets/5fb55ca1-79a4-4494-bdb1-a1d1dca913e0)
![Image](https://github.com/user-attachments/assets/38f1dc29-b47d-40e9-ae88-6e7ece8de05d)

### Acceptance criteria 

1. The "options" in the KSelect are generated based on the "Recipients" that are available in the table, in any row. (Take a peek at some of the `dataHelpers` for finding out where these group names are in state, and how you might access them at the page, not just displaying in the row) 
2. When a user makes a selection, the table should update with the matching recipients 
3. The filter should be inclusive. For example, if Quiz 1 is assigned to Blue Group and Red Group, Quiz 2 is assigned to Blue Group only, if you select "Blue Group" in the dropdown, Quiz 1 and 2 **should both** be displayed. If you select Green Group, it would not display.

**Comment by hustlernik** [comment]
@marcellamaki Can I take this issue?

**Comment by AlexVelezLl** [comment]
Hey @hustlernik! Thanks for your interest in contributing to Kolibri! Unfortunately this issue is not marked as `help wanted` so it was not initially intended for open source contribution per se (You can take a look at the Kolibri [contribution guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)). @marcellamaki will be able to indicate if this is the case, but in the meantime you can take a look at the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories. Let me know if you have any questions :).

**Comment by hustlernik** [comment]
@AlexVelezLl Sure, I will look into it.

**Comment by ozer550** [comment]
Picking this up as a follow up to #12670.
