### ISSUE TITLE
When importing from local network(self hosted studio), devices are unavailabe until some another device with same IP is created

### ISSUE THREAD

**Issue by thesujai** [learningequality/kolibri#12750]
## Observed behavior

**Devices with same IP are shown unavailable**
![Image](https://github.com/user-attachments/assets/47ebbcd5-1b24-4f4c-8938-175d0f1fd39b)
**Now I add another device with same IP, it is availabe**
![Image](https://github.com/user-attachments/assets/7ce21178-d202-41fd-8d7f-88fd0107a5c3)

Now if I refresh again after some time(don't know how much time), then the newly available device is also somehow unavailable, even when the studio is running locally

## Errors and logs

When the `SelectDeviceForm` component renders, a request is made to `update_connection_status/` which will give a 500:
```
[python-devserver] ERROR    2024-10-25 16:01:18,989 Internal Server Error: /api/discovery/networklocation/62143eb22ca04e618af313010afe9d92/update_connection_status/
[python-devserver] Traceback (most recent call last):
[python-devserver]   File "/home/sujai/.pyenv/versions/3.9.9/envs/kolibriNew/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
[python-devserver]     return self.cursor.execute(sql, params)
[python-devserver]   File "/home/sujai/.pyenv/versions/3.9.9/envs/kolibriNew/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
[python-devserver]     return Database.Cursor.execute(self, query, params)
[python-devserver] sqlite3.IntegrityError: NOT NULL constraint failed: discovery_networklocation.operating_system
```

`operation_system` response field from studio's api/public/info should not be None as it is now([code](https://github.com/learningequality/studio/blob/unstable/contentcuration/kolibri_public/views_v1.py#L157)). 

1. It can be empty or can at least attempt to get the os using some tools in studio itself
2. Else this has to be handled in kolibri, which is better as it is the responsibility of this server to handle the any foreign data

I think both kolibri and studio be updated with changes

## Expected behavior

If the studio is running, the devices should be available

## User-facing consequences

No idea, but I faced while working on an issue, everytime I updated the studio channel, I added another device in kolibri

## Steps to reproduce

1. Make sure a Kolibri and a studio instance is running
2. Go to Devices>Channels>Import>Local Netwok
3. Add a device with default IP of studio `0.0.0.0:8080`(It will work)
4. After some time refresh it and it will become unavailable
5. Add another device, it will work, but after some time this will also become unavailable too
## Context

 * Kolibri version: 0.17.2
 * Operating system: Ubuntu 22 LTS
 * Browser: Firefox and Chromium

**Comment by rparadowski** [comment]
@thesujai Normally you cannot connect to other devices using 0.0.0.0. Please see https://superuser.com/questions/949428/whats-the-difference-between-127-0-0-1-and-0-0-0-0

You are trying to connect an instance of kolibri to itself. To test that, please change port of second kolibri instance (so two instances use different ports). You will see that you are not able to connect to correct port (for that you also need to host them on different hosts).


I believe kolibri shouldn't allow for connecting to itself at first place. @MisRob please let me know if I should change that behaviour.

**Comment by bjester** [comment]
@thesujai In order to connect to a local instance of Studio, you should use the `CENTRAL_CONTENT_BASE_URL` [option](https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/options.py#L574), in the Kolibri instance's `options.ini`. Once that is done, you can select the Studio option within Kolibri as you normally would. We've been making some changes to how network locations are handled in Kolibri, and since Studio is not a Kolibri instance itself, adding a local instance of Studio manually in this manner will cause Kolibri to assume it's a Kolibri instance and it just won't work currently.

Also, @rparadowski is correct about `0.0.0.0` and that a Kolibri instance will not connect to itself. Also, their guidance on connecting  2 running Kolibri instances is also appropriate. Thank you @rparadowski !

**Comment by rparadowski** [comment]
@bjester There is still something wierd as it is possible to add device to itself (regardles of performing import) using 0.0.0.0 address:
![Image](https://github.com/user-attachments/assets/9139dd4b-26e6-42d0-8a76-6c8008da5db4)

but it is not possible providing direct address:
![Image](https://github.com/user-attachments/assets/519adc62-4f7d-4dca-af49-ed153f0581f9)
![Image](https://github.com/user-attachments/assets/7d30d136-f035-4d29-8f85-c35acaa95f80)


I could dig into it but I can't see how this response is recieved:
https://github.com/search?q=org%3Alearningequality%20COULD_NOT_CONNECT&type=code

**Comment by bjester** [comment]
@rparadowski Hmm yeah if `0.0.0.0` is being accepted, that is likely something we should address. I don't think allowing it is appropriate, because the the location address is meant to be specific. So the use case for `0.0.0.0` does not apply in this situation. There's also backend code which checks different ports on an address, so this would be problematic with `0.0.0.0`. Finally, end users of Kolibri would most likely not run into such situations where adding `0.0.0.0` would make sense.

As for your other comment, the frontend for network devices is a bit behind newer functionality we've built into the backend. I believe the modal should be making background API calls which in turn may test a connection, but also provides a connection status
