### ISSUE TITLE
Search - 'Clear all' is not resetting the dropdowns

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12821]
@nucleogenesis I did notice one thing while testing over the weekend, and I wanted to investigate more but then the ⛈️ happened: `Clear all` button does clear the displayed search results **and the filter** applied for the search actions performed using _Keywords_, _Categories_, _Activities_ and the _Show resources_ options. 

However, it does not clear the applied filters for any of the dropdown options (_Language, Level, Channel, Accessibility_). Search results are cleared, but the previously applied filter apparently stays visible, but not actually _applied_ anymore, and the user needs to clear them manually. This can be confusing and we should force them cleared as for the other filtering options in the sidebar.

https://github.com/user-attachments/assets/0ddf0972-971d-44e4-8037-9a72ecf61788

_Originally posted by @radinamatic in https://github.com/learningequality/kolibri/issues/12745#issuecomment-2457076719_

**Comment by pcenov** [comment]
@radinamatic - opening a follow-up issue for that comment, so that we can keep track of it.

**Comment by SukhvirKooner** [comment]
I'd like to take on this issue. Please assign it to me.

**Proposed Solution:**

**Extend the State Reset Logic:**

I will ensure that when the 'Clear All' button is clicked, all state variables associated with the dropdown filters (Language, Level, Channel, and Accessibility) are explicitly reset to their default values (e.g., null or default options). This can be achieved by enhancing the existing state management logic, potentially in the useState .

**Trigger Dropdown Re-rendering:**

I will make sure to trigger a re-render for all affected dropdown components when the state is reset to guarantee that the visual state of the dropdowns reflects the cleared state. This will prevent any stale UI behavior and align with the behavior for other filters.

**UI Consistency Check:**

I plan to introduce a unit test or an automated UI test to verify that when the 'Clear All' button is pressed, all dropdowns are effectively reset, alongside any search results or other filters, maintaining a consistent user experience.

**Comment by MisRob** [comment]
Hi @SukhvirKooner, thanks for volunteering! This issue is not open for contribution.

There are contributing opportunities in three repositories. See the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)
- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)
- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

You can also see the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories.

**Comment by AllanOXDi** [comment]
Hi @pcenov could you confirm if this issue still persist.  There was a big internal refactor in KSelect for v5 that broke it and it should be fix now.

**Comment by radinamatic** [comment]
Great news: the original issue is not replicable on the latest assets from the develop branch! 👍🏽 💯 🥳 

All previously applied filters in the Library search are now properly cleared by the **Clear all**.

Closing as not extant anymore.
