### ISSUE TITLE
Coach user should not have access to the class which he does not belong to.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1391]
## Summary
If the coach is not in a class then he should not have access to that class.

## System information

 - Version: Kolibri 0.4.0alpha6
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1.  Login as a coach user.
2. Observe the behaviour.

## Screenshots
![class bmw](https://cloud.githubusercontent.com/assets/12776071/25529298/1acd6568-2c3f-11e7-8c17-072ac706b45a.png)
![coach screen](https://cloud.githubusercontent.com/assets/12776071/25529297/1acd10d6-2c3f-11e7-8068-7dd246df2527.png)
![have acess to all the classes as a coach](https://cloud.githubusercontent.com/assets/12776071/25529296/1acb2f5a-2c3f-11e7-9e80-898ae1f4aec6.png)
![not a coach in hp](https://cloud.githubusercontent.com/assets/12776071/25529299/1acf23b2-2c3f-11e7-939f-b14f4b7789c7.png)

**Comment by indirectlylit** [comment]
The current implementation is a little different from the original spec. For some context:

The original implementation had functionality to elevate a Learner to Coach status on a per-class basis. However, the UI had a few issues (both bugs and design). e.g...

* showed class coaches as facility coaches because the API simply aggregates a list of all roles (#1280)
* All classes were shown to a coach of a single class (#1281)
* Many users were confused that they could not create a Coach during user management, and that they had to add a user to a class first.

We disabled class coaches here: #1290

@swapnil106111 we still need to confirm that this is acceptable for Nalanda's use cases.

Assuming this change is acceptable, some of the language on this page is still confusing. In particular:

* "Manage Learners and Coaches in this class" should be changed to "Manage learners in this class"
* The role column with 'admin' and 'coach' labels should be removed, because it it seems to imply that these are class admins and class coaches, but in fact they are facility admins and facility coaches.

**Comment by harishbalachandran** [comment]
@indirectlylit Thanks for detailed input. 

So, at present considering the challenges, we are okey to say that the Coach user is more like a Facility wide coach and not a class only.

**The two points you have mentioned can be changed to make it more relevant:**
1. "Manage Learners and Coaches in this class" should be changed to "Manage learners in this class"
2.  The role column with 'admin' and 'coach' labels should be removed, because it it seems to imply that these are class admins and class coaches, but in fact they are facility admins and facility coaches.

**Comment by DXCanas** [comment]
Closing because of #1401 being merged.
