### ISSUE TITLE
The attempts for each question that learner takes in an exam is incorrect.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1429]
## Summary
The attempts history for each question that learner takes in an exam is incorrect.

How are these attempts calculated? Also I don't remember making those attempts the tare shown in the screenshot. 

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Give an exam
2. Check the reports  
3. Validate each of the attempts.

## Screenshots
![attempts 1](https://cloud.githubusercontent.com/assets/13453618/25662344/d04b8564-3031-11e7-871a-e97436af9b62.png)

![attempts 2](https://cloud.githubusercontent.com/assets/13453618/25662347/d43b0c3a-3031-11e7-96ca-d441e12cc057.png)

![order](https://cloud.githubusercontent.com/assets/13453618/25662415/1519fd10-3032-11e7-9051-3567c90abc61.png)

**Comment by rtibbles** [comment]
Hi @harishbalachandran most of these are caused by the fact that we are aggressively recording the responses, so as to immediately update the answer status, as requested in https://github.com/learningequality/kolibri/issues/1247 - I have addressed this issue by not logging the responses so aggressively, but without an explicit 'submit answer' button for each question, the response history will sometimes be more finegrained than might otherwise be desirable.

**Comment by harishbalachandran** [comment]
@rtibbles Now the responses recorded are manageable. 
![1429](https://cloud.githubusercontent.com/assets/13453618/25698209/8fee92cc-30db-11e7-9a29-e03480452faf.png)
