### ISSUE TITLE
Unable to reset password and create account on Kolibri demo

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1442]
## Summary

"Reset your password" hyperlink text is not clickable on the log-in page (https://kolibridemo.learningequality.org/user#/signin) and "Finish" button on the "Create an account" page isn't clickable (https://kolibridemo.learningequality.org/user#/signup)

## System information
 - Version: 0.3.0
 - Operating system: Windows
 - Browser: Chrome, Edge

## Traceback or relevant snippet from server.log or browser console
https://kolibridemo.learningequality.org/user#/signin
https://kolibridemo.learningequality.org/user#/signup

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

I continue to share this link with partners but at present, they would be unable to create an account.

**Comment by indirectlylit** [comment]
thanks for the report! There are two independent issues here, both of which are fixed in the upcoming 0.4.0:

* broken password reset link - see #1361
* signup button - see #1331

The question is whether we want to back-port these fixes to 0.3.x, or simply upgrade the the demo server to the (less stable) 0.4.0-beta

**Comment by rtibbles** [comment]
We should update demo server soon, this will be fixed then.
