### ISSUE TITLE
User Create Modal `ui-select` incorrectly uses 'enter' key

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#1456]
Using native HTML, one can tab to the `<select>`  and use arrow keys to choose between various options. `<ui-select>` doesn't seem to be handling this.

@radinamatic @christianmemije

**Comment by christianmemije** [comment]
What's the desired behavior? It's definitely keyboard accessible. 

![lgtm](https://cloud.githubusercontent.com/assets/7193975/25976728/a2b4a8b6-366b-11e7-8a81-753940775946.gif)

@radinamatic Can you test the create new user modal on Develop and see if it has any issues.

**Comment by DXCanas** [comment]
I wouldn't expect to have to press enter for any reason other than submitting the form. Usually, once it's in focus, you just press arrows

**Comment by indirectlylit** [comment]
Yeah it's subtle but I'd noticed the same thing. It's not exactly "broken" but it's not consistent with native behavior.

**Comment by radinamatic** [comment]
You can use the table here for quick reference about which interactions should be checked for the correct keyboard navigation: 

http://webaim.org/techniques/keyboard/#testing

> However, when testing with a keyboard, you are not just trying to interact with the page successfully, you also want to ensure all interactions are predictable. 

The main reason the native elements are preferable is because they are **predictable**, they behave consistently. So on another side the observation by @DXCanas, that moving between the elements in a menu `<select>` with arrow keys upon focus would be much better,  _expected_, user experience, is correct. But, considering that the menu can be expanded with the space bar, and then navigated by arrow keys, in theory I wouldn't consider this a big faux-pas, at least for sighted user who navigates by keyboard.

However, even though this "looks" like a dropdown options menu with `<select>` element visually, it's actually a value pulled from a list nested in a div, which gives no indication to screenreader users what interactive element they are exactly interacting with. Good accessible user experience here is anybody's guess.

It comes a bit to the difference that I mentioned before: **functional keyboard accessibility** (meaning the user can eventually perform all the necessary actions) vs. the predictability (good UX) of **standard/native behaviors** (meaning what the user knows what to expect from previous interactions with a given element).

We could think of adding some additional `visuallyhidden` context for screenreader users to improve this. I'm taking it on to try some solutions.

**Comment by DXCanas** [comment]
@radinamatic Thanks for chiming in. This code a component of @JosephusPaye's [KeenUI](https://github.com/JosephusPaye/keen-ui). Maybe we can collaborate to get the changes upstream?

**Comment by indirectlylit** [comment]
note that this also prevents the form from being submitted using the 'enter' key when the field is highlighted

**Comment by indirectlylit** [comment]
not critical for 0.5 

@christianmemije this would be great to fix in the `k-select` widget.
