### ISSUE TITLE
Table "Kolibriauth_deviceowner" ready exists message while trying to update the version.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1503]
## Summary
While I am trying to update a Kolibri 0.4.0beta1 to beta2, I am getting error message Table "Kolibriauth_deviceowner".

Note:
If I install the Kolibri0.4.0beta2 as a fresh installation without doing an update on the existing feature then I do not get the error and the version seams to work fine.
**But we loose all the user data and content.** 

## System information
 - Version: Kolibri 0.4.0beta2
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Try to update the server that has been running the Kolibri 0.4.0beta1 to 0.4.0beta2.

## Screenshots

Command used to update:
![command for beta2](https://cloud.githubusercontent.com/assets/13453618/26050770/86caf398-397d-11e7-965c-027d954433aa.png)

![deviceonwer error](https://cloud.githubusercontent.com/assets/13453618/26050779/92d2ed1c-397d-11e7-834d-6adae67499db.png)

**Comment by rtibbles** [comment]
@harishbalachandran - sorry, I should have made clear, there is no clean update path from beta1 to beta2 (due to the changes to the database to allow forward compatibility with any future data syncing capability).

You should remove the `db.sqlite` file from the `.kolibri` folder when running the beta2.
