### ISSUE TITLE
Make Download content option for videos configurable at the facility level.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1606]
## Summary

As you know leaners will always be playfully clicking on the Download content and our tablets will get filled up with downloaded content. 

Hence please remove make Download content option for videos configurable at the facility level.

## System information
 - Version: Kolibri 0.4.0beta9
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Log in as a learner
2. Access a video
3. Below the video download content has to be removed.

## Screenshots
![whatsapp image 2017-06-07 at 1 01 07 pm](https://user-images.githubusercontent.com/13453618/26867119-a679d432-4b81-11e7-9548-ee511981b7ca.jpeg)

**Comment by jonboiser** [comment]
One approach would be to let the Superuser configure whether or not the 'Download Content' button appears. To handle this situation, the admin would disable the 'Download Content'.

**Comment by jtamiace** [comment]
^ I think this may be the best approach. To address @rtibbles' concern about proliferating facility configuration options, there are ways to organize the options on the UI so that it appears less overwhelming and complex. It might be inevitable if we want to design for the many different contexts that Kolibri will appear in.

**Comment by khangmach** [comment]
I think @jonboiser's approach is probably our best bet for now. As flags are ever-proliferating, I can definitely see content downloading as an important component a device owner would want to toggle on/off depending on the context. I would suggest embedding the download option in a "more..." options kind of widget/button in order to make downloading more difficult to get to, but we don't have many options other than download at the moment.

**Comment by rtibbles** [comment]
An additional need for this just arose, whereby content partners with special distribution agreements may be recalcitrant to have their content in Kolibri if it can be downloaded like this.

**Comment by rtibbles** [comment]
@indirectlylit if this is just implemented as a facility setting, do you see any further design needed, beyond selecting the default values for this for the three different configuration contexts?

**Comment by indirectlylit** [comment]
This thread began before we introduced superusers and got rid of device owners, so we need to update the plan.

In particular, is it a device or a facility setting? (configurable by facility admins or superusers?)

**Comment by rtibbles** [comment]
From the foregoing, I think it is more of a facility setting, as it depends more on the context of use (which is how we have defined the facility setting scenarios), rather than something inherent to any particular device.

**Comment by indirectlylit** [comment]
Okay, sounds fine to me.

![image](https://user-images.githubusercontent.com/2367265/36496936-af11da70-16ee-11e8-8231-61db204b1bf8.png)

I suppose we will just add a new item to this list. The consistent phrasing would be:

> Allow learners to download content

That might be technically incorrect because a savvy learner could download it anyway. Alternative phrasing:

> Show 'download content' button to learners

Since this is an admin screen, might be good to go with 'technically correct' over 'consistent'?

**Comment by indirectlylit** [comment]
for 0.9, going with:

> Show 'download' button with content

**Comment by swapnil106111** [comment]
@rtibbles Tested on kolibri 0.9.0. If "Show download button with content" is unchecked then it is hiding Download content option. It is working as expected.
