### ISSUE TITLE
Collect static does not seem to get run even when a new version is being run

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1615]
## Summary

It seems like the following version checking: https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/cli.py#L143 is not triggering an update, even when a newer versioned pex file is being used. I am assuming this is because the VERSION file and the kolibri.__version__ are actually reporting the same version number, and hence the update is not getting triggered.

## System information

 - Version: Develop Branch
 - Operating system: Android
 - Browser: Android Web View

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Any Kolibri updates will not trigger updated front end assets.

**Comment by benjaoming** [comment]
@rtibbles the version file in this case is a file written to `~/.kolibri` to track which version last had the `update()` function called. I'll have a look again.

**Comment by benjaoming** [comment]
We still use `develop` for 0.5?

**Comment by benjaoming** [comment]
@rtibbles can you recall if this is regarding a .pex built locally or from Buildkite?

I concur from reading the code that this happens because a `kolibri/VERSION` file isn't updated during building of a .pex. This is the only explanation I see from the current version mechanism.

While developing, static data should be served through the devserver, and this shouldn't be a problem.

The only reasonable alternative to **not trusting the version file**, is to run `collectstatic` every time kolibri is started. I recommend that we accept this until the get_version PR #1498 is merged, and then I'll add a revert of this commit in the PR, so it's rolled back once we merge that PR.

One problem, I've found is in Buildkite where the .pex file is being build on top of results from other processes. This is the Make target:

```
pex:
        ls dist/*.whl | while read whlfile; do pex $$whlfile --disable-cache -o dist/kolibri-`unzip -p $$whlfile kolibri/VERSION`.pex -m kolibri --python-shebang=/usr/bin/python$
```

As you can see, it doesn't depend on anything else. If we made it depend on at least writing a new version file, we could avoid building .pex files locally without having triggered a new version file.
