### ISSUE TITLE
misleading user feedback in facility config

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1665]
During facility config, we allow users to hit 'save' even when no changes have been made. This results in the message "Facility settings updated!" popping up, which is not true.

![image](https://user-images.githubusercontent.com/2367265/27186635-cd280cee-519d-11e7-986c-2675f28cb3cb.png)

We've tried both strategies when it comes to the question of "should a button be enabled even when it does nothing?". It's a subtle question that we should address in the "Forms Patterns" section of the style guide, but I think in this case there's a clear advantage to disabling the button when nothing in the form has changed.

cc @khangmach @jtamiace

**Comment by indirectlylit** [comment]
Another note is that the user feedback appears below the form, but I think in other places it appears above.

**Comment by khangmach** [comment]
@indirectlylit Like within import export, alert message should appear above the fold. 

Yeah, It might be best to have the save button initially disabled. Checking/unchecking any checkbox will be considered a change, even if there weren't any saved, recorded changes in the back end (for example, if a user checks an unchecked box, then unchecks it).

I also think this isn't a standard form by the conventional definitions of them containing form fields. Therefore I think this can be an exception/different type of "form" that can merit a button disabled state.

**Comment by indirectlylit** [comment]
> I also think this isn't a standard form by the conventional definitions of them containing form fields

If this isn't a form, we definitely need a clear definition of what forms are :)

**Comment by khangmach** [comment]
@indirectlylit 

forms component TBD then. Doesn't seem like a form to me, but a list of checkboxes. 

> Use checkboxes in tables and lists only. (from the checkboxes component doc)

**Comment by jonboiser** [comment]
The original reasoning for putting the ui-alert was put on the bottom was because, on small screens, if the alert were on top, then the user would click the button below the form and the alert would be out-of-frame. Probably the same thing happens in import export if one had a lot of channels and were deleting something at the bottom of the list.

**Comment by khangmach** [comment]
@jonboiser that's a good point that the alert would be out of frame. I see many table actions and app processes place alerts on top because when the action or process finishes, the page refreshes (for example, a page refreshing once the user saves a form) or finishes a submission. 

overall, I think placing alerts on top of the fold, regardless of whatever's in the user interface, makes the location of an alert predictable. On the flipside, we can't really predict how long a form will be, so the location of the alert would always be variable. 

Here are some good examples of above the fold:
<img width="1087" alt="ss-alert" src="https://user-images.githubusercontent.com/25045166/27355213-062ee0b0-55bf-11e7-89b9-21d1622cf1cb.png">
<img width="1087" alt="ss-alert2" src="https://user-images.githubusercontent.com/25045166/27355214-06313eaa-55bf-11e7-8df0-ba5eac03e0f1.png">

**Comment by indirectlylit** [comment]
>  On the flipside, we can't really predict how long a form will be, so the location of the alert would most likely be variable

right, that's why material floats snackbars and toasts at the bottom of the screen, above content: https://material.io/guidelines/components/snackbars-toasts.html#

**Comment by khangmach** [comment]
@indirectlylit 

https://material.io/guidelines/components/dialogs.html#dialogs-behavior

>Disambiguation from Snackbars: Snackbars present optional information after an action, such as confirming the discarding of a draft. They often allow a user to undo an action just taken.

For import and export of channels, would we really want them to undo an action/dismiss the snackbar so easily? The process of import export and the weight of its importance is much greater than an smaller micro action such as selecting/unselecting a topic to use for an exam (an example proper use of a snackbar). Import/export is a heavy action, so you would want to use alerts to make the user aware of it's presence and status in the import export flow. Conceptually, snackbars and alerts both provide feedback for the user, but are used in two totally different scopes and should match the weight of the particular action.

**Comment by indirectlylit** [comment]
That's fair; I don't think the transient notification is appropriate for import/export for many reasons (long-running process, might be triggered by another user, etc).

**Comment by jtamiace** [comment]
Another thing to consider is that **most admin users will not be on mobile**, especially for high stakes features like import/export and likely much of the admin interface. Unless an admin uses ONLY a mobile device for admin-related things, they will learn over time from their desktop experience where the alert will appear as long as we make it appear in a consistent place.

**Comment by indirectlylit** [comment]
Should be addressed by upcoming device/facility permissions work, including updates to be more in line with the Forms style guidelines.

**Comment by DXCanas** [comment]
Not sure what the status of Forms style guidlines is - have we established the rules here?

**Comment by indirectlylit** [comment]
guidelines are here: https://docs.google.com/document/d/1rrq8fovV5wBtUKv65wfRqXxP4SfnV30anUZHfzCVmN4/edit

**Comment by jonboiser** [comment]
#2234 Seems to fix the problem in the original post. Create issues, if other outstanding came out in the discussion.
