### ISSUE TITLE
<Enhancement>The landing page after a Admin logs in should be the coach tab rather than the Management tab.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1684]
## Summary
The landing page should be the coach tab rather than the Management tab when a facility admin logs in. 

The Facility admin in Nalanda's implementation will be the teachers themselves and hence most of the time after the initial class setup, the teachers would login to see the coach section more often. 

Also since within Management section the first tab is Classes, the teacher will quickly click on the classes to see the dashboard, and later realise he/she is on the management tab and then navigates to Coach tab. Not a great user experience at present hence the request.

## System information
 - Version: Kolibri 0.4.0beta10
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Login as a Facility Admin
2. The landing page will be the Management tab.

## Screenshots

![teacherlanding1](https://user-images.githubusercontent.com/13453618/27298880-00c254e4-5548-11e7-8478-4e6aaaaae853.png)
![teacherlanding2](https://user-images.githubusercontent.com/13453618/27298884-04a0bcc2-5548-11e7-99b6-47676fa7692c.png)

**Comment by christianmemije** [comment]
@jtamiace & @khangmach agree with this.

**Comment by indirectlylit** [comment]
It's hard to predict what is the "correct" landing page, since different organizations will use user types differently.

Rather than redirecting to `/coach` by default for Admin users, perhaps another solution is that all users should just go to section they were in last?

We would still need defaults for the "first time", and I think it's still reasonable to map these to user types:

* Learners -> `/learn`
* Coaches -> `/coach`
* Admins -> `/manage`
* Super users -> `/manage/content`

thoughts?

**Comment by indirectlylit** [comment]
> Also since within Management section the first tab is Classes, the teacher will quickly click on the classes to see the dashboard, and later realise he/she is on the management tab and then navigates to Coach tab

This is a real problem regardless of default pages. Perhaps we should have a "Manage class" cross-section link in coach reports, and a "View reports" link in class management?

**Comment by khangmach** [comment]
> perhaps another solution is that all users should just go to section they were in last?
I think this work around isn't really a solution, makes navigation arbitrary for both coaches and admins. I wouldn't expect users to make note where they left off, much less care. I'd rather make the location a user lands predictable, as opposed to confused why the UI keeps switching them back and forth between views

>Perhaps we should have a "Manage class" cross-section link in coach reports, and a "View reports" link in class management?
this is going backwards to the first coach design, which was incredibly confusing in navigation. We are trying to get away from intermingling the functions of coach and manage. Especially if in different contexts where the roles of coach and admins are more discrete.

**Comment by jtamiace** [comment]
> Rather than redirecting to /coach by default for Admin users, perhaps another solution is that all users should just go to the last section they were in, when they previously logged out?

Are there apps that use this pattern? Agreed with @khangmach. I feel like there is value in having a "home" that a user goes to, which would help them quickly orient themselves to where they need to go instead of evaluating where they are every time they log in and then figuring out how to get where they need to be.

 It's been a long-term goal to make the landing page of Coach more like a dashboard, with useful metrics and jump off points bubbled up to that landing page rather than an uninformative list of classes. I feel like once we get there, it will help the user quickly recognize where they are and where they should be.

**Comment by jtamiace** [comment]
Regarding the "first time", I think those probably make sense. More thought needs to go into general onboarding for each user type but linking them to the first page according to role could be appropriate for each

**Comment by indirectlylit** [comment]
Not sure if it's a common pattern for web apps, but e.g. Chrome restores tabs and OSX will restore your windows on reboot. E.g. "continue where you left off" is a common pattern.

I guess my thinking is that we have basically two options w.r.t. landing pages.

a) Speculate about where different user types might want to go. Possibly revisit this decision when another user complains that their admins really ought to go directly to user management.
b) Assume that the last thing that a user was doing is a reasonable guess for what they'll want to resume doing next time. This option actually seems less arbitrary to me

Re: cross-section links, I was thinking just subtle text links, not like a big nav interface. E.g.:

![image](https://user-images.githubusercontent.com/2367265/27601681-07ba93b4-5b25-11e7-9da7-c8b5aa44db86.png)

**Comment by jtamiace** [comment]
Yeah I would rather wait to see how admins who rely mostly on Manage end up using Kolibri. The Chrome "restore" is a much different case than Kolibri, since there are lots of processes that could be happening when the computer suddenly reboots (you lose all your open tabs, all your open apps get closed, etc.). However, imo Kolibri really does not have that kind of complexity enough to warrant needing to "restore" the last place they were.

**Comment by indirectlylit** [comment]
BTW, I definitely agree that it would be disorienting to go to a sub-page like a specific video or a nested coach report. E.g. it seems less likely that they'd be interested in looking at the _exact_ same page - just the same top-level section.
