### ISSUE TITLE
Export from USB and import from USB is failing

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#1882]
## Summary

Upon exporting a channel to usb, the progress bar jumps around and it eventually says it fails.
Upon importing a channel from usb, it fails.
It seems as if some of the files downloaded, but I can't be sure they were all downloaded due to it saying its failing.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.5
 - Operating system: OSX
 - Browser: Chrome

## How to reproduce

1. Start local kolibri instance with pex file
2. Navigate to manage content page.
3. Export to usb
4. Also try importing from usb

## Screenshots

![export_bug](https://user-images.githubusercontent.com/6361732/28441548-2cd6b644-6d60-11e7-8543-38f2ac99c2ac.gif)

**Comment by rtibbles** [comment]
I was only able to replicate this error message when I tried to export all the channels on my device, and then realized my error, and cancelled part way through.

I then tried to export again, and got this error.

However, when I cleaned up the files that had already been copied over to the external device, I was able to export normally.

I then deleted the channel from the device and reimported, it worked fine.

**Comment by rtibbles** [comment]
Reimporting again after it had already been imported failed to prompt any error.

**Comment by jamalex** [comment]
Unable to replicate on the Intel CAP -- importing and exporting from/to USB worked smoothly. :small_blue_diamond:

**Comment by jamalex** [comment]
Ok, we've gotten to the bottom of this. It's exactly the kind of scenario @rtibbles describes. Currently, I can see two scenarios in which this would happen:

A:
- Channel is partially downloaded, and then canceled or errors out
- Exporting to USB fails as soon as it hits a file it can't find (due to the partial download)

B:
- Channel is partially exported, and then canceled or errors out
- Importing from USB fails as soon as it hits a file it can't find (due to the partial export)

The "jumping around" that @ralphiee22 observed is due to having multiple channels. For export, it does it by channel, so when it finishes one channel, it goes back and does the next one (resetting the progress bar).

So, more broadly, we can improve behavior around this by:
- Not failing when missing files are encountered (this should probably happen in the context of the new content DB integration, and availability annotation)
- When exporting, export the content itself before exporting the channel database. Then, if exporting content fails, it won't show up as a channel for import on the USB. That will avoid (B), above, for now. I will give this a try.

**Comment by indirectlylit** [comment]
Is there a work-around when it gets into this state?

If so, I think we should document it as a known issue in 0.5 and retarget this for 0.6

**Comment by rtibbles** [comment]
Yeah, I think we should push this to 0.6 and leave it as a known issue for now.

**Comment by aronasorman** [comment]
I can take a look at this today.

**Comment by rtibbles** [comment]
I think these issues should be at least partially solved (or more easily solveable) due to the changes in content import, so should be straight forward. Thanks!

**Comment by aronasorman** [comment]
@lyw07 and me tried replicating this, but we weren't able to do so. I'd close this for now, but let's try to replicate this in a bug bash.
