### ISSUE TITLE
import/export progress bar can jump around with multiple channels

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1927]
As indicated in https://github.com/learningequality/kolibri/issues/1882#issuecomment-319135695 the progress bar jumps around when multiple channels are being imported or exported. 

From a user's perspective, one would expect progress to reflect the cumulative progress of all channels in the pipeline.

**Comment by jamalex** [comment]
Good call. This also ties in with wanting to see progress at a more granular level (like in the KA Lite video download interface), with an "overall" progress bar and then a "current task" progress bar. CC @aronasorman 

Here, it's not so much the progress bar itself, so much as how this is handled on the backend (loading each channel's content is a separate command, and we don't know how many bytes of transfer will be required for each until we're already inside its command). This will be easier to do once the content databases are integrated. CC @rtibbles

**Comment by ivanistheone** [comment]
Related to this, @aronasorman, could you clarify how the [callbacks passing works for progress updating](https://github.com/ivanistheone/kolibri/blob/develop/kolibri/tasks/management/commands/base.py#L85)? What if there are multiple tasks running at the same time in parallel?

I've managed to isolate the problem in bug #1818 to both `importchannel` and `importcontent` tasks running at the same time. We somehow exit the transfer context too soon  https://github.com/ivanistheone/windows-testing/blob/master/session2/server.log#L75   but the file transfer for the db file hasn't finished yet (as can be seen from updates that continue)

Note the code that's running has the added [`update_progress=update_progress`](https://github.com/ivanistheone/kolibri/blob/bugfix/1818/kolibri/tasks/api.py#L169) on the  `importchannel` command (I was hoping this would fix the source-db file lock issue, but no that doesn't fix it as can be seen in session2 logs).

**Comment by jonboiser** [comment]
If the Task could do the math right and combine the progress % for multi-part transfers, that would be great.

One hacky thing we could though, is fake that math on the client-side. So, if importing two channels from a disk, we do this:

* 0% for beginning of channel 1
* 50 * (Percentage for channel 1)
* 50 + (Percentage for channel 2) * 50

And for n channels,

* 0% for beginning of channel 1
* (100 / n) * (Percentage for channel 1)
* m / n * (100 / n ) * (Percentage for channel m)

This is sort of possible, because we can tell when a new channel is switched-over too (the task id changes), which lets us increment the value of m.

**Comment by jonboiser** [comment]
Going to try the hack described above. This logic (or something better) might be moved to the backend later for the same effect and we can revert the change.

**Comment by rtibbles** [comment]
Do we know how many channels are being imported in the front end though? As far as I know that information does not get transmitted back to the front end.

**Comment by jonboiser** [comment]
Currently, things are very simplified. For local imports, we download every channel on the drive. Same for exporting. For remote imports, only one channel at a time can be downloaded.

I think even with the new import/export designs, one can only downloaded a single channel; plus we always know how many channels are going to imported/exported.

**Comment by rtibbles** [comment]
Yeah, that was my point. I don't think for local import we send the information of number of imported channels back to the client?

**Comment by lyw07** [comment]
I was looking into this issue earlier and trying to do it with one ProgressTracker created before calling `exportchannel` and `exportcontent` so all the progress will be shown in one bar. The code is here: https://github.com/lyw07/kolibri/commit/560e3167a5f2cc06ea843198af76557290ea69ed if you are interested in taking a look. But I think that changing the percentage of the progress sounds better, since it doesn't change much of the original code and should have similar result of my way. If things are going well for @jonboiser's way, then I'll start to work on something else.

**Comment by jonboiser** [comment]
@lyw07 I think that it makes sense to normalize how percentages work on the server-side, since the client-side hack to accomplish this makes assumptions of the server that might not be true.

**Comment by lyw07** [comment]
@jonboiser Thanks! Then I will continue to work on the way I was approaching and post here later once I finish, so everyone can review the code and decide whether the way I'm working on is okay. I'm not quite sure whether my way is a good approach, as it changes too much of the original logic from my perspective. But that's what I can come up with now for the server-side, so I'll keep working on it :)

**Comment by jonboiser** [comment]
@lyw07 Sounds good. I will remove the cumulative progress hack from my PR since it was meant to be a shim until we had a permanent fix.

Have you looked at #2206 too? My PR also has a hack to guard against a weird pattern where Task progress spikes to 100% right at the beginning then goes back to normal. Maybe you are working on the relevant code.

**Comment by rtibbles** [comment]
Just commented on #2206 as well, but I think this is due to the fact that importing a single channel is actually running two management commands. I think the same kind of fix you are doing here would also apply to this case as well @jonboiser.

**Comment by jonboiser** [comment]
Do you mean the fix that @lyw07 is doing for "combined progress" could also fix the percentage resets for remote imports? So if the fix works for `export{content,channel}`, then it could be ported over to `import{content,channel}`.

**Comment by rtibbles** [comment]
Anything that combines progress from multiple management tasks to give a monotonically rising progress from 0 to 1.

**Comment by lyw07** [comment]
@jonboiser @rtibbles Yes I think the logic I'm trying to implement could fix #2206 as well. I'm implementing `import` currently. Will post my code here soon once it's done so everyone can take a look before I open a PR.

**Comment by jonboiser** [comment]
@lyw07 Great! If there are fixes incoming, then I will remove both the progress bar hacks from my PR.

**Comment by lyw07** [comment]
The fix for this issue and #2206 is here: https://github.com/lyw07/kolibri/commit/12d74fcbf61a2857506a44743a7f84146cf87d46 I'm not going to open a PR for now since I'm not sure if this implementation is the best way to handle the case. Please feel free to leave comments! Thank you :)

**Comment by jonboiser** [comment]
Should we move these issues to 0.7 if the back-end patch is risky? From a user perspective, it's not that big of a deal, I think.

**Comment by rtibbles** [comment]
Yeah, we can assess the risk of @lyw07's fix and then retarget if so.

**Comment by lyw07** [comment]
PR is open now for this fix: https://github.com/learningequality/kolibri/pull/2313

**Comment by aronasorman** [comment]
We export on a channel-by-channel basis now. Plus we only have one worker on Iceqube, so only one job downloading task can be running at any one time. Don't think this is an issue now with the latest flow.
