### ISSUE TITLE
New tag structure

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#1962]
## Summary

Our current tagging system does not lend to proper alphanumeric sorting by version, particularly on beta and alpha releases.

@benjaoming am I describing this correctly?

**Comment by benjaoming** [comment]
Like totally! But with one adjustment: Perhaps the sorting isn't really important. It seems that Github handles it by understanding the `v` prefix. It also seems that there is a big convention to tag this way.

It might be something we can clean up through scripting, whereby we rename all existing tags. I had some notes about this somewhere :)

But just to give an example:

```
v0.6.1
v0.6.1-alpha1
v0.6.1-beta1
v0.6.1-rc1
```

Could become:

```
stable/0.6.1
prereleases/alpha/0.6.1-alpha1
prereleases/beta/0.6.1-beta1
prereleases/release/0.6.1-rc1
```

The overall goal would be to:

1) Give a clean overview of stable releases
2) Perhaps someday be able to clear out tag garbage with a big shovel :)

But the underlying problem might also be that we just have too many releases and should consider a nightly release mechanism of some sort. So we can keep releasing stuff for testing, but won't have to do alpha-1 and then alpha-2 the day after because alpha-1 had a critical issue.

At this point, I think this issue might be okay to close - but would be interested to hear some other takes on it, since it's more of a release cycle than a tagging issue :)

**Comment by indirectlylit** [comment]
thanks - to your points

1. Give a clean overview of stable releases

During the past dev meeting, we decided to make a page on learningequality.org the primary distribution location, so that should help highlight the stable releases

2. Perhaps someday be able to clear out tag garbage with a big shovel :)

I'm curious what the disadvantages are to keeping old tags around? That seems like a good historical record to me.

On the github release side, I recently cleaned out all pre-releases from https://github.com/learningequality/kolibri/releases/ and I just opened a PR to make this standard operating procedure: #2539

So I think we can safely close this issue?
