### ISSUE TITLE
by default, specify crowdin branch based on kolibri version

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2007]
## Summary

Currently if you are not checked out on the current release branch for which we have messages on crowdin, message upload and download will have weird and unintended consequences.

Recommendation from @benjaoming that we hard code the current branch name (perhaps we could just use the base version introduced in 0.6.x to avoid redundancy?) rather than using git to inspect the current branch.

----

update from @indirectlylit:

a convenience for devs and release managers would be to update the scripts to use a release branch based on the current Kolibri version info by default

We should still allow branches to be specified manually if so desired

**Comment by indirectlylit** [comment]
Should I update the new crowdin.py script to generate the crowdin branch name based on Kolibri's `__init__.py` file?

**Comment by benjaoming** [comment]
The old CrowdIn branches got deleted on CrowdIn itself, as you may be aware of @indirectlylit. So as long as this behavior doesn't block stuff in the future, if CrowdIn branches continue to be deleted... I would really discourage deletion of these branches.

I don't think this is a super-important automation, since API keys also have to be given manually. It should be okay for maintainers to be aware of the CrowdIn branch? Otherwise we risk silently fetching the wrong branch (although the automation might help) and we would still have to be able to override the automated behavior?

**Comment by benjaoming** [comment]
What I suggest is just to close this and discuss the deletion of CrowdIn branches more thoroughly...

**Comment by indirectlylit** [comment]
yeah, agreed the automation is 'nice-to-have' but not critical, and that branch deletion is a separate discussion.

In my workflow the commands are saved in my terminal history, so it would be convenient (and prevent user error) if input args were removed completely

I'll leave this open as a 'dev experience' issue and reword the title slightly

**Comment by benjaoming** [comment]
> In my workflow the commands are saved in my terminal history, so it would be convenient (and prevent user error) if input args were removed completely

Yup, I also have a terminal history full of gems.. and CTRL+R is super useful!

I do, however, try to put a space in front of these commands so that the API key doesn't end up in my bash history... One thing that compromised stuff does, is to send your bash history to a paste bin :)

**Comment by rtibbles** [comment]
Wontfix.
