### ISSUE TITLE
detect and warn about unsupported browsers

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2035]
There are a few browsers that we explicitly do not support. Currently, many of these browsers leave the user with a "broken" experience - for example a loading screen that never goes away.

Instead, we should detect browsers that are not supported and show an explicit message with instructions about what to do.

For example, if we detect that the user is on IE10, we should instruct them to use Firefox. The instructions might vary depending on detected OS (e.g. unsupported browsers on Android might have different recommended next-steps)

We should also update the [`browserlist`](https://github.com/learningequality/kolibri/blob/develop/browserslist) file to accurately reflect our supported browsers.

nice-to-have: also detect when javascript is turned off and warn about that, too

**Comment by jtamiace** [comment]
Potential solution. 

Consensus is to display this if the user is using IE 10 or any version below that. 

Kolibri still "kind of works" on other browsers like iOS & Safari, but we are not addressing those experiences at this time since it's a more pressing issue that the user is left on e.g. an infinite loading screen on IE.

<img width="1145" alt="screen shot 2017-11-02 at 5 28 29 pm" src="https://user-images.githubusercontent.com/6668144/32356567-4b1ddcb4-bff3-11e7-96e0-771ad556b3d7.png">

**Comment by indirectlylit** [comment]
note to add iOS
