### ISSUE TITLE
'recommended' performance issues

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2162]
During the 0.6.x hack session, at least two users saw issues with content appearing slowly or not at all on Learn's 'recommended' tab.

@shivichandra:

> Recommended tab populated itself, then disappeared on refresh with no loading indication. To reproduce, hang out on the recommended page and refresh arbitrarily

@jamalex:

> Same here. Took 40 seconds to load recommendations for me -- probably because of load from the group. Nothing showed in the meantime.

and also:

> Under "Recommended", no more "Resume", and "Next steps" takes a while to update (caching, maybe, on the latter?)

**Comment by aronasorman** [comment]
We might need some load testing on the recommended page. I remember that this is a particularly DB-heavy page -- we had to use a different page as the homepage of nalanda, because loading this took a while.

**Comment by rtibbles** [comment]
That wasn't the reason we changed 0.4 to default to topics, that was just because that was Nalanda's preference.

**Comment by rtibbles** [comment]
We did significant optimizations to reduce the load generated by the recommended page, at least partly because a lot of the recommendations are bootstrapped into the page at initial load.

The main issue is the way we create recommendations - dynamically. We should be storing recommendations for users in the database, and then eliminating or marking them as done when they have completed them. This would also help to solve the related issue caused by our frontend caching of these queries to prevent their repeated, expensive, loading: https://github.com/learningequality/kolibri/issues/2414

**Comment by indirectlylit** [comment]
cc @jamalex this relates to your investigations around database locking and WAL files

**Comment by indirectlylit** [comment]
possible address #1954 if we're doing further load testing - are these the stress tests we used during this work

**Comment by indirectlylit** [comment]
this is still being reported. Recently by Azeez:

> ‘Recommended’ takes a long time to load. Also, the ‘Most popular’ section with the Balloons video opens first, and then rest of the section (Sikhana and other channels) open a couple of second later.

**Comment by indirectlylit** [comment]
closing, as 'featured in' was the main culprit and recommended is no longer the default page
