### ISSUE TITLE
import/export error edge-case testing and handling

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2217]
At a high level, the Import/Export needs to be robust to failure conditions such as dropped or flaky internet and hard shutdown of Kolibri or the computer.

We should systematically test importing and exporting under these conditions, and document the results, and then make updates necessary to make the user experience acceptable.

----

note - some considerations might include

* auto-retry logic
* detection and cleanup of corrupt DBs
* better user-facing messaging

**Comment by aronasorman** [comment]
Here's my expected behaviour for the following scenarios:

> flaky internet
Retry up to N times, otherwise fail that download; continue the other jobs. Bubble up to the user that certain downloads have failed.

> hard reset
"Resume" job. Support for resuming would depend on the type of job (downloads and file transfers can be resumeable, but anything else is ??).

> Corrupt DB
Have a check during startup to see if the DB is readable (it should almost always be, it's SQLite). If it can't read it, clear it out.

**Comment by indirectlylit** [comment]
see e.g. #2242

**Comment by indirectlylit** [comment]
a fair amount of work has gone into this task
