### ISSUE TITLE
Learn Exam page routing issue

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2232]
## Summary

A routing issue in the Learn Exam page does not allow users to take an exam.

## System information

- Version: 0.6

## Console error

```
missing param for named route "EXAM": Expected "questionNumber" to be defined
```

## How to reproduce

1. Create an assign exam to a learner
2. Sign in as learner
3. Go to Lean exam page and click on exam

## Screenshots

![test](https://user-images.githubusercontent.com/7193975/30670054-a40d9bf2-9e15-11e7-8a81-a6d90fa13522.gif)

## Real-life consequences

Cannot complete exam.

**Comment by jonboiser** [comment]
So, it was simple to fix the original post, by adding a `questionNumber` entry in `generateExamLink`:

https://github.com/learningequality/kolibri/blob/de06274bd2397784184b8dec87755359634c0097/kolibri/plugins/learn/assets/src/views/exam-list/index.vue#L60-L80

But once I did that, I found that going straight to `http://localhost:8000/learn/#/exams` causes problems, because it does not seem to bootstrap the channels list in `store.state.core.channels` (it does, if you go straight to `/learn/#`, though).

What happens is that you get redirected to a 'content not found' (see line with `router.replace({ name: PageNames.CONTENT_UNAVAILABLE }); `) page at this line, since the channel for the exam is not in the list:


https://github.com/learningequality/kolibri/blob/de06274bd2397784184b8dec87755359634c0097/kolibri/plugins/learn/assets/src/state/actions/main.js#L425-L435

**Comment by indirectlylit** [comment]
>  it does not seem to bootstrap the channels list in `store.state.core.channels`

Sounds like this is a regression since the switch to the integrated channel experience. Various places in the code might still assume that `store.state.core.channels` is available. Should we reinstate this bootstrapping?

**Comment by jonboiser** [comment]
Fixed the above issue by adding `setAndCheckChannels(store)` into the list of Promises.

**Comment by rtibbles** [comment]
Yeah, that seems like the right fix.

**Comment by jonboiser** [comment]
#2276
