### ISSUE TITLE
high-level task: 0.7 content import/export updates

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2273]
* granular import (sub-tree selection)
* public channel listing
* proquint channel tokens
* channel 'update' function
* "Channel ID" => "Channel Token"

----

Other related issues:

* [x] https://github.com/learningequality/kolibri/issues/2206
* [x] https://github.com/learningequality/kolibri/issues/1927
* [ ] https://github.com/learningequality/kolibri/issues/2217
* [x] https://github.com/learningequality/kolibri/issues/2171
* [ ] https://github.com/learningequality/kolibri/issues/2271
* [x] https://github.com/learningequality/kolibri/issues/1493
* [x] https://github.com/learningequality/kolibri/issues/1211
* [x] https://github.com/learningequality/kolibri/issues/2274
* [ ] https://github.com/learningequality/kolibri/issues/2592

**Comment by aronasorman** [comment]
Went through each issue listed here and marked what still needs to be done:

https://github.com/learningequality/kolibri/issues/2217- testing out the new import/export in general for robustness
https://github.com/learningequality/kolibri/issues/2271 - the `database is locked` error
https://github.com/learningequality/kolibri/issues/2592 - documentation updates to change mentions of tokens instead of channel IDs

**Comment by indirectlylit** [comment]
closing this issue. Let's file individual issues for all remaining issues. issues.

nice job!
