### ISSUE TITLE
License instances are overwriting each other when being merged into main DB

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2327]
## Summary

Saw a few cases of the wrong license showing under content. Turns out we use an auto-incrementing ID on License in the Kolibri models, and only export the licenses used in a channel, so the pk's don't always correspond to a particular license. Then, when we merge them into the joint DB, they overwrite each other (or don't, but in any case, many license FK's end up pointing to the wrong license.

In fixing this, we'll need to think holistically across Studio models, the export process, and the import process, and take into account Special Permissions, which come with custom text (so there's more than one Special Permissions license, in effect).

## How to reproduce

1. Import 66cef05505fa550b970e69c3623e82ba and 8b28761bac075deeb66adc6c80ef119c
1. Go to content pages
1. Depending on which channel was loaded first, content from one channel will show the wrong license.

## Screenshots

![image](https://user-images.githubusercontent.com/618416/31102718-3c8df5ea-a788-11e7-925a-5d4971d6898d.png)

## Real-life consequences

Boatloads of legal trouble for everyone! :)

**Comment by jamalex** [comment]
Flagging for @jayoshih and @rtibbles.

**Comment by rtibbles** [comment]
Joy. The other issue will be remapping the license_id field to the new pk as well.

**Comment by rtibbles** [comment]
(if we want a quick fix)

**Comment by jamalex** [comment]
One option would be to keep an integer PK, to avoid breaking things, but have it come from a unique table on Studio rather than being autoincrement?

**Comment by jayoshih** [comment]
Can we use the license name as the pk? That should remain the same

**Comment by jamalex** [comment]
Would add a bit more complexity on import, if we're maintaining forward-backward compat, but not sure how compat will work out anyway, so may be worth considering some sort of constant value. We'd still need to separately handle Special Permissions, though. How are those stored on the Studio?

**Comment by jayoshih** [comment]
It's just another license constant, and the description is stored on the ContentNode

**Comment by jamalex** [comment]
Ok, yeah -- we may want to just transfer that same approach over to the Kolibri models.

**Comment by jayoshih** [comment]
Will this require a breaking change?

**Comment by indirectlylit** [comment]
> Can we use the license name as the pk? That should remain the same

One small thing to watch out for is preserving the ability to change the display name of licenses if necessary. E.g. if we had "CC BY ND" and later wanted to rename it "CC BY-ND"

**Comment by rtibbles** [comment]
My preferred solution would be to fix this on the Kolibri side first, enhance the import logic to deal with existing license data, and then move the change to studio once we have our ducks in a row on backwards compatibility.

**Comment by rtibbles** [comment]
The proposed fix for this is to emulate Studio behaviour and write license data directly onto ContentNode models.

This will involve:

Deleting the License model.

Adding license_name and license_description fields to the ContentNode model. For now, this will involve complete denormalization of the license data onto the ContentNode.

In future, when we have frontend support for known licenses (like CC-BY), the license_name will be an identifier, rather than a title, and the frontend will handle display of the license name and description for known license types.

In the case of unknown license types the frontend will fall back to using the license_name and license_description from the database.

Note - this approach also allows for proper internationalization of known licenses in the frontend.

**Comment by rtibbles** [comment]
Fixed in #2368
