### ISSUE TITLE
Decide on and apply convention for vertical scrollbar alignment in RTL

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2398]
## Summary

In some browsers, vertical scrollbars will appear on the left hand side in RTL mode.

**Comment by khangmach** [comment]
if we're mirroring the screen in RTL, then left hand seems conceptually correct. But since most people are right handed, and most digital applications place scrollbars on the right side, there is already an established convention that people are already used to. 

If we decide on a permanent left placement, then we'd require a great deal of users to drag their hand across the screen in order to scroll with their dominant hand. 

Keeping it on right side makes sense to me.

**Comment by indirectlylit** [comment]
Which hand is dominant does not factor in here because you don't need to switch hands to move a cursor to the other side of the screen (desktop) or swipe on the other side of a touch device.

The main factors I can think of are:

* Do users have a preference based on conceptual correctness? If so, we should standardize to left-side for RTL and right-side for LTR, overriding browser/system behavior if necessary.
* Do users have a preference simply because they're used to the defaults? If so, then we shouldn't touch anything and let the defaults do their thing.

My guess is that there is will be some mix of the two happening without a clear winner, which leads me to believe it's best (easiest) to do nothing here.

Some links I scanned:

* https://bugzilla.mozilla.org/show_bug.cgi?id=619963
* https://ux.stackexchange.com/questions/24437/scrollbars-in-right-to-left-layout
* https://stackoverflow.com/questions/1261869/setting-the-correct-orientation-for-scrollbars-in-right-to-left-pages/2842081
