### ISSUE TITLE
have buildkite fail if dependencies can't be found

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2433]
If we can't retrieve dependencies, buildkite should fail rather than create and upload a broken build

**Comment by lyw07** [comment]
Yesterday I found some of the `cryptography` wheel files got deleted on PYPI. I'm not sure what exactly happened but I guess it's related to their new release. It caused the failure of getting `cryptography` wheel files from PYPI, but the problem doesn't exist now. 

To prevent this issue in the future, I will add some code in `install_cext.py` to fail the program so that we will be alerted with this instead of knowing nothing about it.
