### ISSUE TITLE
Swap steps 2, 3 and 4 in setup wizard (suggestion)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2511]
### Observed behavior

Setup wizard is:

1. **Please select the default language for Kolibri**
1. **Name your Facility**
1. **Create your Admin account**
1. **Choose a Facility setup**

### Expected behavior

1. **Please select the default language for Kolibri**
1. **Choose a Facility setup**
1. **Name your Facility**
1. **Create your Admin account**

Because the type of facility chosen may guide the kinds of questions and help texts in the remainder of the wizard, we could move the question to the beginning.

Immediately, moving **Choose a Facility setup** to the beginning means that when we ask users to **Name your Facility**, the choice of name is more easily understood because the wizard has exposed roughly which types of facilities Kolibri has to do with.

In the longer run, we can adapt the help text of **Name your Facility** to for instance "Name your school" or the help text below it.

Finally, moving **Create your Admin account** to Step 4 will mean that the admin can log in fresh after choosing her password.

### User-facing consequences

Mainly it's the perception of what a facility is I worry about.

**Comment by indirectlylit** [comment]
cc @jtamiace - thoughts?

**Comment by jtamiace** [comment]
Facility name is something that I thought would come easily and naturally -- it would just be the name of the building, grounds, etc. in which Kolibri is being used. Could you give examples of when a user might think to name their Facility something different based on the setup option?

I'd rather resolve the ordering of "Name your Facility" and "Choose a Facility setup" through testing on users. Reasoning for setting the name first is so that simple concepts about basic definition of a facility is introduced, and then they can see that there is more complexity associated with it. Also, setting titles and names first is a common pattern when it comes to filling out forms.

I do agree that it might be more appropriate to add the admin account last though. Would make more sense to group Facility things together.

**Comment by indirectlylit** [comment]
For what it's worth, I agree with @benjaoming that choosing facility type before name might help the user understand "what is a facility?" and thereby have an easier time naming it

**Comment by indirectlylit** [comment]
added a new issue just for the admin creation here: #2961

migrated the rest of the feedback to the clearinghouse

**Comment by benjaoming** [comment]
@indirectlylit you can use this great app for moving issues+comments from one repo to another: https://github-issue-mover.appspot.com/

**Comment by benjaoming** [comment]
@jtamiace I don't think "facility" is a very straight forward word, it needs a lot of context and if you're not  a native English speaker, it might be difficult.. and I think for translations, the word could turn out even weirder.
