### ISSUE TITLE
Content not found after doing an export through command line

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2529]
### Observed behavior

When we do `exportchannel` and `exportcontent` in command line and then do a local import from USB through browser, the browser is not able to find the content just exported. 

The problem is that when we do `export` through command line, the data folder is named `content/`. However, when we do `local import` through browser, the data folder is supposed to be called `KOLIBRI_DATA/content/`. Thus, the browser is not able to find the data folder and the content just exported.

### Expected behavior

The content in the external drive should be found through browser after doing a command line export.

### User-facing consequences

Users will not able to import content from external drive through browser if the content in the external drive was exported through command line.

### Steps to reproduce

1. Do `exportchannel` and `exportcontent` in command line
2. Check the external drive that the content exists but in the folder `content/`
3. Do `kolibri start` to start in the browser
4. Click `Import` and choose local import
5. Check whether there is content available in the external drive on the page

### Context

* Kolibri version: latest 0.7
* Operating system: Mac OS X
* Browser: Chrome

### Screenshot
<img width="203" alt="screen shot 2017-10-25 at 5 43 19 pm" src="https://user-images.githubusercontent.com/19424916/32065922-f2639638-ba32-11e7-9e3d-06926da64761.png">

**Comment by aronasorman** [comment]
Yeah, this was an explicit understanding that @jamalex and I hashed out, where it's the REST API that would append the `KOLIBRI_DATA` path to where we exported the content. This is because `exportcontent/channel` aren't inherently aware of what a USB drive is, and the logic for what the drives are, and where to place them, is placed within the REST API itself.

I'm closing this for now, unless someone disagrees with this.
