### ISSUE TITLE
Force selection of facility in user login

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#2552]
### Observed behavior

Currently a device with multiple facilities will not let a user login to the non-default facility. This may be at odds with the desires of some deployments who have roving models.

### Expected behavior

Show a list of facilities to login with.

Any simplified login autocomplete should be based on the currently selected facility.

### User-facing consequences

Users can't login!

**Comment by christianmemije** [comment]
Will need to add a k-select. Might be a good time to ditch the dark background... @jtamiace @khangmach

**Comment by christianmemije** [comment]
Would require the addition of strings.

**Comment by rtibbles** [comment]
Punting due to string freeze.

**Comment by indirectlylit** [comment]
> One of my concerns is the possibility of a user becoming irked at the constant need to select a facility via the modal (screen 1) every time they encounter the log in page.

Agreed. Even if it's just once, going to a page and having a modal immediately pop up might be a bit jarring?

> Is there a way via cookies or sessions to preserve their facility selection the next time they log in?

I believe so, yes

> ![image](https://user-images.githubusercontent.com/2367265/35028202-9ed58d2e-fb09-11e7-9377-31e4e6a57dbe.png)

Having the facility selection down with the language selection seems risky because it's the last thing people will see, but the first thing they need to confirm before logging in or creating an account. Would be interested to see a design that puts facility selection somewhere above the login forms?

I'd also try the design on realistic mobile screen dimensions in portrait and landscape - I'm guessing you'll find the mobile view doesn't actually work as expected, particularly once the keyboard is open.

**Comment by christianmemije** [comment]
Why not just include the facility selector above the username field?

### First time landing on sign in page
No default facility set in local storage.
Autofocus on facility selector.
Select a facility
Set as default in local storage.

### All other times landing on sign in page
Default facility is already selected
Autofocus on the username.
If change in facility, will be saved in local storage.

**Comment by khangmach** [comment]
@christianmemije I think with this simplified approach, there is no need to include a facility selector at all in the login UI.

To paraphrase Jamie, 99% of the time we won't need to inquire what facility the user is logging into. Problems only come up when there are collisions in both username and passwords. For example, when a username + password set belong to 2+ facilities, or when a learner's username belongs in 2+ facilities. 

If such ambiguities can be detected after login info input, after pressing sign in, a modal can pop up prompting the user to clarify what facility they actually want to go to. This way we reduce UI clutter.
![facility changing](https://user-images.githubusercontent.com/25045166/35070604-a1aad520-fb92-11e7-8423-feeeacfdfd25.png)

**Comment by DXCanas** [comment]
@khangmach 
There are a good number of edge cases here.

Each facility has it's own config. One of them might have a "simple" sign in with just username. If the default facility doesn't, the password gets shown. In this case, a user might not know how to sign in with the password field there.

Also, we don't currently check for collisions on the background, the facility is specified in the frontend, currently just using the backend's default. 

Initially, I was thinking we could just display this modal whenever there's an error on default signin (so users are given the option to sign in to the proper facility). The issues with this approach is that a single user with the same username/password in 2 places wouldn't ever see it.

Here's the current approach I'm considering, if we dont' want to have a `<select>` on the sign in page:
1. Check all facilities on the device. If any one of them has simple signin, hide the password field.
2. Have the user type in their username, then submit the form
3. Display modal, allow them to select the facility
4. If the facility has simple sign in, sign them in immediately. Otherwise, throw them back to signin page with the password field highlighted.

I would have given the above some gherkin stories, but I'm losing a good amount of time on this bug (Lessons pages still need some stubbing for tomorrow + there's a good amount of work left).

@rtibbles Thoughts?

**Comment by indirectlylit** [comment]
Just a note that most organizations at this point will not have multiple facilities. Recommend making this as simple as possible for now, even if it's a slightly suboptimal UX when there are multiple facilities.

To me that might look like selecting the facility before trying to log in.

**Comment by rtibbles** [comment]
Not sure why having a select (when there is more than one facility), and either a greyed out select or statement of the facility is problematic here? Seems like we are trying to create an overly complex solution for a situation that will not arise particularly frequently.

**Comment by DXCanas** [comment]
If my understanding is correct, the dark bg on the log in page doesn't lend itself well to our components

**Comment by indirectlylit** [comment]
At one point, the design was to just start with this UI when the sign-in page was initially loaded and multiple facilities are available:

![image](https://user-images.githubusercontent.com/2367265/36617154-3e68131c-189b-11e8-84a7-e97e53b5c870.png)

During that state, the username and password fields could be completely hidden because we don't know yet which facility config to use. Once a facility config is selected, the standard login screen updates.

Finally, we'd add a something like this to the login page:

> Current facility: Facility Name [(change)]()

where clicking 'change' pops up the modal again.

**Comment by rtibbles** [comment]
Or, we could just use the default facility's config until the facility is changed?
