### ISSUE TITLE
Replace ui-switch with k-filter

### ISSUE THREAD

**Issue by christianmemije** [learningequality/kolibri#2569]
### Observed behavior

Switches are not part of the style guide. Should be replaced with a `k-select`

### User-facing consequences

Inconsistency 

### Context

* Kolibri version: Develop

**Comment by indirectlylit** [comment]
can we have a mockup of specifically what this should look like? (cc @jtamiace)

**Comment by jtamiace** [comment]
Instead of thinking of it as a toggle, would just be a dropdown with two options. By default, the name of the currently selected option would display.

<img width="898" alt="screen shot 2018-01-02 at 10 21 18 am" src="https://user-images.githubusercontent.com/6668144/34494741-b3907ae4-efa6-11e7-8b49-c1d34492f6fc.png">

**Comment by indirectlylit** [comment]
thanks!

**Comment by christianmemije** [comment]
Fixed in #3115
