### ISSUE TITLE
suggestion: remove 'content type' filters from 'topics' section of Learn

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2619]
### Observed behavior

We've gotten feedback a couple times now that the type filters are confusing:

* https://github.com/learningequality/clearinghouse/issues/30
* recent feedback from VF that selecting content types seems broken

Part of the issue is that user feedback on type selection is poor, so users don't understand what the result of their action is. 

We also can't disable filters that aren't applicable to the current view, like 'Documents' when everything visible is a topic.

Another issue is that type filters in the Recommended and Topic views are simply not that helpful: these views rarely show more than a dozen item. Filters are more helpful when a large (100's of items) list needs to be culled.

### Expected behavior

Filters should behave in a reasonable way, and should not be present when they're not useful.

### User-facing consequences

People are confused by our type filters and think they're broken.

**Comment by khangmach** [comment]
@indirectlylit It seems that this issue ties in with the general confusion over our topic tree structure. From the conversations in the referenced thread, the expectation is that when video filter is selected for example, whether there are videos or not in the current node, Kolibri will show all the videos it can find located within the topic cards in current view. 

Renaming component label "Type" to "Show" won't help if this is the expectation users have. If we want people to understand the purpose of the tree is to navigate in order to find content, perhaps we should remove the filter completely until there's a request for it. Thoughts?

**Comment by indirectlylit** [comment]
> If we want people to understand the purpose of the tree is to navigate in order to find content, perhaps we should remove the filter completely until there's a request for it

yes agreed - that's exactly what I was suggesting here

**Comment by khangmach** [comment]
let's remove the filter component from Topics then. Thanks!

**Comment by christianmemije** [comment]
Fixed in #2624
