### ISSUE TITLE
import/export: inconsistent channel size metrics

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2723]
### Observed behavior

Different pages show channel size info in different ways. Sometimes it shows both total and on device, sometimes it shows neither, and sometimes it's not clear what value is being shown.

Channel list 1:

![image](https://user-images.githubusercontent.com/2367265/33357430-e6f15de0-d476-11e7-9148-b1f651abd95f.png)

Channel list 2:

![image](https://user-images.githubusercontent.com/2367265/33357444-f674db20-d476-11e7-9430-6748756cad24.png)

Channel details:

![image](https://user-images.githubusercontent.com/2367265/33357452-01d9f16c-d477-11e7-81e5-b730f49703d9.png)

### Expected behavior

Consistent, labeled metrics shown throughout

### User-facing consequences

It's confusing how to find numbers, and what the numbers mean when I see them

-----

cc @khangmach

**Comment by khangmach** [comment]
- On the [content management page](https://projects.invisionapp.com/share/Q9D1VQD67#/screens/254175259): the number indicates how many resources you have
- On the export [content page](https://projects.invisionapp.com/share/Q9D1VQD67#/screens/254175331): the number indicates how many resources you have to export
- Everywhere else in the [import flow](https://projects.invisionapp.com/share/Q9D1VQD67#/screens/254175324) there aren't any numbers near the channel because they mean different things to different people, and we should leave the details to the content selection screen.

**Comment by indirectlylit** [comment]
okay - i'll migrate this to the clearinghouse. As a user testing the UI, it wasn't clear to me what the meaning of the numbers were or why they disappeared in certain places.
