### ISSUE TITLE
import/export: channel updates not detected

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2726]
### Observed behavior

After making a change to a channel in studio and re-publishing, those changes are not picked up by Kolibri.

Version 5:

![image](https://user-images.githubusercontent.com/2367265/33355918-6cb428da-d46e-11e7-90cb-6af32a9c82f8.png)

Still version 3, with "Channel up-to-date" message:

![image](https://user-images.githubusercontent.com/2367265/33355933-8109dae6-d46e-11e7-9bb5-a6e58b08b856.png)

### Expected behavior

The "Channel up-to-date" should change to a notification that an update is available and allow me to grab it.

### User-facing consequences

Cannot import new content.

### Steps to reproduce

* create and publish a channel on studio
* import it on Kolibri
* update channel and re-publish
* try to update on Kolibri

**Comment by jonboiser** [comment]
@lyw07 Could we reduce or eliminate the cache for RemoteChannelViewset? Currently, it's 10 minutes.

**Comment by lyw07** [comment]
@jonboiser I can change it to one minute, does it work for me?

**Comment by indirectlylit** [comment]
How about 5 seconds? That would prevent Studio from getting pounded, but still allow people to publish a change on Studio, flip over to Kolibri, and hit 'refresh'

**Comment by lyw07** [comment]
@indirectlylit yup I can do that!

**Comment by jonboiser** [comment]
Caching issue is resolved, but now there is still a problem because the actual channel metadata db is cached as well. So if I originally viewed the channel at V2, it won't re-download the DB and find out that it's at V3.

I think we might need to download the channel metadata fresh _every_ a user wants to view a remote channel.

**Comment by aronasorman** [comment]
@jonboiser you mean the API to check the remote channel's status on Studio is cached?

**Comment by jonboiser** [comment]
Also, I don't know if this is intentional, but whenever you download a newer version of the Channel DB, it replaces the previous one.

1. I download channel contents at V3
1. I then update my channel to V4 on Studio
1. I go back to UI to check out the changes _but do not download anything new_
1. On my device, it thinks I'm now at V4

**Comment by jonboiser** [comment]
@aronasorman Not the result from Studio API or the proxied endpoint. It's the actual Channel Metadata Sqlite that is "cached" via it not being deleted after a user downloads it to view it.

**Comment by indirectlylit** [comment]
(see also the above PR. There's an outstanding issue where users need to update channels even when they don't have content downloaded)

**Comment by indirectlylit** [comment]
another report from @radinamatic during hack session:

![image](https://user-images.githubusercontent.com/2367265/33470629-27b1661a-d61e-11e7-9e1b-e4dd2f056d92.png)

**Comment by indirectlylit** [comment]
@DXCanas what's the state of this fix?
