### ISSUE TITLE
flappy bird is not centered in setup wizard

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2730]
### Observed behavior

it's screen-size-dependent:

![image](https://user-images.githubusercontent.com/2367265/33362677-66605bce-d492-11e7-8f52-f0c89ec069be.png)

### Expected behavior

flappy bird in the center

### User-facing consequences

not too much

### Steps to reproduce

* set up a new server
* resize the window while the bird flaps

**Comment by karlaeavila** [comment]
<img width="1280" alt="screen shot 2018-02-01 at 3 51 00 pm" src="https://user-images.githubusercontent.com/15150234/35710008-0c2c31f4-076a-11e8-811f-be88c2468f22.png">
<img width="1280" alt="screen shot 2018-02-01 at 3 47 49 pm" src="https://user-images.githubusercontent.com/15150234/35710082-6a29a35e-076a-11e8-9237-b77cde5dc44a.png">
<img width="1280" alt="screen shot 2018-02-01 at 3 44 27 pm" src="https://user-images.githubusercontent.com/15150234/35710085-6c54cf0a-076a-11e8-87b3-14b8f49586bd.png">

I have tried recreating this issue by changing the screen sizes but every time I do, the flappy bird is always centered. I am using Google Chrome, is it possible this issue is being caused by using another web browser?

**Comment by indirectlylit** [comment]
Hi @karlaeavila -

The problem is exacerbated at certain sizes. If you look closely at your third screenshot (or measure the pixels), you'll notice it's off-center to the left.
