### ISSUE TITLE
tag name isn't reflected in version

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2762]
### Observed behavior

This was seen with a tagged (beta4) release:

![image](https://user-images.githubusercontent.com/2367265/33458897-dccf52a6-d5dc-11e7-9cfc-62f33d5a2b55.png)

### Expected behavior

release version should reflect tags

### User-facing consequences

unknown what version is being run

### Steps to reproduce

* create a tag
* look at build

**Comment by indirectlylit** [comment]
cc @benjaoming looks like another versioning regression

**Comment by benjaoming** [comment]
@indirectlylit this was a well-known behavior of `git describe` all along - it's actually the original issue from when everything was based off tags and `git describe`

The problem is that the distributed version still says `(0, 7, 0, 'alpha', 0)`:

https://github.com/learningequality/kolibri/blob/v0.7.0-beta4/kolibri/__init__.py

While I think @rtibbles's PR would fix some issues we might have seen with `git describe`, I'm not sure if the PR is correct.

I think you should edit the code to say `(0, 7, 0, 'beta', 5)` and make a new release.

**Comment by benjaoming** [comment]
Since the version has to be written to a `VERSION` file then, maybe the build in question didn't do that? @indirectlylit any chance this is the issue?

I think @rtibbles is fixing that a normal git checkout (with the pre-release tag) might not show a correct version, which is the old `git describe` bug.

**Comment by indirectlylit** [comment]
agreed with @rtibbles here: https://github.com/learningequality/kolibri/pull/2794#discussion_r154397927

pre-releases should be tag-based

**Comment by indirectlylit** [comment]
not necessary to fix for this release since the 0.7 'final' should work as expected ... right?

**Comment by rtibbles** [comment]
Yep

**Comment by benjaoming** [comment]
> not necessary to fix for this release since the 0.7 'final' should work as expected ... right?

Agreed, yet we will probably have pre-releases in the 0.7.1 face, so should keep the target branch nonetheless?

**Comment by rtibbles** [comment]
Oh, true, fair enough. I will retarget back after 0.7.0 is released.
