### ISSUE TITLE
release Kolibri to PyPi

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2844]
tracker issue

**Comment by indirectlylit** [comment]
people are starting to try and use PIP: https://community.learningequality.org/t/please-enter-a-content-channel-id/430

@benjaoming maybe we should just release 0.7.0 instead of waiting for 0.7.1?

**Comment by benjaoming** [comment]
Bad news everyone.

> Uploading kolibri-0.6.1-py2.py3-none-any.whl
> HTTPError: 400 Client Error: File too large. for url: https://upload.pypi.org/legacy/                                                          

I have uploaded 0.5.3 because I wanted to have intermediate releases in case people have to download only one minor release at a time. It worked for 0.5.3 because it didn't contain bundled c extensions.

However, at the 0.6.1 release where c extensions were introduced and the file size went up to ~87 MB.

I would propose to backport #2986 to 0.6.x and 0.7.x and do another release (0.6.2 and 0.7.1) so we don't irreversibly miss a 0.6 and 0.7 release on PyPi. @lyw07 

I asked if we could have the max package size increased to 100 MB: https://github.com/learningequality/kolibri/issues/2844#issuecomment-353789417

**Comment by lyw07** [comment]
@benjaoming I think removing some parts of the c extensions for 0.6 and 0.7 releases is a good idea. I can create PRs for them.

**Comment by benjaoming** [comment]
So, we got extra quota up to 100 MB. I used this to release 0.6.1 and 0.7.0 on PyPi.

When 0.7.1 is released, it will be considerably smaller thanks to @lyw07 's recent updates.
