### ISSUE TITLE
channel descriptions not showing up in Learn view

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2974]
### Observed behavior

Channel descriptions exist and show in import/export but don't show up in Learn

see https://github.com/learningequality/clearinghouse/issues/50

### Expected behavior

show descriptions

### User-facing consequences

> It has become more difficult to make sense of available content and find relevant items. No descriptions of content channels are available. This will become even harder when more channels are added.

**Comment by rtibbles** [comment]
Data should be returned by the API, just needs to be displayed in the frontend:
https://github.com/learningequality/kolibri/blob/develop/kolibri/content/serializers.py#L60

**Comment by khangmach** [comment]
I'm noticing that the channel descriptions do show up, but just not in the appropriate node. Can we have it so that the descriptions always show up in the node after the channel list? 

Here's how it is currently on my instance of Kolibri:
![tessa description](https://user-images.githubusercontent.com/25045166/35006278-168e63c2-faab-11e7-9061-8608cfb7015b.png)

Want:
![want](https://user-images.githubusercontent.com/25045166/35006383-5e3a7b02-faab-11e7-9c36-cdbbf3e2de66.png)
