### ISSUE TITLE
Build platform-specific whl files

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2989]
### Observed behavior

Currently we have one whl file that bundles everything to support all the platforms

### Expected behavior

Whl files with different dependencies bundled in to accommodate the needs for various distributions.
Please see the discussions in the thread [here](https://learningequality.slack.com/archives/C0LE9NLCE/p1513298161000025).

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
relevant transcript below:

----

Jamie Alexandre [16 days ago] 
I think there was talk of having the WHL *not* include these cext optimization deps, and only put them into the PEX, but not sure that went anywhere yet


Jamie Alexandre [16 days ago] 
(that would help with the DEB stuff, too, presumably)


Lingyi Wang [16 days ago] 
jamie yes I can get rid of the cryptography for osx and windows!


Lingyi Wang [16 days ago] 
yes it goes into whl first I think, and based on the whl file, we build the pex file


Lingyi Wang [16 days ago] 
so maybe just getting rid of cryptography for osx for now?


Jamie Alexandre [16 days ago] 
I think the end goal is not having any of the cext deps in the WHL (or maybe not even the pure-Python dependencies), and just have the PEX be the "standalone static" option. The WHL would then just be used for PyPI, with dependencies on the packages it needs. But I think we may also use the WHL in the Windows installer, too, and there we _do_ need the static dependencies.


Jamie Alexandre [16 days ago] 
But yeah, for the short-term, removing OSX sounds good


Jamie Alexandre [16 days ago] 
Can perhaps also even remove 64bit arch, since those systems are likely to be fast enough to not have a problem with pure Python crypto


Benjamin Bach [16 days ago] 
The pex is mainly distributed through Buildkite, and the whl would be a PyPi thing, it's easy to separate these two without creating a new `kolibri-blah` dist name.


Lingyi Wang
[16 days ago] 
I see. Then I’m going to remove OSX and 64bit arch for now.


Jamie Alexandre
[16 days ago] 
>it's easy to separate these two
benjaoming Except that we use the WHL file in the Windows installer. We would need to adapt the installer to separately bundle the static deps if we removed them from the WHL, right?


Benjamin Bach [16 days ago] 
jamie yes absolutely, lingyi could you make install_cext.py somehow receive an argument about which platform to fetch for? We could use this to change the `make` target so for instance we could do a `make dist <win/mac/linux>` ? By having this entry point, it would be possible to create separate .whl files, which is actually supported by PyPi.. just need to figure out how it works, because normally it'll work by setuptools detecting binary code and specifying the platform that it's running on... in this case, we need to tell setuptools which platform the current build is for (because we build everything on linux). See: https://www.python.org/dev/peps/pep-0425/ 


Jamie Alexandre
[16 days ago] 
For PyPI we don't need to bundle, though, right? We can just list deps and let them get installed separately from PyPI? But yeah, Makefile options would be great, and we can build the normal WHL with nothing bundled, and the WHL used for the PEX with Linux deps + pure Python deps bundled, and the one for Windows with Windows deps + Python deps bundled?


Lingyi Wang
[16 days ago] 
Yes I can do that. Will something like `install_cexts.py --platform <win/mac/linux>` help? So since we are not including mac and 64 bit arch anymore, I assume `--platform win` will only get the win32 cryptography; `--platform mac` will not get any cryptography; `--platform linux` will only get linux_i686, linux-armv6l and linux-armv7l cryptography. Am I understanding it correctly here? Thank you! (edited)

**Comment by jamalex** [comment]
I thought the idea was not to include cext (or even other deps) in the main whl at all, and only do the bundling for the PEX? Since the WHL files are mostly installed via PIP, and can pull in deps separately? Or is it because we use the WHL in the Windows and DEB installers, and so we want to have deps pulled in at an earlier stage to use for those?

(Maybe this is suggesting that we have a "no deps" version of the WHL, along with platform-specific ones?) @benjaoming ?

**Comment by benjaoming** [comment]
@jamalex we discussed both intermediate and final goals, should refer to some notes from earlier, as I cannot recall the exact discussion, but I think we had at least 2 meetings about this already :)

Assigned myself and @lyw07 to further clarify what to do.

I don't believe much in platform-specific .whl, I think the source dist should be as pure as possible, leaving freedom and flexibility for installers. But let's see... we also have a fair share of bugs related to host system libraries.

**Comment by benjaoming** [comment]
This is how I *think* the current situation would map out, but it's kind of hard to get a proper overview. Maybe it's better to work out a table.

```
digraph G {
  make [label="make dist\nC extensions:\n32 bit linux&windows"];
  make -> "kolibri-x.y.z-py2.py3-none-any.whl"
  "kolibri-x.y.z-py2.py3-none-any.whl" -> "PyPi source release"
  "kolibri-x.y.z-py2.py3-none-any.whl" -> "Pex"
  "PyPi source release" -> "Debian installers\n(py3)"
  "PyPi source release" -> "Windows installers"
  "PyPi source release" -> "MacOS installers"
}
```

![image](https://user-images.githubusercontent.com/374612/36687610-68de0c82-1b2a-11e8-8c67-2dffa70079d2.png)

**Comment by benjaoming** [comment]
What I'm wondering is if we can get a somewhat simple Graph going that doesn't have too many levels and roots... preferably just one root (and that's the source distribution) so we can reason around have one single release that kicks off the others.

**Comment by benjaoming** [comment]
@lyw07 let's sync up on this soon :)

**Comment by lyw07** [comment]
@benjaoming sounds good to me!

**Comment by indirectlylit** [comment]
This issue is mostly brainstorming, and that process has now [been moved here](https://docs.google.com/document/d/1JjGkQZWGEa6rvNYvw8SVW61L9VbAV6CnKNKU7YHGI30/edit#).

Closing, and we can open targeted & concrete issues for plans after the decisions have been made.

**Comment by benjaoming** [comment]
Agree, let's open up PRs/issues once we identify the concrete steps and have the task measured and divided into iterative steps.
