### ISSUE TITLE
Exercise hint amount indicators fluctuate by increments of 1

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#2993]
### Observed behavior
Hint indicator showing I have 4 hints left. I answer the first question correctly without using a hint. After pressing "check" and getting the answer correct, I press "next question" and the hint amount depreciates to 3 hints left. 

After answering the second question correctly, hint changes back to 4.

### Expected behavior
Hint value to stay the same

### User-facing consequences

misleading hint values, users may not notice hint values changing.

### Steps to reproduce
Choose answer for first question
Click on "check" answer
Get answer correct
Press "next question" button
--Hint changes to 3 left without ever using a hint--
Input a correct answer for the next question
Click on "check" answer
Get answer correct
Press "next question" button
--Hint changes back to 4 left--

### Context

 * Kolibri version: 0.7.0.dev020171130021755-git
 * Operating system: MacOS
 * Browser: Chrome

SCREENSHOTS
![screencapture-localhost-8000-learn-1513807752017](https://user-images.githubusercontent.com/25045166/34231660-c5f8d006-e591-11e7-8cb2-adff78c79540.png)

![screencapture-localhost-8000-learn-1513807768915](https://user-images.githubusercontent.com/25045166/34231671-c96f78f2-e591-11e7-9796-73f10c089568.png)

**Comment by khangmach** [comment]
![screencapture-localhost-8000-learn-1513807752017](https://user-images.githubusercontent.com/25045166/34231645-b9cd7520-e591-11e7-9da3-931268f5d223.png)

![screencapture-localhost-8000-learn-1513807768915](https://user-images.githubusercontent.com/25045166/34231649-bd0338ce-e591-11e7-8610-8f9fdcdaa602.png)

**Comment by geoffrey1218** [comment]
I tried to reproduce this and I don't think it's a bug. It just seems like different questions have different numbers of (unique) hints the user can reveal, instead of a set number of allowed hints for the entire quiz. 

For example, from the quiz given in the report, this question has 4 hints...

![question_4_hints](https://user-images.githubusercontent.com/4992896/35189899-af932d4e-fe09-11e7-86a4-148c34d2fa03.JPG)

... and this question has only 3 hints written for it

![question_3_hints](https://user-images.githubusercontent.com/4992896/35189902-b705398c-fe09-11e7-9e93-3c83a533e5b3.JPG)

It might be misleading to the user to have a hint number only applying to individual questions, but it looks like the system is behaving as intended.
