### ISSUE TITLE
lesson preview page layout is slightly broken

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3279]
### Observed behavior

The description seems to have a fixed height and gets truncated:

![image](https://user-images.githubusercontent.com/2367265/36873295-e7c6b290-1d5c-11e8-93ac-5bbef8978045.png)

### Expected behavior

Description box has no scrollbar, and all content is visible

### User-facing consequences

content is hidden from view

### Steps to reproduce

preview content with a large description while adding to a lesson

### Context

0.8

----

cc @DXCanas @jonboiser

**Comment by rtibbles** [comment]
Seeing a scrollbar, but might be better for it not to scroll, plus the content pane has a different colour background, and also has weird dimensions for this video (way too big):
![image](https://user-images.githubusercontent.com/1680573/36874021-372abd84-1d5f-11e8-87da-186b71001fec.png)

**Comment by jonboiser** [comment]
On the Learner side of things, this long description would appear below the resource. Maybe we can do that here too?

**Comment by DXCanas** [comment]
> content pane has a different colour background

That's coming from the renderer. I'd love to change that! Made some tweaks to the styles there to make it a bit more generic/customizable, could take that a bit further.
> has weird dimensions for this video (way too big):

This is actually something I struggled with a bit while putting this together. The mocs seem to emphasize that this isn't a page that scrolls (everything is above the fold, scrolling is never an option), and making this kind of page responsive is a challenge. Am I wrong in this assumption @khangmach?

**Comment by indirectlylit** [comment]
> The mocs seem to emphasize that this isn't a page that scrolls (everything is above the fold, scrolling is never an option)

that would be pretty inconsistent with most of our other page layouts

**Comment by khangmach** [comment]
Not sure where the assumption above came from. I didn't do the design of this page, but I don't see any kind of documentation that suggests this page shouldn't scroll. This page should function the same way it's presented in the spec deck + invision mock. Of course, if the render is a PDF, that area should be scrollable. The description should not be a scrollable area and the entire text of description should show, since a "see less/see more" was never specced out. Functionality of this page should be nearly to all other pages that have the two columns: [question list][render]

**Comment by DXCanas** [comment]
> that would be pretty inconsistent with most of our other page layouts

I can't find any other page layouts that are entirely made up of 2 columns, though. Besides `core-base` and some small UI bits (that live inside of a full width segment), I can't find any layout that has an element that scrolls within itself rather than the page (app-body).

> I don't see any kind of documentation that suggests this page shouldn't scroll. This page should function the same way it's presented in the spec deck + invision mock.

Looking at this page: 
https://projects.invisionapp.com/d/main/default/#/console/12198808/269638188/preview

The pdf renderer is wider than it is long, which I interpreted to mean that the height was clipped so that it doesn't scroll since the renderer displays it as taller than it is wide in all other cases.

Same with this page: https://projects.invisionapp.com/d/main/default/#/console/12198808/270086011/preview

The question list on the left scrolls, but the page doesn't. The exercise is wide and short, but not long. The height of the question list isn't really specced, 

This page kind of implies that the page scrolls: https://docs.google.com/presentation/d/15fJVQ_QDoPmL0-_XQiBQQFYpHTvL-oP8m0j8alhjowc/edit#slide=id.g2c6e84ca7f_0_37

But it also doesn't include a question list.

> Of course, if the render is a PDF, that area should be scrollable.

That's the case right now, but the size of the the area itself seems to conform to what's left above the fold.

> Functionality of this page should be nearly to all other pages that have the two columns: [question list][render]

This "above the fold" behavior is similar to what the exercise report page is doing, and the behavior of the exam report page is similar, except the top area is shorter. 

I think what makes this ambiguous is that the left column has a set height where it knows it should start scrolling, but it's not specified. And the content in the right column doesn't have a specified behavior. 

Some things to consider if the page scrolls:
How long should we let the question list in the left column go? Will the right column ever be longer than the left column? Should the description have a max height? What about the columns?

**Comment by indirectlylit** [comment]
Those are good points - until now we didn't have any precedent for an exercise with all the questions displayed in a standard learner-like page layout.

My recommendation (let me know what you both think) would be to make the scrolling question list and exercise renderer a single block, where they have equal heights:

![scroll](https://user-images.githubusercontent.com/2367265/36929894-41df8b5e-1e4c-11e8-87ab-8ed2becf60f6.png)

That would be more consistent with the other page layouts which include the content as a single block.

**Comment by khangmach** [comment]
That sounds like a good compromise to me. Would the entire area in green be a scrollable area then? Looking at various multiple choice questions, there's no telling how long the material in the render could be

**Comment by DXCanas** [comment]
@khangmach I think the idea is that the green block will get as long as the renderer needs it to be, with the question list filling the same height in, scrolling when it reaches the end.

**Comment by indirectlylit** [comment]
exactly

**Comment by jtamiace** [comment]
Also think devon's suggestion sounds good and want to apologize for the ambiguity. 

I'll add some q's for future consideration on scrolling behaviors in the design ambiguity doc, feel free to view and adapt later

**Comment by indirectlylit** [comment]
can revisit in a future release

**Comment by christianmemije** [comment]
Fixed in #3890 
![localhost_8000_coach_ ipad](https://user-images.githubusercontent.com/7193975/42055307-94a48d86-7acb-11e8-9c88-2ce4815d246c.png)
