### ISSUE TITLE
Do sanity checks before launching Kolibri

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#3285]
### High-level tracking issue

This is to track different issues that can cause `kolibri start` fail. It is originally from the discussion in a PR: https://github.com/learningequality/kolibri/pull/3273#issuecomment-369713552

Over-all requirements for start-up checks: Execution time should be very short, and failures should supply user guidance.

Furthermore, failures in checks should be an actual API that is usable for a UI. Suggesting return codes w/ descriptions available in a dictionary in `kolibri.cli` or likewise.

We should do several sanity checks before starting Kolibri:

- [x] port is available   https://github.com/learningequality/kolibri/issues/2867 and https://github.com/learningequality/kolibri/issues/3048
- [x] database connection successful: Catch corruption / malformed exceptions, show user guidance https://github.com/learningequality/kolibri/issues/3228 #3332
- [ ] available disk space
- [ ] `KOLIBRI_HOME` is writable

**Comment by benjaoming** [comment]
@lyw07 thanks for opening this! I've edited the description

**Comment by indirectlylit** [comment]
Recommend we close this issue since the two critical tasks are addressed (port and database connectivity), and this issue is otherwise a potentially open-ended placeholder.

As far as I know, there have been no reports of people having trouble due to either low disk space or the `KOLIBRI_HOME` not being writable. If I'm incorrect and we do have evidence that these are states which have caused people problems, let's open up individual issues for them.

**Comment by benjaoming** [comment]
I can answer yes to both, but I don't know if I'm allowed to count as a user :smile:

**Comment by indirectlylit** [comment]
certainly applies if it happened e.g. during your work in the field!

If it was because you're doing development in corrupted VMs or something I don't think it counts :)

**Comment by benjaoming** [comment]
Request for integrity checks: https://github.com/learningequality/kolibri/issues/4539
