### ISSUE TITLE
fix core modal @enter events, parameterize buttons, and conform to style guide

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3311]
### Observed behavior

In many cases in the code base - [example](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/exams-page/rename-exam-modal.vue) - we use a pattern like this:

```html
  <core-modal @cancel="closeHandler">
    <form @submit.prevent="submitHandler">
      ...
      <div class="core-modal-buttons">
        <k-button
          type="button"
          :text="$tr('cancel')"
          appearance="flat-button"
          @click="close"
        />
        <k-button
          type="submit"
          :text="$tr('save')"
          :primary="true"
        />
      </div>
    </form>
  </core-modal>
```

instead of the expected pattern like this:

```html
  <core-modal @cancel="closeHandler" @enter="submitHandler">
    ...
    <div class="core-modal-buttons">
      <k-button
        type="button"
        :text="$tr('cancel')"
        appearance="flat-button"
        @click="close"
      />
      <k-button
        type="submit"
        :text="$tr('save')"
        :primary="true"
        :disabled="submitting"
      />
    </div>
  </core-modal>
```

It might be that this is a work-around for double-submission or some other bug?

### Expected behavior

We shouldn't need to add a form with special event handling in every modal. If this pattern is necessary it should be built into the core modal.

While we're at it, we can update `core-modal` to take the button configuration as prop inputs rather than slots. This would allow us to deprecate the `core-modal-buttons` div convention:
One possible interface:

```html
  <core-modal
    @cancel="closeHandler"
    @enter="submitHandler"
    :secondaryBtn="$tr('cancel')"
    :primaryBtn="$tr('save')"
  >
    ...
  </core-modal>
```

### User-facing consequences

potential for bugs in modal submission due to difficult developer experience

### Context

conversation here: https://github.com/learningequality/kolibri/pull/3301#discussion_r172960515

**Comment by DXCanas** [comment]
This is true in most cases, but we have some modals that are purely informative. Two that come to mind:
- The [Permission Details Modal] (https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/setup_wizard/assets/src/views/onboarding-forms/facility-permissions-form/index.vue#L7) in the onboarding workflow.
- The [Welcome Modal](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/device_management/assets/src/views/welcome-modal.vue#L1) after first sign in.

Both of these cases include buttons, but only to close the modal. I think the UI changes around the modal have contributed to some of the confusion around how to set these up - We used to allow modal escape via:
- Keyboard Escape
- Clicking outside the modal
- Clicking an `X` on the top right.

Some cues were taken from [W3's accessibility guidelines](https://www.w3.org/TR/wai-aria-practices/#dialog_modal) in its creation, too.

Nowadays, we include an explicit "close modal" button on pretty much every modal, which is repeated functionality. And it's hard to bake this into `core-modal` itself because we often place replace the "close" text with something like "cancel" and place it alongside the "submit". 

We've also seemed to gravitate further from event-driven architectures to state-driven (or local state w/ components' `data`), which I think results in the sort of neglect of the modal events you mentioned. 

Speaking of neglect, the error handing features were an accessibility add with [consultation from @radinamatic.](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/core-modal/index.vue#L26) that doesn't see a ton of use. Likely because there's no intuitive reason that the modal should be in charge of alerting users to errors.

I guess what I'm trying to say is there's some re-evaluation to be done on `core-modal`'s feature set. I'm not sure wrapping everything in a form is the right way to go because it makes assumptions about the modal's content.

**Comment by indirectlylit** [comment]
Note that we have a design for the upgraded, standardized modal completed as part of the style guide work:

* [specs](https://docs.google.com/document/d/1102ubWXHSkWEWibHHfni9-cwc16PcQiocBWmOJrEGag/edit#heading=h.bi7jrxa4revs)
* [mockups](https://drive.google.com/file/d/0B3sjMmpdLvk4Tzk4ZnJpUV9nSkE/view)

We could take this opportunity to actually finish implementing that.
