### ISSUE TITLE
Coach/Lessons Doesn't Include a Classroom indicator

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#3470]
### Observed behavior

No class indicator in Coach Lessons after changing header behavior and using breadcrumbs in other coach pages. 
![lessons list](https://user-images.githubusercontent.com/9877852/38273977-39a31c44-3742-11e8-8d97-f1fbeebd511d.png)
![lesson resource page](https://user-images.githubusercontent.com/9877852/38274032-5dfafcb0-3742-11e8-94ba-b9e24102f19a.png)
### Expected behavior

Class would be indicated by something on the page, preferably breadcrumbs to keep in line with the rest of the coach app?

### User-facing consequences

1) Not immediately obvious what class lessons are scoped to
2) No easy way to check what class these lessons are scoped to

### Steps to reproduce

Navigate to `#/[channel]/lessons` and its subpages.

### Context

…

**Comment by indirectlylit** [comment]
cc @khangmach I think there was recent discussion about this?

**Comment by indirectlylit** [comment]
My guess is that the text "Classes" was intended to be the current name of the class. That's the only thing that makes sense to me, since the list of coaches is directly below it. @khangmach can you confirm?

more examples...

----

1. Just one class:

![image](https://user-images.githubusercontent.com/2367265/38530652-94ca654a-3c20-11e8-8690-c2c7c582839b.png)

2. Multiple classes:

![image](https://user-images.githubusercontent.com/2367265/38530666-a51fa16c-3c20-11e8-8934-f9e329f8d82e.png)

**Comment by jonboiser** [comment]
This is the problem line:

https://github.com/learningequality/kolibri/blob/34de7c39808857d44a342a78c3962f0410129353/kolibri/plugins/coach/assets/src/state/getters/classes.js#L6

I think the getter is not getting the right Class Name from the vuex state.

**Comment by khangmach** [comment]
@indirectlylit Yup the "Classes" header shown should return the name of the current class.
