### ISSUE TITLE
The classes option in the learn feature is visible to the users who are only enrolled in the class as learners.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3492]
### Observed behavior

The classes option in the learn feature is visible to the users who are only enrolled in the class as learners. If the user is enrolled as coach/admin, the class is not visible.

### Expected behavior

If the user is a part of the class as learner or coach, then he/she must be able to view the class and its resources in the learn feature.

### User-facing consequences

The coach would not be able to see his/her class and the added resources.

### Steps to reproduce

1. Login as admin/coach and assign the user as coach only of the class.
2. Go to learn and classes,the coach/admin won't be able to see the class.
3. If you enrol coach as the learner also, then the classes option would be visible in the Learn section.

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshot
![class1](https://user-images.githubusercontent.com/38091824/38457538-42c1db06-3aaf-11e8-8c6a-2b04bf29ca0b.png)
![class2](https://user-images.githubusercontent.com/38091824/38457539-43273bfe-3aaf-11e8-8197-2efaec543acc.png)
![class3](https://user-images.githubusercontent.com/38091824/38457540-43657f72-3aaf-11e8-8f95-c07dccdc10f1.png)
![class4](https://user-images.githubusercontent.com/38091824/38457541-43a1daa8-3aaf-11e8-885d-aef952bd0074.png)

**Comment by indirectlylit** [comment]
cc @jonboiser @ralphiee22

**Comment by jonboiser** [comment]
@khangmach I believe this was brought up when developing Class Coaches. If a Coach needs to see what an Exam or Lesson looks like, they can do some from the Coach Tools.

We would give Coaches the ability to view Exams and Lessons as a Learner if we want them to be able to submit exams and experience lessons the same exact way as Learners do.

**Comment by jonboiser** [comment]
I'm not sure if we wanted to add this feature if this is a simple patch. Currently we make these assumptions:

* If a user has a Coach **Role** for a Classroom, they are a Coach
* If a user has a **Membership**, they are a Learner

Having a Coach Role does not entail having a Membership, so if a Coach wants to participate as a Learner, we currently need to explicitly make them a Member.

To show Coaches classes they are only Coaches for, we would need to modify `LearnerClassroomSerializer` to treat Coach-Role-ship as a proxy for Membership (and what happens when a Coach actually is a Member?)

**Comment by rtibbles** [comment]
We could handle it in a similar way to how the basic endpoints are handled, and filter according to those items that the user has permission for, which would then encompass both membership and roles?

**Comment by khangmach** [comment]
Coaches not being able to see the learner's view of a specific assignment/exam is an intentional design. Unless coaches want to engage with the actual lesson/exam, they can view all resources and material in the coach tools. Until there is a good amount of feedback stressing a need for coaches to see and engage with the same material learners do, I would be wary of implementing this feature so soon.

**Comment by indirectlylit** [comment]
Okay, removing milestone. @amit3107 feel free to elaborate on the reason why this seems like an important feature

My intuition is that it relates to giving coaches the ability to preview how learners will truly experience their class, right down to taking the exam. (I assume most coaches take an exam themselves before assigning it to students?)

**Comment by indirectlylit** [comment]
@amit3107 as a workaround, you can set a user to be both a coach and a learner in a class

**Comment by amit3107** [comment]
Thanks @indirectlylit , It would be easier for the coach/admin to see how the class arrangement of exams and lessons look like, instead to going to exam and lessons separately using coach feature. Till then the workaround you suggested works well :+1:

**Comment by rtibbles** [comment]
We are tracking this internally, but closing this for now as wontfix.
