### ISSUE TITLE
Activity manager (job introspection and management UI)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3494]
### Objectives

We need a simple UI that can make admin users aware of what their device is doing, potentially canceling jobs.

The UI ~should~ could:

 * List jobs w/ elapsed time
 * Make job progress visible if it exists
 * Show the order of jobs queued, with ability to cancel queued jobs
 * Optionally 1: Cancel currently running job
 * Optionally 2: Links for where to navigate when a job completes

In Thunderbird, this is called an "Activity Manager"

### Background

On a Raspberry Pi 3, I managed to successfully import channel listings and contents from Sikana. But smaller imports do not reveal why we need an activity manager.

For Khan Academy, I've been unsuccessful. While waiting for the channel listings to appear, I get logged out, and logging back in, I cannot tell if the import listing job is still running. I cannot return to the page, but have to go through the same step again. Is it restarting? Are two jobs running simultaneously?

![image](https://user-images.githubusercontent.com/374612/38458040-15db6faa-3a99-11e8-9008-cbacbbdd2d58.png)

### Expected behavior

1. **Administrators need a job manager where they can see what's keeping the device busy**
2. **Jobs need to run consecutively**

### User-facing consequences

Especially smaller devices like Raspberry Pi will fail the heavier jobs. The user, not being able to tell what's going on, will kill processes and start over, thinking that jobs are stuck or dead.

### Errors and logs

n/a - this issue is not about running out of memory or failures. This is about tracking progress and managing jobs.

### Steps to reproduce

Khan Academy especially with it's 31k items is heavy enough to showcase.

### Context

0.9.0, Raspbian Jessie, Raspberry Pi 3.

**Comment by benjaoming** [comment]
What's it preparing? It's stuck forever...

![image](https://user-images.githubusercontent.com/374612/38458106-5119e924-3a9a-11e8-84ee-5d05d7b45d39.png)

**Comment by indirectlylit** [comment]
This issue has in some ways come to be catch-all for "things we don't like about the current import/export behaviors".

Since it's not feasible for us to implement everything at once, I think it would be helpful to break this apart into actionable subtasks or migrate this to clearinghouse and then write feature proposals based on it.

We should also be careful to clearly define the issues our users are encountering before jumping into the proposed UI solutions so that we can prioritize the order in which features are built or look for alternative, cheaper solutions when possible.

**Comment by benjaoming** [comment]
This is a very good catch-all way of solving several issues. That's why it was created.

**Comment by benjaoming** [comment]
Just to point out the actionable part: To create a simple piece of UI that makes current tasks visible. Yes, we can add more things like task *management* on top of that.

**Comment by indirectlylit** [comment]
> create a simple piece of UI that makes current tasks visible

we already have a simple UI that makes current tasks visible :) that's why I'd like to break this down and get more specific about the issues people are having.

Some concrete examples:

* Currently, no way to queue up imports, which means that users need to 'babysit' the system when importing multiple channels
* Currently, no indication of what changed after an import succeeded. Users might forget what action they initially started when imports take a long time
* Currently, the import UI from local disk is misleading about what's available. People try to import "everything" and are surprised by the results

**Comment by benjaoming** [comment]
@indirectlylit - for UI, I mean one that displays tasks as a list. A queue. For introspection. I agree on all the examples. IMO, the design can be sort of technically oriented -- maybe more like an Iceqube UI :)

**Comment by indirectlylit** [comment]
Yes, the ability to queue tasks is one specific new feature to address a specific challenge our users are facing. It's self-contained and [we have a clearinghouse entry for it](https://github.com/learningequality/clearinghouse/issues/292)

However, this is relatively independent from some of the other challenges being linked to this feature request:

* better error and success reporting
* automatic channel updates
* local drive import content enumeration

The more we try to lump together as a single monolithic change, the less likely any of it will be done. Maybe I'm misunderstanding the intent of tagging this issue from others.

**Comment by benjaoming** [comment]
I would propose this:

1) Sort out a generic activity manager UI for device administrators (this issue)
2) Use it (for scheduling channel imports etc.) (other issues)

I think the activity manager can be built and added in one release, and then subsequent releases can start using it or adapting to it. I agree that a monolithic change won't be successful. Redoing channel imports AND introducing an Activity Manager in one go is probably too risky. If the Activity Manager is introduced with little functionality, it can remain low-risk.. whereas major changes in channel imports are high-risk and should be based on reasonably tested grounds.

**Comment by indirectlylit** [comment]
Let's chat by voice when we have an opportunity. We might be on the same page, but when I see the phrase "generic activity manager UI" I'm still not sure if we're talking about the same thing. Once we chat I can either update this issue with clarifications, or start few new fresh ones without the comments and outdated background. (A lot has changed performance-wise since this was first filed)

**Comment by indirectlylit** [comment]
this is being addressed in the ongoing work on 0.13.0

**Comment by indirectlylit** [comment]
Please feel free to open new follow-up issues after beta testing has begun.

Refs for 0.13.0 work:

* https://www.notion.so/learningequality/Kolibri-0-13-0-content-management-upgrades-81e2e3aeb38942aa930498c18c17a9d7
* https://docs.google.com/drawings/d/1R-ACapv72bDEx_IptRD7EkVtrz4j4Zz-tk12dNVRTJY/edit
