### ISSUE TITLE
Exam status text on mobile view of exam cards is misaligned

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3545]
### Observed behavior

status text:

![image](https://user-images.githubusercontent.com/2367265/38833806-65d8dfa4-417b-11e8-8e08-d6c204d299f1.png)

### Expected behavior

should look a bit more symmetric with title

### User-facing consequences

UI looks a bit broken

### Context

0.9

**Comment by jonboiser** [comment]
It isn't quite _symmetric_ though, since the right hand side naturally wants to be taller than the thumbnail, and the whole card's height is dictated by the thumbnail.

![screen shot 2018-04-24 at 12 27 34 pm](https://user-images.githubusercontent.com/10248067/39209571-fb61a3d6-47ba-11e8-83c6-dc2c76f75c22.png)

**Comment by indirectlylit** [comment]
okay, that'll suffice for now
