### ISSUE TITLE
How to add Manual channel on kolibri ?

### ISSUE THREAD

**Issue by siamraj** [learningequality/kolibri#3581]
![capture](https://user-images.githubusercontent.com/35369929/39132974-c181f7d6-4730-11e8-92e2-b1b62813a8ff.PNG)

Additional Information :
                        How to add device(Memory card or drive) ?

**Comment by indirectlylit** [comment]
Hi, thanks for showing us the behavior you observed!

Would you mind providing...

* Relevant logs from:
  * the command line
  * ~/.kolibri/kolibri.log
  * the browser console
* Precise steps that someone else can follow in order to see this behavior
* Information about your environment, including:
 * Kolibri version
 * Operating system
* Information about where your drives are mounted to

**Comment by siamraj** [comment]
Relevant logs from:
Precise steps that someone else can follow in order to see this behavior : **We faced  Same issues.** 
Information about your environment, including:
Kolibri version : **KALiteSetup-0.17.4**
Operating system : **Windows 10 64 bit**
Information about where your drives are mounted to:
**USB device mounted read/Write permission.  (Pendrive)**

**Comment by indirectlylit** [comment]
Hi @siamraj - I'm sorry but the information you've provided does not have sufficient detail for us to reproduce the issue.

I'd recommend asking for help in our support forums: http://community.learningequality.org/

We can always re-open this issue if it turns out to be a reproducible Kolibri issue.

good luck!
