### ISSUE TITLE
Don't show incorrect username or password when prompting a non-learner for password

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#3582]
### Observed behavior
Currently we show a large warning when a login attempt fails, regardless of whether it was a non-learner user attempting to login through simplified login.

### Expected behavior
Only show the simplified login specific warning.

### User-facing consequences
Can cause confusion as to why an error is reported, as seen here: #3580

### Context
Kolibri 0.9.1

![image](https://user-images.githubusercontent.com/1680573/39133245-0ba0d020-4714-11e8-90d3-5dad2309fc6c.png)

**Comment by jonboiser** [comment]
Not sure I understand the OP. Is this the expected behavior?

1. GIVEN the facility is configured to use the "simplified login"
1. WHEN a non-learner user attempts to login with username only (e.g. "PM")
1. THEN the password input appears with the message "passwrod is required..."
1. THEN the red alert box on top ("incorrect username...") does not appear.

**Comment by rtibbles** [comment]
Yeah, that's what I would expect.

**Comment by rtibbles** [comment]
Fixed in #3584
