### ISSUE TITLE
Kolibri 0.9.1 will not Install on Lubuntu 16.04

### ISSUE THREAD

**Issue by kilimba** [learningequality/kolibri#3651]
### Observed behavior
On running `sudo apt-get install kolibri` on Lubuntu 16.04 I encounter the following:

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kolibri : Depends: python3-distutils but it is not installable
           Recommends: python3-cryptography but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

NB: Installing on Lubuntu 16.04 was only attempted after failing to install on Lubuntu 18.04 which _also_ failed as per https://community.learningequality.org/t/failing-to-install-on-lubuntu-18-04/621
…

### Expected behavior
Expected a smooth install
…

### User-facing consequences
This limits schools in low resource settings, including old computing hardware, from using lightweight OS's more suited to their hardware. The hardware available to me cannot run a full bloat Ubuntu 18.04 nor 16.04, which is what prompted me to try lightweight versions of them (which run fine, except will not install Kolibri as per above)

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by benjaoming** [comment]
Thanks @kilimba ! I spotted this on 18.04 as well after a clean installation.

It is fixed in 0.9.1-0ubuntu2, just released here: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri/+packages

Will get it uploaded to our servers as well, but try the PPA for now, it should fix it. And in case you have any other issues, am in touch here: http://github.com/learningequality/kolibri-installer-debian/
