### ISSUE TITLE
Save button was accidentally press and it's disabled when editing a username

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#3734]
### Observed behavior
When we edit existing username and accidentally click the save, the save button will disabled.  
Refer attached screenshot for more information.

### Expected behavior

We can edit again and save it.

### Steps to reproduce

1. login with admin account.
2. Click on facility.
3. Click on user tab.
4. Click on manage tab of any user.
5. Point the cursor in username text box then save and try to edit username again.

### Context

 * Kolibri version : 0.10.0a1
 * Operating system : MacOS 10.13.3
 * Browser : Chrome

## Screenshot
![screen shot 2018-05-31 at 12 03 30 pm](https://user-images.githubusercontent.com/38421180/40760734-bd43bf62-64ca-11e8-98dd-99504fb6d423.png)

**Comment by indirectlylit** [comment]
I can reproduce this. Nice catch, thanks!

**Comment by indirectlylit** [comment]
From what I can tell, the problem is with this line: https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/facility_management/assets/src/state/actions/user.js#L86

We're referencing an attribute `role` which is `undefined`. Instead, the facility user has a `roles` array which can contain multiple roles - e.g. both coach and admin.

**Comment by indirectlylit** [comment]
cc @jonboiser would you mind taking a look at this
