### ISSUE TITLE
KOLIBRI_LISTEN_PORT in /etc/kolibri/daemon.conf not working

### ISSUE THREAD

**Issue by needlestack** [learningequality/kolibri#3750]
### Observed behavior

After setting `KOLIBRI_LISTEN_PORT=9090` in `/etc/kolibri/daemon.conf`, then starting via `service kolibri start` the server still tried to start on port 8080 (which is occupied on my system).

### Expected behavior

Kolibri should start on the port defined by `KOLIBRI_LISTEN_PORT` in `/etc/kolibri/daemon.conf`

### User-facing consequences

Can't start the server on an alternate port automatically using services

### Context

0.9.2

### Fix

The problem seems to be that the wrong variable name is getting exported in `/etc/default/kolibri` -- the following one-liner will fix the problem:

`sed -i '/export KOLIBRI_LISTEN$/ s/LISTEN$/LISTEN_PORT/' /etc/default/kolibri`

However I can't find this config file in the current repository to deliver a patch.

**Comment by indirectlylit** [comment]
thanks @needlestack 

In 0.10.0 (to be released in approx 2 weeks) you'll be able to set the port using an `options.ini` file. Documentation for how to do that is is forthcoming.

@benjaoming could you confirm that the port config will work as expected when Kolibri is daemonized?

**Comment by indirectlylit** [comment]
if you need this config earlier, perhaps @benjaoming can give advice

**Comment by benjaoming** [comment]
Thanks for reporting this @needlestack - the error is indeed a mis-spelling.

Because the fix is in a file that's maintained by the .deb, you can fix it by upgrading to 0.9.2-0-ubuntu4, released here in the testing PPA: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed

If you can confirm that it works, I'll proceed to releasing the package in the stable PPA...
