### ISSUE TITLE
No compatible source was found for this media

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#3834]
### Observed behavior

during my test in <a href="https://docs.google.com/spreadsheets/d/1FhA5qIDB2DfNJW7bCPZ8lweVI-ZfDUchwY8mJwqdMWE/edit#gid=934550639">kolibri integration testing </a> for Ububtu 18.04, I installed the kolibri 0.10.0b3.
Base on the kolibri scenarios "Engage with but do not complete individual content items" and follow the instruction. when I select a video and open it. theirs a message that "No compatible source was found for this media".

### Expected behavior
can see the video and can play.

### Errors and logs
```
Specified “type” attribute of “video/mp4” is not supported. Load of media resource /content/storage/d/0/d0dbba5528f28c6512ecbe52fb6ccdcb.mp4 failed.
All candidate resources failed to load. Media load paused.
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media 
Object { code: 4, message: "No compatible source was found for this media" }
media_player_module-0.10.0b3.js:12:15736
The video on this page can’t be played. Your system may not have the required video codecs for: video/mp4, video/mp4
```

### Steps to reproduce

-  login as a learner
- go to recommended page
- select a video and open it. The page will load, but can't play the video have a error message.

### Context
Kolibri version: 0.10.0b3
Operating system: Ubuntu 18.04
Browser: Firefox 59.0.2(64-bit)

### Screenshot
![screenshot from 2018-06-21 15-41-48](https://user-images.githubusercontent.com/38421180/41706291-034fb6ce-756e-11e8-8c65-9e37c8cf5ad8.png)

**Comment by radinamatic** [comment]
This is issue only on Ubuntu/Debian with Firefox combo, as some of the media codecs are not included by default in the installation because of the copyright. It is solved by installing [Ubuntu restricted extras package](https://help.ubuntu.com/community/RestrictedFormats).

Added the [warning in the docs](https://github.com/learningequality/kolibri-docs/pull/28/commits/a5f18149caaa06fa8e4dda17b4d5b08e925cdab0 ).

----

Edit - updated docs page:

https://kolibri.readthedocs.io/en/latest/access/access_lan.html#compatibility

**Comment by indirectlylit** [comment]
thanks!

**Comment by mrhrifat** [comment]
thanks

**Comment by NELLIRAJESH** [comment]
Thank you. It worked.
