### ISSUE TITLE
typography in exam reports could be improved

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3872]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/41803941-96b0f0ec-7643-11e8-9921-16bdc260358b.png)

### Expected behavior

* face icon next to header should probably be removed? Or at least given 16px right margin
* elapsed time should be right-aligned and baseline-aligned with 'overall score'

### User-facing consequences

not much

### Context

k0.10.0

**Comment by rtibbles** [comment]
Is this still extant?

**Comment by jonboiser** [comment]
In 0.12, the header "test- Exam performance" is a little different, but the left and right-floated texts are still aligned the same way as in the screenshot above.

**Comment by indirectlylit** [comment]
note that we should be using `KLabeledIcon` for both the header and the progress indicator

**Comment by indirectlylit** [comment]
also I don't think we're supposed to use that face icon anymore – cc @khangmach that should just be a standard 'person' icon, correct?

**Comment by khangmach** [comment]
In the coach report mocks we:
- Did away with the user face icon
- Did away with any user icon on this page and opted for name only. 
- Moved 'exam performance' out of the primary header

<img width="484" alt="Screen Shot 2019-03-28 at 4 54 06 PM" src="https://user-images.githubusercontent.com/25045166/55200150-20d1ef80-517a-11e9-9e4e-37573a2258af.png">

**Comment by indirectlylit** [comment]
cool thanks. Regarding header semantics:

```html
<h1>{{ name }}</h1>
<p>
  <KLabeledIcon>
    <KIcon quiz />
    '{{ quiz title }}' performance
  </KLabeledIcon>
</p>
```

The second line is serving as a "sub-header" and not a paragraph, but we don't yet have any precedent for sub-headers in the app. Sub-headers are [a bit tricky](https://medium.com/@barvysta/if-youve-ever-had-doubts-about-how-to-mark-up-subheadings-220cbe97c361) to get right for screen readers because HTML doesn't have a built-in way of representing them.

In this case, I'd recommend simply removing the sub-heading because the information it provides is already present in the '← Quiz 1 report' app bar back link.

thoughts?

**Comment by jonboiser** [comment]
To stay consistent with our recent thinking on the immersive bar's label, the label coudl be "[X] Adam R Quiz Performance", since the label is supposed to be "the thing" you're looking at currently.

So:

1. Use an "X" icon, since this is a "terminal" location
1. The label should describe the current location (and maybe serve the role of a sub-header in that way)

**Comment by indirectlylit** [comment]
> the label coudl be "[X] Adam R Quiz Performance"

The hard part is the i18n translation string, because we can't just mash together `{name} {quiz name} performance`. We have one string that might be useful called a ["combined label"](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/common/commonCoachStrings.js#L124)

So perhaps something like:

>  ✕ Quiz 1 / Adam R
> 
> ## Quiz 1 / Adam R
> 
> Overall score ...

Seems a little awkward to me though... I still like the simplicity of:

>  ← Quiz 1 report
> 
> ## Adam R
> 
> Overall score ...

The hard part is that then we'd need to flip them depending on how you navigated to the page. I.E. in another part of reports, the same report would look like:

>  ← Adam R
> 
> ## Quiz 1 report
> 
> Overall score ...

**Comment by indirectlylit** [comment]
Totally agree though that most of this is dependent on us resolving the final convention for `h1` tags, header labels, and ←/✕ buttons, and we should decide and document that first

**Comment by jonboiser** [comment]
I don't like the idea of using different headers for the same UI. The screens will look visually distinct, but be basically the same.

**Comment by indirectlylit** [comment]
yeah, agreed

**Comment by MisRob** [comment]
I'm not 100% sure if I get the whole discussion around immersive toolbar right since I don't have much background about it yet so I'm inserting a couple of questions before starting working on that:

Should I use the mockup that @khangmach  provided us to stay up-to-date with our design files just to fix those visual details and in case there are any major logic changes needed, should it be discussed with design folks at first and implemented after the mockup is updated? I suppose that such modifications of immersive toolbar logic might need wider discussion and would also affect more parts of the app, right?

In case I should use another solution based on the discussion above immediatelly:

> In this case, I'd recommend simply removing the sub-heading because the information it provides is already present in the '← Quiz 1 report' app bar back link.

> The label should describe the current location (and maybe serve the role of a sub-header in that way)

The information is somewhat duplicate, yeah, but I'm wondering if including it in the navbar only is sufficient? Especially when it comes to screen readers - having in it header seems to be quite unambiguous when compared to having it in navigation only?

> Use an "X" icon, since this is a "terminal" location

So, in general, are we supposed to use "X" every time a user cannot navigate anywhere "forward", is that correct?

**Comment by khangmach** [comment]
>So, in general, are we supposed to use "X" every time a user cannot navigate anywhere "forward", is that correct?

There aren't rules of thumbs that we consistently follow and it's a thing that I'm working on currently. But in general, the thinking introduced long ago was that :
- terminal pages (end of a flow) were distinguished by their dark color instead of the Kolibri color. 
- X topnav were used on pages that weren't part of a typical page sequence. By "page sequence" I mean pages where the main purpose is drilling down and navigating deeper into the UI. So X's would be used on "pages" that were full-screen modals, or had a separate process

An example is with the coach lessons feature. You can go through a sequence of pages to find a lesson you created, it's report and summary etc etc, but you can also create a new lesson, which is a separate process that  overlays itself/interrupts the main page flow you're going through.

This has changed a bit via Report pages incorporating the X topnavs. So I need to do a bit of revision around the app. I'd recommend putting off this issue until solid rules are designed. 

Did a bit of a diagram of what I mean

![sample](https://user-images.githubusercontent.com/25045166/56612139-69899680-65c8-11e9-91b7-882b97cfe853.png)

**Comment by MisRob** [comment]
Oh nice, I get it now - thanks for a nice explanation @khangmach :)

@jonboiser I'm removing this ticket from my beginners' issues for now but can have a look at navbars in general later when we have new designs.

**Comment by indirectlylit** [comment]
closing because the originally reported issue is addressed.

We still have a lot of work to do getting immersive modals and end states consistent, but it's outside the scope of this issue
