### ISSUE TITLE
Inconsistent progress labels on exams

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#3896]
### Observed behavior

If a learner completes all questions in an exam but does not submit it, the coach can still see that learner's progress on questions, which is intentional by design.

However, the label for the learner's status on the exam is inconsistent:

<img width="1198" alt="screen shot 2018-06-26 at 10 20 32 am" src="https://user-images.githubusercontent.com/6668144/41928618-a63712d2-792a-11e8-9bbc-41539c4de518.png">

### Expected behavior

Whether `in progress` or `completed`, the label should be consistent.

### User-facing consequences

Coach may be slightly confused

### Steps to reproduce

1. Create an exam, set to active, and assign to learners
2. Log in as learner
3. Complete all questions, but do not submit exam
4. Log in as coach or admin
5. Look at exam progres for that learner

### Context

Kolibri 0.10.0b7
MacOS
Chrome

**Comment by indirectlylit** [comment]
Until the exam is either closed by the coach or submitted by the learner, I believe it should be considered in-progress.

**Comment by jtamiace** [comment]
Agreed

**Comment by khangmach** [comment]
+1 on the above(s).

**Comment by jonboiser** [comment]
@jtamiace 	Can you provide a way to reproduce this? The expected behavior for an exam that is in progress is for the "progress" column to say something like "5 of 10 questions remaining".

The condition for the column to say "complete" is that the Exam Log has `complete: true` or its `progress` field is equal to the number of questions in the exam. If the example exam is really not done, there might be an issue with the Exam Log (possibly that the `progress` field is miscalculated)

**Comment by jonboiser** [comment]
This might have actually been fixed in pull request #3499

**Comment by jonboiser** [comment]
Okay, #3499 did fix the back-end, but the front-end did need a minor tweak. The 'complete' message should only appear if the `examlog.complete === true`. If `examlog.progress === exam.question_count` but it's not 'complete', we should still count it as 'in progress'.
