### ISSUE TITLE
Showing KA site hindi content in English 

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3933]
### Observed behavior
Rajasthan channel contains KA content which are in Hindi but after importing those in Kolibri, it shows content in English instead of Hindi.

Channel ID : e890b1acbcad44939688dbb1b7dde2e5
Path : गणित - कक्षा 6 - 3 पूर्णं संख्याएँ - पूर्णं संख्याएँ - पूर्ण संख्याओं के गुणधर्म - गुणन का क्रमविनिमेय गुणधर्म

### Expected behavior
After importing content into Kolibri, it should be same as source content.

### Steps to reproduce
1. Import channel ID : e890b1acbcad44939688dbb1b7dde2e5 content (गणित - कक्षा 6 - 3 पूर्णं संख्याएँ - पूर्णं संख्याएँ - पूर्ण संख्याओं के गुणधर्म - गुणन का क्रमविनिमेय गुणधर्म ) in Kolibri.
2. Try to solve those exercise.

### Context

 * Kolibri version : Kolibri 0.9.2 
 * Operating system : Ubuntu 14.04
 * Browser : chrome 

### Screenshots

Kolibri :

![screen shot 2018-06-29 at 5 05 53 pm](https://user-images.githubusercontent.com/12776071/42090352-c2552a62-7bbe-11e8-9ebf-50e3b4e86b5f.png)

KA Site : 

![screen shot 2018-06-29 at 5 05 45 pm](https://user-images.githubusercontent.com/12776071/42090358-ca8977ce-7bbe-11e8-9478-8a42294f8593.png)

**Comment by ralphiee22** [comment]
Hi @swapnil106111, I believe this is an issue with having old outdated content. Since the channel was curated from the KA hindi channel, and there have been several updates to KA Hindi for things such as excluding non translated content. I have manually synced the channel to bring it in line with the latest KA hindi channel. I also published the Rajasthan channel so this should no longer be an issue. All you need to do is update the Rajasthan channel through the UI.
If you can confirm the fix, we can then close the issue.

**Comment by rupangi11** [comment]
@ralphiee22 this has not been fixed yet. We still see English content in the Hindi channel. The channel does not seem to be synced since there is a difference in the number of resources as well

**Comment by indirectlylit** [comment]
please re-open if the issue persists
