### ISSUE TITLE
Observe the size is not same. I try to import using flash drive.

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#3981]
### Observed behavior
Take a look at the screenshot, the size is not the same on flash drive.

comment by @jamalex 
This one is a known issue; we don't know based on the content database which content node files are actually available on the USB drive, and haven't looked into an efficient way to scan real-time.

### Expected behavior
Must be same amount in flash drive.

### Steps to reproduce
1. login as admin
2. go to device page
3. click Import and select token "pratham books' StoryWeaver" then check only one file like STEM and import it, wait to finish. 
4. then export choose flash drive(kington for ex.), then select the token "pratham books' StoryWeaver" ,then check select all and export it.
5. re-install the kolibri 0.10.0(delete all data files attach).
6. then try to import using the flash drive in offline(no internet connection).

### Context
windows 7
kolibri 0.10.0
firefox 61.0.1(64-bit) 

### Screenshot
![errorondatasize](https://user-images.githubusercontent.com/38421180/42355192-4e98855c-80fe-11e8-91c6-5186d7f4698c.png)

**Comment by indirectlylit** [comment]
* When you "select all", does it calculate at that point which items are actually available?
* When you navigate down the tree, does it indicate availability there?

**Comment by nobicycle** [comment]
Khan Academy (English) import
========================

In 0.11 I just imported overnight what was shown by Kolibri as 4GB worth of import. I know this specifically, because that is my internet quota and I am obviously watching not to exceed it.

In the morning Kolibri the download was reported as complete. I clicked the close button.

However Kolibri is reporting  2GB only in the channel.

**Comment by rtibbles** [comment]
This should be addressed in 0.13.0.
