### ISSUE TITLE
Browser freeze after selecting all exercises.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3983]
### Observed behavior
Browser freeze after selecting all exercises.

### Errors and logs
![screen shot 2018-07-06 at 11 25 54 am](https://user-images.githubusercontent.com/8663934/42358586-e77b5bb2-810f-11e8-972f-6b1cbcb00783.png)

### Steps to reproduce
* Download contents from CK-12 channel with more than 876 exercises.
* Create an exam then select all CK-12 content exercises.
### Context

 * Kolibri version: 0.11
 * Operating system: Windows 10
 * Browser: Firefox 61.0.1

**Comment by indirectlylit** [comment]
cc @jonboiser any chance this is a regression from vuex work?

**Comment by jonboiser** [comment]
Selecting exercises for exams has always been resource intensive since clicking an entire channel actually execute a function for every node in the subtree that is an exercise, and 876 nodes is a relatively large number. It's possible that the reason the browser is still locked is that the request for those nodes is still pending.

**Comment by indirectlylit** [comment]
@mrpau-richard mind checking if the same issue happens in 0.10.0 when you have the same content?

**Comment by mrpau-richard** [comment]
@indirectlylit I confirmed that it's the same behavior in 0.10.

**Comment by indirectlylit** [comment]
I just reproduced this while testing on the raspberry pi. Seemed to peg CPU super high on the client and eventually the browser died:

![image](https://user-images.githubusercontent.com/2367265/42542534-1cda8f5e-845c-11e8-8ff7-e0423e2ad545.png)

This was while trying to 'select all' on a large chunk of KA math.

**Comment by indirectlylit** [comment]
Note that the initial page load was also very slow, but eventually ended. However selection never ended.

**Comment by jonboiser** [comment]
Yeah, it's the client-side logic that is slow. It is actually O(n^2) when batch-adding a bunch of exercises because here's the logic:

In the `addExercise` action

1. For each exercise E chosen to be added
1. For each exercise {F} already chosen
1. If E is in {F}, then add, else don't

Because {F} is growing at every time a new E is added, the loop in `addExercise` gets longer with each new E.

Maybe the fix is to right a specialization of `addExercises` that considers all the new Es at once.

**Comment by jonboiser** [comment]
The issue with the slow initial load might be a longer term fix. The reason it's slow on the demo server is that in the `gotoTopLevel` action, it requests every Exercise in every Channel, which could potentially be a large request.
