### ISSUE TITLE
Enhance the webpack builder to look at INSTALLED_APPS for buildable assets

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#40]
## Use case:

An external contributor does a `pip install kolibri` and then creates their own plugin with frontend JS.

After doing a `kolibri plugin enable` and `npm run build`, webpack should then inspect the list of `INSTALLED_APPS` (where the new plugin is presumably added), and then build assets, and inform Django that the new assets are available for serving.

**Comment by benjaoming** [comment]
install environment != build environment

Gonna ramble a little, but perhaps you can clarify the motivation of this issue a bit and update the description where possible?

Some components and properties of these environments are available to both, but most aren't. To a build environment, the source code is just a bunch of files. And to an installed environment, the build tools aren't available and many directories aren't even writable.

Can I ask, @aronasorman, if you expect `plugin enable` to invoke npm? Because it is very important to keep the build pipe line separate from user commands like `plugin enable`. I would think that `plugin enable` should possibly invoke the `collectstatic` command... but building the static items has to be done within the build env.

>  inform Django that the new assets are available for serving.

= `collectstatic`? Because this is a user command, not a command for the build pipeline. It collects static files on the end-user system and is subject to that install environment.

Someone creating a plugin would of course need to create assets, but this should be from within their own source directory.

INSTALLED_APPS is not part of a build environment, this is only in KA Lite's case of doing stuff the wrong way :) Otherwise it belongs strictly within a uniquely installed target system.

Think of an external plugin (one that is properly packaged) as a complete django app sitting in its own repo with a Makefile, a python package and a setup.py.

**Comment by aronasorman** [comment]
> Can I ask, @aronasorman, if you expect plugin enable to invoke npm?

> Can I ask, @aronasorman, if you expect plugin enable to invoke npm?
I don't expect it to. However, what I do want is a good external contributor development workflow.

> but perhaps you can clarify the motivation of this issue a bit
Here's the use case I'm thinking of, which is the main motivation for opening this issue:

1. I'm an admin in the prison system who just installed Kolibri in debian and everything's going great.
1. However, there are certain types of content that I want to support which isn't supported in Kolibri by default. Like, say, Flash games.
1. I can extend the Kolibri I have installed with my own plugin! I do this by creating a new folder with `kolibri startplugin`, this creates whatever boilerplate we need (including `setup.py`).
1. I write my JS and python code. But I want to test it, so I do a `kolibri plugin enable`. That registers my current code, separate from the main Kolibri code.

How do I continue and add support for my new content? Basically, how can I, while developing, and while Kolibri is just a package and unmodifiable, start testing if my JS works? 

Do I need to install webpack, and use `npm run build`? Can I just declare my assets somehow without needing it?

> = collectstatic?

Sure. I'm just open to the idea of making a wrapper/alternative to such command, as long as it's documented.

**Comment by benjaoming** [comment]
@aronasorman okay, get it! 3 first steps sound good

Step 4: Building JS stuff by hooking in something to the `runserver` command isn't unconventional. Like `browserify`. How they otherwise go about with npm and javascript build configurations, could be up to them. But we could ensure that we have a nice template and simple documentation that lands them with a usable setup of their own?

So if say the developer adds `some_automathic_js_builder` to INSTALLED_APPS in their `kolibri/settings.ini`, that would work? They are allowed to do develop-like stuff in the use case, right?

I was wondering if we can effectively have all these things wrapped up nicely by creating a `kolibri-dev` package, containing all the utilities necessary for *building* a plugin.

This way, we could ensure a proper isolation of our installed user environment and the utilities we intend developers to invoke at dev/build-time and never to be used on the installed target.

**Comment by aronasorman** [comment]
> How they otherwise go about with npm and javascript build configurations, could be up to them.

That sounds fair. Although my impression right now is that the current build process (specifically the `frontend_assets` tag) requires some webpack-specific metadata. Is that the case @rtibbles?

**Comment by aronasorman** [comment]
> Building JS stuff by hooking in something to the runserver command isn't unconventional. Like browserify

@benjaoming do you mean, having the external contributor make their own wrapper for `runserver`, so that it runs the asset bundler of their own choice? Or will we add support for it somehow?

**Comment by benjaoming** [comment]
> Or will we add support for it somehow?

If we decide to do a kolibri-dev package, and it's enabled and comes with a hook for `runserver` (or overshadows the entire command), then I think that's the way to go, because it's easy to say:

# Kolibri plugin development

1. `pip install kolibri-dev`
1. Add the `kolibri_dev_tools` application to the installed apps of your kolibri dev instance, for instance by running `kolibri plugin enable kolibri_dev_tools`
1. Now create a new Kolibri plugin project
1. `kolibri startplugin my_plugin && cd my_plugin && pip install -e .`
1. To run a development server, do `kolibri manage runserver`

**Comment by rtibbles** [comment]
This issue has been instantiated to look at enabled plugins rather than INSTALLED APPS. Closing.
