### ISSUE TITLE
Apache2 Reverse proxy subdirectory /kolibri 

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri#4127]
I found that it was difficult to deploy Kolibri using Apache2 mod_proxy module on subdirectory "/kolibri". The issues stems from the fact that django users absolute paths internally. 

Here is full Apache2 kolibri.conf configuration: 

```<VirtualHost *:80>
    ProxyPreserveHost   On
    RedirectMatch       ^/kolibri$         /kolibri/
    ProxyPass           /kolibri/          http://127.0.0.1:8009/
    ProxyPassReverse    /kolibri/          http://127.0.0.1:8009/
</VirtualHost>
```
And Kolibri Systemd unit file. 

```[Unit]
Description=Kolibri

[Service]
Type=forking
RemainAfterExit=yes
Environment=KOLIBRI_USER=kolibri
Environment=KOLIBRI_HOME=/opt/kolibri
Environment=KOLIBRI_HTTP_PORT=8009
Environment=ALLOWED_HOSTS=localhost
Environment=USE_X_FORWARDED_HOST=True

ExecStart=/usr/local/bin/kolibri start
ExecStop=/usr/local/bin/kolibri stop

[Install]
WantedBy=multi-user.target
```
And the downstream bug: https://github.com/iiab/iiab/issues/913

**Comment by arky** [comment]
@holta Please kindly follow-up kolibri on subpath feature request here. Thanks!

**Comment by holta** [comment]
Another vote for @arky's Django suggestion/recommendation here, so that Kolibri can be cleanly integrated into Internet-in-a-Box 6.7 later this year.

Even if this is not possible for [IIAB 6.6](https://github.com/iiab/iiab/wiki/IIAB-6.6-Release-Notes) in August now, but still honoring teachers' and students' eternal requests for a clean/mnemonic URL like http://box/kolibri

_Profound thanks to @ivanistheone and @benjaoming for all your help to date!_

**Comment by indirectlylit** [comment]
Thanks for the feedback!

We've run into similar situations internally, and we have an item in our roadmap to allow Kolibri to be configured to mount urls under a subpath.

We have it tentatively scheduled for 0.11.0 but it's not currently a hard requirement. Since it looks like it'd be useful for you, I'll try to increase the priority.

**Comment by holta** [comment]
> We have it tentatively scheduled for 0.11.0

Many thanks @indirectlylit.

If you need testing help along the way, definitely let us know~

**Comment by rtibbles** [comment]
I am futzing with the URLs now, so I will implement this on the way.

**Comment by arky** [comment]
Thank you @rtibbles !

**Comment by benjaoming** [comment]
@rtibbles couple of questions:

How many Django configuration settings are necessary for this to work? Will the new implementation respect `STATIC_URL` and `MEDIA_URL`? Are there others?

Furthermore, since there might be several URLs that need prefixing, should we perhaps introduce a `KOLIBRI_URL_ROOT`, which should be allowed to be a full URI? (i.e. `https://learningequality.org/kolibri/demo`) ?

**Comment by benjaoming** [comment]
FTR:

`options.ini` now supports `PATH_PREFIX`

@rtibbles I just remembered, though, that as to my above message, I think we need to add some more context to the naming. Because there are two types of paths: 1) the URL and 2) the disk path.

I think calling this `URL_PATH_PREFIX` is will avoid future ambiguity.

**Comment by indirectlylit** [comment]
> I think calling this URL_PATH_PREFIX is will avoid future ambiguity.

agreed

**Comment by benjaoming** [comment]
@rtibbles before finally closing this, could you quickly rename this? :)

**Comment by rtibbles** [comment]
Sounds good.
