### ISSUE TITLE
Kolibri fails under Python 3.7 - SyntaxError: Generator expression must be parenthesized

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4182]
$ uname -a
Linux tower 4.14.65-1-MANJARO #1 SMP PREEMPT Sat Aug 18 13:29:56 UTC 2018 x86_64 GNU/Linux
[me@tower Kolibri]$ python -V
Python 3.7.0

Hi, install  is now failing since Python moved to version 3.7.

> 2018-08-23 02:04:42 [INFO] Installing /home/archives/Education/Content/Kolibri/kolibri-0.10.1-py2.py3-none-any.whl ...
> Using base prefix '/usr'
> New python executable in /opt/kolibri/kolibri-venv/bin/python
> Installing setuptools, pip, wheel...done.
> Processing /home/archives/Education/Content/Kolibri/kolibri-0.10.1-py2.py3-none-any.whl
> Installing collected packages: kolibri
> Successfully installed kolibri-0.10.1
> You are using pip version 10.0.1, however version 18.0 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> 2018-08-23 02:04:59 [INFO] Performing restart kolibri ...
> Job for kolibri.service failed because the control process exited with error code.
> See "systemctl status kolibri.service" and "journalctl -xe" for details.
> 2018-08-23 02:05:00 [INFO] Performing start kolibri ...
> Job for kolibri.service failed because the control process exited with error code.
> See "systemctl status kolibri.service" and "journalctl -xe" for details.
> 2018-08-23 02:05:00 [INFO] Performing status kolibri ...
> ● kolibri.service - Kolibri server
>    Loaded: loaded (/usr/lib/systemd/system/kolibri.service; disabled; vendor preset: disabled)
>   Drop-In: /etc/systemd/system/kolibri.service.d
>            └─override.conf
>    Active: failed (Result: exit-code) since Thu 2018-08-23 10:05:00 WITA; 14ms ago
>   Process: 14090 ExecStart=/opt/kolibri/kolibri-venv/bin/kolibri start (code=exited, status=1/FAILURE)
>  Main PID: 14090 (code=exited, status=1/FAILURE)
> 
> Aug 23 10:05:00 tower kolibri[14090]:     from django.contrib.admin.options import IncorrectLookupParameters
> Aug 23 10:05:00 tower kolibri[14090]:   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/contrib/admin/options.py", line 12, in <module>
> Aug 23 10:05:00 tower kolibri[14090]:     from django.contrib.admin import helpers, widgets
> Aug 23 10:05:00 tower kolibri[14090]:   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/contrib/admin/widgets.py", line 152
> Aug 23 10:05:00 tower kolibri[14090]:     '%s=%s' % (k, v) for k, v in params.items(),
> Aug 23 10:05:00 tower kolibri[14090]:     ^
> Aug 23 10:05:00 tower kolibri[14090]: SyntaxError: Generator expression must be parenthesized
> Aug 23 10:05:00 tower systemd[1]: kolibri.service: Main process exited, code=exited, status=1/FAILURE
> Aug 23 10:05:00 tower systemd[1]: kolibri.service: Failed with result 'exit-code'.
> Aug 23 10:05:00 tower systemd[1]: Failed to start Kolibri server.

**Comment by nobicycle** [comment]
Same applies to kolibri pex version

> $ ls -l /opt/kolibri/bin/kolibri.pex
> lrwxrwxrwx 1 kolibri kolibri 36 Aug 23 10:57 /opt/kolibri/bin/kolibri.pex -> /opt/kolibri/bin/kolibri-v0.10.1.pex
> [me@tower Kolibri]$ cat /usr/lib/systemd/system/kolibri-pex.service
> [Unit]
> Description=Kolibri (pex) server
> [Service]
> Type=oneshot
> RemainAfterExit=yes
> PIDFile=/run/kolibri-pex.pid
> WorkingDirectory=/opt/kolibri
> User=kolibri
> SyslogIdentifier=kolibri-pex
> ExecStart=/opt/kolibri/bin/kolibri.pex start
> [Install]
> WantedBy=multi-user.target
> [me@tower Kolibri]$ sudo systemctl restart kolibri-pex.service
> Job for kolibri-pex.service failed because the control process exited with error code.
> See "systemctl status kolibri-pex.service" and "journalctl -xe" for details.
> [me@tower Kolibri]$ systemctl status kolibri-pex.service
> [me@tower Kolibri]$ systemctl status kolibri-pex.service --no-pager
> ● kolibri-pex.service - Kolibri (pex) server
>    Loaded: loaded (/usr/lib/systemd/system/kolibri-pex.service; disabled; vendor preset: disabled)
>   Drop-In: /etc/systemd/system/kolibri-pex.service.d
>            └─override.conf
>    Active: failed (Result: exit-code) since Thu 2018-08-23 11:05:54 WITA; 17s ago
>   Process: 22184 ExecStart=/opt/kolibri/bin/kolibri.pex start (code=exited, status=1/FAILURE)
>  Main PID: 22184 (code=exited, status=1/FAILURE)
> 
> Aug 23 11:05:53 tower kolibri-pex[22184]:     from django.contrib.admin.options import IncorrectLookupParameters
> Aug 23 11:05:53 tower kolibri-pex[22184]:   File "/opt/kolibri/.pex/install/kolibri-0.10.1-py2.py3-none-any.whl.8e63b668f3fb4e99fe11bfc…n <module>
> Aug 23 11:05:53 tower kolibri-pex[22184]:     from django.contrib.admin import helpers, widgets
> Aug 23 11:05:53 tower kolibri-pex[22184]:   File "/opt/kolibri/.pex/install/kolibri-0.10.1-py2.py3-none-any.whl.8e63b668f3fb4e99fe11bfc…, line 152
> Aug 23 11:05:53 tower kolibri-pex[22184]:     '%s=%s' % (k, v) for k, v in params.items(),
> Aug 23 11:05:53 tower kolibri-pex[22184]:     ^
> Aug 23 11:05:53 tower kolibri-pex[22184]: SyntaxError: Generator expression must be parenthesized
> Aug 23 11:05:54 tower systemd[1]: kolibri-pex.service: Main process exited, code=exited, status=1/FAILURE
> Aug 23 11:05:54 tower systemd[1]: kolibri-pex.service: Failed with result 'exit-code'.
> Aug 23 11:05:54 tower systemd[1]: Failed to start Kolibri (pex) server.
> Hint: Some lines were ellipsized, use -l to show in full.
>

**Comment by pjames44** [comment]
Please note 3.7 is now the default system python on Arch Linux so Kolibri no longer works on any Arch system.  Error appears to be related to django version, fixed in newer versions:

https://github.com/django/django/commit/931c60c5216bd71bc11f489e00e063331cf21f40

**Comment by nobicycle** [comment]
@pjames44 
python-django is at version 2.1-2 as of now but it is not required to be installed for running Kolibri. Kolibri-Pex is supposed to be self contained. So I supposed your comment is  regarding the packaging g of Kolibri - for that I will just have to wait? Or can I alter something after  a pip install or a pex install to fix it?

**Comment by pjames44** [comment]
Sorry nobicycle, I wasn't commenting as someone knowledgeable: I don't know how to fix the error but it *seems* related to the django version which is why I linked to that.  I wish I could answer your questions since I would like to run kolibri as well!  Clearly the pex version is affected by the system version and is not self-contained since my kolibri broke after moving from python 3.6 to 3.7.

**Comment by nobicycle** [comment]
@pjames44

I got it running as follows

**Download and extract old python, removing any share and link potential conflicts**

Install agetpkg-git
Fetch python3.6.6
Extract to a temporary directory
Remove share folder and and links
sudo cp usr / -R

**Then, here is what I usually do for Kolibri:**

> sudo -u $KOLIBRI_USER /bin/bash -c "
> cd $KOLIBRI_HOME
> virtualenv --python=python3.6  --never-download kolibri-venv
> cd kolibri-venv
> source bin/activate
> pip install '$KOLIBRI_ARCHIVE' $POSTFIX_OPTIONS
> "
> 

**The change is adding  --python=python3.6** 
Note, I download the Kolibri whl in advance. Hence the path variable KOLIBRI_ARCHIVE

**Comment by rtibbles** [comment]
Thanks for providing a workaround, @nobicycle - it looks like Django 1.11 has marked Python 3.7 compatibility as won't fix, so not sure how we can resolve this going forward without forking.

**Comment by indirectlylit** [comment]
(We still have a couple use cases where python 2.7 support is required, which is why we can't yet upgrade to Django 2.0.)

**Comment by benjaoming** [comment]
Different fixes:

1. Create a Kolibri package without bundled imports, but specifying requirements like an ordinary PyPi package - allowing anyone with the issue to install a different patched up Django
1. Create an Arch package that uses Python 2.7 (but that forces Arch users to use 2.7, which they may not be very happy about)
1. Vouch for the introduction of Python 3.7 compatibility for Django 1.11, stating our case to Django maintainers and wait for an upstream fix
1. Mark as WontFix until we have made the jump to Django 2.0 and cut Python 2.7 support
1. Bundle a patched up Django
1. Add a Quilt patch specifically to the .deb for patching up the Django 1.11 bundled code (it's a cleaner way of maintaining such a patch than otherwise).
1. Once the `kolibri-server` Debian package is out with a UWSGI configuration, it should be easy to add a virtual environment for Kolibri on top of this. This way, we can turn the issue into a pure documentation issue, since Python 3.7 users can be considered advanced users until it hits the mainstream in a distant future. Solution resembles what @nobicycle shared below.

**Comment by benjaoming** [comment]
@nobicycle thanks for sharing your Python 3.6 fix and for reporting the issue!

Would you mind sharing how bad in your case it is to install an older version of Python? Just to escalate / deescalate the severity. It does seem like something that has to be fixed soonish. Ubuntu 18.10 was released with Python 3.6, so I can see the wider adoption starting maybe around the time of 19.04...

Advantages of Python 3.7 are a couple, but we cannot IMO make use of them in Kolibri, as we have to handle fallbacks to older Python versions. Thus it's too troublesome, as we are limited in dev resources for such ventures.. thinking about the complexity and legacy maintenance that comes along. Also again for the wider adoption of Python 3.7, that could be 1+ year ahead.

Having broken Python 3.7 support is of course a whole other issue than taking advantage of its features, I just wanted to get it in the picture, so that we see the latter as a separate chapter in a distant future :)

**Comment by nobicycle** [comment]
@benjaoming

I just checked, Ubuntu and I supposed Debian have both python3.6 and python3.7 in their repos. I use Arch/manjaro. Therefore, this covers almost all distros - they all have 3.6 and 3.7 available.

The procedure is as follows:

Download the whl file somewhere and assign variable KOLIBRI_ARCHIVE_PATH pointing to it.

**Install Kolibri**

Install python 3.6 and 3.7 using the package manager.
mkdir /opt/kolibri
create a user kolibri with /opt/kolibri as home
Login as kolibri. sudo -u kolibri  /bin/bash
cd /opt/kolibri
VENV_SUBDIR=kolibri-venv #Change as desired
virtualenv --python=python3.6 --never-download $VENV_SUBDIR
cd $VENV_SUBDIR
source bin/activate
pip install $KOLIBRI_ARCHIVE_PATH

**Create a service**

$ cat /usr/lib/systemd/system/kolibri.service
[Unit]
Description=Kolibri server
[Service]
Type=oneshot
RemainAfterExit=yes
PIDFile=/run/kolibri.pid
WorkingDirectory=/opt/kolibri
User=kolibri
SyslogIdentifier=kolibri
ExecStart=/opt/kolibri/kolibri-venv/bin/kolibri start
[Install]
WantedBy=multi-user.target

**Start Service**
sudo systemctl start kolibri


The above is a vanilla procedure for installing a koliibri virtualenv . The only version specific part is **--python=python3.6**  Therefore the answer to your question "how bad in your case it is to install an older version of Python? " is not bad at all.

For the python-pex method it should be a simple matter of packaging similar to the example below::

> pex **--python=python3.6** -f $PWD requests myexample -e samplepkg.main -o samplepkg.pex

https://idle.run/simple-pex

Obviously the pex package name should include the python version it was built with.

In both cases very simple.

**Comment by benjaoming** [comment]
Sounds good, thanks for sharing your method @nobicycle - using a virtualenv will be easy to configure once we have a UWSGI Debian package. It will ship a `.ini` configuration, which just needs a single line customized to run inside a virtualenv. I'll add this to the above list of ways of fixing this...

**Comment by benjaoming** [comment]
Despite the wontfix, they did fix it :tada: 

@nobicycle do you have a use for a 0.11 patch upgrade for Python 3.7 support or are you fine about waiting for 0.12?

#4548

**Comment by nobicycle** [comment]
@benjaoming
Sorry I only just discovered  your last message, as I was revisiting the issue: Arch ARM devices do not support python 3.6, so I was checking progress to 3.7

Yes I would like to test the patch.
