### ISSUE TITLE
RTD URL has bug in downloading a specific version

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4208]
### Observed behaviour
We tried to download a version 0.7.x, 0.8.x, and 0.9.x that we need in Kolibri RTD but when we click the Install instruction "Download Kolibri Windows installer" , automatically the kolibri version 0.10.2. or the latest version is downloaded instead of kolibri version 0.7.x .

@cpauya -This wrong install URL affects the 0.7.x, 0.8.x, and the 0.9.x Kolibri RTD… 
https://kolibri.readthedocs.io/en/release-v0.7.x/install.html#install

1. We emphasize the link to the LATEST installer within the documentation of the previous releases and mention that we encourage them to use that instead and redirect them to the appropriate documentation for such. The Ubuntu installation instructions already mention `download the latest Kolibri .deb installer...` so that's fine I think.

2. For consistency though, I think we should give them the link to the version they want in that old doc (the same way that Ubuntu still provides the installers from their previous releases in their appropriate install docs). The reason is that I'm not sure if the steps during installation will still be the same between the old versions versus the latest one. When this happens, it may add another layer of confusion.

3. I understand this is trivial so let's move this to the correct repo please. :)

![rtd must follow the versioning](https://user-images.githubusercontent.com/38421180/44971494-59b13980-af88-11e8-8f3b-8b4a5f7a0779.png)

### Steps to reproduce

1. Go to this link: https://kolibri.readthedocs.io/en/release-v0.7.x/install.html#install 
2. Try to download a Kolibri Windows installer

**Comment by cpauya** [comment]
Thanks for reporting @mrpau-julius :)

Let's point those installation URLs to the signed installers at the Pantry server.

**Comment by cpauya** [comment]
This also affects v0.10.x (when v0.11.x is released) coz it also points to the latest Kolibri installer URL.

**Comment by cpauya** [comment]
@mrpau-julius When you got time to make a PR for this the Pantry download URLs for Kolibri releases are at [Kolibri downloads](http://pantry.learningequality.org/downloads/kolibri/).

**Comment by radinamatic** [comment]
@mrpau-dev 2 comments:

1. This is technically a `kolibri-docs` issue, and therefore it should be reported in the [respective repo](https://github.com/learningequality/kolibri-docs) 🙂 
2. We should always encourage users to download and install the latest version of Kolibri, and that's why this link points to the current version from the docs in any version. So even if the user opens the docs link we sent them by email many months ago (and may not be aware that they are reading the old version), we do not want them to download and install the Kolibri version 0.7 that they initially received the information about, but we _do_ want them to install the most recent one. Therefore, in my eyes, this is a _feature, not a bug_. 😉 

True, they will encounter differences between the docs and the version they install, but we could point them to the right one easily. I believe this inconvenience is outweighed by the benefit of them running the most recent version of Kolibri.   

cc @indirectlylit

**Comment by cpauya** [comment]
Ouch sorry, @mrpau-julius please file this issue there.

I am very amenable with your comment#2 @radinamatic -- but to avoid confusion may I suggest that:

1.  We emphasize the link to the LATEST installer within the documentation of the previous releases and mention that we encourage them to use that instead and redirect them to the appropriate documentation for such.  The Ubuntu installation instructions already mention `download the latest Kolibri .deb installer...` so that's fine I think.

2.  For consistency though, I think we should give them the link to the version they want in that old doc (the same way that Ubuntu still provides the installers from their previous releases in their appropriate install docs).  The reason is that I'm not sure if the steps during installation will still be the same between the old versions versus the latest one.  When this happens, it may add another layer of confusion.

3. I understand this is trivial so let's move this to the correct repo please. :)

**Comment by radinamatic** [comment]
@cpauya 

1. Yes, that can can easily be added, you are right that it offers a more precise information about the installer to be downloaded. Putting it on my `docs-todo` list! 👍 
2. I would argue that the use case for downloading older releases of the full operating system like Ubuntu (for example, because of specific hardware constrains), is different from people accessing (most probably by mistake or unawareness) the older version of Kolibri docs, and therefore ending up downloading an obsolete version of Kolibri. 

If somebody for justified reasons really _needs_ to install an older version of Kolibri, I would prefer us vetting those reasons, and providing them with the requested installer if we assess it as more adequate. In my estimation those users will be far, far less in number, compared with people stumbling on older version of the docs, and not realizing that what they are downloading is not the most recent version of the software.

**Comment by indirectlylit** [comment]
Thanks for catching this! There are a few considerations here:

* For older documentation, you're right that we want to make sure people can download the installer if that's in fact what they want
* On the other hand, if people are running older versions of Kolibri or viewing older documentation, we want to encourage them to upgrade to the latest
* We get better analytics when people download through the `learningequality.org/r/...` redirects rather than pantry

I don't believe this is a common issue with typical users. Therefore, for now, I'd recommend holding off on submitting PRs to update the download URLs, until we decide on a solution that can balance the considerations listed above.

In the meantime, for integration testing purposes, all historic installers can be accessed directly from pantry: http://pantry.learningequality.org/downloads/kolibri/

**Comment by indirectlylit** [comment]
whoops sorry - I posted this before I saw all your responses over the last day. Reading now...

**Comment by indirectlylit** [comment]
thanks for all your input. I tried to summarize and migrated it to https://github.com/learningequality/kolibri-docs/issues/48

feel free to add follow-up
