### ISSUE TITLE
numerals not localized in all locales

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4363]
### Observed behavior

| Arabic | Urdu | Farsi |
|--|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/46538839-02520200-c883-11e8-8fe4-077115425e63.png) | ![image](https://user-images.githubusercontent.com/2367265/46539060-8efcc000-c883-11e8-8097-e25260883601.png) | ![image](https://user-images.githubusercontent.com/2367265/46539082-9e7c0900-c883-11e8-9903-68b9900e09bb.png) |

### Expected behavior

Numerals localized in all locales

### User-facing consequences

Difficulty understanding

### Steps to reproduce

Load profile page in various languages

### Context

* Kolibri 0.11
* Chrome 69
* MacOS

**Comment by jonboiser** [comment]
This seems to be a Chrome-specific issue; on Firefox and Safari, the TotalPoints component localizes the big number and the tooltip "correctly" (i.e. with arabic numerals instead of latin).

In Chrome's implementation of `Intl.NumberFormat`, it doesn't seem to like just `ar` as a locale; it wants a more specific code:

```
new Intl.NumberFormat('ar-iq').format(0)

"٠"
new Intl.NumberFormat('ar-sa').format(0)

"٠"
new Intl.NumberFormat('ar').format(0)

"0"

new Intl.NumberFormat('ar-dz').format(0)

"0"
```

According to [this article](https://generatedcontent.org/post/60400838960/intltips), a subset of Arabic-speaking countries use Latin numbers as well, which is maybe why Chrome requires more specificity in the locale code.

**Comment by indirectlylit** [comment]
Thank you for investigating!

I suppose in that case, localization is working "as designed" on a per-browser basis. I opened a chromium issue here to let them decide if it's correct or not:

https://bugs.chromium.org/p/chromium/issues/detail?id=1057881
