### ISSUE TITLE
View more in Recommended page is not working

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4399]
### Observed behavior
In Learners Recommended page, View more label cannot clicked. 

### Expected behavior
Must be clickable the View more label.

### Steps to reproduce
* Sign in as learner
* Go to Learner > Recommended page
* Click the View more label

### Context
 * Kolibri version : 0.11.0b1
 * Operating system : Windows 7 and 10
 * Browser : Firefox  62.0.3 (64-bit)

**Comment by jonboiser** [comment]
@DXCanas This looks like it's because of the large negative margin around the carousel. It overlaps the "view more" button and prevents the user from clicking it.

**Comment by DXCanas** [comment]
Could we just reorder the elements? I think it would be more a11y-friendly too

**Comment by radinamatic** [comment]
It would make sense that the `View more` link comes after the right carousel arrow in the tab navigation order, instead of before the left arrow as of now.

**Comment by jonboiser** [comment]
Is there a simple way to set the desired tab-order with little code (e.g. via a taborder attribute)? Otherwise, #4406 is really narrow in scope that it just tries to fix the original clipped-shadow issue _and_ still have the "View more" button work.

**Comment by radinamatic** [comment]
Setting the `taborder` attribute to positive value to achieve this is not recommended. The right way would be to either set the value to `-1` and do it programmatically, or move the element itself below the corresponding carousel, instead of before it. 

Now it sits right after the `Most popular` heading in the page order (even though visually it is positioned on the right), which does not make much sense for the blind users (_See more of what? Haven't seen anything yet... :thinking:_). Screen readers are CSS-blind, and will read stuff as it appears on the page regardless of it, same as those who navigate by keyboard, who will encounter the `View more` link in the tab order even before having the chance to navigate through the carousel.
