### ISSUE TITLE
cannot remove a resource using preview screen

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4445]
### Observed behavior

Removing a resource from the 'preview' screen does not seem to have an effect after returning to the parent topic:

![loop](https://user-images.githubusercontent.com/2367265/47057104-31fee500-d174-11e8-88e3-e1d77e6e0b9d.gif)

### Expected behavior

Resource is no longer selected in parent topic

### User-facing consequences

User gets trapped in an infinite loop and may never escape

### Steps to reproduce

With a resource selected:

1. click the resource to preview
2. click the 'remove' button
3. click the back arrow button
4. return to step (1)

### Context

0.11

**Comment by jonboiser** [comment]
This seems to be an edge case when you only have one resource. Have at least two resources and it shouldn't be a problem.

@DXCanas 	I think it's because of this line

https://github.com/learningequality/kolibri/blob/1d80b34b0877569f648678283ab8d3fc093c9eaf/kolibri/plugins/coach/assets/src/modules/lessonResources/handlers.js#L38

If `pendingSelections` is empty (e.g. after removing the one and only resource at the preview page), when you go back to the list, it basically re-adds the resource.

This is because we don't auto-save lessons at the preview page, but wait till we're back at the list page.

**Comment by christianmemije** [comment]
fixed in #4457
