### ISSUE TITLE
make concepts of sign-in and guest access easier to understand

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4593]
### Observed behavior

We've observed a fair amount of confusion in the current design regarding signing in and accessing as guest. This includes:

* not understanding that 'continue as guest' allows people to use Kolibri without an account
* entering a username and password, but then clicking 'continue as guest' instead of 'sign in'

Current UI for reference:

![image](https://user-images.githubusercontent.com/2367265/49895794-4672fd00-fe06-11e8-9902-3737aa3fdaf8.png)

### Expected behavior

These concepts and interactions are the first thing many people experience, so they should be as straightforward as possible

### User-facing consequences

Difficulty logging in, especially for non-technical users

### Context

0.11

**Comment by indirectlylit** [comment]
notes so far...

**On language:**

* "Guest" is an abstract concept (@ivanistheone)
* "I can see how 'continue as guest' could use iteration in the language. 'Skip sign-in' seems even more ambiguous as to what that will do."  (@jtamiace)
* "Abstractness seems to be the core issue for users unfamiliar to tech. I feel like there's no way around it though..." (@jtamiace)
* "I like 'Explore without account' or 'Explore as guest' because the verb 'explore' sounds friendlier and has less of a commitment sort of connotation to it. Contrast the word explore with 'continue' or 'use', the latter two almost sound like they promote guest usage as an equal alternative to using Kolibri via an account." (@khangmach)

**On button styling:**

* "today I observed a program admin typing in her log-in credentials and then clicking 'Continue as guest' instead of clicking Log In" (@lauradanforth)
* "We have four different styles of clickable objects which might be confusing" (@indirectlylit)
* "The 'sign in' button is not aligned with the form fields and might not look like a button" (@indirectlylit)
* "I might be on board with changing the style of 'create an account' to the hyperlink for consistency." (@jtamiace)
* "Less on board with changing the width of the button. Aesthetically, it just looks funny to me, honestly no other reason" (@jtamiace)
* "I can't see a lot of value in justifying the [button width and alignment] change." (@khangmach)

**Comment by indirectlylit** [comment]
Based on the discussion above, a common theme seems to be that we should try to avoid using abstract, new concepts before they've been explained. As @jtamiace says there might not be a way around this. However, perhaps we can at least keep the number of concepts to a minimum?

Current concepts:

* guest
* account
* username, password
* sign in
* continue / use / explore

Perhaps we can whittle this down a bit and provide more context to help people understand some critical concepts? For example:

* username, password
* sign in

| form with minimal concepts | tooltip introducing 'account' and 'progress' concepts |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/49896448-39570d80-fe08-11e8-8f00-27408bc0fcea.png) | ![image](https://user-images.githubusercontent.com/2367265/49896456-3eb45800-fe08-11e8-83be-0a1f8f4b118a.png) |

**Comment by khangmach** [comment]
A few notes:
- The tooltip information is on the "sign in to personalize Kolibri" text but has nothing to do with signing in. So it should be near the "Create a user name" text instead.
- "Create a username" is inaccurate because it leads to an account creation page, not just a username creation page. Suggest keep verbiage as is and as a secondary button, as it is an appropriate secondary action we want to encourage.
- Let's put the Kolibri version data + usage/privacy somewhere else like in the footer underneath the language switcher. I always felt like it has no place there (on a log-in form) and is incredibly distracting.
- The meaning of "Personalize Kolibri" is introduced and is even more ambiguous to me. 

All of the discussion around the login components/concepts seem unnecessarily complicated to me when the original issue is with verbiage and the seemingly close proximity of Sign-in/Create account. 
Here is a simplified suggestion that increases the margin between the primary/secondary call to actions and places the sign-in button closer to the form it relates to
<img width="327" alt="screen shot 2018-12-12 at 1 26 32 pm" src="https://user-images.githubusercontent.com/25045166/49899835-bf2b8680-fe11-11e8-8dd9-6c18b748b517.png">

**Comment by indirectlylit** [comment]
Great idea on moving version/privacy info out - that cleans things up a lot.

With the extra help text - independent of the specifics, the goal was to introduce the concept of signing in and why it's beneficial (personalize, tracking, etc). However maybe more text is not going to help?

**Comment by khangmach** [comment]
Illustrating the benefits of signing in and having an actual account is valuable for sure -- login form might just just be ill-suited to house it. I feel like the help text loses its value for returning users and can even unintentionally mess with the button hitboxes as you're inputting your credentials for the nth time. And for new users, the verbiage doesn't have enough info to make the concept of 'personalize' less ambiguous and more informative :/

Some effective methods I can see us utilizing to encourage proper account creation can that once you're logged in as a guest, have a persistent banner below/above the top-nav or have something like an info modal reminding the user of account benefits pop up randomly while a user is in guest mode.

**Comment by jtamiace** [comment]
Also think the sign in form is the wrong place for that helper text - in addition to the messaging throughout the guest UI, maybe also better suited for the create account page itself? 

More space and the altered guest access text as mocked up looks fine to me

**Comment by jtamiace** [comment]
@lauradanforth and @ivanistheone ^^
