### ISSUE TITLE
Not able to move in the channel of coach tab.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4610]
### Observed behavior
Not able to move or click on anything in the channel of coach tab.
To understand this issue in more detail please watch attached video.

### Expected behavior
It allow user to click anywhere in the kolibri.

### Steps to reproduce
1. Solve same exercise using two/three learners.
2. Login with coach user and go to the coach tab.
3. Click on Channel tab.
4. Move to the channel where learner solve exercises.
5. click on learner name and click on every question.
6. Try  to click on back button.

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system: Ubuntu 14.04 
 * Browser : Chrome

### Video
[VID_20181214_192532 (1).mp4.zip](https://github.com/learningequality/kolibri/files/2680347/VID_20181214_192532.1.mp4.zip)

**Comment by rtibbles** [comment]
When you say 'try to click on the back button' do you mean the browser back or the 'back arrow' in the interface that takes you to the previous page?

In the video you posted, when you click the browser back, it takes you to the previous question in the exercise detail view that you viewed - so the reason that clicking on the 'browser back' button does not return you to the overall view is because you have made several navigation events.

**Comment by swapnil106111** [comment]
@rtibbles Tested on Kolibri-0.11.1. It is working as expected.

Able to select different question without any hang in kolibri system.
![2](https://user-images.githubusercontent.com/12776071/51602435-f1f68d80-1f2c-11e9-8380-6989693cf7b9.png)


![1](https://user-images.githubusercontent.com/12776071/51602436-f28f2400-1f2c-11e9-8b96-6d93f06b7c94.png)
