### ISSUE TITLE
Fix demo site banner behavior

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#4616]
### Observed behavior

Some issues:
- Upon page load, banner takes up a lot of space and options "Create an account" and "continue as guest" are the only immediately visible options. 
- Upon closing the banner information, Kolibri logo is never visible.
- Banner position is absolute, which cuts the logo. 
- Verbose text -- needs a cut

<img width="413" alt="screen shot 2018-12-17 at 1 10 36 pm" src="https://user-images.githubusercontent.com/25045166/50115739-2a53cf00-01fd-11e9-870b-3e6d6dfa8897.png">
<img width="364" alt="screen shot 2018-12-17 at 1 10 41 pm" src="https://user-images.githubusercontent.com/25045166/50115751-2f188300-01fd-11e9-8df2-011b8510b29e.png">

### Expected behavior
- Banner to be a div that is relative and is above the rest of the page. This will make the the logo show
![scrollable area](https://user-images.githubusercontent.com/25045166/50116641-a0593580-01ff-11e9-87bb-c879b660833b.gif)

- On page load, an overlay to appear to prevent the user to click on "Create an account"/"continue as guest". Overlay disappears when user presses "CLOSE"
![overlay](https://user-images.githubusercontent.com/25045166/50116738-dc8c9600-01ff-11e9-8bac-3b9442719f38.png)

- Simpler verbiage overall
![demo site language](https://user-images.githubusercontent.com/25045166/50116800-05ad2680-0200-11e9-848e-5b62e1bb28ef.png)

### User-facing consequences
Confusing usability, buggy look, improper logo visibility

**Comment by rtibbles** [comment]
Note: implementation of this would be dependent on having a core banner component.

**Comment by khangmach** [comment]
Can we cut the verbiage and use css to fix the absolute positioning of the banner in the interim while I whip up the banner proposal?

**Comment by indirectlylit** [comment]
see also #4562

**Comment by laurenlichtman** [comment]
@khangmach let's definitely cut the text. I like the edit you proposed with one small change. Can you change the second to last sentence to read: "This demo has features of the latest version of Kolibri, and only contains a sample of the content that is available for offline use."  cc: @lauradanforth as FYI in case she has further edits. 

I think it'd be great if we could proceed as you suggested Khang! Thanks!

**Comment by nucleogenesis** [comment]
@indirectlylit @rtibbles 

I am updating the copy on the banner to match the right side of this image:

https://user-images.githubusercontent.com/25045166/50116800-05ad2680-0200-11e9-848e-5b62e1bb28ef.png

The last paragraph is giving me a little trouble because it is trying to inline <KExternalLink> components inside of a string defined in the `$trs`.

Here are the relevant `$trs`:

```
demoServerP3: 'To learn more about using Kolibri, take a look at our [documentation guides] and [download the latest release].',
demoServerA1: 'documentation guides',
demoServerA2: 'download the latest release',
```

In the current version - the `demoServerP3` text is written to be followed by a list of the <KExternalLink> components - but the revised version is looking to inline those links.

I tried passing an object like:

```
<p>{{ $tr('demoServerP3', {demo: <KExternalLink href='#' text='$tr("demoServerA1")' />) }}</p>
 /* ... later on ... */
demoServerP3: 'To learn more about using Kolibri, take a look at our {demo} and ...',
```

But Vue told me "This isn't React get that mess out of here". 

Do you have any thoughts on how I can maintain the desired accessibility while keeping the `$trs` all properly "self contained" as meaningful and complete strings of text unto themselves?
