### ISSUE TITLE
duplicate lesson and quiz names are allowed

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4626]
### Observed behavior
When coach creates exam, it is allowing to create exam with same name without any error.

### Expected behavior
It must not create existing name exam.

### Steps to reproduce
1. Login with coach and click on exam.
2. Create exam with Exam1 name.
3. Again create exam with Exam1 name.

### Context
 * Kolibri version : Kolibri 0.11.0
 * Operating system : Ubuntu 14.04
 * Browser : chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/50147261-ad4b5700-02db-11e9-8eac-88da9f638342.png)

**Comment by rtibbles** [comment]
I wonder if we should just flag a warning, rather than banning this outright?

**Comment by indirectlylit** [comment]
notes from a quick conversation with @rtibbles :

| Allow duplicates and show warnings | Don't allow duplicates |
|--|--|
| more difficult implementation | easier implementation |
| more complicated UX | simpler UX | 
| more flexibility | less flexibility |

I'm in favor of banning for now, and adding the flexibility later if people complain

**Comment by lauradanforth** [comment]
I don't see any real downsides to banning duplicates and it may also eliminate confusion in cases where there's multiple coaches making exams in one class. It would just be important to make sure this was only applied on an individual class basis (so that you could still have the same exam name in different classes).

**Comment by indirectlylit** [comment]
cc @ralphiee22

**Comment by indirectlylit** [comment]
Was chatting with @ralphiee22 about this briefly on Friday.

One other complexity with warning instead of blocking is that the pattern is not compatible with our conventional validation behavior, which is:

* Do not validate as-you-type
* Validate only when the input element loses focus

If we were to follow the conventional pattern, the user would never see the warning if they were to click the 'Save' button immediately after entering a name.

In order to support warning, we'll have to instead do the validation as the user types with debouncing, which adds a bit of complexity and inconsistency. Not the end of the world, but just something to consider.
