### ISSUE TITLE
no empty state for learners with no content

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4701]
### Observed behavior

When learners have no content, they don't see any 'empty' state. Currently we only have a message intended for admins, e.g. explaining that more content can be imported from the device tab

### Expected behavior

We should have an empty state that tells users to contact their administrator for help

### User-facing consequences

page currently looks broken

### Steps to reproduce

* start a fresh instance of kolibri with no content
* log in as a learner

### Context

0.11.1

**Comment by ryanmavilia** [comment]
@indirectlylit is this the page you are seeing?
![screenshot from 2019-01-27 21-36-04](https://user-images.githubusercontent.com/1221512/51811623-cb618b00-227b-11e9-97b6-a5050de8ec11.png)

**Comment by khangmach** [comment]
@indirectlylit One thing we can do is reuse the unknown error interface and update the messaging. A few notes I was thinking of while writing this:
- A learner isn't guaranteed to know who their Kolibri administrator is. And any authoritative figure they would seek help from would most likely be a nearby coach. 
- When prompted for help, this messaging lets the coach know that this issue could be more relevant for a more administrative person. Thereby this is understandable to both the learner & coach users. 
- Log out seems like a reasonable primary call to action. Or we can remove it so that learners are more likely to bring this screen to an adult figure. 

flagging @radinamatic for thoughts on the verbiage. 

![screencapture-kolibribeta-learningequality-org-learn-2019-02-19-14_44_34](https://user-images.githubusercontent.com/25045166/53052905-c778f100-3454-11e9-8e89-8b7672de5ca2.png)

**Comment by indirectlylit** [comment]
that looks good

not sure why 'log out' would be the call to action though

**Comment by khangmach** [comment]
![update](https://user-images.githubusercontent.com/25045166/53115535-4cb6e100-34fb-11e9-8d90-29731038c42d.png)
:)

**Comment by khangmach** [comment]
@radinamatic is it "doesn't seem" or "don't seem"? I'm confusing myself hahaha

**Comment by radinamatic** [comment]
You and me both, and we [don't seem to be alone](https://english.stackexchange.com/questions/137267/there-doesnt-seem-vs-there-dont-seem)... 😂 

How about `There seem to be no resources on this device`? 
(It also sounds easier to translate to me)

**Comment by khangmach** [comment]
Let's do that. 
Final verbiage: 
**There seem to be no resources on this device**. Please contact your coach or administrator for help

**Comment by indirectlylit** [comment]
was it the coach/learner distinction that's leading you to hedge it?

if the user is a coach or above, we could just say "There are no resources on this device". for learners it's a little less certain because there may be coach content but not learner content.

**Comment by khangmach** [comment]
hmm. I think the messaging can be the same, because learners shouldn't know coach resources really even exist, much less be expected to care about it

**Comment by indirectlylit** [comment]
fixed in #6050
