### ISSUE TITLE
inactive quizzes are not marked as 'completed'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4743]
### Observed behavior

As a coach, I have a number of exams. The 'fixed_order' exam had previously been active, but as a coach I set it to inactive. However as a learner, I still see it, and it links to a learner report:

![image](https://user-images.githubusercontent.com/2367265/51345565-375c1c00-1a50-11e9-81f6-7bb44af25ce1.png)

![image](https://user-images.githubusercontent.com/2367265/51345731-90c44b00-1a50-11e9-9a0c-84cc4f88bcd7.png)

### Expected behavior

Inactive exams should be clearly differentiated from active exams

### User-facing consequences

Confusion over what exams are active from learner perspective

### Steps to reproduce

Take an exam and then deactivate it, while other exams are still active

### Context

0.12

----

cc @khangmach @jtamiace

**Comment by khangmach** [comment]
- Seeing the "inactive" quiz and showing the quiz report is intended behavior if the quiz is completed. 
- The learner doesn't need to know what the difference between active/inactive is, as that's coach/technical terminology. Instead they should be versed with not started/started/completed. Current implementation does this, as we see in the screenshot you provided with the metadata on the quiz card, "Not started". Which should change to "completed" when the quiz is finished

**Comment by khangmach** [comment]
Update:

Behavior captured in screenshots is a bug, as there were no attempts made in the learner quiz report. Per Richard:
> If a learner has not started a quiz that has then been made inactive, it will not show for them

> Inactive quizzes only show for learners who have actually attempted the quiz previously.

**Comment by jonboiser** [comment]
Here's what happened when I tried to reproduce it.

1. Create a new exam 'A'; left it inactive -> Not on Class Assignments Page
1. Activated 'A' -> Is on CA Page
1. As learner, clicked into 'A', but did not make any attempts. Exited without submitting.
1. As coach, deactivated 'A' -> Refreshed on CA page, and 'A' is still there with a small blue bar, indicating a tiny bit of progress and the 'in-progress icon' (not seen in OP screenshot)

![Screen Shot 2019-04-09 at 11 47 21 AM](https://user-images.githubusercontent.com/10248067/55827695-9c5b6700-5abf-11e9-9448-36c12d7d9e45.png)


In the LearnerClassroomSerializer, this filter is intended to satisfy the requirement

> Inactive quizzes only show for learners who have actually attempted the quiz previously.

https://github.com/learningequality/kolibri/blob/c3af46e5b5a47f550cf29efb9c97e6532e1138cf/kolibri/plugins/learn/serializers.py#L112-L117

But because it seems an exam log are created for users when they just open and click around the exam (and not make any attempts), the other requirement is not met

> If a learner has not started a quiz that has then been made inactive, it will not show for them

If, by "not started" we include the case where a learner opens and navigates questions, but does not actually provide answers to exercises.

**Comment by indirectlylit** [comment]
We decided that quizzes become considered "started" as soon as the learner looks at it, so the behavior seems almost correct.

> As coach, deactivated 'A' -> Refreshed on CA page, and 'A' is still there with a small blue bar, indicating a tiny bit of progress and the 'in-progress icon' 
> 
> ![Screen Shot 2019-04-09 at 11 47 21 AM](https://user-images.githubusercontent.com/10248067/55827695-9c5b6700-5abf-11e9-9448-36c12d7d9e45.png)

This seems like the issue: At this stage, I would expect the status to switch from 'in-progress' to 'completed' because the teacher has decided that the quiz is over; the number of questions answered seems irrelevant.

> (not seen in OP screenshot)

curious .. I wonder why I didn't see that.

**Comment by jonboiser** [comment]
The card is still presenting as an in-progress exam, because the ExamLog object would still have `closed: false`, even though it is no longer active (according to the Exam object). So the card

1. should be in in-progress mode (has the icon and the "n question left" message) only if the exam is active
1. should be in "completed" mode (have the star icon and no message) when the exam log indicates it's closed
1. should be in a "inactive but not completed mode" (needs design) when the ExamLog indicates it's not closed, but the Exam says it's not active. Or they should not be on the list at all, to address the initial issue.

**Comment by indirectlylit** [comment]
> should be in a "inactive but not completed mode" (needs design) when the ExamLog indicates it's not closed, but the Exam says it's not active. Or they should not be on the list at all, to address the initial issue.

Shouldn't the quiz be considered "Completed" at this point from the learner's perspective? Whether they pushed submit or not, the quiz is over and they got a score for it.

(cc @rtibbles)

**Comment by rtibbles** [comment]
> Shouldn't the quiz be considered "Completed" at this point from the learner's perspective? Whether they pushed submit or not, the quiz is over and they got a score for it.

Yes - once the coach has deactivated the quiz, it is completed.

**Comment by indirectlylit** [comment]
Updated title to "inactive quizzes are not marked as 'completed'". 

One issue here is that the current concept of active vs inactive sounds like something that can be toggled back and forth, but in actuality it's kind of a one-way street.

@khangmach @jtamiace perhaps this is an opportunity to address some feedback we've had?

1. the process of activating a quiz is confusing since it's deep in the 'edit details' modal
2. it's sometimes useful to hold off sharing answers until everyone has finished

One option: instead of "active, inactive", make the states sequential "not started, started, ended"? Then the flow becomes more explicit:

| state | CTA |
|--|--|
| not started | ![image](https://user-images.githubusercontent.com/2367265/56871021-f23f7280-69cc-11e9-952e-f02d7aa09de8.png) |
| started | ![image](https://user-images.githubusercontent.com/2367265/56871024-01bebb80-69cd-11e9-8906-70ee787c2d2d.png) |
| ended | ![image](https://user-images.githubusercontent.com/2367265/56871094-dc7e7d00-69cd-11e9-9c31-95377f72f645.png) |

**Comment by rtibbles** [comment]
Can we dig deeper on the feedback prompting the 'share answers' stage before committing to this? My concern here is that it pushes the quizzes more towards summative assessments (where it could potentially be left in a state where no feedback is given), and I don't recall any strong feedback about student cheating or some such that might prompt such concerns.

**Comment by khangmach** [comment]
Yeah I'd like to table any further designs on this until we get more field feedback on current quizzes.

**Comment by indirectlylit** [comment]
> Can we dig deeper on the feedback prompting the 'share answers' stage before committing to this?

yup that was just speculation

> Yeah I'd like to table any further designs on this until we get more field feedback on current quizzes.

We have gotten pretty clear internal feedback that active/inactive inside detail editing is confusing, and people want a more straightforward way to enable quizzes

**Comment by indirectlylit** [comment]
I did take this thread a bit  off track from the original issue:

> inactive quizzes are not marked as 'completed'

will add the rest to clearinghouse

**Comment by indirectlylit** [comment]
This has been addressed by changes to quiz management in 0.13
