### ISSUE TITLE
Epub render - does not split tables and font resizing issue

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#4782]
### Observed behavior

1. EPUB files containing tables do not split-render the tables.
2. Font resizing does not work.

Problem can be seen in this capture -

![arryfqrrpl](https://user-images.githubusercontent.com/2577060/51668624-a43f5b00-1fe8-11e9-93ef-a70de6f46230.gif)

### Expected behavior

- Table should be split over multiple pages.
- Font resizing should work 

Expected behaviour shown in the capture herein from Microsoft edge -

![smvgozehpn](https://user-images.githubusercontent.com/2577060/51668702-cf29af00-1fe8-11e9-9f75-89c1c0ee6a3e.gif)

### User-facing consequences

- Content not accessible to users when part of tables are hidden from view.
- Inconvenience for readers who may font a bigger or smaller font size.

### Errors and logs

NA

### Steps to reproduce

Upload the attached epub into a studio channel and take it offline in Kolibri app.

### Context

 * Kolibri version - 0.11.0

**Comment by bjester** [comment]
@intelliant01 I don't see the attached epub file?

**Comment by intelliant01** [comment]
@bjester  Sorry, my Bad. 

Herein are 3 ePubs as per ePuB 3.0 generated using Libreoffice - [epubs.zip](https://github.com/learningequality/kolibri/files/3106094/epubs.zip)
or you may directly import them from studio - token : jafal-zovuk (files under ```ePub checks``` folder)

Apart from the fixed-libreoffice_3.epub, the other two are unusable in Kolibri.

**Comment by bjester** [comment]
I've verified that in Firefox for 0.11 and 0.12, table layouts in the following two files, do not wrap as observed, but the font resizing control does work. Chrome (and Edge as mentioned) does not share this issue.
- `heading-reflowable-libreoffice_3.epub`
- `page_break-reflowable-libreoffice_3.epub`

Also, for both Chrome and Firefox, font resizing doesn't work for the document `fixed-libreoffice_3.epub` but the tables do not have the wrapping issue.

**Comment by bjester** [comment]
Not strictly mentioned in this issue, the initial load of these documents renders poorly.
![epub-initial-load](https://user-images.githubusercontent.com/819838/56616995-98f1d080-65d3-11e9-9fe2-4e08955326d4.png)

**Comment by bjester** [comment]
This appears to be an issue with how Firefox is handling the `writing-mode: horizontal-tb` regarding the table. If I interpret the spec correctly, Firefox is handling it correctly, since a table is block-like content by default. I would think that changing the table to `display: inline-table` would be the appropriate styling and create the expected behavior for all browsers, but it doesn't fix it in Firefox.

**Comment by bjester** [comment]
In `fixed-libreoffice_3.epub`, what's rendered visually is the document as an SVG within an `<img/>` tag. There is a significant amount of whitespace around the bottom of the images and therefore it is rendering them as large as possible even though it doesn't look like it. Also, since the contents are rendered as an SVG blob within an `<img/>`, the font resizing doesn't apply to the SVG contents as expected. Since this is how we would want all images to be rendered in `<img/>`, there isn't much we can do.

**Comment by intelliant01** [comment]
I agree on the ```fixed``` layout epub's analysis. I actually had no issues with its rendering. It is exactly as expected. Should have mentioned this in my comment above.

**Comment by indirectlylit** [comment]
Hi @intelliant01 - just a heads-up that we are in the beta-testing phase of 0.12.4, which includes this fix.

If you'd like to help us test this release, any feedback is welcome!
https://github.com/learningequality/kolibri/releases

Thank you!
