### ISSUE TITLE
Videos not supported in Safari on iPad2

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4819]
### Observed behavior

We've lifted the Safari ban, but videos still seem not supported.

![workspace 1_009](https://user-images.githubusercontent.com/1457929/51876623-202b0180-2361-11e9-85e1-40997d3bccf0.jpg)

### Expected behavior

Videos playing without issues in Safari.

### User-facing consequences

Unable to view videos on iPad2.

### Errors and logs

Nothing in Terminal and console.

### Steps to reproduce & Context

Encountered [during testing](https://github.com/learningequality/kolibri/pull/4794#issuecomment-458315959) with Browserstack simulator of Safari on iPad Air 2 with iOS 9.3.

**Comment by kollivier** [comment]
Do no videos at all play, or is it only certain videos? In my testing, I was able to play videos on iOS 9.3 (sorry, did not write down the ones I tested, but I do think I checked at least one Sikana video). I do know that different videos use different video and audio encodings, and not all codecs are supported by all OSes and browsers. If it's a codec issue, it will probably have problems in OS X when using Safari or Firefox as well, not just iOS.

If this is a codec issue, I think ultimately we will want to standardize on the codecs we use when encoding our videos so that we can ensure they play everywhere. I think @ivanistheone is already considering making this change to ricecooker.

**Comment by radinamatic** [comment]
Tried and failed several KA math videos, haven't had any Sikana to test at that time. Will import and confirm what I find!

**Comment by kollivier** [comment]
Also might be worth checking in with Chris Jackson, to see if they're having this problem as well. Could possibly be a simulator issue?

**Comment by radinamatic** [comment]
It's possible that it's a simulator issue, Chris Jackson did not report the videos not playing, but they work much more with exercises and HTML books from ASB channel.

**Comment by cjbamenda** [comment]
We have not noticed a problem with videos on the iPad2s. The videos we have are from "Hello Channel" English. The grammar videos were re-rendered because they did not work. Someone in LE did this and then reimported them into Studio. I've not noticed the KA English videos not working, nor have heard a complaint. I'm away from the site where it is running this week. When I get back there, I can test and give a report. I did test the KA videos with a current version of Safari on a Mac from where I am at this time (have set up remote access to the RPi where our Kolibri is located and running). Had no problem with KA videos from this platform. I'll report more once I know more.

**Comment by cpauya** [comment]
Videos are working with audio when I tested this in iPad2 Simulator.  I tried the ones under `Khan Academy (English) > Math > Early math > Counting > Counting`.

Maybe we can close this for now @radinamatic and just re-open if we can reproduce it?

Environment:
* Kolibri: 0.12.4 server on Ubuntu 14.04
* Browser: Safari under iOS 9.3 in iPad2 Simulator v10.2.1
* OS: macOS Mojave 10.14.5

**Comment by radinamatic** [comment]
Agreed @cpauya, closing this for now!
