### ISSUE TITLE
regression: 'select all' in quiz creation no longer works

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4823]
### Observed behavior

'select all' checkbox has no effect:

![image](https://user-images.githubusercontent.com/2367265/51921334-0b1f9400-239c-11e9-9c3e-68080725b70b.png)

### Expected behavior

either:

should select all items below

### User-facing consequences

confusion

### Errors and logs

…

### Steps to reproduce

* new quiz
* navigate to a topic
* select all

### Context

0.12

**Comment by jredrejo** [comment]
@indirectlylit  This is due to the use of slots in [CoreBase](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreBase/index.vue) to render the [ContentCardList](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/ContentCardList.vue).
The parent component is not [CreateExamPage](https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/coach/assets/src/views/plan/CreateExamPage/index.vue) anymore.

The solution involves using an ugly hack: 

```@change="$parent.$emit('changeselectall', $event)"```

in `ContentCardList`

An implementation example can be seen at https://codesandbox.io/s/jjqjv4lm49

**Comment by indirectlylit** [comment]
I don't think that `CoreBase` slots are related to the problem.

`CreateExamPage` attaches a handler to the `changeselectall` event of `ContentCardList`, and the handler (`toggleTopicInWorkingResources`) is being called as expected.

**Comment by jredrejo** [comment]
> I don't think that `CoreBase` slots are related to the problem.

You are right, devtools debugger cheated me.
The problem was in the way Vue handles reactivity. Created PR to fix it.

**Comment by jredrejo** [comment]
Closed by #4841

**Comment by rtibbles** [comment]
Oddly, it now takes two clicks off 'select all' to unselect everything..
