### ISSUE TITLE
Not possible to use token to import from "Local network or internet"

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4925]
### Observed behavior

I configured Studio Develop as "Local network or internet" import location, but once there, I don't see the option to use the token. Was it supposed to be there, can't remember...? 🤔 

### Expected behavior

If there's a Studio clone somewhere to import content from, there should be the option to use tokens for import.

### User-facing consequences

Inability to import unlisted channels

### Context

cc @indirectlylit Labeled as bug P0, and 0.12, but you should review.

**Comment by indirectlylit** [comment]
looks like this was an oversight when it was first implemented. Problem exists in 0.11.0 also

**Comment by indirectlylit** [comment]
reducing to P1 because it's not technically a regression

**Comment by indirectlylit** [comment]
Clarification: when a channel is imported into kolibri and made available for peer import, it becomes listed automatically and token-based imports are not supported. Created a follow-up issue here: #4927

For this issue, we're mostly just needing to support cases where studio (rather than kolibri) is the peer, which would happen for things like `staging` studio or studio mirrors.
