### ISSUE TITLE
add handling of unlisted, token-based peer importing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4927]
### Observed behavior

when an unlisted channel is imported into kolibri, other instances of kolibri that import from it will see it as listed

ref: https://github.com/learningequality/kolibri/issues/4925

### Expected behavior

users should have control over whether unlisted channels are available for import by peers

### User-facing consequences

possible security issue with leaking unlisted channels

### Context

0.12.0

**Comment by jamalex** [comment]
It's a bit tricky, because different users/cases may want different behavior. Some channels are unlisted because there's an intention to restrict access to the content, whereas other times it's just because we haven't done QA or the channel is very narrow in scope, and we don't want to clutter up the search results for those importing from Studio.

With the latter, there are strong use cases for being able to see all channels (even if unlisted on Studio). For example, with the UNICEF Uganda country-level server, there will be specific channels curated for use in Uganda (which may not be Public on Studio for now), and part of the goal is to make it easier/faster for users in Uganda to download that content "P2P" from that server.

For this reason, I wonder whether we might have a device-level "flag" on channels to determine whether they show up in P2P search results? And for non-public channels, we'd by default set this to False?

Being able to sync P2P by token could be nice too, but as noted on Slack, we don't currently sync in the token(s) along with a channel. If we did, we'd likely need to only sync in the token that was actually used to download it to that device, otherwise it's a "security" vulnerability, since you'd receive all the tokens for other people's bundles, which might include other channels you shouldn't have access to.

My current suggestion based on the above would be: Having the "show this channel to other devices" flag for channels on a particular device, with sane defaults but allowing changes. And then for other channels, they could be synced using channel IDs but not tokens. (Or, if tokens, only the token that was used, and/or the "non-bundle" token for that channel, which doesn't enable access to additional channels.)

**Comment by indirectlylit** [comment]
cc @khangmach  something to factor in to the ongoing content management work

**Comment by indirectlylit** [comment]
Ref: https://www.notion.so/learningequality/new-setting-allow-other-computers-on-this-network-to-import-my-unlisted-channels-6420ebc83df1419f9d3a40fb4f13ffe1

Decisions:

new setting: allow other computers on this network to import my unlisted channels

**Comment by rtibbles** [comment]
Are we planning on adding the token behaviour on the peer import also for 0.13.0 or just giving the option to hide unlisted channels?

**Comment by indirectlylit** [comment]
For 0.13, I think only unlisted channel hiding was in scope. thoughts?

**Comment by rtibbles** [comment]
Seems fine, just wanted to check as the token behaviour would require more changes, ofc.
