### ISSUE TITLE
lessons never end for learners when an exercise is the last item

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4972]
### Observed behavior

reported by @micahscopes during a hack session:

Micah mastered the lesson Nalanda 2 after getting 3 right, (and not getting any wrong).  He was notified that he had completed the lesson, but was not taken out of the lesson, so he kept being asked more and more questions.

### Expected behavior

After the learner has mastered the last exercise, presumably we should show some kind of congratulatory message about the lesson as a whole and then take them back to the lessons page?

(cc @jtamiace @khangmach)

### User-facing consequences

learners might not get the feeling of accomplishment that we want them to

### Errors and logs

…

### Steps to reproduce

…

### Context

0.12

**Comment by khangmach** [comment]
Some initial thoughts:
- Instilling a sense of accomplishment is important, especially in the Learn tab which could use more positive reinforcement and encouragement. 
- I think an option to redirect a learner to a lesson overview, rather than the class home, has it's subtle, quality of life benefits...as learners can see all their completion stars and resources finished, of course. Contrast this to directing back to the class home page with just a little system message (woo...scroll down, find your lesson, see one star..)
- It's important to note that this completion modal appears at after completion of the *last completed resource*, not the *last resource*. This means you can skip around various resources in the lesson and still get this modal appearing after any resource. 
- I don't we need to double down on two congratulatory mechanisms (modal + snackbar). Modal seems just fine. 
- Looking forward to future implementation, I think there are improvements we can make to an overall guided learner experience, but for now this seems low lift. 

Here's an example of something we can implement:
![completion modal](https://user-images.githubusercontent.com/25045166/53058311-64448a00-3467-11e9-90be-477b4e3ca9df.png)

**Comment by rtibbles** [comment]
This has now been resolved.
