### ISSUE TITLE
Snackbar appears twice when Finish button is pressed too fast

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#4987]
### Observed behavior

[Originally reported here](https://github.com/learningequality/kolibri/pull/4949#issuecomment-461255802), but now I noticed another detail: notification snackbar appears twice when adding the resources to the lesson: first when added (as supposed), and then again **if the _Finish_ button is pressed immediately after**. I didn't exactly timed it, but if the user pauses a couple of seconds, the second (repeated) notification does not appear.

### Expected behavior

Only one notification is required.

### User-facing consequences
…

### Errors and logs
…

### Steps to reproduce
Add resources to a lesson and press the _Finish_ button without any delay.

### Context
 * Kolibri version: `release-v0.12.x` branch
 * Operating system: all
 * Browser: all

**Comment by jonboiser** [comment]
This behavior is actually global since we have gone to using a unique CoreBase instance for every page. This means every time we switch pages, we destroy and re-create the GlobalSnackbar child in CoreBase, which will show whatever message is in vuex.

So you can see this in other places, like if you were to activate an Exam and then quickly switch over to the "Groups" tab, you will see the "changes to quiz made" snackbar pop up twice.

This was probably less noticeable before, because even if the snackbar lingered between pages, it would not pop-up multiple times.

**Comment by rtibbles** [comment]
Do we need to clear snackbar vuex state on navigation now to solve this, or would that be insufficient?

**Comment by jonboiser** [comment]
That would work, but the experience will be slightly different from before, where snackbars would linger between pages (which might be nice) instead of disappearing.

**Comment by rtibbles** [comment]
Hrm, can't actually find what the specified behaviour for snackbars across page navigation events is in Material Design.

**Comment by rtibbles** [comment]
Seems from this Stackoverflow post: https://stackoverflow.com/questions/29989631/android-persist-a-snackbar-across-activities that the default snackbar behaviour in Android is to dismiss snackbars on page navigation, so that might be ok?

**Comment by jonboiser** [comment]
Yeah, I think that's an acceptable behavior.

**Comment by jtamiace** [comment]
Material only has a [vague reference](https://material.io/develop/android/components/snackbar/) in their dev doc to dismissal of snackbars: `disappear automatically, either after a timeout or after a user interaction elsewhere on the screen`

But snackbars disappearing on nav is something I've seen before and also seems ok to me

**Comment by radinamatic** [comment]
Fixed in #5010 👍
