### ISSUE TITLE
notification API seems to be slightly 'ahead' of class summary API

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5025]
### Observed behavior

Observed by @jonboiser during last week's hack sessio:

* report data was updated based on an incoming notification
* refreshed the page, and data went back to previous state

### Expected behavior

Notifications and class summary API should either be in sync, or at least the summary API should contain the most recent data – not the other way around.

### User-facing consequences

Strange fluctuations in reports data

### Errors and logs

…

### Steps to reproduce

…

### Context

0.12.0 beta 4

**Comment by indirectlylit** [comment]
@jonboiser would you mind filling in the steps to repro and I'll take a look?

**Comment by indirectlylit** [comment]
possibly related - https://github.com/learningequality/kolibri/issues/5032

**Comment by jonboiser** [comment]
It's probably easiest to see this on a page like Reports > Lessons.

1. Go to Reports > Lessons and view all of the lessons
1. As a learner, start or complete one of the lessons
1. Shortly after, the relevant lesson will update in the "Progress" column. E.g. it will go from "3 of 12 completed" to "4 of 12 completed", which should happen without a refresh because of an incoming notification.
1. Go to another page.
1. Go back to Reports > Lessons
1. The "Progress" column will have gone back to "3 of 12 completed"

**Comment by jonboiser** [comment]
I just saw this again locally with the Quizzes page

1. I was on Reports > Quizzes> Quiz > Learner page, and it updated when I started the quiz, and it stayed that way even when I navigated away.
1. However, on Reports > Quizzes, all of the quizzes incorrectly say "0 of 0 started" (there are people in the class), and did not update when started or completed the quiz.

**Comment by rtibbles** [comment]
Have we been able to chase this down any further?

**Comment by indirectlylit** [comment]
I haven't looked into it yet - can check tomorrow

**Comment by indirectlylit** [comment]
I've tested and confirmed that this issue has been addressed between beta 7 and now:

* Behavior in beta 7 was that the `class_summary_api` incorrectly reported an in-progress content item as `NotStarted`. This caused the lesson in-progress state to revert back after navigation, which is when we currently refresh the class summary.
* Behavior in current release branch is that in-progress content items are correctly reported
