### ISSUE TITLE
On Lesson Resource Management page, 'show' filter label does not accurately describe its meaning

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5033]
### Observed behavior

reported by @carinediaz 

The label 'show' is not helpful for describing what that filter does:

> ![image](https://user-images.githubusercontent.com/2367265/52677344-5e3c2f80-2ee2-11e9-8972-52d4cb1379f6.png)

(The filter refers to coach content)

### Expected behavior

Label should indicate that this filter is for coach-only content

### User-facing consequences

users might not discover this functionality

### Steps to reproduce

coach -> plan -> lessons -> manage lesson contents

### Context

0.12.0 beta 4

----

cc @khangmach @jtamiace

**Comment by khangmach** [comment]
Yikes. Completely agree with Carine here. 
Two options come to mind...
1. Changes to the filter component 
- Replace the user icon with the coach content icon. 
- label change from "Show" to "Coach resources"
- Filter options become "Show" and "Hide"

2. Place checkbox + string underneath the filters, floating left. Checked by default
- String: "Show coach content"
- Checked state: shows coach content
- Unchecked state: filters out coach content from search results

**Comment by khangmach** [comment]
While messing with the filter I found this bug. I didn't have any resources in my lesson at the time. This happens when you check "Non-coach" filter option and navigate away/navigate back to the page. Should be a string change to something like: 
[Updated search results]

<img width="359" alt="screen shot 2019-02-12 at 4 54 58 pm" src="https://user-images.githubusercontent.com/25045166/52678567-f63c1800-2ee6-11e9-82e2-6ee8a5ce90bc.png">

**Comment by indirectlylit** [comment]
Let's go with this option because it's a bit simpler to implement:

> Changes to the filter component
> * Replace the user icon with the coach content icon.
> * label change from "Show" to "Coach resources"
> * Filter options become "Show" and "Hide"
