### ISSUE TITLE
lessons and quizzes with missing resources are not handled gracefully for learners

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5049]
### Observed behavior

When trying to take a quiz or view a lesson that references exercises which have been deleted, the behavior is broken.

**Lesson:**

> ![image](https://user-images.githubusercontent.com/2367265/53108077-3acd4200-34eb-11e9-9cec-21d4c5a80d96.png)
> ![image](https://user-images.githubusercontent.com/2367265/53108098-46206d80-34eb-11e9-80d5-2a0e3b10886d.png)

**quiz:**

> ![image](https://user-images.githubusercontent.com/2367265/53108345-b7f8b700-34eb-11e9-99b2-395f396d19cc.png)

### Expected behavior

Lessons and quizzes with missing content should be handled more elegantly

### User-facing consequences

app looks quite broken with no explanation

### Errors and logs

```
Uncaught (in promise) TypeError: Cannot read property 'parent' of undefined
    at normalizeContentNode (utils.js:11)
    at contentState (utils.js:22)
    at handlers.js:161
    at conditionalPromise.js:36
```

### Steps to reproduce

* make a quiz and assign it
* delete the contents
* try to take it

### Context

0.12.0 beta 4

----

cc @ralphiee22 @rtibbles @khangmach @jtamiace

**Comment by radinamatic** [comment]
@khangmach This looks like a good candidate to add a Gherkin scenario for 🙂

**Comment by khangmach** [comment]
Before we write any Gherkins, let's go over some resolutions to this that seem natural. Some of my thoughts on the these scenarios:

**1. Contents get deleted while user *is* taking the quiz**
Since there technically isn't a quiz anymore to take...Once contents get deleted, it makes the most sense to me if we do a redirect back to their class page (learn/#/classes/ID) either automatically (preferably) or when they do something that prompts a call, like submitting the quiz/pressing on another question/pressing 'next' 'previous' question. We can show a system message saying something like "Quiz no longer available" once they're redirected. And the quiz is gone from their quiz list. 

**2. Contents get deleted while user *isn't* taking the quiz**
Quiz disappears from their quiz list.

**Comment by indirectlylit** [comment]
expanded the scope of this issue to cover lessons also.

recommendations:

* For lessons, we should hide individual content items from the lesson list that are not available, since the lesson is still potentially useful
* For quizzes, we hide the quiz as @khangmach said above.

For now I don't think we need to worry about handling the case that content is deleted while a user is interacting with it (quiz or lesson) because this would be a very rare occurrence.

**Comment by jonboiser** [comment]
#5140 Sort of fixes things for lessons, by updating lessons when some of its contents are deleted.

#5140 It doesn't really fix quizzes the way it's recommended in this discussion, because this solution would probably need new strings, and the discussion doesn't address the other situation where a quiz is only partially deleted (only some of the exercises won't load). I just made a decision to leave the exam structure intact (same number of questions and order when it was created), and show a basic error page when coach or learner try to view deleted exercises.

I think down the road, it might be worth handling deleted contents in quizzes the same way it's done in lessons: updated affected quizzes. and if a quiz is basically "emptied" by a channel deletion, then we can also just delete the exam.

**Comment by rtibbles** [comment]
I think the main issue with treating quizzes and lessons the same in this regard is for historic data. If the quiz has already been taken and have user data associated, then removing this data from the quiz is more problematic, than it is for removing it from a lesson.

**Comment by jonboiser** [comment]
That's a good point, but the way attempts are displayed after an exercise is deleted is pretty basic. Just that it was right or wrong, but not the actual responses. (But this might be improvedf by providing a simple text-based rendering of the attempt, maybe)

**Comment by rtibbles** [comment]
Yeah... providing the simple text based rendering is a little tricky. I am not sure we can do much better than we are now.
