### ISSUE TITLE
proper handling of lesson with no resources

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5096]
### Observed behavior
Able to create a lesson without resources. Coach user must not able to create a lesson without resource.
When you create a lesson without resource, it will show you a completed by 2 of 2 in report.

### Steps to reproduce
1. Create lesson without resource and active the lesson.
2. and see report for the lesson.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : chrome

### Screenshot
![screenshot from 2019-02-19 12 15 16](https://user-images.githubusercontent.com/12776071/52995245-08b2d600-3440-11e9-94a7-a69ba5a148ff.png)

**Comment by indirectlylit** [comment]
Currently, being able to create a lesson without resources is by design because lessons use an 'auto-save' functionality. This is different from quizzes which has an explicit 'save' step. We may revisit this in the future, but that's a separate issue. (cc @khangmach @jtamiace)

However, there are two things we should do:

1. make sure that empty lessons don't show up for learners
2. either hide empty lessons from reports entirely, or make them show up as 'not started' rather than 'completed'

**Comment by khangmach** [comment]
We can also disable the 'change' link on the lesson details page, then re-enable it when they have at least one resource

**Comment by radinamatic** [comment]
Still extant on `beta9`.

**Comment by jonboiser** [comment]
@radinamatic 	The patch that should hopefully fix this is still open. You can test it by pulling #5140

**Comment by radinamatic** [comment]
Thanks, @jonboiser, missed that one :confused:

**Comment by mrpau-julius** [comment]
same issue found on kolibri 0.12.0 beta 12
[kolibri.log](https://github.com/learningequality/kolibri/files/2918277/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/2918303/server.log)
![image](https://user-images.githubusercontent.com/38421180/53621748-68318400-3bac-11e9-97be-b1384e547051.png)

**Comment by jonboiser** [comment]
#5235

**Comment by yogeshmhaskule** [comment]
Checked it in 0.12.0. And work as expected.
![lesson proper result](https://user-images.githubusercontent.com/7850420/53797759-d84d5a80-3f5c-11e9-8486-97c4dfc6b00e.png)

**Comment by indirectlylit** [comment]
thank you!
