### ISSUE TITLE
Class activity  shows nothing.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5113]
### Observed behavior
We have observed that class activity shows nothing in class home everytime.

### Expected behavior
It must show class activity.

### Steps to reproduce
1. Click on Class Home in coach report.

### Context:
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/53088718-940b9480-3530-11e9-9515-fb6921312efb.png)

**Comment by indirectlylit** [comment]
please test in the latest beta

**Comment by mrpau-julius** [comment]
Also in Kolibri latest beta version 7 & 8, class activity are empty and not automatically notify. 
* Browser : Firefox 65.0(64-bit)
![screenshot from 2019-02-21 15 25 11](https://user-images.githubusercontent.com/38421180/53151292-cdeea080-35ed-11e9-9615-1298a55908fa.png)

**Comment by mrpau-richard** [comment]
Same issue on Safari 11.0.3 using Kolibri beta7
![screen shot 2019-02-21 at 4 02 19 pm](https://user-images.githubusercontent.com/8663934/53153049-2c1d8280-35f2-11e9-8b8f-bdc95d6991ee.png)

**Comment by indirectlylit** [comment]
thank you!

I mis-tagged beta 8, but the beta 7 result is concerning

FYI beta 8b tagged here should be correct: https://github.com/learningequality/kolibri/releases/tag/v0.12.0-beta8b

**Comment by indirectlylit** [comment]
I'm still not reproducing. you're seeing this in beta 9 still on all browsers?

**Comment by rtibbles** [comment]
Please let us know if this is still extant for you - concerning if so.

**Comment by indirectlylit** [comment]
Reproduced some weird behaviors, specifically with exercises. Unsure if it's what this issue is about specifically, but perhaps related:

https://drive.google.com/file/d/1g7Wd7NDf92DnyJh64g_Ui3NddW77c_xP/view?usp=sharing

**Scenario above:**

* `[0:00]` learner on the left, coach with network tab on the right
* `[0:17]` press the 'check' button which should write an activity log and mark it as 'started'
* `[0:17]-[0:37]` looking for any indication of notifications, none found
* `[0:47]` refresh, wait. notification still doesn't show up so apparently it's not in the table yet
* `[1:30]` add another attempt log. still doesn't show up
* `[2:10]` refresh coach again
* `[2:17]` notification shows up!
* `[2:30]` see notification in network console

**Comment by indirectlylit** [comment]
see also:

* https://github.com/learningequality/kolibri/issues/5025
* https://github.com/learningequality/kolibri/issues/5112

**Comment by rtibbles** [comment]
The exercises aspect of this should have been fixed by #5198 - as we have not been able to replicate the other aspects, closing unless this recurs in testing.

**Comment by yogeshmhaskule** [comment]
tested in kolibri 0.12.0 and works as expected. 
![class_activity_1](https://user-images.githubusercontent.com/7850420/53870685-b5847a00-4020-11e9-9cd0-971d14722838.png)
