### ISSUE TITLE
Plan tab and Reports tab information architecture/page layout mismatch

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5143]
### Observed behavior
Lesson page and quiz pages in the PLAN tab don't match the information architecture and page layout seen on their counterparts over in the REPORTS tab and in the mocks.

**(in the plan tab)**
<img width="1086" alt="screen shot 2019-02-22 at 4 04 06 pm" src="https://user-images.githubusercontent.com/25045166/53277947-6a32a900-36bb-11e9-8c79-3aeef9caa53f.png">

**(in the reports tab)**
<img width="1100" alt="screen shot 2019-02-22 at 4 12 51 pm" src="https://user-images.githubusercontent.com/25045166/53278156-78cd9000-36bc-11e9-9cfc-18094d8c5cf0.png">

### Expected behavior
- The same above-the-fold page layout. See screenshot attached
<img width="1062" alt="screen shot 2019-02-22 at 4 10 17 pm" src="https://user-images.githubusercontent.com/25045166/53278102-25f3d880-36bc-11e9-8488-9631e428b120.png">

### User-facing consequences
- Lack of consistency between the information architecture of both tabs
- Looks like nothing changed/you're still on the same page after creating the details of a lesson
- Redundant information appearing twice, such as 'Plan your class' header and its following paragraph text

### Context
…

**Comment by jonboiser** [comment]
~When implementing, I think the idea is we still have the secondary tab buttons (e.g. lessons, quizzes, groups) in the Plan page, which are missing in the Expected behavior screenshot.~

To implement:

1. On the `LessonSummaryPage`: Remove the `PlanHeader` component at the top, and add a "back" link that goes to the `LessonsRootPage`
1. Next to the header with the Lesson's name, add an open book (lesson) icon
1. (Maybe) On `ReportsLessonReportPage`, include the description (?)

**Comment by khangmach** [comment]
I edited those secondary tabs out of the expected behavior screenshot, because they're not supposed to be there. The information hierarchy and expected behavior should follow screenshot #2 in this issue

**Comment by jonboiser** [comment]
Okay, I think I understand.

What about the "Groups" section? In the mockups, the hierarchy is also different between plan and report.

**Comment by khangmach** [comment]
We can apply the changes to the Groups flow as well. Good catch

**Comment by rtibbles** [comment]
Fixed in #5192
