### ISSUE TITLE
Scrollbar occluded by scrolling header on linux

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#5150]
### Observed behavior
When the viewport is narrow enough for the ScrollingHeader to be hideable, The scrollbar extends the full height of the container body, which, due to the overlay of the scrolling navbar header, means that the top part of the scrollbar is covered by it.

![image](https://user-images.githubusercontent.com/1680573/53372744-837c6500-3908-11e9-8330-2023f979b407.png)

### Expected behavior
Scrollbar only extends to the visible portion of the page container.

### User-facing consequences
Might not realize that they can scroll as part of the scrollbar (including the part that has the 'current' scroll section) is covered.

### Context
 * Kolibri version 0.12.0b7.dev0+git.27.g3fbd0fdd
 * Operating system Ubuntu 16.04
 * Browser Chrome

**Comment by jonboiser** [comment]
Currently the main 'content' div pushes things down using an inline-style for margin-top. Maybe this should actually be absolutely positioned with `top: X px` instead?

![Screen Shot 2019-03-28 at 3 47 39 PM](https://user-images.githubusercontent.com/10248067/55197841-01829480-5171-11e9-9649-656df2333977.png)

**Comment by indirectlylit** [comment]
that's exactly what it does when the app bar is not set to scroll offscreen:

https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreBase/index.vue#L279-L304

**Comment by benjaoming** [comment]
Is this a simple fix? Can we fix it for 0.12.8 as well?

**Comment by benjaoming** [comment]
This especially affects Khan Academy topics which have many sub-elements that are hidden.

**Comment by indirectlylit** [comment]
@benjaoming it sounds like you're describing a different issue. This one is just about the _scrollbar_ being occluded.

Would you mind opening a new issue with screenshots?

**Comment by indirectlylit** [comment]
@jonboiser is this issue still valid after your changes in #5971 ?

**Comment by jonboiser** [comment]
Yeah, this will still happen because the header is an overlay on the main content, instead of being positioned above it in the y-axis, which seems to be standard for websites with similar design.

Whether the scrollbar is visible and seemingly cut off by the header depends on the browser and OS, though. For example, in Windows, the scrollbar is visible, but actually will appear along the entire length of the viewport. In macos, the scrollbar only appears while scrolling. The screenshot in the OP might be specific to how scrollbars are displayed in Linux.

**Comment by benjaoming** [comment]
@indirectlylit pretty sure it's this issue.

![kolibri_missing_scrollbar ogv](https://user-images.githubusercontent.com/374612/67978408-54965b80-fc1a-11e9-8b7b-f9e05dc55ca2.gif)

**Comment by indirectlylit** [comment]
The original issue said that users might not realize that they can scroll, specifically because the "thumb area" and top scroll arrow are hidden. @benjaoming does this accurately describe the issue for you, also?

(reference: https://www.pcmag.com/encyclopedia/term/50938/scroll-bar)

It seems to me that this might be mostly a UX issue for Linux desktop users. Mac, Android, and iOS have all stopped showing scrollbars as permanently visible, and instead only show them once the user has started scrolling. As @jonboiser said above, "In Windows, the scrollbar is visible, but actually will appear along the entire length of the viewport."

My guess is that Linux users will still look for a visible scrollbar, whereas users of other operating systems are less likely to use this as a cue, and instead just assume that the window is vertically scrollable.

A couple references:

* https://uxmag.com/articles/the-extinction-of-the-scrollbar
* https://ux.stackexchange.com/questions/56925/why-does-apple-hide-the-vertical-scrollbar-on-mac-laptops

One easy option might be that we make a special case for Linux desktop users, and disable appbar-hiding completely?

**Comment by indirectlylit** [comment]
Alternatively, @rtibbles and @benjaoming I'd be interested whether you know of examples of sites that do app-bar hiding better on Linux?

**Comment by benjaoming** [comment]
> The original issue said that users might not realize that they can scroll, specifically because the "thumb area" and top scroll arrow are hidden. @benjaoming does this accurately describe the issue for you, also?

Yes, indeed. My own experience: I was confused because I thought the page had issues displaying all the contents. I couldn't tell if the page has finished loading, if it's broken or if I should drag-select contents in order to navigate downwards. I didn't realize that I could scroll, because I look for a scrollbar before scrolling!

If contemporary UX development wants scrollbars dead, then resistance is futile. I can't see why Kolibri should bother maintaining UX that is actively sabotaged by its host systems.. that's a pretty uphill struggle.

I would consider this as a `wontfix` because of the presented information - thanks @indirectlylit 

P.S. I'm writing this from a textarea with a useful scrollbar :)

**Comment by rtibbles** [comment]
Closing this as wontfix.
