### ISSUE TITLE
User menu label not automatically updated

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5156]
### Observed behavior
After I updated the username of the admin account, the user menu label still the same. But when I refresh the page, The user menu will update.
### Expected behavior
It should update automatically. 

### User-facing consequences

…

### Errors and logs
![gif-temp](https://user-images.githubusercontent.com/8663934/53391331-02d56b80-39d1-11e9-918a-7da855ad2a54.gif)

### Steps to reproduce
* Log in as admin
* Navigate at the profile page
* Rename your  profile username and click the `save changes`
* See the user menu label
### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.x-beta9
 * Operating system: macOS 10.13
 * Browser: Safari 11.0.3

**Comment by jonboiser** [comment]
Getting this error when trying this out

`[vuex] unknown action type: getCurrentSession`.

Can't find an implementation for getCurrentSEssion anywhere. I believe removing it caused this issue, since as a side effect of getCurrentSession, it replaces `core.session` with the latest data (including the new username).

To fix it, we need to call a mutation on the `core.session.username` using the new username in the `updateUserProfile` action.

**Comment by rtibbles** [comment]
I deleted it and moved all session fetching functionality to the heartbeat code. Thought I had caught every reference, but it seems not.

**Comment by rtibbles** [comment]
Fixed in #5192
