### ISSUE TITLE
Auto sign-out from tablets during normal class

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#5377]
**Observed behavior**
Kids are signout out of their tabs automatically while watching videos or doing quizzes

**Expected behavior**
The user should not be signed out automatically.

**User-facing consequences**
While the kids are in the middle of any exercise or video, they are being automatically signed out. They need to again re-login to continue the session

**Steps to reproduce**
This happens in some of the tabs during a normal classroom session.

**Context**
Kolibri version : Kolibri 0.12.2
Operating system : ubuntu 14.04
Browser : Chrome

![ad5ad6e1-e3cf-497c-a107-e26479a172a2](https://user-images.githubusercontent.com/8583367/56283682-15963200-6130-11e9-99b6-a61d556c359f.jpg)

**Comment by jonboiser** [comment]
Hopefully this gets fixed by #5393, as it seems in the screenshot that the user was not logged out, but encountered an unhandled error. Seeing the Error Page in response to the non-unique log id is new to me though; usually it just resulted in a console error, but the rest of the app still ran fine.

There is a similar issue #3843, which manifests differently (the user actually gets sent to the sign-in page and sees a "logged out due to inactivity" message).

**Comment by indirectlylit** [comment]
I'll close this and we can watch for it in 0.12.3

**Comment by miyer03** [comment]
@indirectlylit this is again observed in 12.8. Attached is the screen shot where sometimes the kids are logged out. The kids are not inactive but sometimes if the page loading is slow the kid keeps waiting. But in all they should not be logged out at least for 45 to 60 mins.

OS :- Xubuntu 18.04
Kolibri :- 12.8
Browser :- Chrome

![IMG_20191214_121157](https://user-images.githubusercontent.com/8583367/71064474-2bfbfe00-2195-11ea-9153-ca0b30de9d3a.jpg)

**Comment by indirectlylit** [comment]
okay, thanks for the report

**Comment by pcenov** [comment]
@radinamatic I'm not able to replicate this issue in 0.15.1 - left the device untouched for ~50 minutes.

**Comment by rtibbles** [comment]
Closing as fixed.
