### ISSUE TITLE
IMPORT/EXPORT - pending tasks are not returned

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#538]
## How to reproduce

1. Start server and navigate to management/content tab. 
2. Import content from internet using content channel id.
3. The progress indicator appears, disappears, and then reappears
4. May need to repeat to see behavior. 

The length of time that the progress indicator is hidden for is longer on slower computers.

## Details

Starting a task (e.g. using `startremoteimport`, `startlocalimport`, and `startlocalexport`) returns a task ID as expected.

However, requesting the list of tasks afterward returns an empty list for a short period of time. This causes the client to have incorrect information about the state of the server.

## User Impact

Behavior feels broken.

More significantly, it's possible that the user - thinking that the transfer did not start - might try to start an import a second time while waiting for the progress indicator to re-appear.

**Comment by jonboiser** [comment]
I don't think I've ever seen this in development, but I think that's because the transfer starts instantaneously.

I think this might actually be a UX/Front end issue because it is correct that the UI does not do anything special in the gap between when a user clicks "import" or "export" and the transfer actually starts (or fails).

**Comment by rtibbles** [comment]
I think this has been fixed by barbequeue. Closing for now.
