### ISSUE TITLE
many text wrapping issues related to titles in cards

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#5468]
### Observed behavior

Also relevant:

* https://github.com/learningequality/kolibri/issues/5464
* https://github.com/learningequality/kolibri/issues/4419

In Firefox, titles on content cards will break in the middle of a word, splitting the word in two pieces without indication that this has happened.
![Word Break](https://user-images.githubusercontent.com/819838/57481889-0a7a8180-7258-11e9-8c50-f1b3003adca4.png)

### Expected behavior

In the English language, I expect to see a hyphen appended to the first half of the word, indicating the word has been broken in half and the rest follows on the next line. Although, it may be advisable to change the wrapping controls to avoid this entirely, opting for a different approach if the title is too long for the area on the card.

### User-facing consequences

Users may misunderstand a content's title because longer words may be split in half with no indication of what's happening.

### Errors and logs

None.

### Steps to reproduce

Find or create content with lengthy titles. Screenshot is taken of content from channel with token `gojad-patot`

### Context

Kolibri - develop
Ubuntu 18.04
Firefox 66

**Comment by jonboiser** [comment]
It seems that Firefox doesn't support the `word-break: break-word` CSS. So the fallback `word-break: break-all` is being used.

Maybe we can remove this fallback rule.

**Comment by indirectlylit** [comment]
what was the problem with `word-break: normal`?

**Comment by jonboiser** [comment]
I don't know. It seems like it doesn't try to do anything if it's `word-break: normal`
![Screen Shot 2019-05-10 at 1 32 50 PM](https://user-images.githubusercontent.com/10248067/57555095-264d5880-7328-11e9-9685-090d1293a483.png)

**Comment by jonboiser** [comment]
Maybe we don't need a word-break rule at all, since there's supposed to be some JS that truncates long titles anyway.

**Comment by indirectlylit** [comment]
the change was in PR #4439 re: issue #4419

| before | after |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/57560825-48050a80-733d-11e9-8bf8-c0422876084a.png) | ![image](https://user-images.githubusercontent.com/2367265/57560831-4fc4af00-733d-11e9-9c68-0b13ac4b1396.png) |

That doesn't really seem like the right fix to the problem to me - we can't just break words across lines at arbitrary places.

Ideally we should be able to just trigger the tooltip from #3278 in order to show the full title when we detect horizontal truncation. The `TextTruncator` component we have only works vertically, not horizontally. If we wanted to do horizontal too, we could potentially add something like a fade-to-white on the edge?

![image](https://user-images.githubusercontent.com/2367265/57561134-e80f6380-733e-11e9-9562-c75891057246.png)

**Comment by indirectlylit** [comment]
In https://github.com/learningequality/kolibri/issues/4419#issuecomment-493780085 @radinamatic posted a screenshot where words were still being broken in 0.12.y.

Re-opening.

**Comment by radinamatic** [comment]
It's inconsistent, some long titles get *`...`*, some get truncated arbitrarily:

![Ubuntu16 04 (start)  Running  - Oracle VM VirtualBox_036](https://user-images.githubusercontent.com/1457929/57996092-dad44080-7ac5-11e9-9fe5-229ca36c8036.png)

`0.12.4b1 DEB` on Ubuntu 16.04

**Comment by indirectlylit** [comment]
also observed by @lauradanforth on Windows with Edge on 0.12.7


![image](https://user-images.githubusercontent.com/2367265/64375346-93bd7d00-cfda-11e9-88d5-71a0d6b36101.png)

**Comment by indirectlylit** [comment]
reported by @jtamiace in an 0.13 bug bash:

![image](https://user-images.githubusercontent.com/2367265/71263931-d2601480-22f7-11ea-9020-042bd95fb175.png)
