### ISSUE TITLE
remove the UserTable component

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5470]
### Observed behavior

Our `UserTable` component is serving too many purposes, united only by the fact that they happen to be tables whose rows correspond to users. It's growing into a difficult-to-maintain beast and doesn't do very much to enforce consistency over just using a bare `CoreTable`

### Expected behavior

We should remove the shared `UserTable` component and replace it with non-parameterized `CoreTable`s

### User-facing consequences

None - just code maintainability

N/A

### Context

0.12.3

**Comment by jonboiser** [comment]
Closing, since I believe that `UserTable` covers all of our current user account-displaying needs, and actually duplicating the code for the various workflows its used in would actually increase the maintenance burden. If a new presentational component is needed for users, though, I would recommend just adding a new one instead of adding more props/features to `UserTable`
