### ISSUE TITLE
Lint for all Python versions

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#551]
## Summary

Currently we only lint under Python 2.7. This might cause some edge cases for non-Python 3 compatible code that doesn't get tested during testing builds.

**Comment by rtibbles** [comment]
Might be better instead to simply run `flake8-print` to make sure we don't use print statements. https://pypi.python.org/pypi/flake8-print

**Comment by ralphiee22** [comment]
I like that idea, also a good safeguard so people don't inadvertently leave print statements in their code. 
Also, for reference https://docs.python.org/3.0/whatsnew/3.0.html#changed-syntax.
But since we are striving for 100% code coverage, technically all code should be ran against python 2 & 3, so that should be catching any failures as well.

**Comment by rtibbles** [comment]
Unfortunately flake8-print is currently broken for flake8 3,4 upwards (https://github.com/JBKahn/flake8-print/issues/23).

**Comment by JBKahn** [comment]
Sorry about that, the issue was that it was off by default after 3.4 but I've just released a fix that should work.

**Comment by rtibbles** [comment]
Fixed in #4551
