### ISSUE TITLE
Learner reports inconsistent last activity records 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5611]
### Observed behavior
I have a `49 years` record of a learner last activity.

### Expected behavior
Should have an consistent learner last activity records.

### Errors and logs
[db.sqlite3.zip](https://github.com/learningequality/kolibri/files/3250445/db.sqlite3.zip)

![Screen Shot 2019-06-04 at 11 48 07 AM](https://user-images.githubusercontent.com/8663934/58849872-b7f97d00-86be-11e9-80fb-98e972e9d42b.png)

### Steps to reproduce
I don't know how to reproduce it it just came out on the records.

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4-beta6
 * Operating system: Windows 7
 * Browser: Firefox 67.0

…

**Comment by mrpau-julius** [comment]
I think this is a similar issue on windows 10. I got an invalid date on Microsoft Edge.
![invalid date](https://user-images.githubusercontent.com/38421180/58852358-d9f7fd00-86c8-11e9-82c9-82795f44889c.png)

**Comment by bjester** [comment]
@indirectlylit Do you think the exam's `completion_timestamp` for the learner should be included in `last_activity`? The learner has no attempt logs for the exams, so `last_activity` becomes `null`, but on the front-end we're not being defensive so that becomes the Unix Epoch. I've resolved the null issue but the table now shows blank in that instance. I think coalescing the completion date seems to make sense to me.

**Comment by rtibbles** [comment]
Makes sense to me too :2-cents:

**Comment by bjester** [comment]
The other `Invalid Date` issue is that the timestamp isn't being formatted in the API as a `DateTimeField` but instead a `CharField`. It looks like by default, `DateTimeField` will format it as ISO 8601 which should guarantee proper parsing by JS (`new Date(...)`) for our supported browsers.

**Comment by indirectlylit** [comment]
>  Do you think the exam's `completion_timestamp` for the learner should be included in `last_activity`

Would a completion timestamp be set if the learner had not made any attempts on an exam, and then the coach closes it? In that case it might actually make more sense to show the 'empty' placeholder instead of a date:

![image](https://user-images.githubusercontent.com/2367265/59052444-f8cece80-8843-11e9-99ae-a962f89d9e52.png)

The current fix is still an improvement, but my sense is that the coach closing the exam shouldn't technically qualify as 'learner activity'

**Comment by bjester** [comment]
Hmm yeah it appears that `completion_timestamp` is set when the exam is marked inactive, which means we don't have enough information to distinguish `completion_date` originating from a learner interaction and a coach action. I believe that's a separate data model issue so I'll remove the coalesce.

**Comment by rtibbles** [comment]
Fixed in #5630
