### ISSUE TITLE
channels briefly become selectable in quiz creation

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5811]
### Observed behavior
- Channel nodes briefly become selectable when user clicks on the node.

![select bug](https://user-images.githubusercontent.com/25045166/61899047-7d96aa00-aecf-11e9-8f0a-2385bf068085.gif)

### Expected behavior

- Channels should be selectable

### User-facing consequences
Looks like broken UI

### Steps to reproduce
- Create a new quiz
- Click on a topic node to drill deeper
- See checkboxes briefly appear to the left of channel nodes

### Context
 * Kolibri version: beta
 * Operating system: MacOS
 * Browser: Firefox, chrome

**Comment by indirectlylit** [comment]
Good catch

> * Clicking on channel nodes do not prompt select boxes to appear
> * Select boxes + select all checkbox on channel nodes are always hidden

Previously we blocked channels primarily as a performance hack. This performance issue has now been mitigated.

Rather than maintaining the inconsistency with topics, let's simply update the UI to allow selection of full channels.

**Comment by khangmach** [comment]
Nicee

**Comment by jonboiser** [comment]
Do we want to allow "Select All" for all channels?

**Comment by indirectlylit** [comment]
Let's test whether there are performance issues on the beta server (lots of content). If it works, we can allow it...

**Comment by jonboiser** [comment]
I don't think that would be a very good quiz.

**Comment by jonboiser** [comment]
I'm wondering if that's a good idea, pedagogically speaking. Even being able to select a whole channel, the quiz is not going to be very focused.

**Comment by indirectlylit** [comment]
Correct, it's generally not a good idea. However, consider:

1. there might be situations where a user has created some custom channels which are more focused
2. we allow selection of top-level topics, which are also quite unfocused for some channels

Since we know so little about the case-by-case usage details, I think the safest thing to do is impose fewer constraints and trust the end user to use it effectively. (Unless there's a performance issue...)

**Comment by jonboiser** [comment]
Implementing being to select Whole Channels or the entire Topic Tree is going to be way more complicated than just fixing the flashing checkbox, since it relies on having the entire set exercises pre-loaded. This is actually how it was implemented many versions back and there were performance issues with that approach.

If we want to bring it back, we might need to look at doing things differently.

I'm just going to fix the original issue of the select-all flash.

**Comment by khangmach** [comment]
>Since we know so little about the case-by-case usage details

We made a user stories doc a while back which suggests that when teachers create quizzes, they spend time in selection granularly choosing particular topics. And I haven't seen any channels that are so well structured/focused, the teacher can select just the highest channel level node.
 
https://docs.google.com/document/d/1wADsJZZ2wIjrZZ7mY-dI_myGINfz_Zy31mxCZYSU6lY/edit

Optimization of channel selection is a great thing, but if we can encourage the continuation of good selection practices and follow the current quiz mental modal (which hasn't changed since this documentation) through a simple change of hiding the channel checkboxes/select all, that would be for the best.
