### ISSUE TITLE
facility selection on sign-in page is not persisted for account creation

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5812]
### Observed behavior

| When a server has multiple facilities, a user sees this |  However, this is ignored by the account creation |
|--|--|
|![image](https://user-images.githubusercontent.com/2367265/61909552-54821380-aee7-11e9-98eb-5bd2e9414b05.png) | ![image](https://user-images.githubusercontent.com/2367265/61912433-f5280180-aeee-11e9-82eb-6bbc91941be6.png) |

### Expected behavior

Facility selection should be consistent across the pages

### User-facing consequences

Slight confusion/frustration

### Steps to reproduce

* Create two facilities
* Go to sign in page
* Select a facility
* Start to create an account
* Select facility again

### Context

0.12.6

**Comment by jonboiser** [comment]
So if I select "Sync Hack Session School" on the modal, then the facility in the Sign Up Page will have that facility selected in the dropdown?

Do we still want to give people the option to create an account for other facilities in the Sign up Page? Or should it be set to the facility and disabled (like it is when there is only one facility)

**Comment by indirectlylit** [comment]
> Or should it be set to the facility and disabled (like it is when there is only one facility)

Let's do this for consistency.

I think we'll need to revamp this whole experience soon anyway.

**Comment by jonboiser** [comment]
This should be fixed in #5861. What happens now is that when a server has more than one facility, the Facility pop-up will appear on both the Sign In and Sign Up pages and the user _must_ select a facility. Whichever facility is chosen will be assumed for both flows.

Specifically for the Sign Up flow, the user cannot pick a different Facility after choosing one from the pop-up. If they want to pick a different one, they can refresh and choose something different.
