### ISSUE TITLE
new accounts are seemingly created in the wrong facility

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5860]
### Observed behavior

Accounts created in one facility seem to actually get created in another facility.

### Expected behavior

Facility should be correct. Might be related to #5812, so we should address that issue at the same time.

### User-facing consequences

Users cannot log in

### Errors and logs

…

### Steps to reproduce

* Navigate to https://mexico.unwomendemo.learningequality.org
* Select facility 'Nueva York'
* Go to the account creation page
* Re-select facility 'Nueva York' (#5812) and create a test account
* Log out
* Navigate back to https://mexico.unwomendemo.learningequality.org
* Select facility 'Nueva York'
* Try to log in - it doesn't work
* Reload page
* Select facility 'No pertenezco a ningún centro'
* Try to log in - it works

### Context

0.12.7

**Comment by jonboiser** [comment]
I think it's because the passed-in facility ID is being ignored. The `create` method for the SignUpSerializer just ignores the facility ID that's passed into the payload.

https://github.com/learningequality/kolibri/blob/f22b5a7b084de69110d8ee42aafe38b876acd89e/kolibri/core/auth/api.py#L294-L301

@ralphiee22 Just change that one line to actually use what's in `request.data`?

**Comment by rtibbles** [comment]
That certainly seems like the issue - I imagine it is set to the default facility for safety, maybe change it to:
`"facility": request.data.get("facility", Facility.get_default_facility().id),`

**Comment by jonboiser** [comment]
This should be fixed in #5861. When a user picks a facility from the Facility pop-up, that facility's ID will be sent to the server when a new account is created, and the new user will be added to that facility.
