### ISSUE TITLE
truncated item list needs language direction set correctly

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5862]
### Observed behavior

| english | arabic |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/62799469-b9b43800-ba95-11e9-9151-45590eecfc2a.png) | ![image](https://user-images.githubusercontent.com/2367265/62799477-bd47bf00-ba95-11e9-8211-fe8e74e5f421.png) |

### Expected behavior
RTL should display correctly

### User-facing consequences

broken formatting

### Steps to reproduce

view 'classes' page in RTL

### Context

…

**Comment by Ali-Kazmi** [comment]
Couldn't reproduce, this issue is probably gone (edit: unless its happening with double digit numbers only... i'll try it now) (edit 2: still works, this issue can be closed)  
<img width="1099" alt="Screen Shot 2020-12-16 at 2 44 55 PM" src="https://user-images.githubusercontent.com/41556074/102415669-6f0dce80-3fad-11eb-9acc-49b51c75c06f.png">
<img width="1045" alt="Screen Shot 2020-12-16 at 2 45 15 PM" src="https://user-images.githubusercontent.com/41556074/102415678-7339ec00-3fad-11eb-8db7-57147981e21d.png">
<img width="1062" alt="Screen Shot 2020-12-16 at 2 46 38 PM" src="https://user-images.githubusercontent.com/41556074/102415729-86e55280-3fad-11eb-9856-5ab684500fa7.png">

**Comment by jonboiser** [comment]
This looks slightly different to me on the latest version of Kolibri, but I think this might have been a recent change to how we formatted this message.

@Ali-Kazmi I think you're right that this is fixed! And now that I see the parens are gone, this issue should be completely resolved. Thanks for looking into this!

English
![image](https://user-images.githubusercontent.com/10248067/102538654-670f6680-4061-11eb-9a61-86e12c28b219.png)

Arabic

![image](https://user-images.githubusercontent.com/10248067/102538529-3e876c80-4061-11eb-965d-4c2c5972169f.png)
