### ISSUE TITLE
*Needs help* status is not preserved after Class home refresh

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5881]
### Observed behavior

*Needs help* (red icon and progress bar portion) status appears for the lesson when a learner inputs incorrect answers, but disappears as soon as the coach navigates away. 

*Needs help* status is still reported in the **Class activity** panel, it's just not there in the **Lessons** panel anymore.

![no-needs-help](https://user-images.githubusercontent.com/1457929/63186685-6033a680-c05d-11e9-82cb-c9a626aa90be.gif)

### Expected behavior
*Needs help* status should be correctly indicated in the **Lessons** panel.

### User-facing consequences
Coach does not have a complete picture of the class progress.

### Errors and logs
Nothing visible in the Network tab or the console.

### Steps to reproduce
1. Observe the activity in Class home as coach or admin.
2. Access lesson as a learner in another browser and give incorrect answers in a lesson.
3. When you see the *Needs help* status in the Lesson panel, navigate away to another tab/subtab.
4. Return to Class home: *Needs help* status is not visible anymore in the Lesson panel, but is still present in the Class activity panel (and all the questions with incorrect answers are marked as *difficult*)

### Context

 * Kolibri version: current `release-v0.12.x` dev branch
 * Operating system: Ubuntu 18.04
 * Browser: both FF & Chrome

cc @indirectlylit @jonboiser

**Comment by jonboiser** [comment]
The navigation behavior also looks wrong (I thought we had fixed all of these, but there must still be gaps in there). 

1. ~At the beginning of the GIF, you click the Activity Feed for "Greg P and others", which should took you to a Greg P report (it should take you to the report for the lesson resource).~ It actually _does_ go to the ReportsGroupReportLessonExerciseLearnerPage, which does show you an exercise report for the first person listed in the notification :shrug:. It's the implementation, but IDK if this makes sense.

1. ~When you click "X" from the Greg P report, it takes you to the Suma Numero... lesson report (should have taken you to the home page)~. And it turns out that the ReportsGroupReportLessonExerciseLearnerListPage actually ignores the query parameter in the URL, explaining why it doesn't go back to the correct page when you try to exit. 🤷‍♂ This is a bug: #5889

**Comment by radinamatic** [comment]
@jonboiser I did not even notice the navigation behavior issues that you mention, my main beef was that the *Needs help* notification is not reported in the **Lessons** pane on **Class home** after refresh or navigating away, but is present in the **Class activity**.

**Comment by jonboiser** [comment]
In the video, you scroll down to the card for "Sumar 1" after navigating around, and the "Needs help" stuff is not there.

Before you clicked the links and so on, were there "Needs help" statuses on the "Sumar 1" card? (that part is missing from the beginning of the video).

**Comment by radinamatic** [comment]
@jonboiser I re-recorded the full scenario, hope this is makes it easier to debug:

![no-needs-disappears](https://user-images.githubusercontent.com/1457929/63655591-9c8e9300-c73e-11e9-8e59-354418067e13.gif)

**Comment by jonboiser** [comment]
This looks like what I expected:

1. The "Lessons" and "Class Activity" areas on the Home Page are getting live-updated from data coming from the Notifications API.
1. However, the Class Summary API, or wherever the "Needs Help" notifications is out of sync with what is coming out of the Notifications API.

This looks similar to this issue #5025, but is different in that the "Needs Help" status does not come after multiple refreshes, which might mean that the Class Summary API is not returning "Needs Help"-related data.

**Comment by jonboiser** [comment]
@indirectlylit 	Could you take a look at this code?

https://github.com/learningequality/kolibri/blob/d321e3a793b40feea023d838ef7339210a0dd99d/kolibri/plugins/coach/class_summary_api.py#L91-L110

The `needs_help` map appears to use `<facilityuser_id>-<contentnode_id>` as a key, but the `get_status` appears to check for the presence of keys in `needs_help` using the `content_id`, e.g. `<facilityuser_id>-<content_id>`.

**Comment by nucleogenesis** [comment]
Fixed with merge of 5955
