### ISSUE TITLE
'Manage resources' window cannot be closed when the session has ended

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5890]
### Observed behavior
When coach closes the browser and turns off the device while on the (full screen) `Manage resources` page for lessons, it is not possible to close that page with the `X` close button in the upper left corner. Since the session is closed on a full screen window that does not have the user menu, there is no way to access the `Sign in` link. Refreshing the page does not change anything, and the only way out seems to be manually editing the URL, which is not an ideal solution for non tech-savvy users. Browser `Back` button might work, but if they were navigating deep and long through the channels while looking for resources in that window, it still would require several clicks.

![2019-08-21_8-43-44](https://user-images.githubusercontent.com/1457929/63412470-1c8fc280-c3f8-11e9-9e0c-82c63133f7e9.png)

As a minimal fix it should be possible to close that window with the `X` close button in the upper left corner, and have a visible option to arrive to the `Sign in` page.

I'm also wondering whether was there a reason not to implement an automatic redirect to the `Sign in` page every time the browser is reopened on a page that requires a running session, but that session has ended? Even when the users find themselves on this `Did you forget to sign in?` page, and path to signing in is clear, they still have to a) open the user menu and b) click on the `Sign in` link anyway. I'm just wondering why not spare them those two clicks also?

### Expected behavior
Closing the full screen window should work properly.

### User-facing consequences
User is trapped and has no visible way to sign in and use Kolibri.

### Errors and logs

![2019-08-21_6-22-38](https://user-images.githubusercontent.com/1457929/63402627-5bb01a80-c3dc-11e9-88b0-5bf8d4d8e5a1.png)

### Steps to reproduce

1. Sign in as coach and enter the `Manage resources` page on a lessons or quizzes. **Don't press the <kbd>Finish</kbd> button**.
2. Close the browser and shut down the device.
3. Restart the device, Kolibri, and reopen the browser.
4. Try to close the `Manage resources` page with the `X` close button in the upper left corner. 

### Context

 * Kolibri version: current `release-v0.12.x` dev branch
 * Operating system: Ubuntu 18.04
 * Browser: both FF & Chrome

cc @indirectlylit @jonboiser 
Tentative milestone set to `upcoming patch`...?

**Comment by jonboiser** [comment]
Similar behavior happens in a lot of different places, where your session has ended, but you'll see an immersive toolbar for item on the top and the "did you forget to sign in" message below.

Maybe we should figure out a consistent behavior for going to arbitrary URLs that require authorization (but you have not logged in yet). It may not make sense to show the immersive toolbar and have the "X" button work, since the screen the "X" would go to would also require authorization.

**Comment by indirectlylit** [comment]
I think we should do two things:

1. When the `AuthMessage` is being shown inside a full-screen modal, the 'X' button should redirect people to the sign-in page. That will address this issue.
2. Add a new sign-in link and post-sign-in redirect behavior:  https://github.com/learningequality/kolibri/issues/5892

**Comment by jonboiser** [comment]
Sometimes the label next to the "X" is missing because the API to fetch that data requires authorization also (e.g. class names, user names, etc.). So maybe just show the normal toolbar for the plugin (no immersive toolbar), because it's hard to know ahead of time which pages this might happen to to code in a placeholder.

**Comment by indirectlylit** [comment]
that sounds good to me

**Comment by marcellamaki** [comment]
Fixed with https://github.com/learningequality/kolibri/pull/8450
