### ISSUE TITLE
Edit profile form field labels overlap placeholders

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5932]
### Observed behavior

Happens in Chrome on Ubuntu, and only on the first load when the user is invited to update their profile. Subsequent entering the `Edit` profile page displays the labels correctly.

![edit-profile-form-labels](https://user-images.githubusercontent.com/1457929/64440890-1b83b400-d0cd-11e9-830a-33aca0f3821d.gif)

### Expected behavior
Labels should not overlap the field.

### User-facing consequences
Unreadable text, unclear function of the field.

### Errors and logs
…

### Steps to reproduce
Login as the user who is still missing the demographic data, so Kolibri directs you to update their profile.

### Context
 * Kolibri version: current `develop` branch
 * Operating system: Ubuntu 18.04
 * Browser: Chrome, but **not** Firefox

**Comment by jonboiser** [comment]
The only difference I can tell between the okay case "Profile -> Edit Profile" and the bad case "Notification -> Edit Profile" is that the bad case goes across plugins (Learn -> User), whereas the ok case doesn't. It seems like it's probably something related to JS performance, or timing.

**Comment by indirectlylit** [comment]
this looks very similar to the problem we saw here: https://github.com/learningequality/kolibri/issues/2673

**Comment by jonboiser** [comment]
@radinamatic 	Do you see any evidence that it's similar to #2673 (Chrome autofill influencing the floating label)? In your video, I don't see the same Chrome autofilling styling in the inputs.

...I just realized it can't be the same since these are dropdown elements. It just seems another OS/Browser specific quirk to me, but maybe the fix will be a similar hack where we have to manually force the floating label to go up on this page if we notice it hasn't done so after some time.

**Comment by radinamatic** [comment]
> another OS/Browser specific quirk 

Yep, seemed the same thing to me 👍 
I'll re-test and check, haven't encountered it since initially reporting it!

**Comment by indirectlylit** [comment]
closing as stale
