### ISSUE TITLE
Really long description tooltips

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#5947]
### Observed behavior

Tooltips as long as the screen can see.

### Expected behavior

Maybe some kind of concatenation?

### User-facing consequences

- Laughter. 
- Confusion?

### Steps to reproduce

Navigate to a resource for a lesson that has a description (Aflatoun pictured above). 
Hover over the card

### Context

Kolibri 0.12.9a1 UN Women build, 
Windows 10 Home
 Chrome Version 76.0.3809.132 (Official Build) (64-bit)

![Screenshot (9)](https://user-images.githubusercontent.com/9877852/65287356-c6e22f00-daf7-11e9-8a27-44c2c563880e.png)

**Comment by priyanka-choubey** [comment]
@jonboiser @indirectlylit @kollivier I want to work on this. How do you suggest I approach this issue? Thank you

**Comment by kollivier** [comment]
@priyanka-choubey I would suggest waiting on this issue until we decide what the expected behavior should be.

**Comment by indirectlylit** [comment]
Agreed, the expected behavior is not currently defined.

That said @priyanka-choubey if you'd like to experiment and propose a solution, we can review the proposal. Some guidance:

* We should not try to modify the text itself (e.g. by inserting newlines)
* The solution might use max-widths and text wrapping on the tooltip
* However this is actually an inappropriate use of tool tips because the text here is user-generated. A different UI to handle this case might be necessary

**Comment by khangmach** [comment]
Related clipping issue via the container:
<img width="1032" alt="Screen Shot 2020-05-11 at 12 11 57 PM" src="https://user-images.githubusercontent.com/25045166/81603315-fabddd80-9382-11ea-8eb3-fe30e3c2e820.png">
