### ISSUE TITLE
channel 'options' does not include 'export'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6079]
### Observed behavior

The options for a channel does not include 'export':

![image](https://user-images.githubusercontent.com/2367265/69011021-f6fd5100-0933-11ea-897c-761cdf4689ff.png)

### Expected behavior

Option to export under 'options' menu

### User-facing consequences

Need to discover one of two less-obvious alternatives:

1. Select a single channel from bulk export mode under 'options' at top of page
2. "Select all" from granular export mode under 'manage' for the particular channel

### Context

0.13.0 alpha 0

**Comment by jonboiser** [comment]
This was removed for this version. If you want to export a channel, you can either 1) go to 'Manage', select some contents and then selectively/granularly export. Or 2) go to the top "Options" dropdown and select "Export channels" to export an entire channel.

**Comment by indirectlylit** [comment]
JB mentioned that

> to make things consistent, maybe could even get rid of the “delete” option too

which would also mean that we can replace the two-click <kbd>Options</kbd> menu with a one-click <kbd>Manage</kbd> button.

@khangmach thoughts on either of these?

1. Add 'Export' to 'Options' menu
2. Replace 'Options' menu with just a 'Manage' button

**Comment by khangmach** [comment]
Having export inside of the management page was an intentional design choice established in very early design review discussions where we were on board with the decision. Some more notes regarding the export dropdown option:

- RE: manage functionalities, we wanted users to see and make first selections and decide whether to follow through with a deletion or export action. This is intentionally the opposite from import, where you want to see the channel first before choosing the content.
- Adding an export button on the screen above will prompt the discussion of checkboxes and multiple channel selection on this screen, which is another complicated discussion.
- The extra method to delete in the dropdown is just a convenience if you're just doing a bit of cleanup through the channel list. No complaints from our users over the option so I'll leave it for now. 

Let's stick with having the manage and delete options intact and see what we should shave off or add on later

**Comment by indirectlylit** [comment]
I think there might still be some confusion here - we're not quite on the same page. That said this is not a major issue so I'll lower the priority.

**Comment by indirectlylit** [comment]
from @khangmach 

> I think if we had to choose a method for consistency, I'd rather have the options dropdown be turned into a 'manage' button and if users want to delete a particular channel they'll go into options > delete channels and have that be the mental model for deleting channels
