### ISSUE TITLE
'generate channel listing' has buttons

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6099]
### Observed behavior

There are buttons shown for 'cancel' and 'close' during and after generation of channel listing:

![image](https://user-images.githubusercontent.com/2367265/69188852-4c2f9300-0aeb-11ea-993a-2c2261d0096c.png)

### Expected behavior

generating channel listing probably shouldn't have control actions exposed to the user

### User-facing consequences

might accidentally stop it from happening.

Similar to https://github.com/learningequality/kolibri/issues/6070

### Context

0.13.0 alpha 3

**Comment by radinamatic** [comment]
This makes sense to me :heavy_plus_sign: :one:

**Comment by jonboiser** [comment]
These controls were shown through version 0.12, but should be able to remove the cancel buttons if we intend for the "Generate listing" type Task to be completely hidden from users (e.g. #6070).

We can even remove the code that silently cancels the task when the user leaves the page, and let the download finish behind the scenes.  It's not an issue if the download continues since Tasks would not block the UI any more.

**Comment by indirectlylit** [comment]
> We can even remove the code that silently cancels the task when the user leaves the page, and let the download finish behind the scenes. It's not an issue if the download continues since Tasks would not block the UI any more.

that sounds great, especially if it means that when they come back maybe it will have finished.

The main thing to watch out for is not to retrigger a _second_ listing generation task
