### ISSUE TITLE
mac DMG file name is not auto-generated

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6146]
### Observed behavior

Generated file name does not match actual build

![image](https://user-images.githubusercontent.com/2367265/69585648-301d6d00-0f95-11ea-8fca-450782722136.png)

### Expected behavior

matches release

### User-facing consequences

confusing behavior to users browsing our releases page: https://github.com/learningequality/kolibri/releases

### Context

0.13.0 beta1

**Comment by DXCanas** [comment]
Do we have thoughts on the naming/versioning scheme? I can try and emulate some of the decisions made for the Android installer.

**Comment by kollivier** [comment]
For now we can probably use the same approach as Android, but one caveat is that we will need to change this if we ever make it possible to update Kolibri from within the app, as we can't update the app's version without re-signing it. The other option would be to independently version the app, but append the Kolibri version to any build outputs.

**Comment by indirectlylit** [comment]
>  The other option would be to independently version the app, but append the Kolibri version to any build outputs.

This is what we should be generally doing for all distributions. For example:

* [Windows](https://github.com/learningequality/kolibri-installer-windows/releases) - 1.3.4
* [Android](https://github.com/learningequality/kolibri-installer-android/releases) - 0.1.0-beta4

The first version of the Mac app will be 0.1.0 ([milestone](https://github.com/learningequality/kolibri-installer-mac/milestone/1))

Build file names should include both the distribution version and the Kolibri version.

**Comment by kollivier** [comment]
Sounds good, thanks! @DXCanas So basically, I think the easiest way to make this happen is after running `pew package`, add "-kolibri-<kolibri_version>" after the "-buildX" part of the filename and upload that file. On the Android side, this means we should probably be removing the Kolibri version from `project_info.json`, because the version string in there ends up in the app itself, not just the apk filename.

**Comment by DXCanas** [comment]
I always thought including it in the app itself was desirable? So that
updates were trivial?

I've got the android versioning script working for the mac app.

Versioning:
https://github.com/learningequality/kolibri-installer-mac/blob/autogen-name-and-makefile/scripts/create_project_info.py#L51

Build #:

https://github.com/learningequality/kolibri-installer-mac/blob/482a9e4ce55300ad050af635bdfa83f78e2b8aba/scripts/create_project_info.py#L58

Any issues with those?

**Comment by kollivier** [comment]
@DXCanas We don't need the Kolibri version in the app version in order for new builds to appear as updates. The buildkite build number already takes care of that for us, doesn't it?

Removing the Kolibri version from the app version string makes life a lot easier for us. The app isn't going to change nearly as frequently as Kolibri itself, and we're probably going to make the app able to discover network facilities (thanks Zeroconf!) and also allow for the app to notify and update the bundled Kolibri. (e.g. think about things like adding the ability for insider program to get automatic notifications of new builds, which would be a pain in the app store model) So ultimately, we want the Kolibri app to be able to run any version of Kolibri from potentially network or other locations, not just the one it was bundled with.

**Comment by DXCanas** [comment]
Might that lead to weird situations where someone tries to install a new
mac app version on top of an existing install that has the latest version
of kolibri installed?

Either way, removing the kolibri version is simple enough. I dont think I
understand how it's a problem with the android installer, where all updates
are always downloaded from the play store.

Thoughts,  @indirectlylit?

**Comment by kollivier** [comment]
> Might that lead to weird situations where someone tries to install a new
mac app version on top of an existing install that has the latest version
of kolibri installed?

Do you mean it would be a new Mac app that bundles an older Kolibri version? I think we would just make a rule to not do that. (I don't think there's any case in which we'd want to anyway.)

> Either way, removing the kolibri version is simple enough. I dont think I
understand how it's a problem with the android installer, where all updates
are always downloaded from the play store.

If we move to having the app auto-update the bundled Kolibri, or allow it to locate and run network facilities, then the app version will not match the actual configuration of the app. e.g. we could have "Kolibri App 0.2.0-0.14.0" running Kolibri 0.15 from a network location. Imagine we get a bug report from that build. It would be very easy to get confused and start trying to reproduce the bug in 0.14 because that's what the version string says the user is running.

Fixing the version string now gives us the flexibility to make those changes without having to worry about things like app store versioning with public builds after the change.

**Comment by DXCanas** [comment]
>  having the app auto-update the bundled Kolibri, or allow it to locate and run network facilities, then the app version will not match the actual configuration of the app

My point about this, though, was that this isn't typical practice in Android. The Play Store handles updates and the associated changelogs for you. I understand that we're not on yet on the Play store, but this feels like it'd defeat expectations.

> Do you mean it would be a new Mac app that bundles an older Kolibri version? I think we would just make a rule to not do that. (I don't think there's any case in which we'd want to anyway.)

No. I was thinking of a situation where the Mac package installed, let's say v1.0, has any given bug. But they're running latest Kolibri version, let's say 0.13

What would the upgrade path look like if a user wanted to get the latest Mac package (v 1.1, for example), that was already bundled with latest Kolibri?

**Comment by kollivier** [comment]
> My point about this, though, was that this isn't typical practice in Android. The Play Store handles updates and the associated changelogs for you. I understand that we're not on yet on the Play store, but this feels like it'd defeat expectations.

In app stores, there's a distinction between app content updates, and app updates. Mobile games are a good example of this. (Sorry, it's what I know! ;-) When a game is having a new event, it commonly downloads new content, but this often does not show up as an update in the Play store. The Play store update happens when the app has actual new features, not just new content. (e.g. if an event adds new features to the game, it may have both an app and a content update) So in a sense, I'm suggesting we consider the Kolibri it's running as app content or assets, rather than a part of the app itself.

> What would the upgrade path look like if a user wanted to get the latest Mac package (v 1.1, for example), that was already bundled with latest Kolibri?

Do you mean in the case the user didn't want to update their Kolibri, JUST the Mac app? If v1.1 has 0.14 and they wanted to stick with 0.13, then as currently implemented on both Android and Mac it would be an issue because it would update their Kolibri as well. 

However, if we treat it as "content" as suggested above, then 0.13 would live in the app's data folder, and v1.1 would just notify them that they could update to 0.14. Then they could choose whether or not to do so. If they chose not to, they would get the new app but their Kolibri installation would remain untouched.

**Comment by kollivier** [comment]
A quick note to add on this. The caveat here is the offline aspect, so we probably always want to bundle some version of Kolibri so that the user doesn't have to run the app to get a Kolibri installation. If Kolibri can auto-update, it may not be essential that we push an app update for each new Kolibri release though so that people aren't constantly having to update the app just because there's a new Kolibri build available.

**Comment by DXCanas** [comment]
Decided to delay this convo in favor of just changing the filename itself for now! Version + build number will remain the exact same as it is rn

The handy Makefile can wait till we can flesh out these thoughts.
