### ISSUE TITLE
test behaves differently locally (macos) and on travis

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6158]
### Observed behavior

observed by @jonboiser and @indirectlylit on macos, running `kolibri/plugins/device/test/test_api.py` locally
results in 

```
    def execute(self, query, params=None):
        if params is None:
>           return Database.Cursor.execute(self, query)
E           django.db.utils.OperationalError: Problem installing fixtures: no such table: content_contentnode__old
```

observed that @rtibbles and @bjester did not see this behavior on Linux

### Expected behavior

Test should run

### User-facing consequences

developers cannot reproduce travis test failures

### Errors and logs

see complete output below:

[output.txt](https://github.com/learningequality/kolibri/files/3894659/output.txt)

### Steps to reproduce

```
tox -r -e py3.7 -- kolibri/plugins/device/test/test_api.py
```

or 

```
pytest kolibri/plugins/device/test/test_api.py
```

### Context

0.13.0 beta 2

**Comment by micahscopes** [comment]
FYI, I'm also experiencing this and I'm on Linux (Arch Linux)

**Comment by lyw07** [comment]
I reproduced this issue on my machine and fixed it by downgrading my sqlite version to 3.25.3. I think any sqlite version greater than 3.25.3 would lead to the error.

**Comment by rtibbles** [comment]
Oh.. that's odd. Looking at the changelog for 3.26.0 the only thing that seems remotely relevant is the new PRAGMA: https://www.sqlite.org/releaselog/3_26_0.html that maintains previous ALTER TABLE behaviour, @lyw07 if you can reliably reproduce this, could you try adding that PRAGMA

**Comment by lyw07** [comment]
@rtibbles sorry for the late reply. 
I realize that I had this issue earlier last year and searched it on Slack - the issue could be due to sqlite 3.26.0's integration with django: https://code.djangoproject.com/ticket/29182 
The fix from Django goes into Django 2.1.5 and got backported to 2.0: https://github.com/django/django/pull/10733 but never 1.11.x

**Comment by rtibbles** [comment]
Looks like the fix is precisely what I suggested doing: https://github.com/django/django/pull/11986/files (this is the closed PR to the 1.11 backport that was rejected as it was not a security fix).

Could you try to apply this fix by adding this pragma here: https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/sqlite/pragmas.py#L1, the `CONNECTION_PRAGMAS` are executed whenever the connection is opened by Django (or SQLAlchemy) so should fix this error.

**Comment by rtibbles** [comment]
As this might be a live issue for users with more advanced SQLite versions, I've set it to a 0.13.1 milestone, if you have capacity to do the test and fix @lyw07 please self assign.

**Comment by lyw07** [comment]
ah I see! Thank you for the explanation! And yes, I will work on this
