### ISSUE TITLE
'back to home' button in coach error page doesn't work

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6181]
### Observed behavior

observed by @jayoshih during the 0.13.0 beta 1 bug bash:

> If there's an error on the classes page, I get an error when I click "Back to Home"
> 
> ![image](https://user-images.githubusercontent.com/2367265/69926064-d4a52080-1467-11ea-98f0-ec066ca46c54.png)

### Expected behavior

'back to home' should take the user back to the main page of the current app

### User-facing consequences

frustrating behavior on an error page

### Errors and logs

`vue-router.esm.js:2051 Uncaught (in promise) NavigationDuplicated {_name: "NavigationDuplicated", name: "NavigationDuplicated", message: "Navigating to current location ("/") is not allowed", stack: "Error↵    at new NavigationDuplicated (http://loca…tend-0.13.0b3.dev0+git.19.gdff6225c.js:120388:14)"}message: "Navigating to current location ("/") is not allowed"name: "NavigationDuplicated"_name: "NavigationDuplicated"stack: "Error↵    at new NavigationDuplicated (http://localhost:3000/js-dist/kolibri.core.default_frontend-`

### Steps to reproduce

In `CoreBase/index.vue` change

```html
      <KPageContainer v-else-if="error">
        <AppError />
      </KPageContainer>
```

to 

```html
      <KPageContainer v-else-if="true">
        <AppError />
      </KPageContainer>
```

### Context

0.13.0 beta 1

**Comment by jonboiser** [comment]
Which URL is the error appearing on? Based on the error output, it seems like it might be on `/coach/`, which I think is the only plugin that has a root URL that doesn't immediately redirect to a different non-root route.

The console errors appear to be due to a change in Vue Router with the new router.push, etc. Promises API, but the router.push still basically works (i.e. you will see an error but still get redirected to the "/" route). The console error is unexpected and might have something to do our extensions to the router. A hack is to append a `catch` method after `router.replace` and swallow the error.

If you are indeed on a root url "/" and that page did fail to load its data, etc., you will see 1) the AppError component 2) the NavigationDuplicated console error when clicking "Back to home", and 3) not appear to go anywhere because you are at the root URL which is broken, then redirecting to the root URL again (which is still broken).

**Comment by indirectlylit** [comment]
I was able to reproduce this in facility also:

![error](https://user-images.githubusercontent.com/2367265/69997958-28684600-150a-11ea-8a25-f6e91f64e079.gif)

**Comment by jonboiser** [comment]
Can you try this on Facility > Data. Facility > Classes is where the root "/" redirects for the facility plugin.

**Comment by radinamatic** [comment]
The same `NavigationDuplicated` error appears in #6169, albeit on **Learn**

![learner-cant-see-classes-with-lessons2](https://user-images.githubusercontent.com/1457929/70000102-8e7cb980-155a-11ea-99f0-956a4e3cbba8.gif)

**Comment by jonboiser** [comment]
Yeah, there I see in the Learn page movie, that the button does redirect you from '/classes/' to '/', which should then redirect you back to '/classes' (if you are assigned to any), which then seems to crash again, but without the AppError page and just a blank screen... 

The blank screen might have something to do with the `showAllClassesPage` handler function, since it doesn't do a force re-request and throw another 500 error.

**Comment by radinamatic** [comment]
Yes, the learner is assigned to a class, but gets this error message **IF** there's an opened lesson in their class. As soon the lesson is made invisible to learners, the 500 error is not there any more. Opened quizzes cause no errors.

**Comment by indirectlylit** [comment]
I'm actually going to lower the priority of this item. I don't think this qualifies as "high impact on UX", especially compared to some of the other things in 0.13

**Comment by Priyaraj17** [comment]
Where should the button direct to? Kolibri home page?

**Comment by indirectlylit** [comment]
from the description:

> 'back to home' should take the user back to the main page of the current app

so this will be one of:

* `/LANG/learn/`
* `/LANG/coach/`
* `/LANG/facility/`
* `/LANG/device/`

**Comment by rtibbles** [comment]
The button already directs to the correct place, it directs to the root level of the current top level app. The error that was reported is an issue that happens when the error happens during rendering of that root level, as it tries to navigate to the location that it already is at.

I don't think it's clear where the button should go in this case.

**Comment by indirectlylit** [comment]
>  it tries to navigate to the location that it already is at

Ah. Then maybe we should hide the 'back to home' button if it is the 'home' URL which is causing the error in the first place.

**Comment by rtibbles** [comment]
I think @indirectlylit describes the simplest fix here. If the 'back to home' button link is equal to the current path, then we should not display the button.

**Comment by pcenov** [comment]
@radinamatic I can't replicate this one in 0.15.1

**Comment by rtibbles** [comment]
Closing as resolved.
