### ISSUE TITLE
Instant Schools should land on About page upon first access

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#6210]
### Observed behavior

Accessing Instant Schools incognito does not lead me directly to the About page

### Expected behavior

Upon first log in or guest access, About page should be the first page seen

### User-facing consequences

VF: expectations not met
In general: Feature not utilized to full potential

### Errors and logs

…

### Steps to reproduce

1. Open incognito page
2. click on guest access
3. Be taken directly to Learn, when About should be the first page seen

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/5150483/70154210-f9b2b280-1664-11ea-92a7-0ba1cc8bb280.gif)

### Context

…

**Comment by nucleogenesis** [comment]
In my testing, this only occurs for guest learners. I created a new account and the first thing that I saw was the About page.

**Comment by rtibbles** [comment]
The issue then is that the default guestaccess is the learn plugin. This is governed by this redirect hook: https://github.com/learningequality/kolibri/blob/release-v0.12.x/kolibri/plugins/learn/kolibri_plugin.py#L21

Which then gets used here for the guest redirect: https://github.com/learningequality/kolibri/blob/release-v0.12.x/kolibri/core/views.py#L138

Unfortunately, just adding this hook to the VF plugin would be insufficient, because then it would rely on the ordering of the hooks, which is not determinate :/

**Comment by nucleogenesis** [comment]
Fixed in the IS plugin in the PR https://github.com/learningequality/kolibri-instant-schools-plugin/pull/166
