### ISSUE TITLE
update Kolibri to handle new h5p content kind

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6211]
### Observed behavior

In order to decouple H5P from the HTML5 content kind and allow us to properly filter supported types, we're migrating H5P to be it's own type.

This will also require changes in other repos such as studio and kolibri utils.

### Expected behavior

```
            Kind        Preset      Extension
---------------------------------------------
Current     html5       H5P_ZIP     .h5p
New         h5p         H5P_ZIP     .h5p
```

### User-facing consequences

must show content when it can be rendered, and not show it when it cannot

### Steps to reproduce

experiment with importing html5 and h5p content in both recently and non-recently published channels

### Context

0.13.0 beta 3

**Comment by ivanistheone** [comment]
`le-utils` PR for introducing new `h5p` content kind is here: https://github.com/learningequality/le-utils/pull/71

Studio changes needed to change h5p export to be of content kind `h5p` so that they can be ignored by 0.12.s Kolibris.

Note Kolibri "can I render H5P" logic changed in  https://github.com/learningequality/kolibri/pull/6268
0.13 now uses format preset check: https://github.com/learningequality/kolibri/pull/6268/files#diff-ef2895192188b3837bcd15d73cafddf2R19
