### ISSUE TITLE
allow lessons to be assigned to individual learners

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6220]
### Observed behavior

Follow-up from https://github.com/learningequality/kolibri/pull/6149

There, we allowed quizzes to be assigned to individual learners

### Expected behavior

Lessons should also be allowed to be individually assigned to learners

### User-facing consequences

current functionality doesn't yet fully address the motivating user needs

### Context

0.13.0 beta 3

**Comment by nucleogenesis** [comment]
I got started on this and noted that the Lesson creation goes through a small modal, which doesn't fit the flow we intended on Quizzes.

We will need to change the New Lesson flow so that it is:

- Large and still a modal
- Or - more likely - it's own page like how the Quiz creation flow goes.

In the latter case, the page will look exactly like the "Edit Details" page for a Lesson. I just want to get some thoughts before moving further.

![lesson-with-individual-learners](https://user-images.githubusercontent.com/6356129/70355913-15b28180-1828-11ea-8672-0a8f948d65c2.png)

@indirectlylit @jtamiace

**Comment by indirectlylit** [comment]
> In the latter case, the page will look exactly like the "Edit Details" page for a Lesson. I just want to get some thoughts before moving further.

Sounds like this is the right direction to move in. We tend to call this a "full screen modal".

Hopefully it won't require a huge refactor...

**Comment by indirectlylit** [comment]
hooray!
