### ISSUE TITLE
layout of video transcripts broken in RTL languages

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6239]
### Observed behavior

observed during the beta 1 bug bash:

by @nucleogenesis:

> Video w/ Transcript in RTL language is offset 
> 
> 
![image](https://user-images.githubusercontent.com/2367265/69927920-bf7fc000-146e-11ea-93be-2298c0df65b3.png)

### Expected behavior

transcript should be on left

### User-facing consequences

* inconsistent UI
* obscured video

### Steps to reproduce

view transcript in RTL

### Context

0.13.0 beta3

**Comment by bjester** [comment]
@radinamatic I remember talking with you about RTL with respect to the transcript. This issue arose because of some refactor after code review, but I think otherwise it should be doing what we expect. The thing I wanted to double check on was whether the transcript cues themselves should be RTL as well? If I remember correctly, we decided that within the transcript box, it should obey the direction of the transcript language. So this screenshot would be correct:
![screenshot-localhost_8000-2019 12](https://user-images.githubusercontent.com/819838/70581662-ce502c00-1b6c-11ea-8dd0-2cee1ff6ad27.png)

**Comment by radinamatic** [comment]
I'm too late, but it doesn't matter!

Awesome job, both directions look great to me! 👍 



![rtl-transcript-en](https://user-images.githubusercontent.com/1457929/70675342-3136e580-1c89-11ea-91bb-e8fac3b7ea18.png)

![rtl-transcript-ar2](https://user-images.githubusercontent.com/1457929/70675560-c508b180-1c89-11ea-9cce-c060b810dfc9.png)

**Comment by radinamatic** [comment]
Hrm, spoke too soon 😂 

Not a blocker, but wasn't the transcript below making use of the full video width?

![rtl-transcript-below](https://user-images.githubusercontent.com/1457929/70675845-a0610980-1c8a-11ea-93d4-256ca3983392.png)

**Comment by bjester** [comment]
@radinamatic Good catch. I think that's likely a consequence of fixing this issue. I'll fix it.
