### ISSUE TITLE
Error when double saving Coach change

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#6400]
### Observed behavior

I accidentally clicked <kbd>Save</kbd> twice after changing a user to coach, and received an error.

### Expected behavior

No error observed.

### User-facing consequences

Could be confusing to end-users as it's not clear what went wrong, which in reality it doesn't appear anything went wrong.

### Errors and logs

```json
{
  "request": {
    "path": "/api/auth/role/",
    "entity": "{\"user\":\"7778df19b6379f898a86217c2ffaf008\",\"collection\":\"a172ab5ad9d60c58c687d1e2c3c6faf7\",\"kind\":\"coach\"}",
    "params": {
      "1576716755649": 1576716755649
    },
    "headers": {
      "Content-Type": "application/json",
      "Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2",
      "X-CSRFToken": "P3snE0TchKHfhUta79BugyXP7VpJGEeWPUVxz0dU2SJxRHtoqSckah1nABAeBmY5"
    },
    "method": "POST",
    "canceled": false
  },
  "url": "/api/auth/role/?1576716755649=1576716755649",
  "raw": {},
  "status": {
    "code": 400,
    "text": "Bad Request"
  },
  "headers": {
    "Allow": "GET, POST, DELETE, HEAD, OPTIONS",
    "Content-Length": "127",
    "Content-Type": "application/json",
    "Date": "Thu, 19 Dec 2019 00:52:35 GMT",
    "Server": "0.0.0.0",
    "Vary": "Accept, Cookie",
    "X-Frame-Options": "SAMEORIGIN"
  },
  "entity": [
    {
      "id": "UNIQUE",
      "metadata": {
        "field": "non_field_errors",
        "message": "The fields user, collection, kind must make a unique set."
      }
    }
  ]
}
```

### Steps to reproduce

1) Create a new coach user
2) Save the user and get navigated to user list
3) Edit details of user just created
4) Change user Coach type
5) Click Save
6) Click Save again
7) Observe error screen

### Context

Kolibri 0.13
Chrome 78.0.3904.108
Ubuntu 18.04

**Comment by jonboiser** [comment]
Did the "submit" button on the UserEditPage/form disable when you clicked save? That's usually how we try to avoid double-saves on the front-end.

Aside from that, the roles-related API should be made to be idempotent when making the same request multiple times. Esp. since there's edge cases like having two tabs on the same page, then pressing save on both one after the other.

**Comment by bjester** [comment]
@jonboiser No the button does not disable.

**Comment by jonboiser** [comment]
The problem is that this check in the code here isn't working correctly. When you click the second time the condition should be false, but it ends up being true because `userCopy` isn't updated after the first save.

For example, if you open this page as a class coach, change to facility coach, then save... then on the second save `userCopy.kind = class coach` still, and `newUserKind = facility coach`.

https://github.com/learningequality/kolibri/blob/a59f65845147f818091ec3846fc08e7ee02e5dde/kolibri/plugins/facility/assets/src/views/UserEditPage.vue#L302-L307

So in the successful save callback, we need to make sure userCopy is updated.

Or a more foolproof thing to do, in my opinion is refetch the Facility User model.
