### ISSUE TITLE
Edit channel order display issue on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6455]
### Observed behavior
Channel name padding display half when I drag and rearrange the channel list.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/72240177-47d0b380-361e-11ea-96c0-f679ce0d2810.gif)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0
 * Operating system: Windows 7
 * Browser: IE11

**Comment by mrpau-julius** [comment]
I think it's similar issue on Windows 10 pro 2015. In the Firefox v72.0.1, the channel list are not arrange.
![cant_in_order](https://user-images.githubusercontent.com/38421180/72500457-798c8900-386f-11ea-9cd7-290f25938515.png)

**Comment by jonboiser** [comment]
The issue with the weird element height while a channel name is being dragged should be fixed in #6506 

@mrpau-julius Could you investigate the issue in your comment and write a more detailed issue. What stands out to me is that the browser on the right is that the channels are in the reverse order as the first two.
