### ISSUE TITLE
create linting rule or unit test to ensure that RunPython is always the last element of a migration

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6514]
### Observed behavior

Follow-up from #6480

It is possible to write migrations that work in sqlite but not in postgresql

### Expected behavior

We should create a linting rule or unit test to ensure that `RunPython` is always the last element of a migration, which will help protect against the behavior described there

### User-facing consequences

extra time spent finding and fixing bugs

### Errors and logs

```
Cannot ALTER TABLE device_devicesettings because it has pending trigger events
```

### Context

0.13.0

**Comment by chrislun16** [comment]
Is this still open? Can I be assigned to this?

**Comment by jonboiser** [comment]
Hi @chrislun16, could you tell us how you plan to approach this issue first before we assign this to you?

**Comment by chrislun16** [comment]
I'm new to django and migrations but perhaps we could grep to see if run python is the lat element of a migration.

For a school assignment, my partner and I have to contribute to an open source project and choose a few tasks. So I chose this repo and I wanted to find a few tasks like this one that I can be assigned to. I wanted to be assigned before someone else comes and completes the task.

**Comment by jonboiser** [comment]
grep might be too simple to do this check. you should consider writing a flake8 plug since you can access the AST of the migration file.

https://medium.com/analytics-vidhya/how-to-write-flake8-plugins-5c5c47faffc2

I would recommend finding a simpler issue for your school assignment, esp. if you are not familiar with Django and Python right now. But for any issue you are interested in, please just give us a technical plan for how you will solve the issue. Then I can assign you to the issue.

**Comment by chrislun16** [comment]
@jonboiser Do you think #6984 would be a good task? If not, could you recommend a task for us? Thank you.

We are both experienced in python but also have some experience in javascript.

**Comment by jonboiser** [comment]
@chrislun16 #6984 might be too complex as well, but if you have a technical plan on how to address, let us know.

I can recommend #7958 which seems to be an issue with our Python Sphinx-based documentation, if you want to check it out.

**Comment by chrislun16** [comment]
@jonboiser Thanks for the suggestion, but our instructor said we can't work on documentation issues. It should be a task that requires changes to the source code. We both have to spend 12 hours each on this project. This can include time researching the source code and tools we'll use.

I was looking through the beginner friendly issues, but it was hard to gauge the difficulty/time needed for a task. I would appreciate if you could recommend a task that would work for these criteria.

**Comment by jonboiser** [comment]
@chrislun16 #7958 is not "just" writing documentation. there is a bug in the source code of our developer docs website https://kolibri-dev.readthedocs.io/en/develop/. The fix might be in python code or the CSS. Let me know if you would be interested. I'm going to hide these comments since they are off-topic from this particular issue.

If you still need more discussion about working on Kolibri, I would recommend starting a new Discussion here: https://github.com/learningequality/kolibri/discussions

**Comment by chrislun16** [comment]
@jonboiser Ok we would be interested in working on that task.

**Comment by rtibbles** [comment]
Note that I am not sure this is actually desirable, but caution is needed when writing manual migrations.
