### ISSUE TITLE
Wrong resource deletion count in Tasks detail view

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#6574]
### Observed behavior

Deleted 6 files + 1 topic folder from an imported channel (`zapok-dofil`) and it shows a very high and unrelated number of resources deleted.

Tried it twice on one server (Linux + Kolibri 0.13.1rc1) and in each case it gave an absurd count.

![wrong_delete_count](https://user-images.githubusercontent.com/2577060/74586253-c8167a00-500b-11ea-8468-f73c58a6c592.gif)

After second delete attempt, just to ratify if the previous number was a result of any pending cleanup -

![Task manager - incorrect resource count-2](https://user-images.githubusercontent.com/2577060/74586259-cd73c480-500b-11ea-978a-0ecaa4c0dba9.png)

Tried it on another as well with a different OS (Windows + Kolibri 0.13.0) and yet got the same issue.

![Task manager - incorrect resource count](https://user-images.githubusercontent.com/2577060/74586263-d8c6f000-500b-11ea-90bb-4a1b9aff3c58.png)

_Added later:_
Tried it with another channel (`lirub-laruk`) to be sure that it isn't an isolated issue w.r.t. a channel. Deleted 8 resources and there is no count shown -

![Task manager - incorrect resource count-3](https://user-images.githubusercontent.com/2577060/74586747-c9967100-5010-11ea-8d4a-82a678f8b647.png)
 

### Expected behavior

Count should be the number of resources a user actually deletes. Herein 6 or 7 if topic folder is counted as resource.

### User-facing consequences

Confusion. Anxiety that they may have deleted something extra unintentionally.

### Errors and logs

Shall provide if needed.

### Steps to reproduce

As evident in animation above.

### Context

Given above.
Referenced channels : `zapok-dofil`, `lirub-laruk`

**Comment by ivanistheone** [comment]
Related issue: https://github.com/learningequality/kolibri/issues/6351

**Comment by cpauya** [comment]
I have encountered this similar issue of (wrong size reported) while testing [Kolibri v0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1) in an Ubuntu 16.04.6 VM

The imported KA-English channel is only 19GB but the delete task shows 54GB:
![kolibri-v0 13 2-b1--delete size wrong](https://user-images.githubusercontent.com/175580/78031700-7a28bc00-7396-11ea-912b-bf85c4cf9c93.gif)

**Comment by rtibbles** [comment]
There seem to be two possible issues here. The first is that the unused files may not be being counted in a way that ensures they are distinct: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/content/management/commands/deletecontent.py#L131 - this means that files might be double counted and the size of content being deleted is being overcounted.

The other issue is that what is being reported to the frontend as `total_resources` is actually the total number of files that is being deleted: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/content/management/commands/deletecontent.py#L141

This is an issue because one 'resource' might have many files associated with it (e.g. a Khan Academy video may have a video file and multiple subtitle files) - so this may be massively overcounting the number of 'resources'.

To fix this, we should be ensuring that we are deduplicating the file size - to do this in a SQLite compatible way, loading the LocalFile ids and file sizes into a dict and then summing the keys.

We should also be returning a count of resource nodes that have been removed or marked as unavailable from the delete_metadata function: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/content/management/commands/deletecontent.py#L22

**Comment by rtibbles** [comment]
Fixed in #8441
