### ISSUE TITLE
Error ("A lesson with this name...") message while naming a new lesson

### ISSUE THREAD

**Issue by riddhiavlani** [learningequality/kolibri#6593]
### Observed behavior

Each time I create a new lesson, I get this message 'A lesson with this name already exists' below the 'Title' text field. It disappears immediately though- within a couple of seconds
![image (5)](https://user-images.githubusercontent.com/44633158/75027793-2b4d5400-54c5-11ea-93d4-dbb53742a1a7.png)

### Expected behavior

The message shouldn't have appeared since there are no lessons with that name

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri 0.13.0
OS: Windows
Browser: Chrome

**Comment by jonboiser** [comment]
Here's an explanation with some code references, hopefully this helps with the fix.

1. When a new Lesson is created, the `createLesson` handler gets called when the `AssignmentDetailsModal` (which used to be a modal but is now more of a form ) emits a `submit` event

https://github.com/learningequality/kolibri/blob/532bae5b69981e05dd5bcfce027d2cea745815e7/kolibri/plugins/coach/assets/src/views/plan/LessonCreationPage/index.vue#L60-L74

2. At the end of this function, the `createLesson` action gets dispatched. The implementation of this action POSTs a new lesson, then also triggers a refresh of the `classSummary` vuex module state.

https://github.com/learningequality/kolibri/blob/532bae5b69981e05dd5bcfce027d2cea745815e7/kolibri/plugins/coach/assets/src/modules/lessonsRoot/actions.js#L34-L42

3. Back at the `AssignmentDetailsModal`, the no-duplicate title validation gets triggered

https://github.com/learningequality/kolibri/blob/532bae5b69981e05dd5bcfce027d2cea745815e7/kolibri/plugins/coach/assets/src/views/plan/assignments/AssignmentDetailsModal.vue#L179-L187

4. This is because the `lessonTitleUnavailable` getter is now returning `true` because of the refresh to `classSummary`

https://github.com/learningequality/kolibri/blob/532bae5b69981e05dd5bcfce027d2cea745815e7/kolibri/plugins/coach/assets/src/modules/classSummary/index.js#L310-L319
