### ISSUE TITLE
API error - `MultipleObjectsReturned`

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#660]
## Summary

```
GET /coach/api/f6d2f857af2e304093648daf2d8cacec/8f70115bf38c5a648914046832cc137f/facility/1/contentreport/ HTTP/1.1" 500 144267
```

* Exception Type:
  * `MultipleObjectsReturned`
* Exception Value:
  * `get() returned more than one ContentSummaryLog -- it returned 2!`
* Exception Location:
  * `python2.7/site-packages/django/db/models/query.py in get, line 391`

## System information

Found using @rayykim's [test DB](https://learningequality.slack.com/files/rachel/F31MH2GQH/db.sqlite3)

## How to reproduce

Launch kolibri and go to:

http://localhost:8000/coach/#!/reports/f6d2f857af2e304093648daf2d8cacec/topic/8f70115bf38c5a648914046832cc137f/facility/1/all/content_view/date/none

**Comment by ralphiee22** [comment]
I think this is a bug of not the coach reports api, but maybe something in the frontend client for creating or retrieving summary logs. There should only ever be 1 summary log created for each leaf node (exercise, video, etc.). Richard mentioned this issue here https://github.com/learningequality/kolibri/issues/563 and said he addressed it in this commit https://github.com/rtibbles/kolibri/commit/a7de4c0c0307279bc636b0eef7b3f47625b16d28. There may be some other underlying reason that multiple summary logs are created.

**Comment by indirectlylit** [comment]
This contentreport query is for the entire facility, not a individual user. I assume that's not a factor?

**Comment by ralphiee22** [comment]
Sorry, I assumed it was for a single user. I now see where that could be causing an issue for an entire facility. I can submit a PR with the change.

**Comment by indirectlylit** [comment]
thank you!
