### ISSUE TITLE
content import stuck at 100%

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6602]
### Observed behavior

possibly related: https://github.com/learningequality/kolibri/issues/6502

We have reports of this behavior from the forums:

* [Thread 1443](https://community.learningequality.org/t/import-via-online-error-100-downloaded-but-still-incomplete-error/1443) and [thread 1400](https://community.learningequality.org/t/downloading-task-is-not-completing-its-stuck-at-100/1400)
* [Thread 1456](https://community.learningequality.org/t/cant-sign-in-on-kolibri/1456)

There was also this similar prior report with a few users chiming in, and we thought it had been addressed: [Thread 1396](https://community.learningequality.org/t/import-export-issues/1396/6)

![Kolibri not completing](https://user-images.githubusercontent.com/2367265/75297663-4aa9f100-57e5-11ea-9a73-1d5a138cf3e1.jpg)

### Expected behavior

Imports work as expected

### User-facing consequences

Cannot import content

### Errors and logs

Example log file: [kolibri.txt](https://github.com/learningequality/kolibri/files/4257287/kolibri.txt)

Some examples of 500 errors people are seeing:

```
{
“request”: {
“path”: “/api/auth/session/”,
“entity”: “”,
“params”: {
“1582667895147”: 1582667895147
},
“headers”: {
“Content-Type”: “application/json”,
“Accept”: “application/json, application/json;q=0.8, text/plain;q=0.5, /;q=0.2”,
“X-CSRFToken”: “WC66F25F0mmnmTMSQH3axSySIbe7jkzM0xUc3K3eCZYCOo84sHzl7PJSKJMHnjwQ”
},
“method”: “POST”,
“canceled”: false
},
“url”: “/api/auth/session/?1582667895147=1582667895147”,
“raw”: {},
“status”: {
“code”: 500,
“text”: “Internal Server Error”
},
“headers”: {
“Content-Length”: “27”,
“Content-Type”: “text/html”,
“Date”: “Tue, 25 Feb 2020 21:59:59 GMT”,
“Server”: “0.0.0.0”,
“Vary”: “Cookie”,
“X-Frame-Options”: “SAMEORIGIN”
},
“entity”: “Server Error (500)”
}
```

```
{
“request”: {
“path”: “/api/device/deviceinfo/”,
“params”: {
“1582203680411”: 1582203680411
},
“headers”: {
“Content-Type”: “application/json”,
“Accept”: “application/json, application/json;q=0.8, text/plain;q=0.5, /;q=0.2”,
“X-CSRFToken”: “jpqvkxHGzPKqHz8NaKpqVjDz4qAXeKpSeWbhyiJn78pjGOuyq97AC2OvdsZw5jEo”
},
“method”: “GET”,
“canceled”: false
},
“url”: “/api/device/deviceinfo/?1582203680411=1582203680411”,
“raw”: {},
“status”: {
“code”: 500,
“text”: “Internal Server Error”
},
“headers”: {
“Content-Length”: “27”,
“Content-Type”: “text/html”,
“Date”: “Thu, 20 Feb 2020 13:03:08 GMT”,
“Server”: “0.0.0.0”,
“Vary”: “Cookie”,
“X-Frame-Options”: “SAMEORIGIN”
},
“entity”: “Server Error (500)”
}
```

```
{
“request”: {
“path”: “/api/device/deviceinfo/”,
“params”: {
“1582203680411”: 1582203680411
},
“headers”: {
“Content-Type”: “application/json”,
“Accept”: “application/json, application/json;q=0.8, text/plain;q=0.5, /;q=0.2”,
“X-CSRFToken”: “jpqvkxHGzPKqHz8NaKpqVjDz4qAXeKpSeWbhyiJn78pjGOuyq97AC2OvdsZw5jEo”
},
“method”: “GET”,
“canceled”: false
},
“url”: “/api/device/deviceinfo/?1582203680411=1582203680411”,
“raw”: {},
“status”: {
“code”: 500,
“text”: “Internal Server Error”
},
“headers”: {
“Content-Length”: “27”,
“Content-Type”: “text/html”,
“Date”: “Thu, 20 Feb 2020 13:03:08 GMT”,
“Server”: “0.0.0.0”,
“Vary”: “Cookie”,
“X-Frame-Options”: “SAMEORIGIN”
},
“entity”: “Server Error (500)”}
```

### Steps to reproduce

…

### Context

At least one user was using  v0.13.1 on Windows 10

**Comment by jamalex** [comment]
Getting a 500 on basic endpoints like login and deviceinfo suggests to me a locked or otherwise problematic database. It would be a huge help to get a copy of the log files (to see a traceback underlying the 500's), and maybe also of the databases, especially if the issue persists across a server restart (should we suggest a confidential channel for sharing them?)

Otherwise, the only thing that I see that interacts with content loading in the deviceinfo endpoint is the checking of free space: 
https://github.com/learningequality/kolibri/blob/release-v0.13.x/kolibri/core/device/api.py#L99

Could this be related to the 32-bit large int issues on RACHEL? Guessing most of these people wouldn't be using 32-bit, though. May be worth asking.

What were the content import changes happened in 0.13? Auto-resume, and the job batching? Interesting that one user mentioned it only happens when they queue multiple things -- does that suggest something with iceqube?

**Comment by indirectlylit** [comment]
It's possibly a locking issue similar to that described here:

https://github.com/learningequality/kolibri/issues/6502#issuecomment-586422052

**Comment by lyw07** [comment]
I think [Thread 1443](https://community.learningequality.org/t/import-via-online-error-100-downloaded-but-still-incomplete-error/1443) and [Thread 1400](https://community.learningequality.org/t/downloading-task-is-not-completing-its-stuck-at-100/1400 ) are the same issue. The user reported 1400 first, and I suggested an upgrade to 0.13.1. The user then reported 1443 after upgrading to 0.13.1 and continuing to see the issue.

**Comment by indirectlylit** [comment]
logs from thread 1456, with database locking:

[kolibri.txt](https://github.com/learningequality/kolibri/files/4257287/kolibri.txt)

**Comment by indirectlylit** [comment]
thanks @lyw07 I've edited the description and your comment to update links to threads

**Comment by jamalex** [comment]
There are several places the `db_task_write_lock` is used -- it shouldn't directly relate to a sqlite "database is locked" issue (different sort of lock, I believe -- especially given the error is being raised on changes to the primary database, not the task database), but... maybe there's a lockfile-induced deadlock that happens in the midst of a write transaction on the main DB, so that when another request comes in, the main DB is locked?

**Comment by indirectlylit** [comment]
Some information that I believe to be factual based on a conversation with @rtibbles:

1. Any concurrent attempts to write to the DB (e.g. from multiple processes or threads) will fail with a `sqlite3.OperationalError: database is locked` error. When triggered by an HTTP request, this gives `500` error like those seen above
2. Prior to 0.13, we saw these errors in some edge cases but for the most part Kolibri was single-threaded and they were avoided
3. In 0.13.0, we added the ability for multiple threads to access the DB in parallel in order to support the new import/export workflows
   * To prevent `database is locked` errors, we added a new reentrant write lock implemented using [`DiskCache`](http://www.grantjenks.com/docs/diskcache/)
   * However, we did _not_ apply the lock to writes triggered via HTTP requests, only to background tasks like import/export. This means that it is currently _expected_ that we will occasionally see `500` errors like those above

Some possible clues:

1. It is _possible_ that a change related to fixing a "too many variables" error during an mptt descendant query in 0.13.1 caused the final annotation phase of the import to take much longer. Users get tired of waiting, try something else, and then get the `500` errors we are seeing above. _However_ it's not clear if this is true because we had at least one report of hanging on 100% in 0.13.0
2. All reports of hanging hanging on 100% were reported in Windows 10. Another possibility is that DB writes during annotation are somehow hanging specifically on Windows 10. This might be related to the lock, or it might be independent of it.

To test:

* Can we reproduce in Windows 10?
* Was there a regression in our mptt descendant query during 0.13.1?

To do in a future release:

* Add locking to _all_ DB write access, to prevent DB Locked errors
* Ensure that no DB writes can take an indefinite amount of time: they should always be batched to allow other concurrent operations to have occasional write access
* If there are operation that require long-running, atomic write access, we need to communicate that the server is temporarily unavailable to end users

**Comment by rtibbles** [comment]
> It is possible that a change related to fixing a "too many variables" error during an mptt descendant query in 0.13.1 caused the final annotation phase of the import to take much longer. Users get tired of waiting, try something else, and then get the 500 errors we are seeing above. However it's not clear if this is true because we had at least one report of hanging on 100% in 0.13.0

Given the reports in 0.13.0 - I think it's also quite possible that it is the query itself that is problematic, rather than how we generate it (so the fact that we changed how we generate it to avoid too many SQL Variables errors might be a red herring). The query might simply be too complex, and hence taking a very long time, resulting in the seemingly never ending write lock on the DB.

**Comment by jamalex** [comment]
> 1. Any concurrent attempts to write to the DB (e.g. from multiple processes or threads) will fail with a `sqlite3.OperationalError: database is locked` error. When triggered by an HTTP request, this gives `500` error like those seen above

I think that description actually matches the [`SQLITE_BUSY`](https://www.sqlite.org/rescode.html#busy) response, which is the one that is "avoided" by setting a a long timeout. [`SQLITE_LOCKED`](https://www.sqlite.org/rescode.html#locked) seems to be a different beast, and is about incompatible operations happening over a _single connection_, in the _same_ process or thread.

>SQLITE_BUSY means that another database connection (probably in another process) is using the database in a way that prevents you from using it. SQLITE_LOCKED means the source of contention is internal and comes from the same database connection that received the SQLITE_LOCKED error.

So it's not just a standard concurrency issue, since every worker thread in Django should be given its own database connection. My guess is that it's some sort of interaction between Django and SQLAlchemy, or related to our use of the `ATTACH DATABASE` command for content databases.

**Comment by jamalex** [comment]
Hmm, yeah, the Django docs say something different than the sqlite docs, though:
>This error means that one thread or process has an exclusive lock on the database connection and another thread timed out waiting for the lock the be released.

https://docs.djangoproject.com/en/3.0/ref/databases/#database-is-locked-errors
