### ISSUE TITLE
pre-commit hooks interfere with in-progress commit dev workflows

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6607]
### Observed behavior

When working locally, git is a powerful tool for storing in-progress work. It's often desirable to commit changes that are not yet complete, even if there are bugs or formatting issues.

Pre-commit hooks impede a developer's ability to use git as a way to save in-progress work.

It's possible to do with `git commit --no-verify`, but this is a hard command to remember and again impedes the flow of the developer's work, especially because it's not available from most git GUIs.

### Expected behavior

Pre-commit should not get in the way of developer's workflow.

The developer, and not the linter, ought to be in control of what is allowed to be committed in local, unshared working branches.

### User-facing consequences

Certain kinds of dev workflows are impeded

### Context

0.13.1

**Comment by benjaoming** [comment]
If `git commit --no-verify` is too hard to remember, one can always create an alias.

> Certain kinds of dev workflows are impeded

To fix this GUI issue or feel motivated to fix it, I think the kind of dev workflow has to be explained.. and then scrutinized :)

**Comment by indirectlylit** [comment]
Please don't assert your own preferences for development workflows and say that others ought to be scrutinized and explained.

People should be able to use their favorite dev tools, and also store in-progress commits in git. Pre-commit impedes both of these workflows.

The basic solution is to recommend disabling pre-commit, which is what I do.

In my case, I use [GitUp](https://gitup.co/), an incredibly powerful git client that supports neither using the current Python virtualenv, nor `--no-verify` because these are both esoteric needs for a git client.

**Comment by benjaoming** [comment]
> Please don't assert your own preferences for development workflows and say that others ought to be scrutinized and explained.

I'm not.

**Comment by benjaoming** [comment]
If we want to work around pre-commit hooks, then we are asking for something that most other open source projects wouldn't do. I think the general assumption out there is that pre-commit is a good convention and that the git hooks just work.

I haven't heard of projects that have done special things for clients that cannot accommodate pre-commit, but if there is inspiration to share from similar issue reports, that would be very helpful?

Research: If the pre-commit githook doesn't work because the git client cannot run inside a virtual environment with the dev requirement, have you tried to set a PYTHONPATH environment manually to see if that works? This could be a good start.

Solution 1, the quick one: We can work around it all because now we have a 1:1 implementation in CI. So this means we could agree that disabling/not running pre-commit hooks can actually be fine.

Solution 2, the quirk: We can make a pre-commit hook that fails silently if it can detect that it's running from inside a known Git client. This way, the user can still go back to her command line and still enjoy pre-commit without having to manually switching the hook on/off.

Solution 3, go for glory: We write our own git hook that can work inside GitUp, switching on a virtualenv and installing pre-commit on the fly. Then we can add this in Getting Started instruction as a note: "If you do not use git from command line ..."

**Comment by benjaoming** [comment]
> The basic solution is to recommend disabling pre-commit, which is what I do.

I also agree with this. So maybe that's the solution and someone can add additional support for pre-commit in GitUp if they find the benefit?

**Comment by indirectlylit** [comment]
[Best practice in git](https://sethrobertson.github.io/GitBestPractices/) is to commit early and often and pre-commit inherently works against this. Coding standards are better enforced by other tools including:

* server-side checks
* editor tooling
* dev server tooling

I agree with your PR above and might even suggest we modify it to recommend only installing `pre-commit` if you find the three options above don't work for you.

**Comment by benjaoming** [comment]
> pre-commit inherently works against this

You can install it as pre-push or whichever local hook of your preference.

https://pre-commit.com/#pre-commit-install

> Best practice in git is to commit early and often

I don't do that? I use stashing quite a lot, though.

**Comment by indirectlylit** [comment]
If that works for you then that's fine, but there are [more effective strategies](https://softwareengineering.stackexchange.com/questions/255165/is-using-git-stash-as-a-workflow-an-antipattern) for saving in-progress work using git
