### ISSUE TITLE
African Storybook on the iPad2s does not work anymore

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#6624]
### Observed behavior
When using kolibri in iPad2s (limited to iOS 9.3.5)
The maximize button no longer works, nor does the page turn feature, the back arrow to on the page to return to the folders does not work and the page reloads following an error with Safari reporting “A problem occurred with this webpage so it was reloaded.” Following the reload, there is not improvement in behavior of the page.

The web page crashes after some time and is non-responsive otherwise (only once an ASb content is loaded)
It works fine on later versions of iOS. Also, I discovered one strange thing. I tried it out on an iPad2 that has only iOS 7.7 installed. ASb worked except the  cover page of the book does not load completely. However every other page loads find and the controls work fine also

### Expected behavior
ASb worked in previous versions of Kolibri in this devices using this IOS  version

### User-facing consequences
Using ASb is not possible

### Errors and logs
Here’s the errors in Web Inspector:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (2_css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (3_css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (right.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (left.png, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (NotoSans.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (NotoSansEthiopic-Regular.ttf, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (NotoSansEthiopic-Bold.ttf, line 0)

```

### Context
Reported by Chris Jackson
Using kolibri 0.13.0 & 0.13.1 on a Raspberry Pi server
Clients are the iPad2s (limited to iOS 9.3.5)

**Comment by indirectlylit** [comment]
likely a regression from https://github.com/learningequality/kolibri/pull/6268

**Comment by benjaoming** [comment]
* Ruling out that this is a cache error
* Re: List of 404 errors: These errors are on all systems.

Found this traceback on iOS 8 Safari to investigate:

```
TypeError: undefined is not an object (evaluating 't.content.children[0]')
(anonymous function) @ hashiframe-28bd5b9….js:1
map @ [native code]:1
b @ hashiframe-28bd5b9….js:1
g @ hashiframe-28bd5b9….js:1
```

[Edit: Updated the traceback]

Because of issues on Browserstack, I cannot re-run this with a debuggable development build of our assets.

**Comment by indirectlylit** [comment]
You might be running into this: https://github.com/learningequality/kolibri/issues/4826

**Comment by indirectlylit** [comment]
you might be able to use [ngrok](https://ngrok.com/) to expose your dev server in a way that browserstack can handle

**Comment by benjaoming** [comment]
@indirectlylit yes it's what I do already with localhost.run -- I think my **production** assets are available just fine to the Browserstack instances, it's a very varied experience between different iOS and Safari versions.

[Edit: production assets are available, as development assets won't work due to WDS, additional port forwarding and hard-coding of `localhost`]

I'll try to investigate further tomorrow, hoping that their Dev Tools stop 502'ing.

Things are broken en different ways on different versions of iOS/Safari.

Running Safari on iOS 9 for iPhone 6, and the result is similar to iOS 9.3 on iPod 2 -- but in this case, I get the web page reloaded (displaying the item correctly), however unresponsive. It keeps reloading automatically every now and then until it crashes.. as described in the PR.

![image](https://user-images.githubusercontent.com/374612/77471205-2a844680-6e12-11ea-9b46-c24cf5128a9d.png)

**Comment by benjaoming** [comment]
Safari 8 on iOS 8. This time, running with development JS assets, I suppose that `hashiframe` only is included as a minified version, so it's hard to trace `TypeError: undefined is not an object (evaluating 't.content.children[0]')`.

![image](https://user-images.githubusercontent.com/374612/77524473-b08ea480-6e87-11ea-900d-6387262eddd2.png)

**Comment by benjaoming** [comment]
By chance, I provoked a very similar case, but on all browsers: The African Story Book item showing up fine, but the buttons are unresponsive, and there is a `$$ is undefined` error. It turns out that `hashiframe-fdf6b89fc1e09fe9faa9.js` is not found, an asset that is built but needs to be in a served location. Running `kolibri manage collectstatic` fixed the issue:

![image](https://user-images.githubusercontent.com/374612/77536914-77f9c580-6e9d-11ea-801f-430d3d7313ee.png)

So in lack of better options, would be nice to run `collectstatic` on the affected server.

I stumbled upon a real iPhone 6 with Safari 11, and I get similar results as well: No arrows show up for page next/previous, but changing the page by swipe and horizontal scrollbar works.

Reproducible by loading http://kolibridemo.learningequality.org/en/learn/#/topics/c/9fcded2bda9050109defb09e64e83297 directly on iPhone 6 w/ Safari 11.

There is a set of 404s while loading assets, but these are exactly the same 404s that occur when loading in a Firefox instance w/o any symptoms.

**Comment by benjaoming** [comment]
Okay so here's my suggestion for reproducing the issue.

### Minimal case

* Use Browserstack's Safari on iOS 9 for iPhone 6S _or_ Safari on iOS 9 for iPhone 6S Plus
* The Dev Tools on Browserstack are very buggy, so wait around for up to several minutes before the Web Inspector panel actually shows anything.. otherwise, it'll say to reload the session (which you shouldn't). I think I had more luck with the Dev Tools with the browser extension switched off.
* Navigate to `http://kolibridemo.learningequality.org/en/learn/#/topics/c/9fcded2bda9050109defb09e64e83297`

### Development version

Unfortunately, I haven't had luck forwarding the 3000-3010 port intervals to Browserstack, nor making its local network forwarding work with the Browserstack browser extension. Hence, I can't make development version assets work on a remote connection.

* Run `yarn run devserver`, check that it works locally
* Run ngrok, forwardding multiple ports
* Load up your external ngrok address in Browserstack.

**Comment by benjaoming** [comment]
Here's data from Browserstack Dev Tools, which unfortunately wipes the Console log every few seconds when Safari 9 reloads, even with persistent logging enabled. I don't see anything useful in the traceback at this stage :(

![image](https://user-images.githubusercontent.com/374612/77547839-0118f880-6eae-11ea-9795-6002d7c09122.png)

**Comment by kollivier** [comment]
I suspect the hashiframe issue is caused by the `replaceScript` trick relying on some HTML or JS support that older versions of Safari don't have. 

I'll try to look into fixing that once I'm done with current tasks, but I also think it may be a good time to introduce a way to mark content as not needing Hashi. Several of our existing content sources pre-date Hashi and don't use its features, and it would be nice to not have to worry about Hashi changes breaking compatibility for content that doesn't even use it.
