### ISSUE TITLE
Kolibri does not report to the user that disk is full during channel import.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#6697]
### Observed behavior
When importing a channel from Kolibri Studio (online)/Internet (example: Khan Academy English), Kolibri does not report to the user if the disk is full.  This causes the import to "freeze", which eventually makes Kolibri unresponsive.

On a similar note, Kolibri also does not prompt the user that the size of the channel to import is larger than the available disk space.

#### Screenshots

I started the import the day before and when I came back to the page the following morning: Kolibri "froze" at 80% during my import.
<img width="1013" alt="Screenshot 2020-03-25 11 32 33" src="https://user-images.githubusercontent.com/175580/77608217-8a383a00-6f57-11ea-8333-90a701e8b91a.png">

After I reloaded the page many times, I saw this.
<img width="1552" alt="Screenshot 2020-03-25 13 34 56" src="https://user-images.githubusercontent.com/175580/77608222-8efcee00-6f57-11ea-919e-45e26f615a70.png">

Today, I re-created a VM with a 20GB disk and tried to import channels with total size greater than the available disk space but Kolibri did not prompt me of an issue.
<img width="1431" alt="Screenshot 2020-03-26 11 52 28" src="https://user-images.githubusercontent.com/175580/77608590-a8eb0080-6f58-11ea-876f-569ef8b3760b.png">

Tried to import channels with 20GB+ in size twice to make sure but Kolibri still went on with the import.
<img width="1435" alt="Screenshot 2020-03-26 11 53 29" src="https://user-images.githubusercontent.com/175580/77608651-d33cbe00-6f58-11ea-913e-88afdadac78b.png">

### Expected behavior
User must be notified when the disk is (almost) full during a channel import and then stop the import process.  Kolibri then, must still be working and shouldn't crash.

Another expectation is to notify the user that the channel to be imported is too big for the available/free disk space, to prevent Kolibri crashes like this.

### User-facing consequences
Kolibri stops working when the import process is interrupted because the disk is already full.

### Errors and logs

From `~/.kolibri/logs/kolibri.txt`:
```
...
ERROR 2020-03-24 03:23:37,985 importcontent An error occurred during content import: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
INFO 2020-03-24 03:23:38,801 importcontent Waiting for 30 seconds before retrying import: https://studio.learningequality.org/content/storage/9/9/99441f1d6debd2a8870a845e22de7525.vtt
ERROR 2020-03-24 12:58:58,202 importcontent An error occurred during content import: [Errno 28] No space left on device
INFO 2020-03-24 12:58:58,568 annotation Setting availability to True of 55222 LocalFile objects based on passed in checksums
ERROR 2020-03-24 12:59:00,639 worker Job a29c1ebc46c3452f9b9d61cc3aaf82a4 raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/base.py", line 724, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/lib/python3/dist-packages/kolibri/dist/sqlalchemy/engine/default.py", line 462, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: database or disk is full
...
```

### Steps to reproduce

1. Create an Ubuntu Server 16.04.6 Virtual Machine with a 20GB disk space.
1. Download the `.deb` Ubuntu installer for [Kolibri v0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1) and install following the [instructions here](https://kolibri.readthedocs.io/en/latest/install/ubuntu-debian.html#install-from-a-deb-file).
1. Connect to the VM using a web browser and setup Kolibri.  Example: http://192.168.1.10:8080/
1. Import Khan Academy English channel content via Kolibri Studio (online).  Select content with total size larger than the VM disk free space (>= 19GB).  Example: `Math` and `Science` nodes currently total to 19GB.

**Notes**

1. Content size of 19GB is okay because Ubuntu Server 16.04.6 and Kolibri uses about 2GB of data, which leaves about 18GB of free space in the 20GB VM disk.
1. For faster testing, use a smaller disk size for your VM like 4GB.  Just make sure that the channel size exceeds the free space of roughly >= 2GB.

### Context
 * Kolibri version: [0.13.2-beta1](https://github.com/learningequality/kolibri/releases/tag/v0.13.2-beta1)
 * Operating system: Ubuntu 16.04.6 LTS on a Virtual Machine
 * Browser: Safari v13.0.5 (web browser used to access Kolibri)

**Comment by indirectlylit** [comment]
A more specific example of the more general note in https://github.com/learningequality/kolibri/issues/6686

**Comment by MasakoOllivier** [comment]
I saw the same issue on Android devices. (I used a cell phone and a tablet.) 

When I started importing 10 GB resource, Kolibri didn't warn me that I didn't have enough free space (I knew both devices had only 9GB of free space). It kept importing on both devices until they were pretty much out of free space. It seems that when a cell phone doesn't have much free space left, it can have problems sending emails. (I couldn't send pictures from it until I clear the data.)

**Comment by riddhiavlani** [comment]
Here is how we can address it:

Given that the user is trying to import a channel that is bigger than the available disk space; After selecting the resources, if the user clicks on import, then a modal window could appear informing the user that the channel cannot be imported because the import size (eg. 10GB) is more than the available disk space (eg. 9GB). And maybe a call to action button to deselect resources.    

I am assuming that when there is no partial import happening, right?

Something like this:
![Not enough disk space to import (1).png](https://images.zenhubusercontent.com/6054cbf6e1e4e5d5abc9e647/fca24bbd-6a4a-4156-9095-071c788500a4)

**Comment by indirectlylit** [comment]
That looks good! There are a couple other things I would consider factoring in:

1. Some indicator of available disk space that's visible even if you aren't hitting the limit could be useful. This can help people plan for the future.
2. There's an edge-case where the user may have had sufficient disk space when starting the import, but due to external factors the disk space still runs out while doing the import. For example – if they download very large files or install other applications at the same that Kolibri import is running

**Comment by jamalex** [comment]
@rtibbles has noted that a message like that _should_ already appear when clicking import and space is insufficient:
https://github.com/learningequality/kolibri/blob/02fc882b827a1c822d9d5863d37c0a9e1cd5ab61/kolibri/plugins/device/assets/src/views/AvailableChannelsPage/index.vue#L449

So it seems like either some glue broke and it isn't showing for some reason, or maybe the space estimation is off somehow. One way the space estimation might be off is if the content to be loaded has many many very small files (smaller than the disk block size), so that the actual space consumed on disk is larger than the sum of the bytes of each individual file. The proper way to address that specific possibility would be to look at the target disk block size and round up the source file sizes to the nearest block size multiple.

@rtibbles also suggested that this checking logic may not have been activated on the bulk channel import, so that's something else to confirm.

>the user may have had sufficient disk space when starting the import, but due to external factors the disk space still runs out while doing the import

This is a really important possibility to consider -- so we should probably add checks during the import process itself and stop if storage is getting low.

A related thing I've advocated for in the past is being able to set a "minimum free space %" (probably as a device setting, and defaulting to... 5%? 10%?), and then we'd use that both when starting an import and during the import process for deciding when to stop if we're nearing the threshold.
