### ISSUE TITLE
Question: Channel IDs

### ISSUE THREAD

**Issue by tim-moody** [learningequality/kolibri#6766]
Will

`KOLIBRI_HOME=<my location> kolibri manage listchannels `

return the same set of ids for channels whenever and wherever run? That is do channels always have the same id?

At present I get:

INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Invoking command listchannels
Pos       ID                                      Name
---       --                                      ----
1         1ceff53605e55bef987d88e0908658c5        Khan Academy (English)
2         197934f144305350b5820c7c4dd8e194        PhET Interactive Simulations (English)
3         c1f2b7e6ac9f56a2bb44fa7a48b66dce        Khan Academy (Español)

**Comment by indirectlylit** [comment]
Yes, the IDs of public channels will remain constant across Kolibri installations that have the same channels installed.

Just a caution that, the output of the `listchannels` command might change in a future version to use "channel tokens" instead of or in addition to channel IDs. These are the shorter, more human-readable strings that are provided by Studio.
