### ISSUE TITLE
include user database IDs in facility CSV imports and exports

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6823]
### Observed behavior

It is desirable to be able to change usernames during CSV export/import, but this is currently not possible.

### Expected behavior

* UUID of user should be included during export
* If the UUID does not already exist, that user should be skipped with an error
* If the UUID is left blank, that user should be created
* Duplicate usernames are always errors

### User-facing consequences

Cannot perform bulk updates of usernames using CSV export/import

### Context

0.14.0

**Comment by jredrejo** [comment]
@indirectlylit  If we change to user uuid instead of the username as source of trust (what seems logical from a technical point of view, but less friendly for the users) why can't we allow duplicate usernames? it should not be a problem anymore. If not duplicate per facility to avoid problems with user logins, duplicate per device should not be a problem.

**Comment by indirectlylit** [comment]
The import is scoped to a single facility, and we enforce unique usernames within a facility to prevent login issues as you say.

Duplicates in different facilities would not be an error.
