### ISSUE TITLE
testing optimized static file loading and home directory

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6839]
### Observed behavior

From @jamalex - https://github.com/learningequality/kolibri/pull/6805#issuecomment-622171202

> Main thing I raised that would be good to test is switching KOLIBRI_HOME to be on another filesystem (than where the Kolibri Python package has been installed), especially if that's a different filesystem type (e.g. FAT/NTFS) and making sure that works too.

### Context

0.13.2

**Comment by lyw07** [comment]
in our `kolibri-dev` server, the symlinks of static files break the server because the infrastructure of `kolibri-dev` separates Kolibri app and Nginx into two containers(servers), while the two containers have access to a shared filesystem containing KOLIBRI_HOME. In this case, other than reading from the shared filesystem, the Nginx container needs to read from the Kolibri app container's disk as well, which is not accessible by the Nginx container.

the diagram may help explain the infrastructure.
<img width="589" alt="Screen Shot 2020-05-09 at 12 36 07 PM" src="https://user-images.githubusercontent.com/19424916/81596656-4e2b2e00-9379-11ea-90af-8b657e673b0d.png">


so my current workaround is:

1. start kolibri so that we will run the update process
2. stop kolibri
3. run collectstatic with no `link` option to copy the static files to KOLIBRI_HOME
4. start kolibri again (I'm starting kolibri twice because I need kolibri to run in the foreground...)

I'm wondering if there is a better approach here to work around this. If there are any suggestions on optimizing this workaround, that will be great! thank you!!

Also, for the setup mentioned by Jamie, where we have `kolibri-server` that runs Kolibri and Nginx on the same server, I think the symlinks should work well even if we have another filesystem storing KOLIBRI_HOME.

**Comment by rtibbles** [comment]
Right - might be good to allow this behaviour to be better conditionalized, and allow it to be toggled off?

**Comment by lyw07** [comment]
yes, that will be great!
so do you mean something like `kolibri start --static-symlink=true/false`?

**Comment by rtibbles** [comment]
I think probably doing it as an option and so it could get set as an envvar (rather than overloading the command line).

**Comment by lyw07** [comment]
ah makes sense to me. thank you! I can work on this later ~~this week~~ :)

**Comment by indirectlylit** [comment]
just merged your options.ini PR. Anything else need to be done here?

**Comment by lyw07** [comment]
Yes, I think we can close it. Other than my PR, I also tested the scenario described in the issue -- having Kolibri_HOME on a FAT file system, and it worked well.
