### ISSUE TITLE
error message does not display row number correctly

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6850]
### Observed behavior

Currently shows this:

![image](https://user-images.githubusercontent.com/2367265/81125301-9a472000-8eec-11ea-95f5-619818a4c4b2.png)

### Expected behavior

The simpler fix:

| Row number | Error column | Current value | Error |
|--|--|--|--|
| 3  | Password (PASSWORD) | `*` | The password field is required. To leave the password unchanged in existing users, insert an asterisk (*) |

If we also want to show the username, could do something like this:

| Row number | Username | Error column | Current value | Error |
|--|--|--|--|--|
| 3 | `some_user` | Password (PASSWORD) | `*` | The password field is required. To leave the password unchanged in existing users, insert an asterisk (*) |

### User-facing consequences

slightly confusing error output

### Steps to reproduce

create a new user during CSV import, and set the password to `*`

### Context

pf-mvp

**Comment by jredrejo** [comment]
@indirectlylit there is a problem with this part. 
Validation is done in two phases:
1- csv validation (fast), row numbers are known, and invalid rows are discarded
2- database validation (slower): row numbers might be wrong if rows have been discarded in the csv validation 
For the password error message, validation is done at step 2, because at the step 1 we don't know yet if the user exists in the database or not. So, the row number there could be wrong.

I see several alternatives:
-  adding another value to the error message: username, so in these cases instead of saying row:x, we say username:x. This would require changes in the frontend too
- refactoring the backend code, to keep all the lines in phase 2, so they would be database validated even if they are wrong. The code would be slower but the row numbers would be correct and not changes are needed in the frontend
- refactoring the backend code with some hack to keep the row numbers without validating against the db rows that are known as incorrect.

I'll try the third alternative, but not sure if the result will be clean, so I'd like to know your opinion about the other two options in case the third is too dirty.
