### ISSUE TITLE
Clicking the volume up/down buttons on Android functions to close the app

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#6890]
### Observed behavior

First click: user gets a warning:
![Screenshot_20200516-111235_Kolibri](https://user-images.githubusercontent.com/6668144/82358068-d4b7bf00-99ba-11ea-9090-33ff64a06856.jpg)

On second click, the app closes

### Expected behavior

Volume buttons should control volume

### User-facing consequences

Bad vibes

### Context

Kolibri version: 0.13.3
OS: Android

**Comment by indirectlylit** [comment]
cc @kollivier mind taking a look at this?

**Comment by micahscopes** [comment]
Okay so I just tested this and found that for me, the message pops up but if I actually click the volume button again, it doesn't really close Kolibri.  @jtamiace in your experience, it sounds like the app actually did close?

**Comment by micahscopes** [comment]
Ah, I figured out why this is happening.  There's a bug in python-for-android.  Working on it now.

**Comment by nucleogenesis** [comment]
Notes from Kolibri Tactical today:

Per @kollivier - we need to change the build process to clean out the existing build if the Android App wrapper dealy - not super familiar how to do that on the docker side. Can probably now - since it's disconnected from main Kolibri pipeline - it's probably okay to add a clean command to each build.

Per @DXCanas - can easily do this but questions about ideal way to handle this automatically.

Per @rtibbles & @DXCanas - no need for a clean each time so would hate to undo time optimizations every time.

**Comment by DXCanas** [comment]
Good news is that this was really easy to do - the distribution that p4a generates lives in a subfolder inside of `~/.local`, which is bound at runtime to a Docker volume named `p4a_cache` (suffixed with architecture, which is new). 

No longer caching could be a reasonable solution, as the Android build runs much less often now. The main reason it's cached this way is that p4a downloads things and builds the distribution at runtime, with no command (as far as I know) that we can run to have that happen during build time. If I'm wrong, and we can have the distribution build at build time instead, then we could just rely on the Docker cache to wipe itself whenever there's a change to Kevin's fork of p4a, which is already a  built in feature.

All this to say, the problem should be fixed @micahscopes - have you been able to test it?

**Comment by micahscopes** [comment]
@DXCanas thank you!

We tested it at the bug bash on Thursday and it was fixed :relieved:
