### ISSUE TITLE
router errors and warnings in setup wizard 

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7068]
### Observed behavior

![image](https://user-images.githubusercontent.com/2367265/84841132-53be0880-aff6-11ea-8ffc-640eb88c771e.png)

### Errors and logs

```
router.js:51 [vue-router] Named Route 'UngroupedSetupSteps' has a default child route. When navigating to this named route (:to="{name: 'UngroupedSetupSteps'"), the default child route will not be rendered. Remove the name from this route and use the name of the default child route for named links instead.
SetupWizardIndex.vue:53 Uncaught (in promise) Error: Avoided redundant navigation to current location: "/".
    at HashHistory.confirmTransition (vue-router.esm.js:2185)
    at HashHistory.transitionTo (vue-router.esm.js:2126)
    at HashHistory.replace (vue-router.esm.js:2601)
    at vue-router.esm.js:2916
    at new Promise (<anonymous>)
    at VueRouter.replace (vue-router.esm.js:2915)
    at Vue.beforeMount (SetupWizardIndex.vue:53)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854)
```

### Steps to reproduce

open setup wizard

### Context
0.14

**Comment by jonboiser** [comment]
This is caused by the router.js wrapper assigning the component name as a the route name. E.g. The parent route is given a `name` of `UngroupedSetupSteps`, even though it's not set in the `routes` array.

In the SetupWizard, we don't don't make the mistake of using `to: {name: 'UngroupedSetupSteps'}`, so we can ignore the warnings for now.
