### ISSUE TITLE
error page formatting

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7098]
### Observed behavior

copy button missing top margin, and clipped shadows:

![image](https://user-images.githubusercontent.com/2367265/85152577-087c4380-b20a-11ea-8de0-8e3f7c411910.png)

observed in https://github.com/learningequality/kolibri/issues/7097

### Expected behavior

proper formatting as seen in 0.13

### User-facing consequences

styling regression

### Steps to reproduce

manually force an error

### Context

0.14 beta 2

**Comment by MisRob** [comment]
Both issues are caused by removing `margin` from buttons.scss ([0.13](https://github.com/learningequality/kolibri/blob/release-v0.13.x/packages/kolibri-components/src/buttons-and-links/buttons.scss#L13) vs [kolibri-design-system](https://github.com/MisRob/kolibri-design-system/blob/develop/lib/buttons-and-links/buttons.scss)). @nucleogenesis or @indirectlylit was that change intentional?

If yes, I can solve this issue by adding

```
:style="{ marginTop: '8px', marginBottom: '8px' }"
```

to [TechnicalTextBlock `KButton`](https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/core/assets/src/views/AppError/TechnicalTextBlock.vue#L20).

**Comment by indirectlylit** [comment]
sorry for the delayed response and thanks for the fix
