### ISSUE TITLE
inconsistent learner enrollment issues with multiple facilities

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7138]
### Observed behavior

observed by @carinediaz 

> I created my Learners and when I tried to enrolled them into my class, Kolibri wasn't finding them and I realized I was somehow taken to Facility 2, when I created my class and all my users under Demo Facility

corroborated by @nucleogenesis 

> I second this - I don't know if I marked this in the last bug bash or not but this is something I've encountered.
> 
> Like if I start creating learners in a Facility that is not the first one that was created - then after one or two learners being created the third one is created into a that facility (the one I made during provisioning)
> 
> Not easy or consistently replicated though 😕

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
I believe that the problem is that the link to this button is hard-coded and "forgets" the Facility ID in the URL that's used to help the app remember what facility the admin is working with

![image](https://user-images.githubusercontent.com/10248067/85441264-c1f95280-b543-11ea-9e49-17726273344e.png)

So if you're creating and enrolling learners, click the "All classes" link, and do more work, you may end up enrolling learners in the wrong classroom.

**Comment by jonboiser** [comment]
Just found that the same issue is in the new bulk-import-by-CSV workflow, so I'll need to apply the fix in #7166 to those pages as well.
