### ISSUE TITLE
On Facility > Data page, sync interface needs to allow "P2P" sync

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7153]
### Observed behavior

reported by @jonboiser 

On Facility > Data page, my facility has been synced, but the "register" button is still enabled

![image](https://user-images.githubusercontent.com/2367265/85485777-4072e600-b57e-11ea-9719-ee502280051e.png)

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
I think what happened here is that I imported "here" via P2P-facility import, so this facility has a `last_synced` timestamp, but was not actually registered to KDP. So I'm not sure this is a bug, since we technically do allow this sequence

1. Import a Facility from a non-KDP peer
1. Register (on the computer from Step 1) the Facility to KDP
1. Sync that facility with KDP (or any other peer with that facility)

**Comment by jonboiser** [comment]
So it turns out we want the "Sync" button here to work the same as the "Sync" button the "Device > Facilities" page.

This means the "Sync" button should always be enabled, and have the same behavior

1. If the Facility is not registered, pressing sync opens modal that lists the available networ addresses.
1. Otherwise, go a step backwards where user can select between using KDP or P2P as a sync source.

The fix here is to move some of these Sync Components in the Device Plugin up to the core `syncComponentSet` thing and integrate it into the Facility page.
