### ISSUE TITLE
users go to Classes page by default even when not enrolled in a class

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7154]
### Observed behavior

e.g. an admin not enrolled in a class goes here when clicking on 'Learn'

![image](https://user-images.githubusercontent.com/2367265/85485903-8465eb00-b57e-11ea-9492-894f13e45dd3.png)

### Expected behavior

land on Channels instead

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
I have a feeling that this might be due to a race condition, because everything in this screenshot is indicating that this `handler` should have done that right thing and gone to "Channels":

1. The "Channels" and "Recommended" tab are visible, so `canAccessUnassignedContent` must be `true`
1. There are no classes cards, so `memberships.length > 0` must be false
1. Therefore, In the `ROOT` handler (below), we should have redirected to `TOPICS_ROOT` aka "Channels"

It's possible that because it's hard to predict the timing of when `handler`s get executed relative to other async code, that `!canAccessUnassignedContent` can evaluate to `true` (in spite of how the device is configured, etc.), causing the redirect to `ALL_CLASSES`

```
  {
    name: PageNames.ROOT,
    path: '/',
    handler: () => {
      const { memberships } = store.state;
      const { canAccessUnassignedContent } = store.getters;

      // If a registered user, go to Classes Page, else go to Content
      return router.replace({
        name:
          memberships.length > 0 || !canAccessUnassignedContent
            ? ClassesPageNames.ALL_CLASSES
            : PageNames.TOPICS_ROOT,
      });
    },
  },
```

I think the fix I'll try is to add a secondary guard inside the `AllClassesPage` to redirect back to the Channels page if:

1. `memberships.length === 0` and
1. `getters.canAccessUnassignedContent` is `true`
