### ISSUE TITLE
demo banner does not play nicely with login page updates

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7176]
### Observed behavior

banner state is not preserved and doesn't show at all on some pages

![2020-06-24 13 43 14](https://user-images.githubusercontent.com/2367265/85626318-ba0fe000-b621-11ea-9228-c8b7c07a869c.gif)

### Expected behavior

* banner should be visible on all sign-in pages
* banner 'closed' state should be persisted
* scroll position should not change

### Steps to reproduce

see beta site

### Context

0.14.0 beta 3

**Comment by jonboiser** [comment]
This is unusual-looking, but I don't think it's really critical since the demo server is not typically deployed with 2+ facilities . So, when visiting the URL, you will see the Demo Banner + the Usual Login screen.

Conversely, I'm not sure how many real-world multi-facility deployments will actually want to show the Demo Banner.

**Comment by indirectlylit** [comment]
> not typically deployed with 2+ servers

you mean 2+ facilities?

agree it's not critical, but would still be good to address in the course of the login flow refactor if possible
