### ISSUE TITLE
Update profile modal displays to super admin account created with setup wizard 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#7204]
### Observed behavior
_(Wouldn't even know this might be an issue if I hadn't been reviewing super admin Gherkins all past week :blush:)_

According to the [Gherkin scenario](https://github.com/learningequality/kolibri/blob/release-v0.13.x/integration_testing/features/learner/learner-profile-update-notification.feature#L22), this should not appear:

![Ubuntu16 04 (start)  Running  - Oracle VM VirtualBox_677](https://user-images.githubusercontent.com/1457929/85937605-68a76f80-b905-11ea-8f75-88ff846fa271.png)

### Expected behavior
No profile update modal for the super admin.

### User-facing consequences
Annoyed super admin.

### Errors and logs
…

### Steps to reproduce
1. Install Kolibri
2. Go through the setup wizard
3. Go to Learn 

### Context
 * Kolibri version: 0.14.0b6, DEB installer
 * Operating system: Ubuntu 16.04
 * Browser: both Firefox and Chrome

**Comment by jonboiser** [comment]
In the Setup Wizard code, this looks intentional because we automatically set both gender and birth date to "not specified". So it's as if we've pressed "skip" for them on the Profile Update modal.

**Comment by jonboiser** [comment]
This is still happening with the Quick Start setup option, because the demographic fields aren't being saved on the FacilityUser model even though we've passed in the correct `DEFERRED` enum to the `DeviceProvision` endpoint.

I see now that it's probably because the `create_superuser` function here doesn't actually pass the demographic fields into the FacilityUser factory function https://github.com/learningequality/kolibri/blob/e4852df6c2acd95f062d944eb177f0564a4960c1/kolibri/core/device/utils.py#L78-L86

**Comment by rtibbles** [comment]
That seems the right diagnosis!

**Comment by radinamatic** [comment]
@jonboiser It's still unclear to me if this is an issue, or was supposed to happen...? :confused: 
Do I need to amend the Gherkin scenario?

**Comment by jonboiser** [comment]
The Gherkin scenario is correct, and we shouldn't be showing the "Update Profile" modal to superusers at all.
