### ISSUE TITLE
Breadcrumbs nav problem when starting from link inside channel

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#7315]
### Observed behavior

Step to reproduce
1. go to https://kolibri-beta.learningequality.org/km/learn/#/topics/t/6b3f3f468773514b91d305fcaeb87a00
2. click on channel name
3. I see content unavailable error page

<img width="849" alt="breadcrubs navigation bug" src="https://user-images.githubusercontent.com/163966/87608372-c392e200-c6cd-11ea-9bc4-fec134ad9e46.png">

confirm nav problem on aother channel too
1. go to https://kolibri-beta.learningequality.org/en/learn/#/topics/t/79bb64c653f347fc8584210e48bc9140
2. click on channel name 
3. I see content unavailable error page

### Expected behavior

3. Expected: navigate to channel root

### User-facing consequences

Navigation problems and possibly indicates some frontend page history state problem.

### Steps to reproduce

Note to trigger this issue must start navigation from a subtopic within a channel.
If you navigate to channel, then clock on topic, then click to subtopic, the breadcrumb links will work fine.

### Context

Kolibri 0.14.0b11  in Firefox and Chrome

**Comment by jonboiser** [comment]
My suspicion is that it might have something to do with this handler code

https://github.com/learningequality/kolibri/blob/1ab74fc5b5a907ada4592d8ab1f5897886058e19/kolibri/plugins/learn/assets/src/modules/topicsTree/handlers.js#L65-L70

I grepped `CONTENT_UNAVAILABLE` to see where in the code we might redirect to this page. Other places might be at play, but it seems plausible this is it because there might be some difference in the Vuex state within a topics page (where the link doesn't work) and the top-level channels list page (where the same link _does_ work)

**Comment by rtibbles** [comment]
Presumably we could put a break point in here in the code, and attempt to replicate to see if this line gets triggered to confirm this? Good sleuthing!

**Comment by nucleogenesis** [comment]
A "fix" --> https://github.com/learningequality/kolibri/commit/0baef4e644e462ed9ea65dc7227afd740d5b74f7

The issue is that whatever is being cached in the `__modelCache` on the `ContentNodeResource` includes only two of the fields `{ id, title }` but we need more than that (namely `channel_id`) to complete the `showTopicsTopic()` handler linked to by @jonboiser above.

So if we bypass the cache it works properly.

@rtibbles I dug a bit and could not see how/where/when the data being cached in being mapped somehow to a reduced structure - or why that would only happen when you enter the route from a direct link. Any thoughts?

**Comment by rtibbles** [comment]
Hrm, it sounds like the ancestors fetch is somehow overwriting the main ContentNodeResource cache - we probably didn't see this issue previously, because of the separation of ContentNodeSlimResource and ContentNodeResource, but since I eliminated the former, we are now seeing the issue.

**Comment by rtibbles** [comment]
At this point, we should probably remove most of the caching in the APIResource layer - content node stuff is already relying on browser caching so it wouldn't affect that, and I think in the case of most 'editable' interactions, we are already using the 'force' key because of issues like this.

**Comment by nucleogenesis** [comment]
> At this point, we should probably remove most of the caching in the APIResource layer - content node stuff is already relying on browser caching so it wouldn't affect that, and I think in the case of most 'editable' interactions, we are already using the 'force' key because of issues like this.

@rtibbles should this be a sweeping change of some kind - or should I apply this fix for the specific issue for now and create a separate issue for a future release to audit and improve our front-end caching?

**Comment by rtibbles** [comment]
Yes, I think your targeted fix is appropriate for now, I was just flagging future actions!

**Comment by jonboiser** [comment]
I just encountered this when clicking the "X" button on the PDF viewer, on dev but it seems stochastic/random (not sure if it always happens).

Viewing PDF from "Kolibri QA channel" in arabic

![image](https://user-images.githubusercontent.com/10248067/88227820-1109d480-cc23-11ea-9a6a-b3ef27808757.png)
