### ISSUE TITLE
font baseline issues with mixed latin/khmer script

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7318]
### Observed behavior

observed by @ivanistheone 

![image](https://user-images.githubusercontent.com/2367265/87699770-35107600-c74a-11ea-82a8-725c71aeff98.png)

noticed behavior is a bit different when the overall language changes:

![image](https://user-images.githubusercontent.com/2367265/87699935-6f7a1300-c74a-11ea-8b45-a461251f379e.png)

### Expected behavior

consistent baseline for text in mixed scripts

### User-facing consequences

awkward text reading

### Steps to reproduce

see https://kolibri-beta.learningequality.org/km/learn/#/topics/t/6b3f3f468773514b91d305fcaeb87a00

### Context

0.14 beta 10

**Comment by jonboiser** [comment]
With some recent changes to links in KDS, I think this issue might be a little less noticeable

![image](https://user-images.githubusercontent.com/10248067/97213551-fba2ca00-177e-11eb-99b0-bf2663767ca6.png)

![image](https://user-images.githubusercontent.com/10248067/97213827-65bb6f00-177f-11eb-990d-55dc32965b73.png)

The underlines do help a little to make the differences in vertical alignment less noticeable. The lack of Khmer characters in "Channel" are probably why it sticks out more before we had underlines.

I think I will consider this as a "wontfix" issue, because the solution I see doesn't seem desirable, where we would need to manually raise the baseline for Latin characters so, e.g. the "y" descender would be at the same level as the Khmmer descenders through hacks like using `@font-face` or manually manipulating the HTML through JS.

Lowering the Khmer baseline would not be a good idea because descenders would be completely covered by the underline.

**Comment by indirectlylit** [comment]
Seems reasonable to close this.

The issue may be with the upstream font files, if Khmer is somehow inconsistent with the other Noto fonts. If this were to be the case, updating the source font files might help using the `update-font-manifest` and `download-source-fonts` commands:

https://github.com/learningequality/kolibri/blob/42012dfb5423a09558758425ce3e1c97da8e379e/build_tools/i18n/fonts.py#L625-L628

However I tried this during the 0.14 release and it appeared that some of the more recently added fonts don't merge cleanly when generating subsets so I backed out the change.
