### ISSUE TITLE
ensure that quizzes and lessons are not modified when they reference missing content

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7327]
### Observed behavior

current behavior might be that quizzes and lessons might actually be modified, deleting the missing resource reference, if those lessons or quizzes are edited on a device without all the content

### Expected behavior

let's double-check the behavior and ensure that no data modification occurs

### User-facing consequences

data loss

### Steps to reproduce

* create a lesson or quiz on one device
* sync to another device which lacks the content
* edit lesson and quiz
* sync back and ensure that no references were deleted

### Context

0.14.0

**Comment by jonboiser** [comment]
There's a pretty good chance this does happen for Lessons because how we store lesson resources as a simple array of IDs and then replace-and-save the entire thing once the Coach begins the Manage Resources workflow.

But this would only happen if the Manage Resource workflows does some kind of immediate "cleanup" (e.g. remove IDs because they are not annotated as "available"). Otherwise, it might simply just leave those IDs alone since one cannot select/deselect those resources.

**Comment by jonboiser** [comment]
@rtibbles Mentioned that some filtering of the `Lesson.resources` array might be happening whenever it is updated due to some new validations that will not permit its entries (content node IDs) to be added to the array if they do not exist in the ContentNode table. 

The suggested fix was to remove this validation for now, but we need to make sure this doesn't end up breaking the frontends for lesson management if there are non-available IDs in the `resources` array.

**Comment by jonboiser** [comment]
Just confirmed that there is this validation on the `LessonSerializer`

https://github.com/learningequality/kolibri/blob/594f2f81cc67f1d79cc0480125b496a6265d5a2f/kolibri/core/lessons/serializers.py#L67-L88

This makes it seem like that rather than losing content, it might be impossible to save a Lesson if it is synced and some of the resources are missing.

One solution would be to remove this validation on the `resources` field on the model, but make the `resources` field on the serializer a computed one that filters for the available resources.

**Comment by rtibbles** [comment]
Have done some further investigation here, and the frontend does remove items that are not available if the items that are visible are reordered.

If you then try to manage resources when one is missing, a 404 fetching the resources results in breakage of the app.

**Comment by jonboiser** [comment]
Could we do something simple like disable the lesson editing stuff if there is a single missing resource? e.g. disable the "Manage resources" button and the "resource reordering" controls.

**Comment by jonboiser** [comment]
@rtibbles Aside from fixing the immediate front-end issues to support this scenario in the short-term, in the long term, do you think we should try to encode the resource-quiz/lesson linkage in a structured way? 

Earlier I think we didn't want to have to create an actual foreign key relationship between resources and quizzes/lessons (and create more of a DB overhead), but it might be the way to go to handle missing resources in a more robust way, instead of this quasi no-sql approach with the `contentnode_ids` array thing we have.

**Comment by rtibbles** [comment]
Yes - I think the long term solution is to turn quizzes and lessons into a kind of content, so a lesson would just become a special kind of topic. For quizzes, I think it would be best to bundle up all the required questions and save them as a new piece of content, rather than dynamically referencing them.

**Comment by jonboiser** [comment]
Cool, is there an issue for this? I think this change should be a prerequisite for #7325  so we can prevent having to re-write the missing content features if/when we make that change.

**Comment by rtibbles** [comment]
I think the time scale over which this will happen is going to be much longer than #7325 - and even with these changes, it is likely that we will allow much more partial synchronization of content metadata in the future, so the work for #7325 will still be useful.
