### ISSUE TITLE
sign-in cleanup issues

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7366]
### Observed behavior

| issue | screenshot |
|--|--|
| 'back' button doesn't work here | ![2020-07-23 08 09 59](https://user-images.githubusercontent.com/2367265/88303667-267f0d00-ccbc-11ea-927c-15d054393396.gif) |
| This should say "Go to home page" using the string from _AuthMessage.vue_ | ![image](https://user-images.githubusercontent.com/2367265/88303774-40205480-ccbc-11ea-83ea-1668718dd441.png) |
| spacing issue between arrow and link | ![image](https://user-images.githubusercontent.com/2367265/88304056-9b524700-ccbc-11ea-9ac6-c16af4e15171.png) |

### Context

0.14 beta 13

**Comment by nucleogenesis** [comment]
That arrow's spacing is fixed in https://github.com/learningequality/kolibri/pull/7360

Will include string fix and back-button fixes in same PR

**Comment by nucleogenesis** [comment]
@indirectlylit the back button issue is a bit complicated but basically, every KRouterLink is pushing to the history rather than replacing the route.

Issue in KDS: https://github.com/learningequality/kolibri-design-system/issues/85

Even when I tried it locally and played with that, the way history was stacked got really wonky going back and forth.

I'd consider it to be a bit of an edge case to some extent - and it is one that will take some time and probably discussion to resolve.

---

The other two items have been fixed.

Wrong string: https://github.com/learningequality/kolibri/pull/7406
Go back issue: https://github.com/learningequality/kolibri/pull/7360
