### ISSUE TITLE
On Safari/Mac App/Webkit, `KLabeledIcon` `width: 100%` rule does not take full width of parent, causing text to wrap

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7378]
### Observed behavior
Also occurs in user drop-down menu
![image](https://user-images.githubusercontent.com/2367265/88338850-d5880c80-cced-11ea-91a5-c338e118b14d.png)

### Context

MacOS Safari and Mac app

Kolibri 0.14 b13

**Comment by jonboiser** [comment]
Here are more examples from @jtamiace , they seem to also be related to the Labeled icon component.

![image](https://user-images.githubusercontent.com/10248067/88345629-35d17b00-ccfb-11ea-899f-a330d38bb43f.png)

**Comment by nucleogenesis** [comment]
@jonboiser @indirectlylit 

I don't have a Mac so I cannot be 100% sure this fix works, but it seems like it is the culprit.

I believe this will be fixed with: https://github.com/learningequality/kolibri-design-system/pull/83

To test, change your Kolibri package.json entry for KDS to: "kolibri-design-system": "github:nucleogenesis/kolibri-design-system-1#0.14-pre-release-bugs" then `yarn install --force` 

Then you should see the issue fixed.

---

Alternatively, check out my branch locally and `yarn link` it per the instructions at the bottom of the KDS readme: https://github.com/learningequality/kolibri-design-system#development-in-parallel-with-other-applications

**Comment by indirectlylit** [comment]
thanks, will test this

**Comment by indirectlylit** [comment]
This seems to be addressed in some cases but not all:

![image](https://user-images.githubusercontent.com/2367265/89243248-57164f00-d5b8-11ea-8164-c144fd1a3966.png)

![image](https://user-images.githubusercontent.com/2367265/89243265-60072080-d5b8-11ea-92af-8483cbe64d4e.png)

It appears the fundamental issue is that in Safari, the parent `<a>` element has `display: inline-block` and chooses to make it small instead of allowing it to expand horizontally.

![2020-08-03 18 35 59](https://user-images.githubusercontent.com/2367265/89243630-43b7b380-d5b9-11ea-9e0b-dfade5d82bf6.gif)

Other browsers apparently will handle this situation differently. For example, Chrome allows the parent `inline-block` element to be as large as possible:

![image](https://user-images.githubusercontent.com/2367265/89243677-5e8a2800-d5b9-11ea-8fb7-e3f78835e46c.png)

Not sure at this point whether the best fix is in KDS or Kolibri, but preferably it would be something we can change in one place rather than many

**Comment by nucleogenesis** [comment]
@indirectlylit I did some Googling on this earlier today and I think the fix is to set `max-width: 0` - which allegedly acts in Safari like `max-width: auto;` does in proper web browsers - which is also the default `max-width` value that is improperly handled by Safari.

I don't think I'll have time to implement a fix and get it tested today but wanted to note it here for posterity.

**Comment by jonboiser** [comment]
Closing with https://github.com/learningequality/kolibri-design-system/pull/195, which partially resolves this (namely, it fixes the issue in the SideNav and in some BackLink components). I'm going to follow up with new issue to document the remaining problems.
