### ISSUE TITLE
Online channel content import option not available - beta15

### ISSUE THREAD

**Issue by cjbamenda** [learningequality/kolibri#7426]
### Observed behavior

After upgrade to beta15, online channel content import is not longer available.

![image](https://user-images.githubusercontent.com/44643658/89127657-14387680-d4e7-11ea-88e4-6101135d6eba.png)

### Expected behavior

Online content import option should be selectable.

### User-facing consequences

Can't import new content, or update current content.

### Errors and logs
<!--
Relevant logs from:
 * the command line
 * ~/.kolibri/logs/kolibri.txt
 * the browser console

[kolibri.txt](https://github.com/learningequality/kolibri/files/5012455/kolibri.txt)
[daemon.txt](https://github.com/learningequality/kolibri/files/5012458/daemon.txt)

No errors reported by Kolibri

### Steps to reproduce

Device > Channels > Import

### Context

Version:           0.14.0b15
OS:                Linux-4.19.69-v7+-armv7l-with-debian-9.11
Python:            3.5.3
Installer:         kolibri(apt) with kolibri-server Version: 0.3.8~beta2-0ubuntu1
Server:            nginx/1.10.3
Database:          /home/pi/.kolibri/db.sqlite3
Free disk space:   40 GB
Server time:       Sun Aug 02 2020 11:23:59 GMT+0100 (WAT)
Server timezone:   Africa/Douala

Client: MacOS 10.14.6; Safari Version 13.1.2 (14609.3.5.1.5)

**Comment by intelliant01** [comment]
@cjbamenda This works for me. It is only not selectable when and if the Kolibri device is not connected to the internet.

**Comment by jredrejo** [comment]
Hello @cjbamenda I can confirm this happen when either
1. There is not Internet connectivity
2. There are more than one interface configured in the device and some of them have not Internet connectivity. If your routes are note correctly set (or your dns are failing because dnsmasq is messing them up, this is something that might happen in a RPi used as a hotspot which I think it's  your case) kolibri won't be able to detect the online Studio server. 

None of these cases are due to the new beta version, it will happen on any previous version, whenever Kolibri can't resolve or find a path to the online Studio server.
