### ISSUE TITLE
Don't set user as created_by for lesson when superadmin from Facility B creates a lesson in Facility A

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7453]
### Observed behavior

This is an edge case scenario for a multi-facility setup i.e. `Facility A` and `Facility B` available on the same device. In the current implementation of 0.14 it is possible that a `Super admin B` of the device and associated with `Facility B` creates a lesson `Lesson AB` for a Class of `Facility A`.

If this happens then upon syncing `Facility A` to another device, it does not sync the Lesson created by the `Super admin B`. 

### Expected behavior

1. Do not allow even a super admin not associated with a facility to modify any lessons in the unassociated facility.
**or**
2. Allow sync of lessons if created by a device super admin irrespective of associated facility. This will be consistent with the existing behaviour of syncing users and other artefacts created by such a super admin. *Am not aware of any demerits of allowing the same. Rather it shall be convenient for a device super user to manage.*

### User-facing consequences

Confusion about missing data.

### Errors and logs

NA

### Steps to reproduce

1. Create two facilities - `Facility A` and `Facility B` on a device with superusers `Super Admin A` and `Super Admin B` respectively.
2. Login as `Super Admin B` and create a class and `Lesson AB` in `Facility A`
3. Sync `Facility A` to another device.
4. Note that `Lesson AB` will not sync to the destination device.

### Context

Kolibri 0.14.0

**Comment by jonboiser** [comment]
This is the expected behavior:

> 2\. Allow sync of lessons if created by a device super admin irrespective of associated facility. This will be consistent with the existing behaviour of syncing users and other artefacts created by such a super admin. _Am not aware of any demerits of allowing the same. Rather it shall be convenient for a device super user to manage._

@bjester @jamalex Is it possible that the Lesson made for a Facility A class ends up "belonging" to `Super admin B`'s facility `Facility B` because of this of code? The `FacilityDataset` the lesson gets linked to is for the creator's facility.

https://github.com/learningequality/kolibri/blob/0beb63c921f4568a228c03fb96f444319818016d/kolibri/core/lessons/models.py#L77-L82

**Comment by jonboiser** [comment]
Here's the same code for Quizzes (nee Exams)

https://github.com/learningequality/kolibri/blob/0beb63c921f4568a228c03fb96f444319818016d/kolibri/core/exams/models.py#L143-L145

**Comment by rtibbles** [comment]
Yes - I think that is absolutely what is happening here - I think instead of looking up the dataset by the user who created it, we should be looking up the dataset by the Collection. However, in either case we will have an additional problem where either the created field, or the collection field will have an invalid foreign key reference also. We may need to make the 'created_by' and 'creator' fields nullable in order to let them be synced when they are created by superadmins from a different facility.

**Comment by jamalex** [comment]
Making them nullable won't be a silver bullet -- Morango is still going to
try to set the fields and then they won't validate, and hence won't be
deserialized. Unless you mean not setting the values in this case at all,
which would be ok for syncing, but not sure what it does on terms of other
functionality.

When we discussed this previously, I recall being told we wouldn't support
having a super admin create lessons on a facility that is not their own,
for this reason. Foreign keys can't cross partition boundaries like this.

**Comment by cyberorg** [comment]
> We may need to make the 'created_by' and 'creator' fields nullable 

Possible to automatically "transfer creatorship" to admin of the facility if the user does not exist there? 

Superadmins could also be automatically added as admins to all facilities.

**Comment by intelliant01** [comment]
May be the same logic that is applicable to the scenario wherein a coach who has curated a lesson is deleted from the facility, can be applied herein. If the coach deletion case is not handled then this too needs to be addressed.

**Comment by jamalex** [comment]
>Possible to automatically "transfer creatorship" to admin of the facility if the user does not exist there?

I can only speak to the syncing side of things (not the interactions with the app logic around Lessons/Quizzes): Just changing the admin to be an admin of another facility wouldn't be possible. Syncable data in Kolibri is organized into partitions, and the primary key of a model is calculated such that it is namespaced under the partition (as a security measure, to ensure a malicious user couldn't force an ID collision and overwrite data from another partition). So the best that could be done here would be "cloning" the Lesson into the other facility (before syncing), but I don't think that's quite what's wanted.

>Superadmins could also be automatically added as admins to all facilities.

Unfortunately this wouldn't work, as a user can only belong to one facility (their account is under that facility's partition, and is synced along with that facility, etc).

However, I think @rtibbles is saying above that the app doesn't actually depend on these fields (a quick search through the codebase didn't pop up anywhere that actually _uses_ these fields). If that's so...

>We may need to make the 'created_by' and 'creator' fields nullable in order to let them be synced when they are created by superadmins from a different facility.

@rtibbles Turns out they're *already* nullable. But what we need to do is not set them at all in the first place if the creator is from a different facility, and then yes, definitely should be inferring the dataset from the collection instead.

**Comment by bjester** [comment]
@rtibbles @jamalex Finally taking a look at this, it appears the dataset inference has already been updated in https://github.com/learningequality/kolibri/pull/7887. I can move ahead with nulling out creator fields in this scenario, but it appears that we also have the same problem for `LessonAssignment` and `ExamAssignment` which do not allow those fields to be nullable.

**Comment by rtibbles** [comment]
Yeah, that seems like the best path forward - it should be an edge case mostly. Maybe it's safer when we set those values on the model to do the check pre-emptively, but that might be overkill if we just ensure it doesn't block syncing.
