### ISSUE TITLE
Removing and then re-importing a facility shows incorrect "removing facility" status

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7454]
### Observed behavior

Removing a facility and importing it again without executing `Clear completed` continues to show the incorrect status of `Removing facility` as shown herein -

![facility_readdition](https://user-images.githubusercontent.com/2577060/89669258-c368b980-d8fc-11ea-97aa-880e7f6ce76b.gif)

### Expected behavior

Correct and latest status should be shown.

### User-facing consequences

Confusion.

### Errors and logs

No browser console errors spotted.
No error spotted in logs.

### Steps to reproduce

Explained above.

### Context

Kolibri 0.14.0

**Comment by jonboiser** [comment]
I believe this is happening because when the facility is re-imported, it keeps the same ID, so in the table, this function

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue#L39

Which is implemented here

https://github.com/learningequality/kolibri/blob/4cf820b14386aecc228fecff64c847bad407cbb1/kolibri/plugins/device/assets/src/views/FacilitiesPage/facilityTasksQueue.js#L89-L101

Is seeing a matching "Deletion" task for the facility, thus causing the "Removing facility" indicator to show. That is, for this facility there are two tasks in the queue (in this chronological order)

1. Delete the facility
1. Import the facility

And the deletion task takes precedence on the UI.

I think, in the short, term the way to fix this is to fix the precedence issue.

In the long term, I think there might need to be some kind of logic that automatically cleans up Tasks, esp. if they represent something like a unique state for a Facility (i.e. a facility can either be 1. syncing, 2. deleting, 3. "at rest", but not two of these simultaneously).
