### ISSUE TITLE
Lesson Resource Preview page action button is "Add" when resource is already in Lesson

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7475]
### Observed behavior

"Pim's Mother" video is already in the Lesson:

![image](https://user-images.githubusercontent.com/10248067/90086040-570c0280-dcce-11ea-9efb-6efa2c32e194.png)

But when you look into the preview, the action button says "Add"

![image](https://user-images.githubusercontent.com/10248067/90086068-67bc7880-dcce-11ea-9aa9-0624b18f12cb.png)

And clicking the "button" seems to re-add the the resource to the Lesson. Because unselecting it via checkbox will say something like "Removed 3 resources" if you e.g. clicked "Add" twice.

cc @MisRob if you have any insights on what's causing this.

### Expected behavior

1. If resource is in lesson, then the button in the preview says "Remove" and causes a remove action when clicked.

### Errors and logs

…

### Steps to reproduce

1. Add a resource to a lesson
1. Go to that resources' preview in the Manage Resources workflow
1. See the wrong button ("Add") on the top corner

### Context

0.14.1

**Comment by alexMet** [comment]
The is another issue because of this bug. When you reload the preview page, the correct remove button shows up and then if you go back to the list, nothing shows up.

![bug](https://user-images.githubusercontent.com/3750511/94998824-58b2c200-05bd-11eb-961d-8c960188d3ec.gif)

The above pull request fixes that also.
