### ISSUE TITLE
In Manage lesson resources, "Saving your changes" snackbar shows when navigating content

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#7477]
### Observed behavior
"Saving your changes" snackbar appears just by navigating through the lesson topic tree

![coach-bug-1](https://user-images.githubusercontent.com/25045166/90422237-7066d300-e06f-11ea-95da-a00cbb1fb05d.gif)

![coach-bug-2](https://user-images.githubusercontent.com/25045166/90422252-7492f080-e06f-11ea-8403-964754889385.gif)

### Expected behavior
Snackbar only appears if you add or remove lesson items.

### User-facing consequences
Buggy behavior

### Steps to reproduce
- Go into a lesson with existing items
- Navigate through the manage resources topic tree

### Context
Tell us about your environment, including:
 * Kolibri version: beta site
 * Operating system: MacOS
 * Browser: Chrome, Firefox

**Comment by indirectlylit** [comment]
tangent: whenever I've added issues to milestones in the past, I've also given them a `P*` priority label. Conversely, I've tried to make sure that issues without a milestone never have a priority.

If we want to update this, recommend documenting in https://kolibri-dev.readthedocs.io/en/develop/development_workflow.html#priority

**Comment by jonboiser** [comment]
Currently, it seems this bug only happens when clicking from the top-level list of channels into the the next topic. I don't see it like in the original post, where it happens there _plus_ when going from a topic into a resource preview. Based on how it happens, I see a sort of full-page refresh occur right before the snackbar shows up, which is related to another sort of bug where if you refresh during the resource-selection workflow, a pop up will appear saying something like "Added 10 resources".

Screen capture from kolibri-beta server: 

![CleanShot 2020-10-08 at 14 19 07](https://user-images.githubusercontent.com/10248067/95514887-958e0880-0971-11eb-9493-c530f65a9094.gif)

**Comment by jonboiser** [comment]
I'm able to reproduce this reliably on kolibri-demo.learningequality.org (0.14.3), but not locally with 0.14.3-4 or on kolibri-beta.learningequality.org (0.14.4). I think I'll move this to 0.14.5 for now, but close it if this stops happening on the same Lessons on kolibri-demo after we upgrade it.
