### ISSUE TITLE
Informal (aka "personal use") facilities should have "learners can sign up" default to true.

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri#7505]
### Observed behavior

In the apps, the default workflow is the "Quick Setup" option (i.e. informal facility). Currently this setup has new user creation off by default, so no "Create an account" button appears unless the admin user turns it on in settings.

### Expected behavior

Since in the at-home case it may not be unusual for multiple family members to share a tablet or computer, and also it is unlikely for them to be familiar with facility management options like a facility admin would, we decided instead to change this default to true, so that creating a new account works out of the box.

### User-facing consequences

Multiple home users may think they need to share login / progress and not have individual progress tracking.

**Comment by jonboiser** [comment]
This should be easy to fix by updating this line:

https://github.com/learningequality/kolibri/blob/6443d53eea37bcd8d33c42c592ffb93ab2074f22/kolibri/core/auth/constants/facility_configuration_presets.json#L30-L31

**Comment by AdamStasiw** [comment]
Hi! I'm an engineer who's brand-new to open source. Kolibri looks like a really exciting project, and I'd love to get involved! Is it okay if I take this issue so that I can learn the open source dev process and make my first contribution?

**Comment by jonboiser** [comment]
Hi @AdamStasiw , thanks for offering to help! I believe that the fix for this bug is a simple one-line change in the JSON file I linked, but it would be important to verify this fix by running and testing the app. 

So here are some resources to help understand some of the context in the original issue, esp. since we refer to this "learners can sign up" concept in a bunch of different ways:

Screenshot of the button that should be shown when the "learners can signup/create own account" setting is true

![image](https://user-images.githubusercontent.com/10248067/95612824-d856eb80-0a18-11eb-9f01-628773cfaece.png)


[Docs on the "Quick setup" which makes it simple to set up Kolibri with a "personal use" facility](https://kolibri.readthedocs.io/en/latest/install/initial_setup.html#quick-start)

[Docs on where to find the Facility Settings, where we are most interested in the "Allow learners to create accounts" setting](https://kolibri.readthedocs.io/en/latest/install/initial_setup.html#quick-start)

[Docs on how to set up Kolibri for local development](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html)

**Comment by AdamStasiw** [comment]
Okay, I left a few questions on the Pull Request because of my lack of knowledge around testing and around the PR process, but I think I've got this working - the documentation was _incredibly_ useful!
