### ISSUE TITLE
Fullscreen option disabled for videos on Android

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7537]
### Observed behavior

On Android, users are unable to view a video clearly as it expands beyond the viewport or is too small. Have tried this with Khan Academy and PheT videos. 

### Expected behavior

Fullscreen mode could address this issue but the fullscreen option in the video player is disabled.

### User-facing consequences

Unable to consume the content on handheld Android devices.

### Errors and logs

N/A

### Steps to reproduce

Install the app on Android device.
Import any channel containing a video and try to view the video in fullscreen mode.

### Context

Kolibri 0.14.3 Android app installed on any android device.
I have tried with 3 devices - 2 phones and a tablet, all with Android 6.0 or above.

**Comment by rtibbles** [comment]
Note that this is deliberately disabled because the fullscreen APIs we use outside of Android do not work in the app context.

**Comment by kollivier** [comment]
The underlying issue is that, at least on some platforms, the app, not the browser, needs to be the one to handle the fullscreen request. So on each platform, we'd need to add explicit code to enable this. For WebView / Chromium on Android, we should be able to do that by handling the following callbacks: 

https://stackoverflow.com/questions/38842869/how-to-fullscreen-youtube-video-in-webview

**Comment by rtibbles** [comment]
This has been fixed in the 0.15.6 release of the Android App.
