### ISSUE TITLE
PDF.js renders to canvas, making text unselectable

### ISSUE THREAD

**Issue by kollivier** [learningequality/kolibri#7547]
### Observed behavior

When viewing PDFs, all content is rendered as an image, regardless of how the actual content is encoded in the PDF. This disables the ability to do things like text selection. 

Here's an example PDF that contains text that is selectable in the Studio preview (which uses the original renderer):

https://studio.learningequality.org/channels/b62c5c2139a65fb2aaf68987a25b28a1/edit/9167e5d/291e817

Here's the same content in Kolibri, rendered as an image:

https://kolibri-catalog-en.learningequality.org/en/learn/#/topics/c/291e8172471155e9890ebd75cbe88e8f

This appears to be because PDF.js renders everything to an HTML canvas object, meaning it essentially draws the document as an image.

There is also an SVG backend, which should restore things like text selection, but would probably need testing with a variety of PDFs to ensure rendering still works properly for content.

An alternative option would be to switch to using the built-in PDF renderer, which would resolve this and also would likely improve accessibility as well. If we did this, we would probably have to take an approach to progress that matches HTML5 apps, such as doing calculations on total time needed based on reading speed and number of pages, and then tracking interaction time.

### Expected behavior

Text content should be selectable, this is especially important in examples like the above that contain sample code, etc.

### User-facing consequences

Users have to type out text they wish to 'copy' line-by-line.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by DXCanas** [comment]
Context:

Text selection works on Studio because the pdfs are rendered using the browser's default PDF renderer.

We tried that once in Kolibri, but ran into inconsistencies across browsers, as not all of them included a PDF renderer. Sometimes, the renderer would actually be there, but be REALLY REALLY slow. Crashed a few browsers on a some tablets/phones.

So we had to roll our own and bake it in as a plugin. And we included some performance optimizations for good measure. Using our own renderer also allows for "progress tracking", whatever that means in this context

To do so, we used the same library the native browser uses, pdf.js. But the docs are sparse. They include descriptions for rendering the canvas that makes up the PDF page, but make no mention of including the text:
https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples

Some stackoverflow posts have alluded to enabling this feature by importing viewer, but a deeper dive in the sourcecode is probably necessary before we can do anything, since the docs don't provide a ton of guidance. We also don't know how much of an impact this will have on the render performance.
