### ISSUE TITLE
When we click on 'Cancel' button on 'Edit Profile' page, a confirmation message appears stating "Changes Saved"

### ISSUE THREAD

**Issue by JatinSharma12** [learningequality/kolibri#7562]
**Observed behavior**

When we click on Edit button on Profile page an[d then click on cancel button on Edit Profile page, a confirmation message is displayed as "Changes saved" whereas there should not be any confirmation [message.](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/super-admin/super-admin-change-language.feature)

…

 **Expected behavior**

When we click on Edit button on Profile page and then click on cancel button on edit profile page, profile details page should load without a confirmation message because if we are clicking cancel button means we are not allowing it to make any changes and hence there should be no confirmation message like "Changes saved".

…

**User-facing consequences**

User might get confused that he didn't make any changes then why a confirmation message is displayed.

…

### Errors and logs
…

### Steps to reproduce

1. Login as Super Admin.
2. Navigate to User menu and click on 'Profile'.
3. Click on Edit button available on top left corner of the page.
4. Make some changes in any of the fields and click 'Save''.
5. Observe that a confirmation message is displayed stating "Changes saved".
5. Again click on Edit and now click 'Cancel'.
6. Observe that a confirmation message will get popped up stating "Changed Saved".

PFA a video  for reference.
[Kolibri_Editprofile_issue.zip](https://github.com/learningequality/kolibri/files/5385276/Kolibri_Editprofile_issue.zip)

…

### Context
 * Kolibri version 0.14.3
 * Operating system: Windows 10

…

**Comment by jonboiser** [comment]
Thanks @JatinSharma12. I just reproduced this on our kolibri-demo.learningequality.org demo server.

One detail that I think is relevant is that I need to first click "Save" (then see a first confirmation message). After that, I see the message every time I return to the Edit Profile page and click cancel.

If I refresh the Edit Profile page and click "cancel" before doing anything, I _don't_ see any message.

### Possible root cause

I believe the issue is that in the Vuex `core.snackbar` module, after that first "Save", the `core.snackbar.isVisible` is set to `true` and stays that way permanently. So the second time we go to `ProfileEditPage` and click cancel, we re-render the `ProfilePage` with the snackbar data from the first time (since it never got erased).

### Potential fixes

I think the fact that the snackbar state doesn't get cleared after it disappears is tech debt. What should happen is that after the snackbar is no longer visible `snackbar.isVisible` returns to `false` and `snackbar.options` returns to its default value.
