### ISSUE TITLE
When downloading channel content, the 'Total Size' resources do not always match 'On Your Device' resources. 

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7622]
![Total size vs device size - mac Kolibri](https://user-images.githubusercontent.com/73143721/97263746-da72c580-17e0-11eb-9571-1259a1b68644.png)

### Observed behavior

When downloading large channel content, the 'Total Size' resources do not always match 'On Your Device' resources. The channel downloaded in the screenshot above was 'Khan Academy Standardized Test Prep' - channel ID: 6616efc8aa604a308c8f5d18b00a1ce3

### Expected behavior

The number of resources on the device should be the same as the resources in the channel.

### User-facing consequences

User may notice the number discrepancies and assume that the resources do not match the exact content expected. Alternately, they may think it looks buggy, decreasing their feeling of reliability about the software. (Obviously this particular minor difference in numbers would not likely have a dramatic effect, but noting in case!)
…

### Errors and logs

…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Super Admin account
2. From the left-nav hamburger menu, click "Device"
3. Click the "Import" button 
4. On the "Select a source" pop-up window, make sure that "Kolirbri Studio (online) is selected
5. Click "Continue" 
6. In the search bar, enter "Khan Academy Standardized Test" 
7. Next to "Khan Academy - Standardized Test Preparation" click "Select Resources"
8. Click the "select all" checkbox and make sure that all resources are selected
9. Observe that the total number of resources at the top of the page reads "2539" but at the bottom of the page, even with all resources selected, it reads "2544 resources selected" and note that these numbers do not match.
…

### Context

MacBook Pro - Catalina 12.15.7 - Kolibri Mac version 0.14

**Comment by jonboiser** [comment]
Could you share the channel ID for this channel? It should be the alphanumeric string like `6616efc8aa604a308...` that appears in the URL when you're on this page.

I was looking at a channel with the same name, but there are some discrepancies, since that channel is only one Version 1 and has a different total number of resources.

**Comment by MindfulQA** [comment]
@jonboiser Absolutely; we'll look into this today and follow up. Thanks!

**Comment by MindfulQA** [comment]
@jonboiser Update - here's the relevant channel ID:

6616efc8aa604a308c8f5d18b00a1ce3

We also tested additional examples of this today, and were only able to reproduce with that specific channel so far. So it may be a bug related to the setup for that channel, rather than a universal app-wide bug.

Here's another example showing the discrepancy even before the download starts:

![additional-khan-academy-channel-data-exampe](https://user-images.githubusercontent.com/73143721/97358067-f06f9d00-1857-11eb-8695-d1696064dffb.jpeg)

**Comment by jonboiser** [comment]
Okay, thanks. Yeah this might be specific to this channel, because on the Kolibri Studio page, the "Total resources" and Version are different, so there might be something out of sync.

Here's what the channel looks like on studio (total resources is 2845, versus 2539 on your screenshot).

![image](https://user-images.githubusercontent.com/10248067/97358311-52c89d80-1858-11eb-9ba8-905ee151f3dd.png)

**Comment by pcenov** [comment]
@radinamatic this one is not valid in 0.16.0b10 - the correct number of resources is being displayed.

**Comment by radinamatic** [comment]
Closing as not extant on the latest 0.16 build.
