### ISSUE TITLE
Unable to dismiss login dialog by clicking on 'x'

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#768]
## Summary

Once the login dialog is opened, it is impossible to dismiss it.

## System information

 - Version: vue2 Nalanda preview build
 - Operating system: Linux and OSX
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

Unrelated error (probably related to #757)
```
default_frontend-0.1.1c1.js:89 Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
    at a.focusElementTest (default_frontend-0.1.1c1.js:89)
    at n (default_frontend-0.1.1c1.js:13)
```

## How to reproduce

1. Click login.
2. Press 'X' to close dialog.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1680573/21830649/2e243542-d76c-11e6-85b0-f72661dd44ff.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Confusing if not able to dismiss dialog.

Confirmed independently by @khangmach

**Comment by christianmemije** [comment]
Somehow `showLoginModal()` is also triggered.

**Comment by christianmemije** [comment]
`navBarClicked()` function within the session-nav-widget is called after clicking the close button.

**Comment by DXCanas** [comment]
Update: about to put up a PR to fix this. Made a change to the structure of the app. 

@christianmemije You're right. The problem was that the modal was wrapped inside the session widget, which had a click listener associated with the element. The modal was _technically_ inside of the widget. Moved it out, but because of the implied changes in logic, though it would be better to separate 2 vue components. 

There may be some refactoring in order though. Sort of touched on it in #765, but the structural changes that would need to happen for it to be acceptable code were beyond the scope of that PR.

**Comment by christianmemije** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/800
