### ISSUE TITLE
Large `REMOTECONTENTIMPORT` tasks can take a long time to cancel (e.g. over 10 min to cancel KA Mathematics)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#7690]
### Observed behavior

When importing a large topic like KA Mathematics, then immedidiately canceling it in the Task Manager, it can take a very long time for the task to go from a `CANCELING` status to a `CANCELED` status, even if I click "Cancel" immediately.

I believe that the time it takes is proportional to the size of the topic being downloaded. So a smaller topic would probably cancel more quickly.

### Expected behavior

Ideally, cancelling an import task should be a fast operation and take the same amount of time regardless which topic is being downloaded.

### User-facing consequences

The time it takes to cancel a task can be inconvenient and breaks expectations that cancelling something should be immediate or proportional to the amount of "clean up" that needs to be done.

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by rtibbles** [comment]
To manage this, we'd need to find a way to batch these queries: https://github.com/learningequality/kolibri/blob/44bf1ed3591321f4b7ef7c4e5c6ceda8c01db7ae/kolibri/core/content/utils/channel_import.py#L331 - the issue is that currently that entire topic tree will be copied in a single SQL query, so we can't really interrupt it while the SQL query is ongoing.

**Comment by rtibbles** [comment]
@radinamatic reports this is no longer replicable.
