### ISSUE TITLE
task frozen: deleting imported chanals from studio not woking

### ISSUE THREAD

**Issue by MBKayro** [learningequality/kolibri#7705]
Problems when deleting imported channels from studio in  device section, and the tassk froze in production version.

# first build the assets
yarn run build
# now, run the Django devserver
kolibri manage --debug runserver -- 0.0.0.0:8000

![Capture d’écran de 2020-11-22 12-54-52](https://user-images.githubusercontent.com/328784/99903063-40f4e180-2cc2-11eb-94ec-aa61a1451320.png)

**Comment by rtibbles** [comment]
> kolibri manage --debug runserver -- 0.0.0.0:8000

This is insufficient to run the full devserver, specifically, this does not run the asynchronous task runner, hence why your tasks are not running.

See the `services` command for how to run the services independently of the dev server, an example of this invocation is in our package.json: https://github.com/learningequality/kolibri/blob/release-v0.14.x/package.json#L23

Note that in develop now, the dev server is actually using cherrypy rather than the Django devserver.
