### ISSUE TITLE
Languages UX to match Studio's languages links on main page

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#7748]
### Observed behavior
Kolibri does not have "dots" between its languages the way that Studio does; they should both match in terms of UX.

|Studio|Kolibri|
|--|--|
|![Screen Shot 2021-01-19 at 8 37 49 PM](https://user-images.githubusercontent.com/13563002/105127759-5a35c680-5a96-11eb-8d18-66ea6b33a830.png)|![Screen Shot 2021-01-14 at 3 09 47 PM](https://user-images.githubusercontent.com/13563002/104659984-90301080-567a-11eb-900b-affe3637936f.png)|

### Expected behavior
Kolibri should also have dots between the languages links. The component (`LanguageSwitcherList`) in Kolibri needs to be updated to match that component in Studio.

### User-facing consequences
UX should match on both products.

### Steps to reproduce
1. Open Kolibri
2. Look at the links at the bottom that give you the languages. Note that there are no dots between them.

### Context
Browsers: Chrome, Firefox

**Comment by indirectlylit** [comment]
Flagging that this might be a tension to bring up in the Design System circle because it involves cross-product consistency. We've had some related prior conversations about how to render lists of items in a single line.

If we choose to consistently separate lists of items in a line using dots, we'll also need to decide on conventional spacing and line-wrapping behaviors.

**Comment by rtibbles** [comment]
These dots no longer appear to be on Studio either - so closing this issue for now.
