### ISSUE TITLE
Import from Kolibri Studio page - one of the channel cards is not horizontally aligned with all the others

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7751]
### Observed behavior

On the Import from Kolibri Studio page one of the channel cards (Citoyennes de la Terre) is not horizontally aligned with all the others. Padding-left needs increase to align it with all the other channel cards.

<img width="570" alt="channelsAlignment" src="https://user-images.githubusercontent.com/72492554/105175734-01653d00-5b2d-11eb-92ff-3554b09cd5cf.png">

### Expected behavior

All channel cards on the import from Kolibri Studio page have to be aligned correctly on the page.

### Steps to reproduce
1. Login to Kolibri LP
2. Click the Import button
3. Select Kolibri Studio (online)
4. Click Continue
5. Scroll down a bit to see the "Citoyennes de la Terre" channel card

### Context
Kolibri 0.14.6rc1
Windows 7 vm
Firefox 84.0.2 (32-bit)
IE 11.0.9600
Chrome (latest)

**Comment by jonboiser** [comment]
I think this would be resolved once some thing like the responsive img component is implemented https://github.com/learningequality/kolibri-design-system/issues/23. Currently, this part of the app just tries to assume that the channel thumbnails coming from the Studio public API are of the same dimensions.

I think, typically, what people would do is make the container for the thumbnail a fixed size like 200x200px and use CSS like [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) to responsively adjust its height/width. We've avoided using this solution because it's not supported in IE.

**Comment by pcenov** [comment]
@radinamatic - this issue is still valid in 0.15.1

**Comment by rtibbles** [comment]
Fixed in #9658
