### ISSUE TITLE
Investigate & Replicate: Pdf rendering cuts half of the page

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#7759]
## Acceptance Criteria

- [ ] Determine if this is specific to the nature of the file used (is this a content problem or a bug we can address?). One way to test is to use pdftk's dump_data to see the PageMedia metadata to see if they are affecting the size.
- [ ] If this is a bug and not due to the content itself, either: 1 )Fix the issue if it is easy to resolve or 2) Create a subsequent issue (closing this one) that describes in full the bug and what steps will be needed to fix it.

### Observed behavior
Half of the page is hidden in the view, even when full screen is used
Screenshots available at https://community.learningequality.org/t/cont-not-displaying-correctly-on-the-screen/

### Expected behavior
Full width of the page should be visible

### User-facing consequences
Users can't read the documents

### Steps to reproduce

Using channel `kifaz-vifal`
Import English > Language > Parts of speech: the noun >Introduction to nouns
and try to see the "Introduction to nouns" doc

### Context

 * Kolibri version 0.14.3 - 0.14.6
 * Operating system: Ubuntu
 * Browser: Chrome and Firefox

**Comment by jonboiser** [comment]
This looks related to (but the inverse of) #5917 (here the PDFs are rendered as too wide because of a few landscape-orientation pages). The docs in the School In a Box (SIB) channel are all landscape-orientation pages of a slideshow, but are being fit into a portrait-orientation page.

This issue #1971 points to a possible fit-page-to-screen API in PDF.js that might be useful. My hunch is that we don't do this by default and just assume PDF docs are all in portrait-orientation.

Link to example SIB PDF on Kolibri Beta: https://kolibri-beta.learningequality.org/en/learn/#/topics/c/25605a10eed54688b6a4519a1183f9a4

**Comment by jonboiser** [comment]
@jredrejo When I download the file, I actually get a PPTX (powerpoint) file. But, when I tried to see if this was a problem with PPTX in general, I found I couldn't even upload one to my channel on Studio.

Do you think this is just a matter of trying to display an unsupported file format?

**Comment by jredrejo** [comment]
@rtibbles I can confirm the issue persists, it's easy to reproduce it following the steps in the description of the issue

**Comment by rtibbles** [comment]
I think the most systematic way to handle many of our PDFJS related issues might be to do a fuller port of their default viewer code into Kolibri - but that would be a lot of work.
