### ISSUE TITLE
Kolibri App - SCORM resource freezes on loading screen, but the resource is marked as completed after some time

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7772]
### Observed behavior

Kolibri App > the SCORM content items in the Kolibri QA Channel - a SCORM resource freezes on loading screen and if it stays like that long enough the resource is marked as completed.

<img width="960" alt="scoemIssue" src="https://user-images.githubusercontent.com/72492554/106105774-2ff69f80-614d-11eb-81cf-76412fc964ae.png">

### Expected behavior

SCORM content loads with no issues and the resource item is marked Completed in case it has been fully loaded and browsed by the user.

### Steps to reproduce

Preconditions: Kolibri QA Channel imported with the SCORM content
1. Login to Kolibri App as a learner
2. Click the Kolibri QA Channel
3. Click the HTML5 folder
4. Click the SCORM folder
5. Click a single item

### Context

Kolibri 0.14.3 - App
Windows 10 vm

**Comment by rtibbles** [comment]
Note that we think there are two issues here:

1. SCORM content will not render properly in 0.14.x without a special configuration that allows for the SCORM API to be accessed. This is fixed in current develop branch.
2. Currently we only suspend 'time based' flagging for SCORM content once we have received a signal from inside the SCORM content that it indicates it is progress tracking. We might want to set a permanent flag at import time to mark this up front, although fixing 1 will ameliorate this.

cc @kollivier

**Comment by rtibbles** [comment]
This is resolved by the ability to flag the completion criteria as "set by content".
