### ISSUE TITLE
Issue downloading Summary log CSV reports in 0.14.6

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#7788]
Reported by UNW Chile:

### Observed behavior
They were unable to download the summary logs on all facilities except for INFOCAP (which downloaded successfully) on the [UN Women Chile server](https://chile-kolibri.mylearningpathway.org/). I'm not sure if it's related, but I've noticed INFOCAP is sometimes the only facility that has issues auto-syncing to KDP.

This is the error seen when trying to access the summary logs:
![image](https://user-images.githubusercontent.com/22602993/107794502-85be7080-6d25-11eb-9a22-5fbd7ffa5a55.png)

I was also able to reproduce it on my side when logging into the Chile server.

### Context

Tell us about your environment, including:
 * Kolibri version: v0.14.6 on Cloud Kolibri
 * Operating system: UN Women online server
 * Browser: Chrome

…

**Comment by jredrejo** [comment]
> Could we add a defensive capability check in Kolibri too, just in case we run across non-utf8 enabled file systems? (and change the filenames accordingly)

@rtibbles  I have been able to reproduce the problem in a normal filesystem inside a Docker container running the same image kolibri cloud uses. It happens the issue is on the linux environment (lack of language vars) and it's impossible to create any file or dir with accents in the name. Theorically this will never happen in a "normal" system.

**Comment by rtibbles** [comment]
Could we add a defensive capability check in Kolibri too, just in case we run across non-utf8 enabled file systems? (and change the filenames accordingly)
