### ISSUE TITLE
Kolibri App > Upgrade available modal - "Learn more and download it here" link doesn't open the download page

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7793]
### Observed behavior

In Kolibri App, the Upgrade available modal - "Learn more and download it here" link doesn't open the download page. On-click the link nothing happens.

<img width="960" alt="2021-02-16_110739" src="https://user-images.githubusercontent.com/72492554/108081861-196fa400-707a-11eb-99ff-721946d9558d.png">

### Expected behavior

Clicking the "Learn more and download it here" link opens the download page in a browser.

### User-facing consequences

Users of Kolibri app are unable to upgrade it to a newer version.

### Steps to reproduce

1. Click the kolibri.exe file to launch the app
2. Login
3. See the Upgrade available modal 
4. Click the "Learn more and download it here" link 

### Context

Kolibri App version 0.14.3 (Kolibri and KOLIBRI_DATA folders hosted on a USB drive)
Windows 10

**Comment by jonboiser** [comment]
@metodimilevqa Do you have access to any logs for the windows app?

@nucleogenesis @rtibbles If this feature is breaking because maybe the URL didn't come through from telemetry, it might actually be a good idea to hard code the link in the component as a fallback since it really doesn't change from release to release. It's always (www.learningequality.org/download)

**Comment by kollivier** [comment]
@jonboiser The Kolibri app doesn't have a way currently to open external URLs. Even if it did, there would be no Windows app in the downloads page to upgrade to because we don't have portable app releases yet. 

The apps should be getting excluded from update notifications, so if these are active again we will have to figure out why this is happening. The Endless Key v1 Windows app will crash if it gets an update notification.

**Comment by metodimilevqa** [comment]
> @metodimilevqa Do you have access to any logs for the windows app?
> 
@jonboiser Yes, I have access to the logs

**Comment by metodimilevqa** [comment]
@jonboiser Here are the log files:
[kolibri.txt](https://github.com/learningequality/kolibri/files/6004029/kolibri.txt)
[kolibri-app.txt](https://github.com/learningequality/kolibri/files/6004030/kolibri-app.txt)

**Comment by jonboiser** [comment]
> The apps should be getting excluded from update notifications, so if these are active again we will have to figure out why this is happening. The Endless Key v1 Windows app will crash if it gets an update notification.

@kollivier Is there a way to disable this feature in the front-end code only for Windows apps?

**Comment by kollivier** [comment]
@jonboiser Not that I'm aware of, though I think such a thing could be useful. We still have to address it from telemetry anyway because we can't update the Endless Key version of the apps. 

Telemetry should have logic to exclude these builds, and when I tested a few days ago it seemed to be working, but I can check again today.

**Comment by rtibbles** [comment]
We are no longer developing the windows app, and there is already an open issue for this on the Mac App, so closing this one.
