### ISSUE TITLE
Mobile-responsive views for each new learning activity type

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#7873]
- Watch: video renderer & controls
- Read: document renderer, fullscreen
- Listen: audio renderer & controls
- Reflect: content renderer, fullscreen
- Practice: question renderer, answer attempt checker
- Play/Interact/Experiment: content renderer, fullscreen
- Create/Make: content renderer, fullscreen
- A new side panel for resource details

**Comment by khangmach** [comment]
### Figma page:
https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1402%3A195559

### Context:
There are a way too many observed issues with the current content render page at the moment. 

**Information hierarchy and display**
The page currently just vertically stacks information, actions, and icons without proper spacing or usage considerations. It's extremely difficult to tell what's going on when a lot of content is rendered and you've used hints and interacted with various UI on-screen. Description, metadata, actions, hints, engagement UI, mastery criteria: they're all scattered around in different areas and its time to consolidate

**Not enough space for proper engagement, especially on mobile devices**
- There are duplicated title headings via the app-bar title & in-page title
- At least 200px of empty vertical space that trickles all the way down to mobile devices. Extra horizontal padding with no purpose
- No text styles, padding, or margin adjustments on mobile breakpoints levels 0-2, compounding the space issue. 
- Tertiary support metadata like description, download, copyright, etc, is prominent and doesn't need to be in the learner's view at all times. 

**Learnable, but awkward controls**
- Seen in site visits, children often times spend too much time time scrolling up and down, panning between resource render, rendered hints, and the answer box. Given how little space there already is, this constantly puts the exercise material out of focus when you give your answer
- Awkward scrolling with the right hand on tablets, but then having to use your left hand/thumb to press "Check". 

**Exercise attempt bar needs quality of life adjustments**
- Currently it cannot visually accommodate an overflow of attempt placeholders. For example, if the mastery criteria is get 12 out of 14 correct, we have a tough time display that edge case
- Difficult to see system feedback: Kolibri gives feedback such as "correct, incorrect, check your answer again" when a learner checks an answer, but it's so hard to see. 

### Core changes:
-  Scrapping the current duplicated title, [introduce one custom topbar](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=387%3A26928) only. No in-page resource title
- [Place metadata info, description etc into an information sidebar](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=387%3A27721)
- [Place lesson plan/topic pathway information into a custom sidebar](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=616%3A52716) instead of the current card display beneath rendered content
- Bookmarking functionality for learners and coaches ([separate project page](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/?node-id=76%3A6407))
- [Allowing learners to manually mark a resource as complete](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=517%3A46959), which changes its completion status everywhere in the system
- [Exposing an estimated time it takes to complete the resource](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=692%3A56119)
- [Adjusted styling for displaying in-progress vs complete](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1763%3A88374)
- [Improved, non-buggy display of hints](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1142%3A2679)
- Responsive form factors for all designs
- Changes to the completion icon
- [Introduces a couple of new action icons](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=335%3A26002)

### Core exercise (now 'practice') exclusive changes:
- Attempt bar now [accommodates overflow attempts](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1829%3A89)
- [Attempts now have a style that is easier to scan](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1821%3A412) (new animation included)
- Checking your answer now [brings up a more visible feedback message ](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1821%3A348)(new animation included)
- The first answer attempt slot is now always highlighted. No more explaining why answer attempts move left to right
- Remove sticky behavior from top appbar. It contains non-engagement elements and shouldn't persist. Space is more important
- Instead, upon scrolling down, a different bar will be sticky that contains the completion criteria and the use hint button. By doin this we save the user vertical space and focus engagement related information on the page without having it be in different places on the screen. 
- As a learner clicks 'use a hint' button, Kolibri should pan down to put that hint into view, if it already isn't in view (new animation included)

### New technical stuff
- Page topnav is **NOT** sticky
- More than one sidebar cannot be open at a time
- New empty states for sidebars
- Many changes for level 0-2 mobile breakpoints

### Related design work
- [Uses the new learning activity icons](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/?node-id=1192%3A0)
- References the [new bookmarks work](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/?node-id=76%3A6407)
- For the information sidebar, uses the same structure as the sidebar found in learn/home page redesigns that Jessica and Riddhi worked on

**Comment by marcellamaki** [comment]
New github issues have been created for design -> dev handoff, assigned points, assigned priorities, and associated with this epic.
