### ISSUE TITLE
Would be good to explain why something is appearing in "Next Steps" in Learn

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#789]
Something along the lines of:

"Because you finished <video title> in <parent topic>"

<img width="519" alt="screen shot 2017-01-12 at 3 09 21 pm" src="https://cloud.githubusercontent.com/assets/6668144/21912206/55bdedf0-d8d9-11e6-9c87-db19b8552cd0.png">

**Comment by 66eli77** [comment]
@jtamiace The contents shown under `Next Steps` depends on the contents you finished. Likely based on multiple finished contents. So it can look like "Because you finished in Math 1, English 5, Physics 113, CSE 110 ...". And because there is no clear one to one mapping between the next-step-content and finished-content, it might be confusing too.

**Comment by radinamatic** [comment]
Is there still `Next steps`? Not seeing it anymore...

![selection_336](https://user-images.githubusercontent.com/1457929/28004544-9a0bafe4-6545-11e7-97f0-e6b19df2c703.png)

**Comment by indirectlylit** [comment]
no more next steps
