### ISSUE TITLE
kolibri start, stop, and status commands are not working.

### ISSUE THREAD

**Issue by amodia** [learningequality/kolibri#79]
**Branch:** 'Master`

**Current behavior:** Running these kolibri commands start, stop, and status are not working. These commands are use for the kolibri installers. 

**Steps to reproduce:**
 1. Follow the steps to run kolibri https://github.com/learningequality/kolibri
 2. Run the commands kolibri start, kolibri stop, and kolibri status on the terminal. 

I attached sample screenshot below.

![screen shot 2016-05-11 at 7 16 00 pm](https://cloud.githubusercontent.com/assets/8663934/15179192/da7bc93e-17ac-11e6-80a7-d5b2497e032a.png)

**Comment by benjaoming** [comment]
Well, they do work -- they just don't do anything because there's no cherrypy etc. available.

Cherrypy has been 99% decided upon, and I think we'll go for a similar daemon behaviour as the one we ended up with in ka-lite.

For now, you should run a conventional Django development server:

    kolibri manage runserver

or straight from source

    python -m kolibri manage runserver

**Comment by indirectlylit** [comment]
cherrypy is now integrated
