### ISSUE TITLE
Responsive behaviors on setup wizard language switcher list no longer work as originally designed

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7997]
## Observed behavior

The number of visible languages is changing based on screen size breakpoints even though the available space is not changing.

This may have been an unintentional consequence of some unrelated layout changing, e.g. making the max-width of the setup wizard smaller.

![2021-04-12 12 19 26](https://user-images.githubusercontent.com/2367265/114449390-89397100-9b89-11eb-9707-b2e18c92f349.gif)

## Expected behavior

UI layout should be responsive to actual available screen real estate.

## User-facing consequences

Layout and text wrapping behavior on the very first screen users see behaves poorly.

## Steps to reproduce

resize setup wizard window

## Context

0.14.7 rc2
0.16.0b10

**Comment by pcenov** [comment]
@radinamatic this one is still valid in 0.16.0b10

**Comment by FidalMathew** [comment]
@rtibbles Can I work on this issue?

**Comment by AlexVelezLl** [comment]
Hi @FidalMathew! Sure! I will assign this issue to you. Thank you!

**Comment by FidalMathew** [comment]
https://github.com/learningequality/kolibri/assets/84982038/8e7f8418-a30f-445d-8ef4-82fad6a2f08a

@AlexVelezLl I think the setup_wizard page doesn't exist now. The language option is present on the auth/#/signin page. Can you confirm this? Let me know if any changes are required. Thank you!

**Comment by rtibbles** [comment]
@FidalMathew - the setup wizard still exists, however, you need to have a fresh KOLIBRI_HOME directory in order to see it, it is only used during initial setup.

You can see it again by running Kolibri with the `KOLIBRI_HOME` environment variable set to a new folder (if it doesn't exist, it will be created). When I do this, I tend to just use today's date as the folder name: `KOLIBRI_HOME=~/.20240206 yarn run devserver-hot` - this will run with a fresh folder, and should show you the setup wizard.

**Comment by FidalMathew** [comment]
Thanks, @rtibbles got it!

**Comment by AlexVelezLl** [comment]
Fixed in #11847.
