### ISSUE TITLE
Coach/Plan/Lesson - A deleted resource cannot be removed 

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8092]
## Observed behavior
While managing my lesson resources I am getting an error in the console when I attempt to remove a resource which has been deleted from a channel and the resource cannot be removed.

![2021-05-19_12-54-23](https://user-images.githubusercontent.com/79847249/118797880-b1fa0800-b8a5-11eb-8ee3-e6b97fe62171.png)

## Errors and logs
```
TypeError: Cannot read property 'title' of undefined
```

## Expected behavior
It should be possible to remove a deleted resource.

## Steps to reproduce
1. Import a channel from Studio and create a Lesson by using the resources from the newly created channel.
2. In Studio remove a resource from the channel and publish the channel.
3. In Kolibri go to Device/Channels and click the 'Manage' button next to the modified channel
4. Click the 'View changes' link and then click the Update channel button
5. Go to Coach/Plan/Lesson and click the 'Remove' button next to a removed resource

## Context

 * Kolibri version: 0.14.7
 * Operating system: Windows 10
 * Browser: Chrome

**Comment by marcellamaki** [comment]
Evgeni is starting on this issue, and I'm wondering if @jtamiace or anyone else -- @indirectlylit @nucleogenesis @rtibbles -- might have some context on the setup of this error message? It does seem like having an error message would be helpful, and my guess is it was added to manage edge cases, but having to remove a resource that doesn't exist seems like it could be confusing from a user point of view... I suggested to Evgeni that we check in to see if the best approach here is a technical fix (i.e. to make the remove button work), a design fix (i.e. to either not show resources that don't exist, or maybe not be able to remove them? not sure what makes more sense), or some combination. Open to any background or recommendations. 🙏  (He will follow up with any questions or ideas he has in the comments here next week, since it's Friday evening now for him).

**Comment by rtibbles** [comment]
We want to preserve this error message (rather than hiding non-existent resources), so as to be transparent to users when they have facility data (like lessons) that does not have all associated content data. This is important, because otherwise when syncing happens, if we just hide things people might think that data loss has occurred.

So, the fix here is to allow the `remove` button to work in this instance.

The immediate error that seems to be happening is that the `remove` action seems to be assuming that we have a valid reference to the content node - presumably because we are using that title to populate a toast that informs the user that the removal has happened.

As we are past string freeze, we will need to use an existing string in the place of this title, or come up with some other workaround.

**Comment by marcellamaki** [comment]
Fixed with https://github.com/learningequality/kolibri/pull/8471
