### ISSUE TITLE
Create new base top bar component with mobile responsive breakpoints 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8106]
**Overview**: 
The new top bar component should replace the current duplicated title, and there should be no in-page resource title. The top bar is _not sticky_ and has new mobile responsive breakpoints. 

**Done when**: 
- Top bar replaces current layout and correctly renders title metadata 
- Top bar correctly displays the correct layout of icons (placeholder icons okay if this a bottleneck, but please add a code comment `TODO` that can be checked for later and note in the PR) and menu options based on new breakpoints 
- Top bar renders new tooltips with strings on hover for all icons and menu options

**Beyond scope of this ticket**:
- Menu interactions working 
- Top bar fully implemented in all places where it is used
- Status/progress indicators

**Figma references**:
<img width="770" alt="Screen Shot 2021-05-25 at 10 05 54 AM" src="https://user-images.githubusercontent.com/17235236/119512797-a729f200-bd41-11eb-83cd-5c8529f64e18.png">
<img width="399" alt="Screen Shot 2021-05-25 at 10 01 00 AM" src="https://user-images.githubusercontent.com/17235236/119512799-a729f200-bd41-11eb-9530-ec464fdb6cf8.png">
<img width="709" alt="Screen Shot 2021-05-25 at 10 00 51 AM" src="https://user-images.githubusercontent.com/17235236/119512800-a729f200-bd41-11eb-88c7-cb67b7b36e97.png">
<img width="489" alt="Screen Shot 2021-05-25 at 10 00 00 AM" src="https://user-images.githubusercontent.com/17235236/119512801-a729f200-bd41-11eb-98dd-ea834dc6fb84.png">

**Comment by marcellamaki** [comment]
@MisRob - I have tried my best to include all of the relevant details from the designs here in this issue, but for your reference, here is [the figma associated with this feature](https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=387%3A26928) and you can also see some [details/context from Khang in the original design ticket](https://app.zenhub.com/workspaces/kolibri-ecosystem-6047e525b8b9d900182e2d6f/issues/learningequality/kolibri/7873). (This issue only covers the first bullet point.) Please feel free to reach out with any questions!

**Comment by MisRob** [comment]
Thank you, @marcellamaki

**Comment by nucleogenesis** [comment]
@MisRob @marcellamaki 

> Top bar fully implemented in all places where it is used

This is kind of a built in if you update the existing component I think. It doesn't seem like we'd need a separate version of the component to handle the updates.

Just want to note that we currently use [ImmersiveToolbar](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/ImmersiveToolbar.vue) to handle the top bar when viewing a resource.

---

I think that the context menu shouldn't be implemented at all for acceptance of this since none of the functionality there in can be hooked up. In this case a follow-up issue could be created and the work here could be simplified a little bit (who knows the requirements for that form might change so why make it a requirement if it's not actually fully designed and planned?).

I'll get #8095 for the bookmarks done today so you can have that available.

---

@khangmach what does "View Lesson Plan" do? When does it show - only when the user entered the resource _from_ a lesson or if the resource is in any lesson? What if the resource is in multiple lessons?

**Comment by nucleogenesis** [comment]
Also - those icons are not currently available and won't be until https://github.com/learningequality/kolibri-design-system/pull/236 is merged and a release is made.

If KDS doesn't provide a release, you can target the branch directly or `yarn link` to the local repo during development to have access to the new icons.

**Comment by marcellamaki** [comment]
> I think that the context menu shouldn't be implemented at all for acceptance of this since none of the functionality there in can be hooked up. In this case a follow-up issue could be created and the work here could be simplified a little bit (who knows the requirements for that form might change so why make it a requirement if it's not actually fully designed and planned?).

That sounds fine to me @nucleogenesis! Thanks for your feedback

**Comment by khangmach** [comment]
@nucleogenesis

See the figma file for more specific specs, but basically it opens up a side sheet component where the user can see all the other resources in that topic node (if they're in a topic resource) or lesson (if they're in a lesson resource). If the resource is multiple lessons that's fine, the drawer should only show resources pulled from the lesson it came from/currently resides in.

**Comment by MisRob** [comment]
@nucleogenesis @marcellamaki 

> This is kind of a built in if you update the existing component I think. It doesn't seem like we'd need a separate version of the component to handle the updates.
> Just want to note that we currently use ImmersiveToolbar to handle the top bar when viewing a resource.

It may not be the case - depends on implementation details. After doing a bit of research and planning today, I am actually preparing a new component, focusing on a new UI and responsive behavior, because at this point it's simpler. I will see later how much logic I will use from the `ImmersiveToolbar` itself. I am working on it in a way so that we can eventually switch those two.

From my point of view, it makes sense to have this issue prepared as is, focusing on styling and UI logic. I don't think we could refactor `ImmersiveToolbar` at this point because that would break Kolibri - there is a lot of logic that is not in place to be able to make a new toolbar functional. We don't even have some required metadata specified. For example, see [@rtibbles 's comment](https://learningequality.slack.com/archives/CB37UM23A/p1622560330068200?thread_ts=1622539686.067200&cid=CB37UM23A):
> We will be adding new constants for these activities, but the metadata is still being specced

---

> I think that the context menu shouldn't be implemented at all for acceptance of this since none of the functionality there in can be hooked up. In this case a follow-up issue could be created and the work here could be simplified a little bit (who knows the requirements for that form might change so why make it a requirement if it's not actually fully designed and planned?).

Regarding the context menu, it's not very clear to me how to work on it separately, because it directly depends on a toolbar for smaller breakpoints - the same items can be displayed in a bar or in a context menu depending on the screen size. If we don't want the context menu, we will need to get rid of those items in the navbar too. Can we do that?

---

If there is no agreement on this, I'd suggest having a look again at what we need before I continue working on it.

**Comment by MisRob** [comment]
As [discussed on Slack here](https://learningequality.slack.com/archives/CB37UM23A/p1622539686067200), some dependencies of this issue may need to be clarified

**Comment by MisRob** [comment]
@marcellamaki:
> It's fine to proceed as is, and focus mostly on the UI aspects of the feature as originally described in the ticket

I'm continuing my work on this
