### ISSUE TITLE
Hybrid Learning Library, Topics pages -- design alignment follow up to-dos 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8563]
Topics Page 
- [x] Header - title alignment, better truncation, and overall spacing. 
- [x] Header - add text truncation for description 
- [x] Remove "channels" breadcrumb
- [x] Add "active" styles for folders and search tab 
- [x] Add "show more" option below trimmed channel resources 
- [x] Add "end folder view" 
- [x] Add header for folder topic above topic links
- [x] update footer: add progress, remove "more options" footer icon 
- [x] Remove breadcrumbs for search 
- [x] investigate and potentially fix breadcrumbs - some of the ordering seems incorrect
- [x] Fix "squished" view on limited search results
- [x] Remove thumbnail outline on topic thumbnail in header

Library page 
- [ ] change colors, and background color to tokens
- [x] Fix mobile card view that sometimes shows up as a grid with toggle, when should just be single card
- [x] Fix "squished" view on limited search results
- [x] Fix text overflow caused by shrinking page and long title
- [x] search: card spacing, and ensure toggle list/grid is visible 
- [ ] remove list/grid toggle if no content cards displayed

Classes page 
- [x] remove 'Library' breadcrumbs

Bookmarks page 
- [x] Card: Add text truncation to manage long description overflow and spacing issues 

Search panel
- [ ] Clear an activity or category by clicking on an active button
- [x] Fix spacing on side bar to ensure scroll to the bottom of the panel works, even on a limited folder list in the main content [ETA: this is actually because Marcella is so used to seeing the dev view, and it was not actually broken]
- [x] Activity buttons should appear on mobile

Cards 
- [ ] double-digit coach count overflows side of card
- [x] [Fix label ordering and alignment](https://github.com/learningequality/kolibri/pull/8708#pullrequestreview-808114144)

**Comment by pcenov** [comment]
Hi @marcellamaki, posting here some additional issues spotted after testing [this 0.15 build](https://buildkite.com/learningequality/kolibri-python-package/builds/4003) so that you can sift through them and maybe disregard or create follow up to-dos:

Major issues:
1. Library - Clear all is not functioning now - clicking on it results in a TypeError: Cannot convert undefined or null to object

![2021-11-02_14-31-33](https://user-images.githubusercontent.com/79847249/139894499-0e069e9d-9cb4-4e39-9a60-0ab5a82c2642.png)

2. Browse channel: clicking the 'i' icon results in a error that freezes the entire browser page - TypeError: Cannot read properties of undefined (reading ‘id’)
Library/Recent: 0 locations link???

![2021-11-02_16-12-46](https://user-images.githubusercontent.com/79847249/139895461-85d41bf9-a16c-478d-836d-ba87f9167d72.png)

Minor issues:
1. Console error - Selecting any of the filtering options causes the following error in the console: Uncaught (in promise) Error: Avoided redundant navigation to current location: "/library".

![2021-11-02_14-35-58](https://user-images.githubusercontent.com/79847249/139895981-3c7d66cd-7408-4798-888f-e7e8ba872a6a.png)

2. Browse channel console error: Errors in the console such as: TypeError: Invalid attempt to spread non-iterable instance. In order to be iterable, non-array objects must have a [Symbol.iterator]() method.

![2021-11-02_14-37-10](https://user-images.githubusercontent.com/79847249/139896567-1d897257-df43-4788-8980-dc2165ac43d7.png)

3. Library: Channel cards are misaligned in responsive design view.

![2021-11-02_16-00-35](https://user-images.githubusercontent.com/79847249/139897280-07beed4c-463d-4bb2-9654-f76e684570fc.png)

4. Library/Recent: 0 locations link

![2021-11-02_16-38-23](https://user-images.githubusercontent.com/79847249/139901498-e52d488f-b5d8-48ed-9f70-5c43d63fa974.png)

5. Bookmarks link displayed in 'Manage resources' for a lesson looks like a work in progress and I'm not sure it it is a known issue:

![2021-11-02_16-31-39](https://user-images.githubusercontent.com/79847249/139899504-f5474ceb-695d-4977-8dfc-2bce180acd68.png)

**Comment by jtamiace** [comment]
In a channel, within the level 3 breakpoint, probably better to display 3 cards per row instead of 4

<img width="959" alt="Screen Shot 2021-11-04 at 3 00 44 PM" src="https://user-images.githubusercontent.com/6668144/140433447-b9434474-a5c4-47cf-9113-608dd3b14eb8.png">

---

The number of cards that show per row in "Recent" and the cross-channel search results should be consistent with the cards within a channel. Right now it shows 3 per row even at the widest browser width

<img width="934" alt="Screen Shot 2021-11-04 at 4 17 08 PM" src="https://user-images.githubusercontent.com/6668144/140434869-6d0af725-d6b4-4d3e-9fea-b5229193d1af.png">

---

Sorry if this is already resolved somewhere else [and/or we're not quite ready to do this yet (slack thread)](https://learningequality.slack.com/archives/C023DNC5GCX/p1634223121207500?thread_ts=1634192628.194100&cid=C023DNC5GCX), but the "Classes" tab and "Library" action should be removed

<img width="739" alt="Screen Shot 2021-11-04 at 4 16 20 PM" src="https://user-images.githubusercontent.com/6668144/140434595-f38e76fe-08cc-49ad-b4e1-89ef8eefb39d.png">

---

Cards within a channel shouldn't have the channel thumbnail show in the top right corner. Also have some notes to make more room on the cards for longer titles

<img width="870" alt="Screen Shot 2021-11-04 at 4 16 47 PM" src="https://user-images.githubusercontent.com/6668144/140434639-d41765ff-dbe1-485b-8d7a-d488b8ffbf42.png">

---

"View more" raised secondary button for more visual prominence in the search results

<img width="771" alt="Screen Shot 2021-11-04 at 4 16 57 PM" src="https://user-images.githubusercontent.com/6668144/140434762-7b9475ce-8eec-4017-82c3-654e9e4721eb.png">

---

At the end level of a folder, we should keep the Folders panel even though it would only have one folder listed ("Install a Solar Panel" in this example).

<img width="908" alt="Screen Shot 2021-11-04 at 4 29 56 PM" src="https://user-images.githubusercontent.com/6668144/140435235-d9748e6f-b3e4-4ca6-922a-5f92c76228d2.png">

---

And......... I do not have a solution at the moment but I realize how challenging the mobile experience will be and I will get back on a better experience here

<img width="492" alt="Screen Shot 2021-11-04 at 4 18 49 PM" src="https://user-images.githubusercontent.com/6668144/140435732-ef5d6134-218b-45c9-ac62-b9189cb64000.png">
