### ISSUE TITLE
Fix issue with info panel freezing, not closing

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8611]
Reported by @bjester and @jtamiace during bug bash 

> Clicking the info icon on a resource in the Library tab opens a side panel with information, but there's no way to close it as the "X" does not function and clicking outside doesn't close it either. Tab CPU consumption hits 100% and stops responding

> Kolibri froze and crashed after opening information panel while browsing a channel. Repeatable

**Comment by marcellamaki** [comment]
See also https://github.com/learningequality/kolibri/issues/8594

**Comment by nucleogenesis** [comment]
@jtamiace @bjester 

What channels/contents were you viewing when you encountered the error?

Would you be able to replicate and try to salvage a screenshot of any console errors that might be coming up? I've tried to replicate with many types of contents in several channels but not once have I had any issue with either of:

- 100% CPU infinite loop / memory leak situation
- Being unable to close the side panel

I tried Fedora & Ubuntu & iOS Chromes but could not replicate.

Perhaps there is some quirk of how a channel is set - or perhaps I need to try again with more cross-channel shared contents? In any case, whatever content you replicate with will hopefully do the same on my end.

**Comment by pcenov** [comment]
Hi @nucleogenesis, I can replicate this issue in the [latest 0.15 build](https://buildkite.com/learningequality/kolibri-python-package/builds/4103) by going to the Library page, selecting any of the available channels such as Sikana and then clicking the View Information icon on any of the resources displayed within the Browse channel view:

![2021-11-10_13-28-09](https://user-images.githubusercontent.com/79847249/141105500-f487c8f2-ab9f-48f1-8df2-4b83d5cd4ecf.png)

Note that I'm currently not seeing any errors for that in the browser console.
However when I initially reported that issue here: https://github.com/learningequality/kolibri/issues/8563#issuecomment-957902024 the error was: `TypeError: Cannot read properties of undefined (reading ‘id’)`

![2021-11-02_16-12-46](https://user-images.githubusercontent.com/79847249/139895461-85d41bf9-a16c-478d-836d-ba87f9167d72.png)

cc @radinamatic

**Comment by bjester** [comment]
@nucleogenesis It appears this happens specifically when browsing a channel. Here are steps to reproduce:
1. Open Chrome's task manager
1. Sign in as a learner
2. Click the Library tab
3. Browse a channel on the device
4. Click the info icon on a resource
5. See the tab consuming 100% of CPU once open
6. Cannot close the info side panel

I ran profiling when this happened. It seems it's stuck in a re-render loop
[Profile-20211110T075913.json.zip](https://github.com/learningequality/kolibri/files/7514190/Profile-20211110T075913.json.zip)
