### ISSUE TITLE
Library Search - Category labels are not right aligned when viewed in RTL language

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8771]
## Observed behavior
The labels of the Categories are not right aligned when viewed in RTL language.

## Expected behavior
The labels of the Categories should be right aligned.

## Steps to reproduce the issue
1. Install the following [build.](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta2)
2. Import some channels and run the following management command: `kolibri manage labeltestdata `
3. Switch to RTL language such as Arabic and observe the labels of the Categories.

## Additional information

![2021-11-23_17-05-05](https://user-images.githubusercontent.com/79847249/143052752-c7f7fa3f-5480-47e7-baa5-741f4f194b81.png)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by akash5100** [comment]
can you point out the code? It would be helpful

**Comment by MisRob** [comment]
Hi @akash5100, it seems that categories are [in this `<div>` of `EmbeddedSidePanel` component](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/learn/assets/src/views/EmbeddedSidePanel/index.vue#L58).

Do you use [Vue.js devtools](https://devtools.vuejs.org/)? Besides other things, it can be handy for locating a component in Vue code since it can display the whole tree of Vue components

![devtools](https://user-images.githubusercontent.com/13509191/143897650-b5ac2ae0-0c40-45ac-894d-0a9aecb54135.png)

and it also offers[ the "Select component in a page" feature](https://flaviocopes.com/vue-devtools/#select-component-in-the-page). Once you have the component name, you can locate it in the code more easily :)

Are you still planning to work on this issue?

**Comment by akash5100** [comment]
Thanks for the information, I will start working on it.

**Comment by MisRob** [comment]
Great, thank you

**Comment by MisRob** [comment]
@akash5100 I'm adding you as an assignee and am also adding myself. I am not working on it, assigning myself only to keep an eye on the issue. Let me know if you need anything.

**Comment by akash5100** [comment]
Hey @MisRob, are you here?
I haven't changed the code yet, I tried the Vue developer tools ( It was amazing ), Can you check the following output?

# before
![Screenshot from 2021-11-29 23-39-24](https://user-images.githubusercontent.com/53405133/143920935-b1231f78-52ee-4590-97f4-681ff7b4346d.png)

# after making changes in developer console
![Screenshot from 2021-11-29 23-39-11](https://user-images.githubusercontent.com/53405133/143921042-8928dd8c-1c19-456a-a7a0-996f4eb9c0ad.png)
![Screenshot from 2021-11-29 23-38-53](https://user-images.githubusercontent.com/53405133/143921053-995dd699-a4ce-4b71-a41a-09c5c0ee63c9.png)

**Comment by MisRob** [comment]
Thank you @akash5100, the output looks good to me :+1:  We also have a section on [RTL support in our documentation](https://kolibri-dev.readthedocs.io/en/develop/i18n.html#rtl-language-support) that might be helpful to check before submitting a PR, if you haven't seen it already.

**Comment by akash5100** [comment]
Hi @MisRob, I found that `dir: rtl` was not working on the KButton component so I tried changing the display type. I am not sure this is correct or wrong but it gives the desired output. 
Please have a look at this, if anything is wrong please tell me.
![kolibri-3](https://user-images.githubusercontent.com/53405133/143984916-e3f0e491-c8f4-45c8-ac1f-36abbe454103.gif)

**Comment by akash5100** [comment]
@MisRob should I submit a PR with the above solution?

**Comment by MisRob** [comment]
Hi @akash5100, we use `dir="auto"` for user-generated text (e.g a resource title) but categories labels are predefined in our codebase so there should be no need to change `direction` or `dir`. If you have a fix working, feel free to open a PR, and we can follow up there after seeing your code changes.

Just to clarify, was your recording made on a dev server with a hot reload?

**Comment by akash5100** [comment]
devserver

**Comment by MisRob** [comment]
I see an issue that might also mean a problem in our automatic flipping of `text-align` from `left` to `right` that should happen during the build process. However, this can also get broken on the dev server with hot reloading on which is something we're aware of and it shouldn't impact bundles produced without hot reload (mentioned in the guide I referenced). So asking to know if this would be something to check on too.

Thank you for debugging.

**Comment by akash5100** [comment]
No, I haven't used hot reload, 

> Hi @akash5100, we use `dir="auto"` for user-generated text (e.g a resource title) but categories labels are predefined in our codebase so there should be no need to change `direction` or `dir`. If you have a fix working, feel free to open a PR, and we can follow up there after seeing your code changes.
> 
> Just to clarify, was your recording made on a dev server with a hot reload?

**Comment by akash5100** [comment]
I started the server with `yarn run devserver`
I think hot reload is off in this command.

**Comment by akash5100** [comment]
Sorry to disturb you but I am new to vuejs can you help how should I change the display to flex for each `KButton`'s

**Comment by MisRob** [comment]
Was there any particular reason for using `flex` to fix this issue? Since I saw on your recording that we have set `text-align: left` on buttons, at first, I'd recommend checking that it's been changed properly to `text-align: right` after you switch to RTL language without hot reload. If it's not happening, then you can try to do it in code on your own by conditionally choosing between `text-align: right` and `text-align: left` style based on whether `isRtl` is `true` or `false.` `isRtl` is one of our utilities that is available for use in each component. You can [see an example here](https://kolibri-dev.readthedocs.io/en/develop/i18n.html#behavior), or you can search the codebase for more examples.

Regarding styling Vue components or Vue components in general, I recommend Vue documentation, where you can also find a [section on various ways to style components](https://vuejs.org/v2/guide/class-and-style.html), including dynamic styling. Regarding styling specifically `KButtons` that are coming from Kolibri Design System you can have a look at [`appearanceOverrides` property](https://design-system.learningequality.org/kbutton/#prop:appearanceOverrides).

**Comment by akash5100** [comment]
Thank you @MisRob for your guidance.
I submitted a PR please have a look!

**Comment by MisRob** [comment]
Thank you too, @akash5100
