### ISSUE TITLE
Potential completion modal error when clicking "Move On"

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8848]
From @jtamiace: Clicking 'Move on' from the completion modal gave me an error but I'm having trouble reproducing this

https://www.notion.so/learningequality/REGRESSION-Learn-Content-renderer-27-BUG-3d5728de3b8c430e848bf654bf27bf77
<img width="1323" alt="Screen Shot 2021-12-07 at 10 15 58 AM" src="https://user-images.githubusercontent.com/17235236/145107352-a0534b6a-34ef-43dc-a9db-18e158a33830.png">

**Comment by jredrejo** [comment]
@jtamiace can you lend me a hand to reproduce this problem?
OS, browser and an example of resources that're causing it?
I have tried several combinations without success, the  '`Move on'` button always worked fine

**Comment by jtamiace** [comment]
Yes I'll try. It happened a few times but not consistent

**Comment by jtamiace** [comment]
I was able to reproduce this in a different way but it gave me the same error as "move on" 
1. Click into a video
2. Refresh the page while on the video
3. While the video is playing, open the "Also in this" panel
4. Click a resource in that list

![ezgif-7-b6ee0ed0476f](https://user-images.githubusercontent.com/6668144/145307156-9f756aa4-cd3f-4d7c-a006-0d259da2723b.gif)

For comparison, here is the error after clicking "Move on" but I still haven't been able to reliably reproduce this
<img width="1478" alt="Screen Shot 2021-12-08 at 3 08 02 PM" src="https://user-images.githubusercontent.com/6668144/145307333-f6fe20e9-0216-4eb6-bb70-c31d4c913258.png">

**Comment by rtibbles** [comment]
I think this is a consequence of the global logging state. Because it's not encapsulated on a per resource page basis, it is possible for logging for the old session to interact with logging for the new session.

I have some WIP work that may help address this by encapsulating the logging state into a composable helper, meaning it should no longer be shared. I can take this on.

As such, I think this is related to and has the same underlying cause as: https://github.com/learningequality/kolibri/issues/8776
