### ISSUE TITLE
PDF resource completion

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#8868]
## Observed behavior
It does not seem possible to achieve completion on any PDF file, no matter how short they are, or time learner spends with the resource. I added 3 more short PDF files (3-9 pages) to the QA channel, but it seems impossible to complete them.

## Errors and logs
…

## Expected behavior
Ability to complete PDF resources.

## User-facing consequences
... 

## Steps to reproduce
...

## Context

 * Kolibri version: 0.15.0b3
 * Operating system: Android 8.0 and 9.0
 * Browser: -

cc @marcellamaki @rtibbles

**Comment by sairina** [comment]
Additional issues noted with the PDF resource completion:
- The PDF renderer is not registering the first page of the PDF as being visited (unless a user stops scrolling at some point on the first page)
- The content card does not register immediately (or sometimes too quickly) that the PDF has been completed. The progress bar is still there even when the user has completed the PDF in the renderer and points have been awarded.

**Comment by pcenov** [comment]
Just adding a note here that I'm managing to 'hack' the pdf completion by first decreasing the size of the pdf pages and then increasing it up to  about 150% percent and slowly scrolling down. Not sure why that works but it sure does so adding it here as an additional clue...

**Comment by jamalex** [comment]
I'm still seeing some version of this on 0.15.1 -- pages that I spend time on and scroll back and forth past still often don't get marked as completed. Context: https://kolibri-demo.learningequality.org/en/learn/#/topics/c/57bc2d771781589fb353abc14964ad91?lessonId=461fd0c27110982efc30768d55a0ff84&classId=4d3ff8ff23e47585c6cee4d7460aa48b&last=LESSON_PLAYLIST

**Comment by akash5100** [comment]
Hey @radinamatic, I have worked in the past with pdf rendering. So I feel I could help with some pdf-related issues. Any pointers on how to get started?

**Comment by sairina** [comment]
Hi @akash5100 , would love it if you could take a look at this issue. Some of the original glitches seemed to have been fixed, but as you can see, there seems to still be bugginess in trying to track completion. In [this PR](https://github.com/learningequality/kolibri/pull/8937), you'll find some of the files that are relevant to this issue, particularly in the `useProgressTracking` composable.

**Comment by akash5100** [comment]
Hi, @sairina thank you for the reply. With the help of that I went through the issue, and it's a bit confusing :)

When I tried to read pdf's in the development server I found that on the top the icon "in progress" doesn't change to "complete", which happens in your [PR](https://user-images.githubusercontent.com/13563002/146285425-765612c1-a52d-4c5c-87ee-2fdebbcbb34a.gif) (when you finished reading the pdf). So is this the issue here? (can I get any more details?) 

Can you tell me how the files under `__test__` are executed like you did [here](https://github.com/learningequality/kolibri/pull/8937/files#diff-470423c5d12491f1c837cf725608c0716f97c205025a5ad54bb940a1c7ed1076) (should I make changes under `__test__` dir? )

**Comment by sairina** [comment]
Oof, that's so unfortunate!

I just pulled that branch and it seemed to be that I was able to get the icon to change, so that is strange 🤔 . However, a lot has changed in the code since then (I think including dependencies), so it's possible that this is no longer working OR that my original fix was not the right fix - also highly possible. 

To run tests, we use `yarn run test-jest [file_name]`. If you want to add tests to that component, you can just add them to the test file and they will get run.

@radinamatic, would you mind testing this issue again and seeing exactly what the problems are? I think that will help us better define the problem.

**Comment by sairina** [comment]
@akash5100 I did a quick run-through of the typical user workflow for reading a PDF on the `release-v0.15.x` branch, and this is what I found to be the current problem:
- If a user clicks on a PDF resource and starts reading, progress is being tracked, but there is no longer any visual indication in the component (the icon - `ProgressIcon` - in the bar at the top of the page -`LearningActivityBar` - is not updating)
- However, when the user is back on the `TopicsPage` (the page with all the content cards), the progress bar does show progress.
- If the user than clicks back into that PDF from the content card, you will see the `ProgressIcon` appropriately indicating that it is in progress, and it will correctly turn to "complete" when all the pages in the PDF have been viewed both in the activity bar at the top of the page and back on the content card.

Hope that helps at least for you to get started - let me know if you're seeing a different issue pop up as you investigate this more closely.

**Comment by akash5100** [comment]
Thanks, @sairina that's a lot of help. I start my research on this issue and open a PR soon. 😄

**Comment by akash5100** [comment]
Just a small question, When we fork kolibri the default branch is `release-v0.15.x` whereas in here the default branch is `develop`, so if I make any changes should I work on `develop` or `release-v0.15.x`, and while making a PR I should target `develop` branch is that right?

**Comment by rtibbles** [comment]
Fixed in #9776
