### ISSUE TITLE
Forms not working in HTML5 content on v15 (but had worked in 0.14)

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#8984]
[Reported from the community forum](https://community.learningequality.org/t/forms-not-working-in-html5-content-on-v15/2274): 

> Hi LE team
> Some HTML5 content that we have imported from RACHEL have forms elements in order to browse for content quickly.
> In v14.7 there was a [HTML5] section in options.ini file
> We just added allow-forms to the “sandbox” line and then forms worked right away
> v15 options doesnt have this section, we have added it but with no results, kolibri ignores that section
> The new documentation doesnt say anything about it
> How can we get forms to work in v15?

**Comment by jredrejo** [comment]
Forms and any other external HTML loaded by kolibri do work.
It's just the `HTML5` section does not exist any more because it's not needed.

Any HTML5 content loaded by kolibri is now server under a different TCP port to allow both full functionality and avoid security risks to kolibri itself.
If a server is used to receive these external forms data they have to be aware of their different TCP setup that can be either automatically assigned by kolibri or manually set by [the `ZIP_CONTENT_PORT` option](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/utils/options.py#L464-L472)
