### ISSUE TITLE
Refactor HybridLearningCardGrid to make less brittle and improve readability

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9004]
The HybridLearningCardGrid component handles a variety of different card displays and manages mobile responsiveness. The code is also inconsistent in places, especially around the conditions that determine the card style that is rendered in the grid. 

The following problems should be solved by the refactor: 
- [ ] update all places that check which page is the current page to consistently use `PageNames`
- [ ] brittleness in conditions/checking
          - can the conditional checks themselves be improved for stability? If so, refactor these
          - otherwise, they should at least be easier to read (potentially turn into computed props rather than long `&&` `||` etc
- [ ] comments should be added for readability and understanding which cards are rendered by which sections of code
- [ ] any other cleanup welcome

Important also when refactoring the conditions to ensure that the mobile view doesn't display two very long (vertically) very squished (horizontally) cards, a regression that popped up earlier, although I cannot find the issue now...

**Comment by MisRob** [comment]
Regarding

> update all places that check which page is the current page to consistently use PageNames

I'd rather suggest removing these "current page" dependencies

https://github.com/learningequality/kolibri/blob/2f93cb01fe9de910843bbaf462ae82c5b7a088ea/kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue#L20

and all others completely from `HybridLearningCardGrid` and its sub-components.

Generally speaking, a component that's responsible for grid layout and cards rendering doesn't need to know what page it is on. Such dependencies usually result in bad readability and more maintenance time. I can see that the `HybridLearningCardGrid` has more responsibilities than only the layout of cards, however, I haven't noticed anything that would be preventing us from solving this in a different way. Some possible solutions might be to rather use more components or have something similar to [`CardGrid` types](https://github.com/learningequality/kolibri/blob/2f93cb01fe9de910843bbaf462ae82c5b7a088ea/kolibri/plugins/learn/assets/src/views/cards/CardGrid.vue#L39). `HybridLearningCardGrid` is more complex than `CardGrid` though and it seems to me that it'd be more straightforward to have its logic split into different components for the library, lesson. and bookmarks pages. That would also help us to get rid of these conditions

https://github.com/learningequality/kolibri/blob/2f93cb01fe9de910843bbaf462ae82c5b7a088ea/kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue#L20

https://github.com/learningequality/kolibri/blob/2f93cb01fe9de910843bbaf462ae82c5b7a088ea/kolibri/plugins/learn/assets/src/views/HybridLearningCardGrid.vue#L31

would make testing (https://github.com/learningequality/kolibri/issues/8983) easier and better readable,

and we might not need comments

> comments should be added for readability and understanding which cards are rendered by which sections of code

since it won't be complex by means of design itself

**Comment by marcellamaki** [comment]
That's a great suggestion @MisRob -- I definitely think this could be a better approach, and it would also allow us to make use of the regular KGrid or KFixedGrid in many places, rather than trying to fit everything into one complex component. I'm going to get started on this today, and would love your review later this week :)

**Comment by MisRob** [comment]
Of course, thank you @marcellamaki
