### ISSUE TITLE
Internet Explorer - The info side panel is not displayed

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9100]
## Observed behavior
The info side panel of a resource is not displayed when I click the info icon of a card at the Library page or at the Bookmarks page while using IE browser.
This issue was initially reported here: https://github.com/learningequality/kolibri/pull/9063

## Expected behavior
Fully functional side panel in IE browser.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-windows/builds/3154
2. Go to the Library/Bookmarks page and click the info icon of a card.

## Screenshots
![2022-02-11_15-25-53](https://user-images.githubusercontent.com/79847249/153612389-bcce6a43-d08c-44f3-8a00-582d0caffb56.png)
![2022-02-11_16-20-04](https://user-images.githubusercontent.com/79847249/153612392-0b6b09ac-4cf8-4db9-99da-43cc4c17e7a7.png)

## Usage Details
Windows 7 and 10, Internet Explorer

**Comment by pcenov** [comment]
@radinamatic

**Comment by radinamatic** [comment]
I'm able to replicate this in IE11, and apparently the same error happens when user clicks on the *View folder resources* or *View information* buttons. 

On top of it, after that error occurs, which has no user-facing notification (just the console), the _Go back_ button (top left arrow) does not work, and the user is effectively stuck there with no way to go anywhere, a part from manually editing the URL (if they know how) 😞 

*View folder resources* | *View information* | _Go back_ (top left arrow)
--- | --- | ---
![Win10 (start)  Running  - Oracle VM VirtualBox_001](https://user-images.githubusercontent.com/1457929/153804625-f029d6b0-1e49-4393-8a29-26fd0c825be1.png) | ![Win10 (start)  Running  - Oracle VM VirtualBox_002](https://user-images.githubusercontent.com/1457929/153804624-f39ae7e9-8dfe-4713-9b40-96363e16f3b2.png) | ![Win10 (start)  Running  - Oracle VM VirtualBox_003](https://user-images.githubusercontent.com/1457929/153804621-fefaf725-d2d0-4d7d-8371-d02ca4d3d644.png)

**Comment by radinamatic** [comment]
@marcellamaki This looks like P0 (blocker) to me.

**Comment by MisRob** [comment]
Seems to be more important than what I've been working on so I'll check if I can find out something before our US friends get up :)

**Comment by MisRob** [comment]
Made some progress but am not done yet, see https://github.com/learningequality/kolibri/pull/9103. I'm unassigning myself now in case someone would like to pick this up. If I don't see anyone working on this tomorrow morning, I'll finish it.

**Comment by MisRob** [comment]
Should be fixed by https://github.com/learningequality/kolibri/pull/9080

cc @marcellamaki @pcenov @radinamatic
