### ISSUE TITLE
Create new routes for change facility workflow

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9319]
# Overview 

This issue is to support the implementation of the state machine created in #9318. The states created in this issue will each have a route associated with them. This issue adds those routes to the `user_profile` plugin.

## Acceptance Criteria 
- [ ] Add routes for each route identified in the new xState machine for facility change

**Comment by jredrejo** [comment]
@marcellamaki  I agree with the comment @rtibbles did on #9318 , and even more after looking at the Figma design. The user story starts on its Profile page and he does not need to have access to the Facility plugin at any moment. I think routes should be created in `user_profile` plugin instead of the `Facility` one.

**Comment by marcellamaki** [comment]
Yes, thank you @jredrejo -- I should have updated that point in this issue as well. I will edit it to correctly reflect that it should be the `user_profile` plugin

**Comment by marcellamaki** [comment]
Close with #9419
