### ISSUE TITLE
Create "Choose Admin" page

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9326]
# Overview 

Adds a page where a user can select a new admin, if the current user leaving the facility is the superadmin.

## Figma 
![Screen Shot 2022-04-20 at 11.08.44 AM.png](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/cca831f3-fc71-4b8f-b145-f6807782f518)

### Accessibility notes
Tab order: 
1) Search for user
2) Radio buttons in read order (top to bottom)
3) "Continue" primary button 
4) "Back" secondary button 
5) "X" close out flow 

### Out of scope 

Adding the route itself is not part of this issue

### Acceptance criteria

- [ ] Page is created with correct strings
- [ ] Results correctly display possible admins to choose from, and using the "search for a user" correctly filters results
- [ ] UI layout to spec with correct tab order and spacing
- [ ] Continue button disabled until a user is selected

**Comment by MisRob** [comment]
Before implementing this issue, we need to decide what happens in the change facility workflow when there's only one user and therefore there's no one to choose the new admin from. This could happen in general and at this point, we don't even allow a user to access the change facility feature if their facility has some other users. Therefore with our current assumptions, implementing this step wouldn't make sense right now since the only user will never have some other users to choose from.

Even if we decided to allow the change facility feature on facilities that have more users, we will still need to clarify what should happen when there's only one since that could happen. I assume that we could simply skip this screen in such a case, but let's confirm that first as it relates to other decisions that need to be made.

Some suggestions and more information can be found [in this Slack thread](https://learningequality.slack.com/archives/CB37UM23A/p1657194662123749), but we didn't make a decision yet.

cc @jtamiace @marcellamaki @jredrejo @rtibbles

**Comment by jredrejo** [comment]
@MisRob is this blocking the work on the following screens?
If it's blocking it I think you could do a blank screen with just a continue button so we continue working in the rest of the epic while a decission is made.

**Comment by MisRob** [comment]
I think it doesn't need to block work on other screens since we use the state machine. We can implement states quite independently on another states, and then at some point, connect the remaining pieces, I'd say?

**Comment by MisRob** [comment]
- we decided to allow access to the change facility workflow on certain kinds of facilities even when they have more users => makes sense to implement it
- when there's only one user we'll skip this screen
