### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by maxbrunet** [learningequality/kolibri#9486]
Python 2 has reached its end of life on January 1, 2020, meaning it does not get any more bug or security fixes:

> In 2006, we started Python 3.0. [...] In 2008, we announced that we would sunset Python 2 in 2015 [...]. In 2014, we extended that sunset till 2020.

https://www.python.org/doc/sunset-python-2/

It also increases the development burden and blocks updates of many dependencies:

- Django 2+
- pytest 5+
- pytest-django 4+
- SQLAlchemy 2+
- ...

It seems Kolibri has been supporting Python 3 from day one.
I believe all major Linux distributions have stopped depending on Python 2 for their core packages. 

To do before:

- Communicate end of support timeline to end-users
  - Announce last release supporting Python 2 in release notes
  - Warn user still using Python 2 about end of support via startup log, banner
- If needed, document how to migrate Kolibri setup from Python 2 to 3 and share link

To do:

- Remove Python 2 tests from CI
- Update required Python version for package (e.g. setuptools' `python_requires`)
- Possible clean up of Python 2 workarounds (e.g. `__future__`, `six`, `if sys.version_info`...)

Blocking issues, if any:

- #...

**Comment by rtibbles** [comment]
Noting that the main blocker here is that according to our anonymized telemetry reports we still have a significant number of Kolibri installations using Python 2.

All of these appear to be on Linux systems, so it is possible that this is due to default `python` still being Python 2 - but we will hopefully gather more information after the release of 0.16 that will help us further clarify this.

**Comment by rtibbles** [comment]
This has been completed.
