### ISSUE TITLE
Enroll learners/Assign coaches - Missing search bar

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9519]
## Observed behavior
The search bar at Facility > Classes 'Enroll learners' and 'Assign coaches' has disappeared. It's still there in 0.15.2 so this is a regression caused by a change in 0.15.3. There are no errors in the console. 

## Steps to reproduce the issue
1. Install the official 0.15.3 Kolibri build
2. Go to Facility > Classes
3. Select or create a class 
4. Select 'Enroll learners' or 'Assign coaches'

## Screenshots
![2022-06-15_16-26-15](https://user-images.githubusercontent.com/79847249/173839454-a1a124e5-36cc-4deb-ac9f-2c5ccb9d7ff6.png)

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic

**Comment by marcellamaki** [comment]
Closed with https://github.com/learningequality/kolibri/pull/9525

**Comment by eapdso** [comment]
We are seeing this issue happening again in 15.7 version. Can this be reopened as a regression?

**Comment by radinamatic** [comment]
@eapdso The current release is 0.15.8 where the issue is not extant anymore. Please [update your Kolibri](https://learningequality.org/download/) instance.

![Win10 (0 15 8)  Running  - Oracle VM VirtualBox_001](https://user-images.githubusercontent.com/1457929/195903055-39d65f68-5eac-4773-b3c6-bf9674570ee7.png)
