### ISSUE TITLE
Completed EPUBs  should not be  shown on the most recent 

### ISSUE THREAD

**Issue by AllanOXDi** [learningequality/kolibri#9745]
## Observed behavior
Completed content is still being filtered and returned in the recent filter.
The progress bar does not correlate with the consumed content progress. This might be the reason for the bug

## Errors and logs
Video of behaviour:

https://user-images.githubusercontent.com/1680573/192615285-b04348e7-ca04-499c-a114-47de3294114a.mp4

## Expected behavior

When a learner(User) finished interacting with the epub, it should not be returned on the most recent filter. It should be discarded from the filter 

## User-facing consequences

…

## Steps to reproduce

…

## Context

 * Kolibri version 0.15.7
 

…
cc @rtibbles

**Comment by nucleogenesis** [comment]
I dug into the EPub renderer a while back and I think the issue I was looking at is related here.

If I am recalling correctly, the logic around tracking progress as a user goes through pages is busted where the epubjs instance is not consistently sharing the total number of pages. Epubs reflow (change their amount of pages altogether) as the space available changes (or font size, etc) so how the % is calculated of how much the user has viewed was never able to get to 100% so the Epub would never show 100% (it got stuck at 99% or something) and I think this may be related to the issue here.

Hope this helps a bit - good luck!

**Comment by rtibbles** [comment]
From what I recall, the issue was that we were using a mechanism that should be robust to reflow, but that there was another issue happening in terms of the generation of the page ids that was causing the issue.

**Comment by AllanOXDi** [comment]
Update! From what I have seen so far. This issue is affecting not only EPUBs but some video content as well. This gives us a little bit more clue on what to look for.

**Comment by AllanOXDi** [comment]
This seems to be fixed by PR #9813. I am closing it.
