### ISSUE TITLE
Device Settings Updates: Primary and Additional Storage Location(s)

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9780]
## Overview 

This issue is a full-stack issue that updates the Device Settings page to include a setting where the user can determine the primary storage path. It also implements the full CRUD functionality, so a storage path can be added, deleted, and read, and the storage location which is the primary can be changed.

To avoid having to create a new migration for each field, we will be using a feature branch for this project `update-device-settings`. Please make PRs to this branch, which will later be merged into develop when the feature is complete.

### Figma 

Please see [complete figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1384%3A16773).

➡️ Accessibility notes: 
* The title for this section ('Download on metered connection') is an `<h2>`
* Please use `KComponents` for wherever possible to ensure that the content is properly passed on to screen readers, and that focus outlining and focus shift works. (See [KDS docs](https://kolibri-design-system.netlify.app/) for more information)

### API changes 

The changes to the API should be made within the existing API file in the `/device` plugin: `kolibri/plugins/device/assets/src/views/DeviceSettingsPage/api.js` unless it is discovered that there would be some blocker to use this setting. As an alternative, `options.ini` could be considered.

Backend changes should include updating the model `kolibri/core/device/models.py` and related serializer `kolibri/core/device/serializers.py`

## Acceptance Criteria
- [ ]  Frontend is updated with correct strings, using existing components
- [ ]  On saving, the setting is updated on both the frontend and the backend, and a *Settings have been updated* message displays. (This snackbar should already exists and it should appear by default on a successful update to the device settings).
- [ ]  The `DeviceSettingsPage.spec.js` should be updated so that existing tests still pass (as necessary) and there should be at least one test written to cover this scenario

## References 
- [Notion project page](https://www.notion.so/learningequality/Updates-to-Device-Settings-45529cbcc4f74aeb9b19559228c97579)
- [Figma spec](https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=1384%3A16773)
- [Gherkin scenarios](https://www.notion.so/learningequality/Gherkin-scenarios-02096ac9925844f8902c818cab607d4b#1959b753421648308fb467e21bdaa125)

**Comment by jredrejo** [comment]
@marcellamaki while working on this with @LianaHarris360 we have thought that we should hide this part of the UI to the user if the user is running the browser in a machine different than the server. It does not make too much sense to show a standard file picker in a machine other than the server to select the paths for the locations, as you would not see the server disk.
Hope this sounds ok, if not we should discuss the alternatives, if any

**Comment by marcellamaki** [comment]
Yes @jredrejo that makes complete sense to me -- good thinking!

**Comment by jredrejo** [comment]
@marcellamaki @jtamiace I'm afraid the Figma specs can't be done as they are for this issue.
Due to security reasons, browsers don't allow selecting a folder path using the native file picker  as stated in Figma. 
There's a [recent browser api ](https://caniuse.com/?search=showdirectorypicker)to do it, but a) it only works in Chrome and b)It only works on https connections what discarded if utility in kolibri .

I see three options here, but they all will require new decissions and design:
1. Just remove these path features from the browser UI and leave it only in the `options.ini `file of kolibri
2. Instead of the file picker, show input boxes where the user can write down the path. An api will check if that's a valid folder in the server and if it's read-only or not
3. Implementing a web file picker. It'll require the browser connecting to the server to explore the files in the server. It'll require a complete development both in the backend and in the frontend to design and create a tree component [similar to this ](https://www.jqueryscript.net/other/json-xml-data-tree.html) that can communicate with the serve while exploring the disk.

On the other hand, for the storage location, I think they conflict with the https://github.com/learningequality/kolibri/blob/develop/kolibri/utils/options.py#L493-L505 settings . I don't think having three sources of truth (the database, environment variables and the options.ini file) is a good idea, so I wonder if this has been considered when designing this issue. The web UI can be used to write/read on the options.ini file (if the kolibri application at the  server has write access on this file) but it will never change the environment variables. This is very important when running kolibri on headless servers, in cloud or in any automated installation.


Looking forward to knowing your ideas

**Comment by marcellamaki** [comment]
Hi @jredrejo! Thanks for the details about this issue. I will be happy to hear from @jtamiace, but from my first read through, it seems like option 2 might be the best option. I think getting rid of the path feature, unless absolutely necessary, would not be ideal, and option 3 of implementing a web file picker seems more complicated than it is worth. In your opinion, do you find the second option the most straightforward to implement? (Apart from the potential conflicts you describe.)

As for the storage location conflicting, and three sources of truth, that is not something I had considered. I do recall talking to @rtibbles about the web UI setting `options.ini` to try to ensure there is not a conflict there, but I had not considered the environmental variables, and I am not familiar with the implications for kolibri in specific types of installations. Maybe he can jump here with some suggestions or further questions, because I think I am a bit in over my head 😄

**Comment by rtibbles** [comment]
I think we should show a file picker in app mode, but otherwise do the path based system you suggest.

The paths should be updating the options.ini and initiating a Kolibri restart, we should not be coding these separately from the options.ini - apologies if I ever gave that impression.

In the case where the options.ini settings are being overridden by environment variables, we should probably disable this interface.

**Comment by jredrejo** [comment]
After reading these comments I think the best approach would be:
1. Use option 2 (Instead of the file picker, show input boxes where the user can write down the path. An api will check if that's a valid folder in the server and if it's read-only or not)
2. As @rtibbles suggested, doing the needed changes in the backend to communicate to the frontend these options are being handled by env variables, thus they must not appear in the UI

Any objections? and if not, @jtamiace any ideas on the design change or shall we (@LianaHarris360 and I ) do a fist attempt that you could evaluate?

**Comment by rtibbles** [comment]
Let's open a follow up issue for adding a path picker on Android - I think it's the most needed use case, but is too much for the implementation for now.

**Comment by rtibbles** [comment]
Fixed in #9833
