### ISSUE TITLE
Update messages for filters on CoachExamsPage (and lessons too)

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#9886]
I spotted this while reviewing #9863 and saw some linting changes in the diff for `CoachExamsPage` where there are comments indicating that we were temporarily commenting out the Active/Inactive filters for exams in #6174 due to not having updated the strings.

With the guidance from @radinamatic in #6174 we need to be sure we have the correct strings defined in the component and that the select dropdown is visible and working as expected.

Note that `CoachExamsPage` isn't the only place where this is an issue, there are others as can be seen in https://github.com/learningequality/kolibri/pull/6233/files (the PR that commented the filters out).

**Comment by akolson** [comment]
@radinamatic could you please guide on the strings that need to be corrected?

**Comment by radinamatic** [comment]
The suggestion by @indirectlylit was to involve the design team to decide the best way to proceed, so it's not just about the (new) strings.

@jtamiace Could you review the past conversation in #6174 and let us know if you have additional recommendations for this filtering, given multiple statuses? Thank you!

**Comment by jtamiace** [comment]
To keep things simple, the label names could be non-specific:

For lessons:
Filter label: Status
Options: All, Visible, Not visible

For quizzes:
Filter label: Status
Options: All, Not started, Started, Ended

Would this be sufficient for i18n? Otherwise for specificity it could be Lesson status, Visible lessons, Not visible lessons etc.

I know the column label in the table is "Visible to learners" and not "Status," but directly mapping column label and toggle meanings to a the filter label doesn't seem as clear or consistent. For example, if the filter label is "Visible to learners" with options All, Yes, No.

**Comment by akolson** [comment]
@jtamiace Thanks for the design insights. This below seems more consistent with other filters in Kolibri and I think is a better option to pursue.

> For lessons:
Filter label: Status
Options: All, Visible, Not visible

> For quizzes:
Filter label: Status
Options: All, Not started, Started, Ended

@radinamatic  any concerns regarding i18n?

**Comment by radinamatic** [comment]
This will work very well @jtamiace @akolson 💯 

Let's just make sure we put the proper context for translators:

```
filterLessonStatus: {
        message: 'Status',
        context: 'Label for the selector used to filter and display lessons by status.',
      },

---

filterLessonAll: {
        message: 'All',
        context: 'Refers to LESSON. Default option in the selector used to filter and display lessons by status. ',
      },

---

filterLessonVisible: {
        message: 'Visible',
        context: 'Refers to LESSON. Option in the selector used to filter and display only the lessons visible  to learners. ',
      },
```

...and so forth 🙂
